home-assistant/android

- .idea/dictionaries/awarecan.xml
- README.md
> Add basic dev env setup guide

- app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
> Fix round icon background color

- app/src/main/AndroidManifest.xml
Well this was easier than I thought it would be. Add the permission, the webview uses it :tada:
> Add vibration support

- .travis/script.sh
According to the doc `TRAVIS_BRANCH` will be set with the tag value
https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
> [TRAVIS] Publish

- build.gradle
Updates to `com.android.tools.build:gradle:3.5.2`
> Update Gradle to 3.5.2

- app/build.gradle
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
- app/src/test/java/io/homeassistant/companion/android/webview/WebViewPresenterImplSpec.kt
- build.gradle
https://github.com/home-assistant/home-assistant-android/issues/32
> Crashlytics Setup

- app/build.gradle
- app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupFragment.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupPresenterImpl.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupView.kt
- app/src/main/res/layout/fragment_manual_setup.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupPresenterImplSpec.kt
Show a simple error when there is a URL parse exception
> Error Message on URL Parse Exception

- gradle/dependencies.gradle
https://github.com/home-assistant/home-assistant-android/issues/68
> Jackson dependency

- app/build.gradle
- app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
- app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Fixes crash introduced at https://github.com/home-assistant/home-assistant-android/pull/72
> [Lokalize] Update version

- .travis/script.sh
- app/build.gradle
Travis output 
> export VERSION_NAME=`git describe --tags $(git rev-list --tags --max-count=1)`
git describe --tags $(git rev-list --tags --max-count=1)
git rev-list --tags --max-count=1
echo $VERSION_NAME
1.0.0
> [TRAVIS] Release version name

- app/build.gradle
- app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
- app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
I reported the bug to Lokalise.
Let's wait for a stable version 2 of the SDK., and till then update translations manual.
Fixes https://github.com/home-assistant/home-assistant-android/issues/103
> Remove Lokalise SDK

- app/src/main/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
Fixes https://github.com/home-assistant/home-assistant-android/issues/141
> Add some error handling around getting zones from HA.  

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt
- app/src/main/java/io/homeassistant/companion/android/notifications/ServiceComponent.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
- app/src/test/java/io/homeassistant/companion/android/launch/LaunchPresenterImplSpec.kt
- app/src/test/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImplSpec.kt
- build.gradle
- data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationService.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/RegisterDeviceRequest.kt
- data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImplSpec.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/DeviceRegistration.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
- domain/src/test/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImplSpec.kt
This PR will do the following:
- Implement foreground receiving
- Push token and url to HA for notifications
- Update HA with new tokens
Fixes #7
> Basic Notification Support

- app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupPresenterImpl.kt
- app/src/test/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupPresenterImplSpec.kt
- data/src/main/java/io/homeassistant/companion/android/data/authentication/AuthenticationRepositoryImpl.kt
- data/src/test/java/io/homeassistant/companion/android/data/authentication/AuthenticationRepositoryImplSpec.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/MalformedHttpUrlException.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/authentication/AuthenticationRepository.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/authentication/AuthenticationUseCase.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/authentication/AuthenticationUseCaseImpl.kt
- domain/src/test/java/io/homeassistant/companion/android/domain/authentication/AuthenticationUseCaseImplSpec.kt
this should fixe this bug https://github.com/home-assistant/home-assistant-android/issues/150
> Url improvement

- app/src/main/res/layout/fragment_discovery.xml
- app/src/main/res/layout/fragment_manual_setup.xml
- app/src/main/res/layout/fragment_mobile_app_integration.xml
- app/src/main/res/values/styles.xml
Fix : https://github.com/home-assistant/home-assistant-android/issues/91 
https://github.com/home-assistant/home-assistant-android/issues/84
> Application style

- app/build.gradle
- app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
- app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Copy paste bug was fixed in beta 4.
> Add back Lokalise SDK

- .github/ISSUE_TEMPLATE/Bug_report.md
Just a small typo in the issue template
> Small typo

- app/build.gradle
- app/src/main/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
- app/src/test/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImplSpec.kt
- build.gradle
- common/src/main/java/io/homeassistant/companion/android/common/dagger/DataModule.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
- data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImplSpec.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/DeviceRegistration.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
- domain/src/test/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImplSpec.kt
Fixes:  https://github.com/home-assistant/home-assistant-android/issues/143
> Allow editing of Device Name

- .travis/script.sh
Fix https://github.com/home-assistant/home-assistant-android/issues/12
> [CI] Change log

- app/src/main/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/166
Fixes: https://github.com/home-assistant/home-assistant-android/issues/145
> Set minimum accuracy for location updates.

- build.gradle
This PR upgrades from kotlin 1.3.50 to 1.3.60.
This allows to support building with Java 11.
Without this change:
```
javac 11.0.5
Already on 'master'
Your branch is up to date with 'upstream/master'.
> Task :app:processDebugGoogleServices
Parsing json file: /home/patrick/workspaces/android/home-assistant-android/app/google-services.json
> Task :common:compileDebugJavaWithJavac FAILED
/home/patrick/workspaces/android/home-assistant-android/common/build/generated/source/kapt/debug/io/homeassistant/companion/android/data/HomeAssistantRetrofit_Factory.java:4: error: pac
kage javax.annotation.processing does not exist
import javax.annotation.processing.Generated;
^
/home/patrick/workspaces/android/home-assistant-android/common/build/generated/source/kapt/debug/io/homeassistant/companion/androi …
```
> Upgrade to kotlin 1.3.60

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
- app/src/test/java/io/homeassistant/companion/android/webview/WebViewPresenterImplSpec.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
- data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImplSpec.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
- domain/src/test/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImplSpec.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/92
> Support remoteUiUrl from the mobile_app integration.

- data/src/main/java/io/homeassistant/companion/android/data/url/UrlRepositoryImpl.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/219
Fixes: https://github.com/home-assistant/home-assistant-android/issues/217
> Fix integration registration overriding url.

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/233
Fixes: https://github.com/home-assistant/home-assistant-android/issues/211
> Add permissions for Camera and Audio.

- common/src/main/java/io/homeassistant/companion/android/common/dagger/DataModule.kt
- common/src/main/java/io/homeassistant/companion/android/common/dagger/Graph.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/DiscoveryInfoResponse.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationService.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/RegisterDeviceRequest.kt
- data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImplSpec.kt
- data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationServiceSpec.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/226
> Send device_id for HA versions above 0.104.0

- app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
- common/src/main/java/io/homeassistant/companion/android/common/dagger/DataModule.kt
- common/src/main/java/io/homeassistant/companion/android/common/dagger/Graph.kt
- common/src/main/java/io/homeassistant/companion/android/common/migrations/Migrations.kt
And prepare for multiple instance support.
> Support Migrations

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Fixes #240
Fixes: https://github.com/home-assistant/home-assistant-android/issues/242
Fixes: https://github.com/home-assistant/home-assistant-android/issues/238
> Only show error screen if main url fails to load.

- data/src/main/java/io/homeassistant/companion/android/data/url/UrlRepositoryImpl.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/240
> Fix issue when we are on local wifi without local url.

- common/src/main/java/io/homeassistant/companion/android/common/migrations/Migrations.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/241
> Fix migration to pull from the correct preference.

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/71
> Add timeout to UI on load.

- app/src/main/java/io/homeassistant/companion/android/webview/WebView.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
- app/src/main/res/values/strings.xml
- data/src/main/java/io/homeassistant/companion/android/data/authentication/AuthenticationRepositoryImpl.kt
- data/src/main/java/io/homeassistant/companion/android/data/authentication/AuthenticationService.kt
- data/src/test/java/io/homeassistant/companion/android/data/authentication/AuthenticationRepositoryImplSpec.kt
- data/src/test/java/io/homeassistant/companion/android/data/authentication/AuthenticationServiceSpec.kt
- data/src/test/resources/authentication/refresh_token_error.json
Fixes: https://github.com/home-assistant/home-assistant-android/issues/79
> Add specific error handling around revoked token.

- app/src/main/java/io/homeassistant/companion/android/PresenterComponent.kt
- app/src/main/java/io/homeassistant/companion/android/PresenterModule.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryFragment.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryPresenter.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryPresenterImpl.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryView.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/HomeAssistantInstance.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/HomeAssistantSearcher.kt
- app/src/main/res/drawable/navigate_next.xml
- app/src/main/res/layout/fragment_discovery.xml
- app/src/main/res/layout/instance_item.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Fixes: https://github.com/home-assistant/home-assistant-android/issues/6
TODO List:
> Initial work on automatic discovery of HA on local network.

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
- data/src/main/java/io/homeassistant/companion/android/data/HomeAssistantRetrofit.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
Fixes crash introduced with theming application.
> Fix get theme because of missing fields in DTO.

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/261
> Stop the app from opening browser when logging out.

- app/build.gradle
- app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryFragment.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupFragment.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsView.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
- build.gradle
- common/build.gradle
- common/src/main/java/io/homeassistant/companion/android/common/dagger/DataModule.kt
- common/src/main/java/io/homeassistant/companion/android/common/dagger/Graph.kt
- common/src/main/java/io/homeassistant/companion/android/common/dagger/GraphComponentAccessor.kt
- data/build.gradle
- data/src/main/java/io/homeassistant/companion/android/data/HomeAssistantRetrofit.kt
- data/src/test/java/io/homeassistant/companion/android/data/HomeAssistantMockService.kt
- domain/build.gradle
Fixes: https://github.com/home-assistant/home-assistant-android/issues/258
> Reload UI url more proactively

- .travis/before_install.sh
Fixes: https://github.com/home-assistant/home-assistant-android/issues/279
> Place the mock google services for debug only.

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenter.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
- app/src/main/res/layout/fragment_mobile_app_integration.xml
- app/src/main/res/values/strings.xml
Fixes: https://github.com/home-assistant/home-assistant-android/issues/119
Fixes: https://github.com/home-assistant/home-assistant-android/issues/192
Fixes: https://github.com/home-assistant/home-assistant-android/issues/192
Fixes: https://github.com/home-assistant/home-assistant-android/issues/227
> Request we be exempt from Doze.

- app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
- app/src/main/res/drawable/ic_fullscreen.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
- data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
Reverts home-assistant/home-assistant-android#293
> Revert "Add Fullscreen option"

- app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
- app/src/main/res/drawable/ic_fullscreen.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/xml/preferences.xml
- data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/230
Add Fullscreen option in app settings :
> Add Fullscreen option

- app/src/main/AndroidManifest.xml
Fixes Play Store rejection for Android TV
> Microphone is not required

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/res/values/styles.xml
Test if notch or not, if notch just hide nav bar
Test on virtual device :
> Fix Fullscreen for notch

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt
- app/src/main/java/io/homeassistant/companion/android/notifications/NotificationAction.kt
- app/src/main/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt
- app/src/main/java/io/homeassistant/companion/android/notifications/ServiceComponent.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationService.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/entities/DiscoveryInfoResponse.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/entities/DomainResponse.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/entities/EntityResponse.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/entities/FireEventRequest.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/entities/GetConfigResponse.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/entities/IntegrationRequest.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/entities/RegisterDeviceRequest.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/entities/RegisterDeviceResponse.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/entities/ServiceCallRequest.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/entities/UpdateLocationRequest.kt
- data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImplSpec.kt
- data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationServiceSpec.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
Current work in progress.  Basic functionality working.
Example service call (supports up to 3 actions):
```
- service: notify.mobile_app_pixel_2
data:
message: 'Something really cool happened'
title: 'Action Time'
data:
data:
action_1_key: 'EVENT_KEY'
action_1_title: 'Button Text'
```
Example event in HA:
```
{
"event_type": "mobile_app_notification_action",
"data": {
"action": "KEY_ONE",
"action_2_title": "Action 2",
"action_3_title": "Action 3",
"action_1_title": "Action 1",
"action_1_key": "KEY_ONE",
"action_2_key": "KEY_TWO",
"action_3_key": "KEY_THREE"
},
"origin": "REMOTE",
"time_fired": "2020-02-02T04:45:05.550251+00:00",
"context": {
"id": "abc123",
"parent_id": null,
"user_id": "123abc"
}
}
```
Example Consumption in Automation:
```
- id: '1523975760898'
alias: '[Notification - …
```
> Actionable Notifications

- app/src/main/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt
I was not able to test this yet, since it seems that I cannot send pull notifications from a development app? https://github.com/home-assistant/home-assistant-android#setup-development-environment
> implement request_location_update via push notifications

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt
- app/src/main/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt
- data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
- data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImplSpec.kt
Needs https://github.com/home-assistant/mobile-apps-fcm-push/pull/2 to function.
Still need to think about backwards compatibility...
> Add support for images and actions no matter what the app is doing.

- app/src/main/java/io/homeassistant/companion/android/webview/WebView.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/res/layout/dialog_authentication.xml
- app/src/main/res/values/strings.xml
Add authentication dialog for http basic auth request in iframe (like Blue Iris, Kodi, IDE Cloud 9...)
> Add Authentication Dialog

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt
- app/src/main/java/io/homeassistant/companion/android/notifications/NotificationAction.kt
- app/src/main/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/354
Fixes: https://github.com/home-assistant/home-assistant-android/issues/353
Fixes: https://github.com/home-assistant/home-assistant-android/issues/349
Fixes: https://github.com/home-assistant/home-assistant-android/issues/335
Needs: https://github.com/home-assistant/mobile-apps-fcm-push/pull/6 to fully function
```
title: 'Title Text'
message: 'Body Text'
data:
actions:
- action: test
title: Click Me
- action: URI
title: Open Url
uri: https://google.com
image: 'imageUrl'
tag: tag
sticky: 'true' # or 'false'
color: '#2DF56D' # or 'red'
clickAction: 'https://google.com' # action when clicking main notification
ttl: 0 # https://firebase.google.com/docs/reference/admin/node/admin.messaging.AndroidConfig.html#optional-ttl …
```
> Multiple Notification Options

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt
- app/src/main/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/375
> Fix regression with notification actions.

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/322
> Ensure activity isn't finishing when showing errors.

- README.md
Improvement in the steps.
Hopefully this will make it easier for everyone to set up their own work environment.
> 📚 Improve step-by-step environment setup

- app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationFragment.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationPresenterImpl.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationView.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryFragment.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nl-rNL/strings.xml
- app/src/main/res/values-pl-rPL/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values/strings.xml
Fixes: https://github.com/home-assistant/home-assistant-android/issues/369
Fixes: https://github.com/home-assistant/home-assistant-android/issues/367
Fixes: https://github.com/home-assistant/home-assistant-android/issues/323
Fixes: https://github.com/home-assistant/home-assistant-android/issues/366
> Squash bugs

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
- app/src/test/java/io/homeassistant/companion/android/webview/WebViewPresenterImplSpec.kt
- data/src/main/java/io/homeassistant/companion/android/data/authentication/AuthenticationRepositoryImpl.kt
- data/src/test/java/io/homeassistant/companion/android/data/authentication/AuthenticationRepositoryImplSpec.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/authentication/AuthenticationRepository.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/authentication/AuthenticationUseCase.kt
- domain/src/main/java/io/homeassistant/companion/android/domain/authentication/AuthenticationUseCaseImpl.kt
- domain/src/test/java/io/homeassistant/companion/android/domain/authentication/AuthenticationUseCaseImplSpec.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/257
> Allow front end to force credential refresh.

- app/src/main/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt
- app/src/main/res/values/strings.xml
Show toast when we fail to send event and keep notification so you can
retry.
Fixes: https://github.com/home-assistant/home-assistant-android/issues/453
> Better handling of action events.

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/res/values/strings.xml
Fixes: https://github.com/home-assistant/home-assistant-android/issues/454
> Add better handling for slow connections.

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/467
> Ensure on click works when sticky is true.

- app/src/main/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorWorker.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/470
> Geocode Sensor.

- README.md
> just a "the" instead a "to"

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Fix fullscreen when virtual keyboard is show (issue : #488)
> Fullscreen & Keyboard Fix

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Fix for small video size from "Developer Tools> States" when PiP is expanded (back in app)
Part fix of issue : #479
> Fullscreen Video Fix

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/486
> Use same flags for actions as clickAction.

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/504
> Make sure sticky settings honored.

- app/src/main/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorWorker.kt
Fixes: https://github.com/home-assistant/home-assistant-android/issues/497
Fixes: https://github.com/home-assistant/home-assistant-android/issues/513
> Geocoded Location Fixes

- build.gradle
> Update gradle to v3.6.2

- data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
Until @timmo001 updates this call to use the webhook, we are going to stop making this request.
> Stop calling an endpoint that will never come.

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Fix "White box appears when keyboard is displayed" in fullscreen mode with screen cutout (issue : #597)
> Fix Keyboard in Fullscreen mode with screen cutout

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
CookieManager added to accept cookies in Webview (Fix issue #568 
Tested with "http://www.html-kit.com/tools/cookietester/" in iFrame card :
> Add CookieManager

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
- Fix issue #537
- Fix screen orientation change in OnboardingActivity (Discovery fragment, Manual fragment, Authentication fragment & Integration fragment included)
> Fix Screen Orientation Change in OnboardingActivity

- app/src/main/java/io/homeassistant/companion/android/webview/WebView.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
- app/src/main/res/values/strings.xml
- Fix issue #528
- WebView.ShowError() now show detailed SSL error
- WebView.ShowError() now show error description of onReceivedError()
> ShowError Enhancement

- .github/release-drafter.yml
- .github/workflows/release.yml
- README.md
- app/build.gradle.kts
- buildSrc/src/main/kotlin/Config.kt
> Update Production Release Steps.

- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/HomeAssistantSearcher.kt
Fixes: https://github.com/home-assistant/android/issues/631
> Ensure thread safety around NsdManager.

- app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
> Ensure sensors only start when we are actually logged in.

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt
> Only update registration when we are actually connected to HA.

- app/src/main/res/values/strings.xml
When lokalise integration was down this got missed.
Fixes: https://github.com/home-assistant/android/issues/667
> Fix translation.

- app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
Fixes https://github.com/home-assistant/android/issues/630
> Ensure we have permissions before trying to get Wifi data

- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenter.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationView.kt
- app/src/main/res/layout/fragment_mobile_app_integration.xml
- app/src/main/res/values/strings.xml
- data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
This is discouraged but helpful for contributors.  This way we don't need everyone to setup firebase just to help on the app.
Fixes: #558
> Allow the firebase instance id be optional.

- app/src/full/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
- app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
Location tracking broke after the initial creation of the minimal flavor, this PR fixes that.
> Fix location tracking

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Fixes: https://github.com/home-assistant/android/issues/694
Missed one last one from the refactor.
> Ensure the correct class is used for broadcast of location updates.

- app/src/main/java/io/homeassistant/companion/android/sensors/AllSensorsUpdater.kt
Fixes: https://github.com/home-assistant/android/issues/661
> Request accurate location when we update sensors.

- data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
Fixes: https://github.com/home-assistant/android/issues/679
> Add device_id whenever we fire an event.

- app/build.gradle.kts
Fixes: https://github.com/home-assistant/android/runs/941541686?check_suite_focus=true
https://github.com/Triple-T/gradle-play-publisher#disabling-publishing
> Disable minimal publishing.

- README.md
Just thought we should make mention of these new things in the read me file
> Mention app flavors and actions APK in the read me file

- app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
Fixes html formatting of collapsed notifications (Issue #711)
Also added possibility to use html on title and group summary of notification.
Collapsed notification with html formatting:
```
message: 'This is a <b><span style="color: red">HTML</span></b> <i>text</i><br><br>This is a text after a new line'
title: "Cool HTML formatting"
```
Html formatting for group summary and title:
```
message: 'Part of group 1'
title: "<b><i>Cool HTML formatting</i></b>"
data:
group: '<span style="color: blue">Blue group summary</span>'
```
```
message: 'Part of group 2'
title: "<b><i>Cool HTML formatting</i></b>"
data:
group: '<span style="color: blue">Blue group summary</span>'
```
> Notifications - HTML formatting for title, group summary and collapsed notifications

- app/build.gradle.kts
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/res/values-v29/styles.xml
- buildSrc/src/main/kotlin/Config.kt
Fixes #710 #138 
More details in #713 that had to be closed due to a commit issue.
> Fix android dark mode

- app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
> Make sure titles for notifications are optional.

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Fix for #719
It's not the best solution because the problem is still there but it fixes for now the issue to skip the authentication.
> fix: Biomatric authentication skip issue

- app/src/full/java/io/homeassistant/companion/android/sensors/LocationBroadcastReceiver.kt
Fixes: https://github.com/home-assistant/android/issues/420
Fixes: https://github.com/home-assistant/android/issues/681
Fixes: https://github.com/home-assistant/android/issues/698
Fixes: https://github.com/home-assistant/android/issues/703
> Try to fix some location issues

- app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorWorker.kt
Fixes: https://github.com/home-assistant/android/issues/751
> Dagger Injection Fixes

- app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
I thought it might be nice to allow some fields that the user can't edit to be copied.
> Allow certain fields to be copied

- app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
- app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
- app/src/main/java/io/homeassistant/companion/android/database/widget/ButtonWidgetDao.kt
- app/src/main/java/io/homeassistant/companion/android/database/widget/ButtonWidgetEntity.kt
- app/src/main/java/io/homeassistant/companion/android/database/widget/StaticWidgetDao.kt
- app/src/main/java/io/homeassistant/companion/android/database/widget/StaticWidgetEntity.kt
- app/src/main/java/io/homeassistant/companion/android/migrations/Migrations.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidget.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/StaticWidget.kt
Apparently Kotlin does funny things when importing a class with the same name as the current class.
> Fix name-spacing issue

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Fixes #783 
I have experienced similar problems. This issue happens when user has a good connection, but HA server is not reachable so quickly (slow server or home networking problems).
> Increased connection delay

- app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
- app/src/main/java/io/homeassistant/companion/android/database/widget/StaticWidgetEntity.kt
- app/src/main/java/io/homeassistant/companion/android/migrations/Migrations.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/StaticWidget.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/StaticWidgetConfigureActivity.kt
- app/src/main/res/layout/widget_static_configure.xml
- app/src/main/res/values/strings.xml
> Added possibility to use multiple attributes for static widgets

- app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidget.kt
- data/src/main/java/io/homeassistant/companion/android/data/HomeAssistantRetrofit.kt
> Fixed widget errors with service calls containing "entity_id: all"

- app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
- app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
- app/src/full/java/io/homeassistant/companion/android/sensors/LocationBroadcastReceiver.kt
- app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
- app/src/main/java/io/homeassistant/companion/android/database/sensor/Attribute.kt
- app/src/main/java/io/homeassistant/companion/android/database/sensor/Sensor.kt
- app/src/main/java/io/homeassistant/companion/android/database/sensor/SensorDao.kt
- app/src/main/java/io/homeassistant/companion/android/database/sensor/SensorWithAttributes.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/LastRebootSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/StepsSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt
- app/src/minimal/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
- app/src/minimal/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
- app/src/minimal/java/io/homeassistant/companion/android/sensors/LocationBroadcastReceiver.kt
In this PR we now persist all sensor data to the local DB.  This allows us to keep the UI and Home Assistant better in sync.  This also allows sensors to return data asynchronously and allows for more reliable update with those sensors.
> Sensor Refactor

- app/src/full/java/io/homeassistant/companion/android/sensors/LocationBroadcastReceiver.kt
Fixes: https://github.com/home-assistant/android/issues/814
> Fix wakelock error for requesting accurate location.

- app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Fix: https://github.com/home-assistant/android/issues/817
Not sure how location is null but it was apparently.
> Sensor Crashes

- app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
Fixes: https://github.com/home-assistant/android/issues/823
> Fix requests for accurate location on app open.

- app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
Fixes: #831 
#831 mentioned other issues as well but that is out of scope for this fix as its a bigger change.
> Fix location updates in the background

- README.md
README updated basing on my experiences while running the project from scratch.
> Update instructions for running the project from the scratch

- README.md
Updates the instructions to mention you need to install the required SDK.
> Mention install SDK in README

- app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
Prevent a caught exception from being an exception to begin with.
> Guard for null in bluetooth sensor

- app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
- app/src/main/java/io/homeassistant/companion/android/database/sensor/Sensor.kt
- app/src/main/java/io/homeassistant/companion/android/database/sensor/SensorDao.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
The time between a sensor updating and sending the data to Home Assistant could cause a race condition.  This PR should fix it by changing from a boolean indicating successful send of state to the actual value we last sent.
> Fix a race condition Sensor Update

- app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/res/xml/preferences.xml
Fixes: #925
Also hide the timeout when it's not applicable.
> Fix Security Bypass

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/share/ShareActivity.kt
- app/src/main/java/io/homeassistant/companion/android/share/ShareComponent.kt
- app/src/main/res/values/strings.xml
> Add the ability to share things (text) to Home Assistant.

- app/src/main/java/io/homeassistant/companion/android/widgets/WidgetDynamicFieldAdapter.kt
> Fix dynamic field crash for service call widget

- app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
- app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
- app/src/main/res/values/strings.xml
Fixes: https://github.com/home-assistant/android/issues/868
> Settings for location accuracy!

- app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt
Logic should've been reversed :)
> Fix icon logic for mic muted

- common/src/main/java/io/homeassistant/companion/android/common/data/HomeAssistantRetrofit.kt
> Only add the logging interceptor for debug builds.

- app/src/full/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenter.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterBase.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationView.kt
- app/src/main/res/layout/fragment_mobile_app_integration.xml
- app/src/main/res/values/strings.xml
- app/src/minimal/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
- app/src/test/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImplSpec.kt
Fixes: https://github.com/home-assistant/android/issues/385
> Make on-boarding a more streamlined experience

- app/src/main/java/io/homeassistant/companion/android/nfc/NfcSetupActivity.kt
- app/src/main/res/layout/activity_nfc_setup.xml
- app/src/main/res/values/strings.xml
Fixes: https://github.com/home-assistant/android/issues/940
> Ensure that we don't write to tags unless explicitly asked to do so.

- app/src/main/java/io/homeassistant/companion/android/sensors/SensorWorker.kt
Fixes: #993 
Probably should've started with this 😃
> Fix sensor worker blank text

- app/src/main/java/io/homeassistant/companion/android/util/NotificationActionContentHandler.kt
Fixes: https://github.com/home-assistant/android/issues/956
> Allow opening of apps via notifications.

- README.md
We needed to update the URL as we were getting a 404 after the refactor.
> Update readme push_url link after refactor

- app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
Fixes: #561 
The best way to make sure a notification stays as expected while also respecting Android 8+ channels lets use a specific channel to bypass the devices ringer mode.  The notification will make a sound (regardless if the device is on vibrate/silent) and behave much like an alarm, the stream will stop once the user interacts with their device. The default sound will be the default alarm which may be enough for most users.  There is also code to support legacy devices too, we are just reading the channel name and changing the stream accordingly.
Example:
```
message: Time to wake up!
data:
channel: alarm_stream
```
Docs: https://github.com/home-assistant/companion.home-assistant/pull/354
> Allow notifications to use the alarm stream

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
- app/src/main/res/values/strings.xml
Fixes: https://github.com/home-assistant/android/issues/554
> Last Notification Sensor

- app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt
It has been about a month since #891 was merged.  Now lets close out part 2 for #899 #901 #902 #904 #905
> Remove attributes part 2

- app/build.gradle.kts
- app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
- buildSrc/src/main/kotlin/Config.kt
This commit also enables the room incremental annotation processor.
This also fixes the export schema warning in the console logs.
> Update AGP, Kotlin.

- app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
- app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
- app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
- app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
- app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
- app/src/main/java/io/homeassistant/companion/android/controls/SceneControl.kt
Power menu now supports:
* Scenes
* Climate
* Cover
* Fan
It also refreshes while on the power menu ever 5 seconds long with after changes.
> Power Menu Enhancements

- app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
> Fix light power menu control

- app/build.gradle.kts
- build.gradle.kts
- buildSrc/src/main/kotlin/Config.kt
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
Also enable Gradle parallel flag and caching flags.
> Update to Gradle 6.7.

- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt
Fixes: https://github.com/home-assistant/android/issues/1039
> Request background location after requesting accurate location.

- app/src/main/java/io/homeassistant/companion/android/database/notification/NotificationDao.kt
- app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationHistoryFragment.kt
- app/src/main/res/drawable/ic_filter.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/notifications.xml
Let the user switch between 25, 50 or 100 last notifications
> Notification history filter options

- app/build.gradle.kts
- buildSrc/src/main/kotlin/Config.kt
- gradle.properties
Also disable some unused build features to improve configuration time.
> Update distribution plugin.

- .github/workflows/weekly.yaml
Also fix commit check, I'm really bad with bash apparently...
> Change play store publish to weekly

- .github/workflows/weekly.yaml
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
- app/src/main/res/values/strings.xml
Still trying to fix our inability to publish to Google Play....
> Explicit prompt for location

- app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
- app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
- app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
- app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
- app/src/main/res/values/strings.xml
This PR allows localization of the states in the new power menu controls
> Add translations to power menu

- app/src/main/java/io/homeassistant/companion/android/database/widget/ButtonWidgetDao.kt
- app/src/main/java/io/homeassistant/companion/android/settings/widgets/ManageWidgetsSettingsFragment.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetDynamicFieldAdapter.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/manage_widgets.xml
> Make button widget editable

- app/src/main/java/io/homeassistant/companion/android/database/widget/MediaPlayerControlsWidgetDao.kt
- app/src/main/java/io/homeassistant/companion/android/settings/widgets/ManageWidgetsSettingsFragment.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidgetConfigureActivity.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/manage_widgets.xml
> Make media player widget editable

- app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
Fixes: #1113 
Reference: https://data.home-assistant.io/docs/states#database
> Limit the state of last notification to 255

- app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
This is an attempt to fix #871 and #929  based on the data reported.   I am not certain this will fix all cases but it should make the situation better.
*  Skip location updates if the time property is in the future compared to `now`
*  Skip location updates if the time property is before the last update we sent, we don't need data in the past
*  Skip location updates if the time property is more than 5 minutes earlier than the current time, we don't need old data
*  Add ADB debug statements for future debugging purposes.
I ran this for several hours and can see that certain events get filtered as expected and location updates still come in as expected.
```
2020-10-28 18:06:08.137 23832-23917/io.homeassistant.companion.android.debug D/LocBroadcastReceiver: Registering for location …
```
> Skip location update if the time of location is not as expected

- app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt
> Correct battery level icon to better match its state

- app/src/main/java/io/homeassistant/companion/android/sensors/LastUpdateManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorWorker.kt
- app/src/main/res/values/strings.xml
Fixes: #529 
The state will either be `SensorWorker` or the intent that caused the update to be sent.
Docs: https://github.com/home-assistant/companion.home-assistant/pull/377
> Add last update sensor

- .github/pull_request_template.md
Lets also add the screenshot section to match the iOS PR template, we often request for it anyways
Documentation: home-assistant/companion.home-assistant# N/A
Ref: https://github.com/home-assistant/iOS/pull/1257
> Add screenshot section to PR template

- app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
- app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
- app/src/main/java/io/homeassistant/companion/android/controls/DefaultSliderControl.kt
- app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
- app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
- app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
- app/src/main/java/io/homeassistant/companion/android/controls/LockControl.kt
- app/src/main/java/io/homeassistant/companion/android/controls/SceneControl.kt
Fixes: #1150 
Before:
After:
Documentation: home-assistant/companion.home-assistant# N/A
N/A
> Power Menu - default to entity ID when friendly name is not provided

- app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
Android notifications have a **Chronometer** option which shows a timer at the top which counts up or down to the given time. This PR enables the sending of notifications with this option. This takes two new options under **data**:
* chronometer - true to enable chronometer mode
* when - timestamp in milliseconds of the time to count up or down to 
For example:
```yaml
- alias: Notify of Next Alarm Time
trigger:
...
action:
service: notify.mobile_app_<your_device_id_here>
data:
title: Next Alarm
message: >-
Next Alarm At {{ states('sensor.<your_device_id_here>_next_alarm') }}
data:
chronometer: true
when: >-
{{ state_attr('sensor.<your_device_id_here>_next_alarm', 'Time in Milliseconds') / 1000 }}
```
Documentation: home-assistant/companion.home-assistant#386
This requires additional keys …
> Add support for Chronometer notifications

- app/src/main/java/io/homeassistant/companion/android/sensors/AppSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
- app/src/main/res/values/strings.xml
Fixes: #1155 by providing a current version sensor that represents the current installed version.
Documentation: home-assistant/companion.home-assistant#390
> Add a sensor for the current installed version

- .github/ISSUE_TEMPLATE/feature_request.md
I have seen a few feature requests get submitted with what should've been hidden in a comment, so lets clean that up 👍 
> Place FR template descriptions in a comment field so they remain hidden when created

- app/src/main/java/io/homeassistant/companion/android/nfc/TagReaderActivity.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
Lets add some debug logs so users can help investigate #942 
n/a
Lets see if we can get some users to test the debug apk before merging?
> Add some debug logs for scanning a tag

- buildSrc/src/main/kotlin/Config.kt
Got prompted to update the Gradle plugin as well as Kotlin so thought its time to do some updates along with them.
https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.4.1
https://github.com/JetBrains/kotlin/releases/tag/v1.4.21
https://github.com/google/dagger/releases/tag/dagger-2.30.1
https://github.com/getsentry/sentry-java/releases/tag/3.2.0
Ran a few tests with widgets and sensors and didn't see anything out of the ordinary.
> Bump some app dependencies

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Reworded the issue templates with the following things:
* Bug report: add a note "please check its not already reported"
* Feature request: replace "will laugh at you in private" with a more friendlier text
- seems harsh and not CoC conforming
- I can understand the prior wording quite well, but still had to laugh after reading that and shortly later the CoC
- just an idea on how to word this better
I'm sorry this is my first contribution ^^'
> Reword issue templates

- .github/actions/inflate-secrets/action.yml
> Inflate secrets in wear os app.

- app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
- app/src/main/res/values/strings.xml
Fixes: #1156 and #1253 by providing new sensors that contain the expected data.
Last Removed Notification will behave like Last Notification except the state updates as notifications are removed by either the user or an application.  This sensor will also have an Allow List.
Active Notification Count will update as the count of notifications update, this also includes a `post_time` attribute for each notification to help determine if its new or not.  If the state does not change then we may not see updates here. Due to the nature of the sensor there will not be an allow list, all notification data is also provided as attributes for the sensor. This sensor will update alongside all other sensors, it will update faster if a user enables one of the other 2 notifications.  Both will need to …
> Add new notification sensors and add new attributes to existing sensor

- buildSrc/src/main/kotlin/Config.kt
changes: https://developer.android.com/jetpack/androidx/releases/webkit#version_140_3
> Bump webkit dependency

- app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
Fixes the following sentry error by keeping track of the notification listener being connected in order to read active notifications.  The listener should actually be connected in order for us to read notifications being posted/removed but seems there is some type of edge case occurring on some devices.  Now we only update if the listener is connected and we also catch the exception to prevent the app from crashing.
```
java.lang.SecurityException: Disallowed call from unknown notification listener: android.service.notification.INotificationListener$Stub$Proxy@10f6e9 class android.service.notification.INotificationListener$Stub$Proxy
at android.os.Parcel.createException(Parcel.java:2071)
at android.os.Parcel.readException(Parcel.java:2039)
at …
```
> Check that notification listener is connected before attempting to update active notifications

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Hopefully the last fix for #1218 
Since we are performing a check on the first 5 characters lets ensure we actually have them since its possible we are not getting a URL from: https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L235
> Check that resource URL is at least as long as we expect

- app/src/main/java/io/homeassistant/companion/android/webview/WebView.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
- app/src/main/res/values/strings.xml
This will show a popup if a a user is using core version `2021.1.3` or below.
> Add a security warning for vulnerably.

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
- app/src/main/res/values/strings.xml
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
Only show dialog once every 24 hours rather than every time.
None
> Only alert about out of data HA version every 24 hours

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle.kts
This upgrades to Gradle 6.8 and takes advantage of the new central declaration of repositories feature.
> Update to Gradle 6.8

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
> Update link to security blog post

- buildSrc/src/main/kotlin/Config.kt
https://firebase.google.com/support/release-notes/android#google-services_plugin_v4-3-5
https://developer.android.com/jetpack/androidx/releases/work#2.5.0
https://developer.android.com/jetpack/androidx/releases/biometric#1.1.0
https://developer.android.com/jetpack/androidx/releases/navigation#version_233_3
https://developer.android.com/jetpack/androidx/releases/constraintlayout#2.0.4
> Bump some more dependencies

- app/src/full/java/io/homeassistant/companion/android/location/HighAccuracyLocationService.kt
I noticed that i get sometimes doubled high accuracy notifications. Sadly I can't reproduce this. Because of that, i improved the service with some safety checks to hopefully get rid of the doubled notification.
- Run service in NOT STICKY mode instead of REDELIVER_INTENT mode, because the service will restart itself on the next sensor update, if the system was in low memory mode.
- Call stopForeground(true) if service gets destroy to remove the notification
- Block external service starts/stop while restarting service
- Add debug logs for service
> Improve high accuracy mode

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Detects 3 finger swipe down gesture only on the webview activity launch the quickbar by sending the keycode for `e`.  When the quickbar is open the swipes will flip between the 2 types of quickbar views.
https://photos.app.goo.gl/39KVvKNP6upAcPP47
Documentation: home-assistant/companion.home-assistant#459
> Webview gesture quickbar

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
For devices that support it we will print the webview package name and version, should help with debugging purposes if we or the user ever need it.
```
2021-02-11 09:56:20.092 17891-17891/io.homeassistant.companion.android.debug D/WebviewActivity: Current webview package com.google.android.webview and version 88.0.4324.152
```
> Log webview package and version

- .github/actions/create-release-notes/action.yml
- .github/workflows/pr.yml
Fix the release notes generation
N/A
N/A
> Add some logging to release note generator.

- app/build.gradle.kts
Disable failing lint in Github.
N/A
N/A
> Disable failing lint in Github.

- app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/ServiceData.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/ServiceFields.kt
Adds support for targets (well, only shows entity id now, like before)
Fixes https://github.com/home-assistant/android/issues/1376
> Add support for target to button widget configure

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
- app/src/main/java/io/homeassistant/companion/android/launch/my/MyActivity.kt
- app/src/main/java/io/homeassistant/companion/android/util/UrlHandler.kt
- app/src/main/res/layout/activity_my.xml
Add basic support for [my.home-assistant.io](my.home-assistant.io) and `homeassistant://navigate/`.
https://github.com/home-assistant/my.home-assistant.io/pull/4
> Add my.home-assistant.io support

- app/src/main/java/io/homeassistant/companion/android/util/UrlHandler.kt
Fixes: https://github.com/home-assistant/android/issues/1388
> Fix URL handling

- app/src/main/java/io/homeassistant/companion/android/util/UrlHandler.kt
Ensure we don't get multiple `/` in the URL unintentionally when handling `homeassistant://navigate/` URLs.
> Fix potential issue with `homeassistant://navigate/` handling.

- app/src/main/java/io/homeassistant/companion/android/util/UrlHandler.kt
> Make sure we don't get double `/`

- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryFragment.kt
- app/src/main/res/layout/fragment_discovery.xml
- app/src/main/res/values/strings.xml
Noticed a small trend in play store reviews from users who never heard of Home Assistant and were utterly confused until they found the home page. There is now a "What is this?" link at the top for users who don't know what an instance is so they are not confused.
> Add a link during onboarding for new users

- .github/workflows/pr.yml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values-night/styles.xml
Fixes a side effect from #1397 
> Restore night theme

- build.gradle.kts
- buildSrc/src/main/kotlin/Config.kt
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle.kts
Bumping versions of dependencies.
> Bump versions, Kotlin, Gradle, etc.

- app/src/main/java/io/homeassistant/companion/android/authenticator/Authenticator.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Fixes the following sentry error by directly setting the title in the method, this seems similar to the blank notification title we saw with the `Sensor Worker` so the fix is the same:
```
java.lang.IllegalArgumentException: Title must be set and non-empty.
at androidx.biometric.BiometricPrompt$PromptInfo$Builder.build(BiometricPrompt.java:570)
at io.homeassistant.companion.android.authenticator.Authenticator.authenticate(Authenticator.kt:46)
at io.homeassistant.companion.android.webview.WebViewActivity.onWindowFocusChanged(WebViewActivity.kt:740)
at androidx.appcompat.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:124)
at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:2319)
at …
```
> Fix blank title for authenticator

- common/build.gradle.kts
- common/src/main/java/io/homeassistant/companion/android/common/data/HomeAssistantRetrofit.kt
Fixes: #1364 by using a custom user agent string that also contains the app version for identification
> Use a custom user agent string to avoid being blocked

- .github/actions/download-translations/action.yml
> Don't use empty translations.

- app/src/main/java/io/homeassistant/companion/android/sensors/AppSensorManager.kt
Fixes the following sentry by skipping the iteration if we have no running processes:
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
at io.homeassistant.companion.android.sensors.AppSensorManager.updateImportanceCheck(AppSensorManager.kt:243)
at io.homeassistant.companion.android.sensors.AppSensorManager.requestSensorUpdate(AppSensorManager.kt:100)
at io.homeassistant.companion.android.sensors.SensorDetailFragment$onCreatePreferences$$inlined$let$lambda$1.onPreferenceChange(SensorDetailFragment.kt:103)
at androidx.preference.Preference.callChangeListener(Preference.java:1118)
at androidx.preference.TwoStatePreference.onClick(TwoStatePreference.java:67)
at …
```
> Only get the state of importance if we have running processes

- app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetDynamicFieldAdapter.kt
Fixes the below sentry error by only saving the text if we are in bounds
```
java.lang.IndexOutOfBoundsException: Index: 9, Size: 1
at java.util.ArrayList.get(ArrayList.java:437)
at io.homeassistant.companion.android.widgets.common.WidgetDynamicFieldAdapter$onBindViewHolder$3.afterTextChanged(WidgetDynamicFieldAdapter.kt:144)
at android.widget.TextView.sendAfterTextChanged(TextView.java:10588)
at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13429)
at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1277)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder. …
```
> Fix out of bounds exception in field adapter

- buildSrc/src/main/kotlin/Config.kt
https://github.com/getsentry/sentry-java/compare/3.2.1...4.3.0
https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.4.3
https://github.com/material-components/material-components-android/releases/tag/1.3.0
https://square.github.io/okhttp/changelog/#version-491
https://github.com/Dimezis/BlurView/compare/version-1.6.5...version-1.6.6
https://github.com/FasterXML/jackson-module-kotlin/compare/jackson-module-kotlin-2.12.1...jackson-module-kotlin-2.12.2
https://github.com/google/dagger/releases/tag/dagger-2.33
> Bump some dependencies

- app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
This PR fixes broken database migration.
> Fix broken database migration

- app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
Fixes: #1456 
Looks like we had this hard coded instead of using what was provided in the notification service call
> Use service call provided action title for reply actions

- app/src/full/java/io/homeassistant/companion/android/location/HighAccuracyLocationService.kt
- app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/util/ForegroundServiceLauncher.kt
- app/src/main/res/values/strings.xml
This PR tries to fix following error in the high accuracy location service:
`Context.startForegroundService() did not then call Service.startForeground()`
This is a very common error when using Android services. Some say, this is fault of the android framework and some say it's the fault of the app. 
Please read here: https://stackoverflow.com/questions/44425584/context-startforegroundservice-did-not-then-call-service-startforeground
The error occurred, for me,  this morning randomly, resulting in a non working high accuracy mode.
I tried to fix this issue by calling the `startForeground` method as soon as possible. And that is in the `onCreate` method of the service. Previously it was called in the `onStartCommand` method. Maybe this was too late in some circumstances.
Additionally i …
> Rework high accuracy location service

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/settings/log/LogFragment.kt
- app/src/main/java/io/homeassistant/companion/android/util/LogcatReader.kt
This PR improves the show and share log feature. 
- Fix crash on screen rotation, due that enabled screen rotation for settings activity
- Fixed first automatic scroll down after showing log
- Faster logcat reading
- Use correct lifecycleScope instead of globalScope
> Improve Show and Share Log

- app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenter.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
Noticed that opening settings is a bit slow. Turns out it is the `getRateLimits` call which runs blocking.
Now the `getRateLimits` call runs in the IO thread an updates the settings fragment as soon it's ready.
`onCreatePreferences` method of `SettingsFragment` call time before fix:
```
2021-04-02 22:15:18.942 20598-20598/io.homeassistant.companion.android.debug D/SettingsFragment: Time: 1135
2021-04-02 22:15:25.014 20598-20598/io.homeassistant.companion.android.debug D/SettingsFragment: Time: 584
2021-04-02 22:15:28.839 20598-20598/io.homeassistant.companion.android.debug D/SettingsFragment: Time: 678
2021-04-02 22:15:32.934 20598-20598/io.homeassistant.companion.android.debug D/SettingsFragment: Time: 783
2021-04-02 22:15:36.240 20598-20598/io.homeassistant.companion.android.debug …
```
> Fix slow settings startup

- app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
- app/src/main/res/values/strings.xml
This PR fixes the missing translation for the notification rate limit preference. Also the "Reset at" date will be formatted to the locale of the system (If Android >= Oreo)
> Fix notification rate limit translation

- app/src/main/java/io/homeassistant/companion/android/settings/log/LogFragment.kt
This PR fixes missing log fragment title.
> Fix missing log fragment title

- app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
Allow users to control any active media session provided they know the package and send a proper command
Users can pause, play and any other supported media key event by the app.
I have tested pause and play with spotify.
Notification will post as normal if the proper data is not received or active media sessions are not found
```
message: command_media
title: play
data:
channel: com.spotify.music
```
Documentation: home-assistant/companion.home-assistant#494
FCM: https://github.com/home-assistant/mobile-apps-fcm-push/pull/45
> Add a command to control active media sessions

- app/src/full/java/io/homeassistant/companion/android/location/HighAccuracyLocationService.kt
- app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
Fixes #1509 
This PR fixes:
- High accuracy mode notification remains visible although the high accuracy mode was switched off
- Hopefully fixes the multiple registration of the location requests
- Enhance logging, to see more info about multiple location requests. 
> High accuracy mode fixes

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
- app/src/main/java/io/homeassistant/companion/android/database/qs/TileDao.kt
- app/src/main/java/io/homeassistant/companion/android/database/qs/TileEntity.kt
- app/src/main/java/io/homeassistant/companion/android/qs/Tile1Service.kt
- app/src/main/java/io/homeassistant/companion/android/qs/Tile2Service.kt
- app/src/main/java/io/homeassistant/companion/android/qs/Tile3Service.kt
- app/src/main/java/io/homeassistant/companion/android/qs/Tile4Service.kt
- app/src/main/java/io/homeassistant/companion/android/qs/Tile5Service.kt
- app/src/main/java/io/homeassistant/companion/android/qs/TileComponent.kt
- app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsComponent.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
- app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesFragment.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
- app/src/main/res/drawable/ic_tile.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
- app/src/main/res/xml/quick_setting_tiles.xml
Adds support for quick settings tiles to execute a script/scene!
https://developer.android.com/reference/android/service/quicksettings/package-summary
As we have to define each tile in the manifest and link it to its own class I have opted to start with 5 and based on user feedback we can add more easily.
Users are required to set the label and select an entity ID. Subtitle is optional and an icon can be selected too.  Once a tile is added we will update the tile data when it is visible and when the user clicks on the tile.  Adding a tile with proper data set will show as inactive and will be active once selected and will go back to inactive upon success.  Failures will show a toast message and tiles added without any data will be in an unavailable state.
Documentation: …
> Add quick settings tiles for scripts and scenes

- app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
> Fix DB Migration.

- app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
Fixes the following sentry errors
This sentry error is odd as `onStartListening` gets called when a tile has already been added and is visible so the system should've register it already without us needing to.  Looking at the trend it seems to be Lenovo devices only so maybe something specific? Just catching the error so we don't crash the app, I have not seen this personally.
```
java.lang.IllegalArgumentException: Service not registered: com.android.systemui.qs.external.TileLifecycleManager@b017d21
at android.os.Parcel.readException(Parcel.java:2009)
at android.os.Parcel.readException(Parcel.java:1951)
at android.service.quicksettings.IQSService$Stub$Proxy.updateQsTile(IQSService.java:215)
at android.service.quicksettings.Tile.updateTile(Tile.java:182)
at …
```
> Catch a QS tile crash and add a null check

- app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/UpdateLocation.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/UpdateLocationRequest.kt
- common/src/test/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImplSpec.kt
- common/src/test/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationServiceSpec.kt
This is one of the fixes for https://github.com/home-assistant/core/issues/51127 which was caught during beta testing for HA core 2021.6.  As we were always sending a blank string we might as well remove it as the fix will work with versions before and after 2021.6.
This may have been caused by one of the typing PRs submitted to HA core.
> Remove location name from location updates since its always blank

- .github/dependabot.yml
- .github/workflows/beta.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/weekly.yaml
Update the setup-java action to v2.  Needed additional parameters.
Also dependabot recursively looks for build files, only need one.
> Setup Java Update + dependabot update

- app/build.gradle.kts
- app/src/full/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
- app/src/full/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
- app/src/main/java/io/homeassistant/companion/android/launch/LaunchPresenterBase.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterBase.kt
- build.gradle.kts
- common/build.gradle.kts
- wear/build.gradle.kts
Update dependencies w/ changes needed to actually run the application.  Basically needed to get Firebase token on io thread not main.
> Dependency Updates.

- app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
- app/src/main/res/values/strings.xml
Fixes: #1567 
Documentation: home-assistant/companion.home-assistant#566
> Add a binary sensor for the state of high accuracy mode

- app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
> Fix service call for tiles to account for scenes

- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
As discussed this check is no longer needed.
> Remove version check during registration

- app/src/main/java/io/homeassistant/companion/android/sensors/DNDSensorManager.kt
Removes the old icon name as its removed in a future release of MDI. The new name has been around since MDI 1.x so don't need to worry about backwards compatibility here :)
Related: https://github.com/home-assistant/frontend/pull/10002
Enabled all sensors to ensure no other warnings for any existing sensor.
> Use a better icon name for DND (same icon just wont be removed in future release)

- app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationPresenterImpl.kt
To help #1708 with troubleshooting so we can see the actual error.
> Print the stack trace when authentication fails during onboarding

- app/src/main/java/io/homeassistant/companion/android/settings/log/LogFragment.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
Just use androidx.core.view.isVisible, for less code
> use androidx.core.view.isVisible

- app/build.gradle.kts
https://developer.android.com/jetpack/androidx/releases/work#version_260_3
> Bump work manager dependency

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
> Add permissions for modify audio settings for webview activity

- app/src/main/AndroidManifest.xml
> Fix sharing export flag

- app/build.gradle.kts
Bump the compose libraries to the latest
> Bump compose libraries

- app/build.gradle.kts
- app/src/full/java/io/homeassistant/companion/android/notifications/NotificationAction.kt
- app/src/full/java/io/homeassistant/companion/android/settings/SettingsWearActivity.kt
- app/src/main/java/io/homeassistant/companion/android/launch/my/MyActivity.kt
- app/src/main/java/io/homeassistant/companion/android/nfc/NfcEditFragment.kt
- app/src/main/java/io/homeassistant/companion/android/nfc/NfcReadFragment.kt
- app/src/main/java/io/homeassistant/companion/android/nfc/NfcSetupActivity.kt
- app/src/main/java/io/homeassistant/companion/android/nfc/NfcWelcomeFragment.kt
- app/src/main/java/io/homeassistant/companion/android/nfc/NfcWriteFragment.kt
- app/src/main/java/io/homeassistant/companion/android/nfc/SingleLiveEvent.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryFragment.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupFragment.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetDynamicFieldAdapter.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidgetConfigureActivity.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
- wear/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationActivity.kt
- wear/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationActivity.kt
- wear/src/main/java/io/homeassistant/companion/android/onboarding/manual_setup/ManualSetupActivity.kt
- wear/src/main/java/io/homeassistant/companion/android/util/LoadingView.kt
Removes kotlin-android-extensions and replaces it with ViewBinding, which was already included in the codebase.
N/A - code refactor
N/A
Also updated some findViewById calls.
Patterns are based on the codebase and Android Developers documentation site.
> Replace kotlinx.android.synthetic with viewbinding

- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
> Fix version check.

- wear/build.gradle.kts
- wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/ListHeader.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/OtherSection.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
- wear/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt
Makes use the Android Studio preview feature for compose units. Should help with reducing the back and forth when tweaking a design and such.
> Add preview functions for easy UI tweaking in Android Studio

- wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
- wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
- wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
- wear/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt
Now while the wear os app is open we get instant feedback when entities change!
N/A
> Wear OS Instant Updates

- .github/dependabot.yml
Rather than letting dependencies build up, lets hear about them daily.
N/A
N/A
> Get dependabot to run daily

- app/src/main/java/io/homeassistant/companion/android/webview/WebView.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
By material design spec, the navigation bar should have the same color as the background color of the app or the bottom navigation bar element.
Currently the navigation bar has the same color as the status bar, which results in a "interesting" ui.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
> Change navigation bar background color to be the same as the app's background color

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/BaseWidgetProvider.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/DataModule.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
This PR gets widgets to update near instantly by using the websocket!  Clicking the template will update the value as well.
N/A
> Instant Update Widgets

- wear/build.gradle.kts
https://developer.android.com/jetpack/androidx/releases/wear-compose#1.0.0-alpha11
https://developer.android.com/jetpack/androidx/releases/appcompat#1.4.0
> Bump wear libraries

- app/src/main/java/io/homeassistant/companion/android/nfc/NfcSetupActivity.kt
> Fix NFC crash when inside read fragment

- app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
- app/src/minimal/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
Fixes:  #1958 
Fixes: #1961 
N/A
N/A
> Multiple Bug Fixes

- common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
> Fix Websocket crash when we don't get exactly what we expected.

- app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt
Fixes issue with media player widget and images hosted not on actual Home Assistant Instance.
> Ensure media sources such as Pandora work as expected for Widget.

- app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearFavoritesView.kt
We slightly changed the URLs and I forgot to update the link here
> Fix broken docs link since companion site change

- .github/workflows/release.yml
Fixes an issue with not publishing wear bundle.
> Fix issue with not publishing / promoting wear bundle on release.

- common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
Fixes https://github.com/home-assistant/android/issues/1969
> `context` is optional for Entities.

- app/build.gradle.kts
- app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
- app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
- common/build.gradle.kts
- wear/build.gradle.kts
- wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/EntityListView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SetTileShortcutsView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
- wear/src/main/java/io/homeassistant/companion/android/util/RotaryEventDispatcher.kt
https://github.com/material-components/material-components-android-compose-theme-adapter/releases/tag/material-v1.1.1
https://developer.android.com/jetpack/androidx/releases/navigation#2.4.0-rc01
https://developers.google.com/android/guides/releases#december_16_2021
https://developers.google.com/android/guides/releases#december_09_2021
https://developer.android.com/jetpack/androidx/releases/wear-compose#1.0.0-alpha13
https://developer.android.com/jetpack/androidx/releases/room#2.4.0
Some dependency updates:
*  Wear OS compose bump required changes for rotary input
*  Location update required chagnes to both activity sensors and single accurate location (both tested to work on my end)
For API 25 in `RotaryEventDispatcher` we are using this method which should be safe given the source: …
> Bump dependencies and make required changes

- app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
- common/src/main/res/values/strings.xml
Falls in line with some of the configuration screens like Energy and Home Assistant Cloud since the title is kept the same there
> Update settings screen title to match Configuration menu

- app/src/main/AndroidManifest.xml
Fixes: #2064  apparently some launchers still want export to be `true` while this works fine in other launchers.
> Export widget configuration activities for launcher that require it

- app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt
- app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
- app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
- app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesFragment.kt
- app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt
- app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidgetConfigureActivity.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/HomeAssistantApis.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationRepositoryImpl.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationService.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationService.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
- wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
- wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
- wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
- wear/src/main/java/io/homeassistant/companion/android/tiles/TileActionReceiver.kt
This PR attempts to better handle exceptional cases better that throwing exceptions and allowing them to crash the app.  This should hopefully gracefully stop working rather than hard crashing.
Fixes: https://github.com/home-assistant/android/issues/2056
> Work on error handling from Websocket.

- app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
Fixes: #2096 by skipping updates only if the sensor settings were not configured at all
> Fix allow list in notification sensors

- .github/actions/inflate-secrets/action.yml
- .github/mock-google-services.json
- .github/workflows/beta.yml
- .github/workflows/release.yml
- README.md
- app/build.gradle.kts
- app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
- app/src/quest/AndroidManifest.xml
- app/src/quest/java/io/homeassistant/companion/android/CrashHandling.kt
- app/src/quest/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
- app/src/quest/java/io/homeassistant/companion/android/onboarding/MessagingToken.kt
- app/src/quest/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
- app/src/quest/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
- app/src/quest/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
- app/src/quest/java/io/homeassistant/companion/android/settings/wear/SettingsWearActivity.kt
- app/src/quest/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearMainView.kt
Introduces 2 new build variants for the Quest as a release version and a debug version. Hopefully I got everything right. The idea here was to make it match the `minimal` flavor while also complying with the pre-requisites from Oculus. Also went ahead and hid some features from settings that are just not available on this flavor. 
https://developer.oculus.com/resources/publish-uploading-mobile/
As of now notifications are only allowed for apps that are published to the Oculus Quest store so until we get to that point we cannot test that feature. In terms of sensors we have 47 of them and all seem to be functional. Some good sensors for this device asides from battery and charging status would be the new Last Used app sensor and also the Interactive sensor to determine when the device is …
> Initial commit of the Quest build

- app/src/quest/AndroidManifest.xml
Missed this change in #2110 🙈 
> Set the GLES version for quest variant

- app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/QuestSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
- common/src/main/res/values/strings.xml
Adds a mount state sensor to the quest
Shows as a binary sensor on the frontend 
Documentation: home-assistant/companion.home-assistant#659
N/A
> Add Mount State sensor to the Quest

- app/src/main/java/io/homeassistant/companion/android/controls/DefaultButtonControl.kt
- app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
- common/src/main/res/values/strings.xml
Home Assistant 2021.12 [added the button entity type](https://www.home-assistant.io/blog/2021/12/11/release-202112/#the-button-entity), and 2022.2 [will add the _input_ button entity type](https://github.com/home-assistant/home-assistant.io/blob/next/source/_integrations/input_button.markdown). This PR allows adding them to and pressing them from the Android device controls.
The existing `SceneControl` which is used for scenes and scripts already acts like a button (stateless square you can press), so it has been renamed `DefaultButtonControl` and updated for the (input) button entity type.
The UI is provided by the system, this is on a Google Pixel 4a running Android 12. Only showing buttons but input buttons look and work the same.
|View when added|Add controls screen|
|-----|-----| …
> Support button entity type for device controls

- app/build.gradle.kts
https://developers.google.com/android/guides/releases#january_05_2022
> Bump to latest google play location service

- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/HomeAssistantSearcher.kt
Fixes: #2141 so `onError()` can be shown
> Catch the nsd discovery failure so we show the error

- wear/build.gradle.kts
- wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
Updates wear compose to 1.0.0-alpha14 and removes the BackHandler in HomeView.kt as it is now natively supported in alpha14
https://developer.android.com/jetpack/androidx/releases/wear-compose#1.0.0-alpha14
> Update Compose And Remove BackHandler

- app/src/full/java/io/homeassistant/companion/android/notifications/FirebaseCloudMessagingService.kt
- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
- app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationHistoryFragment.kt
- app/src/main/java/io/homeassistant/companion/android/settings/notification/views/NotificationDetailView.kt
- app/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt
- app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt
- app/src/main/res/xml/preferences.xml
- common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
- common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
- common/src/main/java/io/homeassistant/companion/android/database/notification/NotificationItem.kt
- common/src/main/res/values/strings.xml
Fix a bunch of small issues that were found with Websocket notifications.
* Race condition in Websocket send
* Add source of notification (FCM vs Websocket)
* Fix missing pings when we should be ensuring a Websocket connection
* Move Websocket setting into other since it's not technically only about notifications.
> Websocket Notification Bug Fixes

- README.md
Just some minor clean up from some left over parts after the last update, the instructions were actually moved down to a new section so they are no longer needed here.
> Remove duplicate building notes from readme

- wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/EntityListView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/ExpandableListHeader.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/ListHeader.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SetTileShortcutsView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/TemplateTileSettingsView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/ThemeLazyColumn.kt
Adds helpers for duplicate Wear Compose code. Lots of layout-related code is duped in every Wear OS screen, and the goal here is to make it easier to keep things consistent.
> Add helpers for duplicate Wear Compose code

- app/build.gradle.kts
- common/build.gradle.kts
- wear/build.gradle.kts
- wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/EntityListView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SetTileShortcutsView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/TemplateTileSettingsView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/ThemeLazyColumn.kt
- wear/src/main/java/io/homeassistant/companion/android/util/RotaryEventDispatcher.kt
Bump some dependencies and also fix Wear OS rotary input after #2175 
https://developer.android.com/jetpack/androidx/releases/appcompat#1.4.1
https://github.com/androidx/constraintlayout/wiki/What's-New-in-2.1#new-features-in-213
https://github.com/material-components/material-components-android/releases/tag/1.5.0
https://github.com/material-components/material-components-android-compose-theme-adapter/releases/tag/material-v1.1.3
https://developer.android.com/jetpack/androidx/releases/room#2.4.1
> Bump app dependencies and fix wear rotary input

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Adds a new notification command to update sensors.
`message: command_update_sensors`
Documentation: home-assistant/companion.home-assistant#666
FCM: https://github.com/home-assistant/mobile-apps-fcm-push/pull/65
> Add notification command to update sensors

- app/src/main/res/xml/changelog_master.xml
Just to keep things current :)
> Mention recent merges in changelog

- app/src/main/res/xml/changelog_master.xml
Just a small update to the changelog based on some discussion and feedback 
> Update changelog to reduce duplicates and mention all websockets changes together

- common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
Just to help with troubleshooting instant updates lets make sure to print the intents that get pushed to the sensor receiver.
> Log the received intent to help with troubleshooting instant updates

- app/src/main/java/io/homeassistant/companion/android/settings/websocket/WebsocketSettingViewModel.kt
Make sure UI displays default setting correctly.  Before it would always default the UI to Screen On.
N/A
N/A
> Make sure UI displays default setting correctly.

- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/RegisterDeviceRequest.kt
Since 2022.2 supports websocket only notifications it should be safe to only support this on the newer installs rather than the hack that was in place.
Core PR: https://github.com/home-assistant/core/pull/63208
> Only support websocket only notifications on 2022.2 and above.

- app/src/main/res/xml/changelog_master.xml
updates the changelog for all changes done this week
> Weekly update for changelog

- app/src/main/java/io/homeassistant/companion/android/sensors/LastAppSensorManager.kt
- app/src/main/res/xml/changelog_master.xml
Fixes: #2249 by providing the old state as an attribute
Documentation: home-assistant/companion.home-assistant#679
> Add an attribute to last used app sensor for the label

- app/src/main/res/xml/changelog_master.xml
> Bump change log version.

- app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
- app/src/main/java/io/homeassistant/companion/android/settings/websocket/views/WebsocketSettingView.kt
> Make persistent connection and manage tiles settings screens scrollable

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Fixes the below sentry error by ensuring the value is as expected
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.Collections$SingletonList.get(Collections.java:4872)
at io.homeassistant.companion.android.notifications.MessagingManager.handleSmallIcon(MessagingManager.kt:804)
at io.homeassistant.companion.android.notifications.MessagingManager.sendNotification(MessagingManager.kt:722)
at io.homeassistant.companion.android.notifications.MessagingManager.access$sendNotification(MessagingManager.kt:77)
at io.homeassistant.companion.android.notifications.MessagingManager$handleMessage$12.invokeSuspend(MessagingManager.kt:367)
at …
```
> Add better notification icon checks to ensure the value is as expected

- app/src/main/res/xml/changelog_master.xml
Updating changelog earlier as it felt odd seeing changes from 2022.2 still :P
> Changelog update for week of 2/16

- app/src/full/AndroidManifest.xml
- app/src/main/AndroidManifest.xml
Fixes: #2296 
Was able to reproduce the issue and can confirm the fix
> Fix notification receivers for all builds

- app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/TransmitterManager.kt
- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/database/sensor/SensorDao.kt
Fixes: #2149 by allowing the command to accept more options.
examples:
```
message: command_ble_transmitter
title: ble_set_transmit_power
data:
ble_transmit: ble_transmit_low
```
```
message: command_ble_transmitter
title: ble_set_advertise_mode
data:
ble_advertise: ble_advertise_balanced
```
Documentation: home-assistant/companion.home-assistant#695
> Enhance command_ble_transmitter to change additional options

- app/src/main/res/xml/changelog_master.xml
> Changelog update for week of 2/25

- app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
Fixes: #2333 by ensuring that we properly remove and request location updates along with the command.
> Make sure to remove and start location updates when controlled via command

- app/src/main/res/xml/changelog_master.xml
only 1 new feature this week, rest of changes were bug fixes :)
> Update change log for week of 3/4

- wear/src/main/java/io/homeassistant/companion/android/tiles/TemplateTile.kt
> Add haptic feedback to templite tile refresh

- common/src/main/res/values/strings.xml
Noticed while testing a debug build from the actions tab that we missed updating 1 string to reflect the setting name change.
> Replace websocket with persistent connection in string

- app/src/main/res/xml/changelog_master.xml
Mentioning 2 new features, rest are all bug fixes
> Update changelog for week of 3/11

- app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
Fixes #2102
Fixes #2382
I hope this PR fixes the turning on of the high accuracy mode via the command.
Once the command to turn on the high accuracy mode is sent, the high accuracy mode will stay on until you enter one of the expanded zones. From this point on, the high accuracy mode will no longer be forced on, instead it will revert to normal mode.
As soon as you leave the expanded zone, the high accuracy mode is switched off.
> Fix high accuracy mode turns off after turning on with command

- app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
This PR fixes the problem that no real new line control char were replaced. Until now only "\n" in strings were replaced, but not the new line control char.
> Fix new line in message

- app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
Fixes: #2386 by checking that display name is not null and also catching any other potential failures
> Fix SIM sensor crash

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Fixes #2401
Documentation: https://github.com/home-assistant/companion.home-assistant/pull/721
> Correct minimal value for high_accuracy_set_update_interval

- wear/src/main/java/io/homeassistant/companion/android/data/SimplifiedEntity.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SetTileShortcutsView.kt
- wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt
Fixes #2403 by using an extension property so something simple like this won't happen in the future
n/a
n/a
> Fix Wear default domain icon on shortcut tile

- common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
Bumps the DB version to prevent a crash that showed up after the latest beta
```
2022-03-25 10:24:18.922 24171-24171/io.homeassistant.companion.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
Process: io.homeassistant.companion.android.debug, PID: 24171
java.lang.RuntimeException: Unable to create application io.homeassistant.companion.android.HomeAssistantApplication: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6767)
at android.app.ActivityThread.access$1500(ActivityThread.java:256)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091) …
```
> Bump DB version to prevent a crash on updating

- app/src/main/res/xml/changelog_master.xml
> Update changelog for week of 3/25

- app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationFragment.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/HomeAssistantApis.kt
This PR updates the user agent used by the app to improve compatibility with sites that use user agent sniffing and to be more consistent, both for the different modules and with the iOS app. Because some users expect a certain user agent string from the app, **this is a breaking change**. Fixes #2438.
The app's main user agent is updated to `Home Assistant/{app version} (Android {Android version}; {device model})`: the same string for okhttp calls and the webview instead of different app versions, and a format that better matches 'normal' browsers and [the iOS app](https://github.com/home-assistant/iOS/blob/cd6534b12ce3e1cd30889cd2fcf74cf635ce80b5/Sources/Shared/API/HAAPI.swift#L58) (but not exactly the same as iOS to limit what information is exposed). Example output:
```
Home …
```
> Breaking change: update user agent and append to webview UA

- app/src/main/res/xml/changelog_master.xml
> Update change log for week of 4/16

- app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingViewModel.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationView.kt
- app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailViewModel.kt
- app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/database/sensor/SensorDao.kt
- wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
Working on SensorDao some more to move database operations into Room transactions.
> Move SensorDao operations to Transactions

- app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
This PR fixes #1206 by converting common types in the notification's bundle that don't provide human readable text when `toString()` is used, to a format that will result in human readable text.
For example, the original issue mentions multiple messages:
- Depending on the conversation, these will now will be readable in `android.textLines`: the attribute will show something like `[Message 1, Message 2]` instead of `[Ljava.lang.String;@5d099f62`. 
- The `android.messages` attribute in the active notifications sensor will also be mapped to something like `[{extras={}, sender_person=android.app.Person@3ad7a7bf, sender=+31 6 12345678, text=Message 1, time=1651061234000}, {extras={}, sender_person=android.app.Person@72a1ed2c, sender=+31 6 12345678, text=Message 2, time=1651061245000}]` …
> Notification sensors: make arrays and bundles within main bundle readable

- app/src/main/res/xml/changelog_master.xml
> Update changelog for week of 4/30

- app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
> Fix bad merge

- app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
- app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesFragment.kt
- app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesViewModel.kt
- app/src/main/java/io/homeassistant/companion/android/settings/qs/TileSlot.kt
- app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
- common/src/main/java/io/homeassistant/companion/android/database/qs/TileDao.kt
- common/src/main/java/io/homeassistant/companion/android/database/qs/TileEntity.kt
Removes blocking calls and reduces recompositions in ManageTilesView. The viewmodel was rewritten to use private setters and suspend functions.
> Update ManageTilesView for performance

- app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationChannelFragment.kt
- app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorSettingsFragment.kt
- app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorSettingsViewModel.kt
- app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorUpdateFrequencyFragment.kt
- app/src/main/java/io/homeassistant/companion/android/settings/websocket/WebsocketSettingFragment.kt
- app/src/main/java/io/homeassistant/companion/android/settings/widgets/ManageWidgetsSettingsFragment.kt
There was an issue with missing annotations needed by hilt.  Really fixes: https://github.com/home-assistant/android/issues/2565
> Fix issues with initing view models.

- app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
Fixes #2580 
If the app is unable to map a `Bundle`, it will include a string representation instead when it is not the top-level `Bundle` to distinguish it from `null` values. Based on my tests, this usually looks like `Bundle[{}]` with any basic objects such as strings, int etc still readable.
n/a
n/a
> Fix crash when notification extras cannot be mapped

- app/src/main/java/io/homeassistant/companion/android/settings/websocket/views/WebsocketSettingView.kt
- common/src/main/res/values/strings.xml
Fixes: #2582 to remove mention of Google so the text is more clear about whats required or not for when notifications can be received.
Making sure not to mention the minimal flavor but also making it clear how each option is intended to work.
> Use minimal specific string for home wifi option on persistent connection

- app/src/main/res/xml/changelog_master.xml
> Update changelog for week of 6/9

- app/build.gradle.kts
- app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
Noticed that the play services location dependency had an update so made the necessary changes, did a quick test as well and location update and geofencing still occurs.
https://developers.google.com/android/guides/releases#june_7_2022
> Update location service dependency

- app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
Fixes #1409 by rendering vector icons in `ButtonWidget`s at a resolution large enough to fill the widget (instead of always rendering at the icons' "intrinsic" dimensions, which seem to typically be 24x24).
**Before:**
**After:**
N/A (I think!)
- Due to the way the widget rendering lifecycle works, if a widget is resized (from small to large), the icon resolution increase won't take place automatically. The re-rendered icon will appear after the user interacts with the button or re-configures the widget.
- Evidently, there's no simple way to retrieve the actual size of the button's ImageView (or of the widget itself), so I've chosen to calculate dimensions based on AppWidgetManager's [OPTION_APPWIDGET_MAX_WIDTH](https://developer.android.com/reference/android/appwidget/AppWidgetManager#OPT …
> Render widget button icons at higher resolutions

- app/src/debug/res/mipmap-anydpi-v26/ic_launcher_round.xml
- app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Implement a themed app icon according to Android 13 user eperience
https://developer.android.com/about/versions/13/features#themed-app-icons
> Implement a themed app icon

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
We have been seeing a lot of users having issues with loading the HA frontend. In most of those cases it seems users have enabled Prioritize Internal even when they don't typically leave location off. This is not a big issue when using API calls because we silently fail and try other URLs. When it comes to WebView we can't reliably detect when it fails to load and the feature prioritize internal is for our users who actually leave location off on their device typically and are ok with the needing to refresh the window. This ends up causing users confusion as to why HA is not loading.
Now we will only try the internal URL if location is disabled on the device and prioritize internal is enabled, otherwise if location is enabled the app will continue to function as it does which includes …
> Only apply prioritize internal to WebView when location is disabled on the device

- app/src/main/res/xml/changelog_master.xml
> Update changelog for week of 7/1

- common/schemas/io.homeassistant.companion.android.database.AppDatabase/30.json
- common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
- common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
- common/src/main/java/io/homeassistant/companion/android/database/sensor/Sensor.kt
- common/src/main/java/io/homeassistant/companion/android/database/sensor/SensorDao.kt
Show the charging state on the Battery Level sensor's icon.
A different icon will be shown for wired and wireless charging.
A new DB property called `last_sent_icon` is added, so I needed to implement a new DB migration.
A side effect of these changes:
From now on, changing only the icon (but not the state) of a sensor will also trigger sending an update to the server.
Wired charging:
Wireless charging:
Not charging:
Wear OS:
> Show the charging state on the Battery Level sensor's icon

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
Fixes: #2470 by introducing new parameters for BLE command.
- `ble_set_uuid` with `ble_uuid` to change the UUID
- `ble_set_major` with `ble_major` to change Major
- `ble_set_minor` with `ble_minor` to change Minor
Documentation: home-assistant/companion.home-assistant#783
FCM: https://github.com/home-assistant/mobile-apps-fcm-push/pull/84
> Allow UUID, Major and Minor to be changed via notification command

- app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationFragment.kt
- common/src/main/res/values/strings.xml
Noticed in our Authentication Fragment that we were not printing errors, we should still print errors in case our error messages are not completely correct to help with troubleshooting.
I have also changed the generic error message to include error content like status code and description
Ref: https://discord.com/channels/330944238910963714/377667559303938050/1001786919665012736
> Improve logging and error messages during onboarding

- common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
When logging out in the app (or the server telling the app that the user has been logged out), only session and url-related data is actually deleted, almost all other server-specific data is kept. When logging back in, this can create problems, for example for sensors because the app needs to keep track of the registration state. 
This PR updates the sensor registration checks to be able to detect registered sensors that the server doesn't know about, and will re-register them properly. Fixes #2724
This doesn't fully fix the more general problem of server-specific data not being removed on logout, and also doesn't fix sensor re-registration core versions before 2022.6. That should be handled by removing said data in [`WebViewPresenterImpl.onRevokeExternalAuth`](https://github.com/home-assi …
> Fix sensor re-registration on logout/login on core 2022.6+

- app/src/main/res/xml/changelog_master.xml
> Update changelog for week of 7/21

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Fixes: #2739 by introducing a new command `command_stop_tts` that will stop TTS. No need to check if the engine is currently running. Added `onStop` to ensure alarm volume get set back properly if `alarm_stream_max` is used.
```
message: command_stop_tts
```
Documentation: home-assistant/companion.home-assistant#786
FCM: https://github.com/home-assistant/mobile-apps-fcm-push/pull/85
> Add a notification command to stop TTS

- app/src/main/res/xml/changelog_master.xml
> Update change log for week of 8/3

- app/build.gradle.kts
> Add fragment dependency to resolve settings view model crashes

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Fixes #2706 by downloading images for notifications using the `OkHttpClient` used elsewhere in the app, which will handle any certificate authentication that might be required (as well as cookies).
n/a, notifications will show images again instead of not including them
n/a
> Use OkHttpClient to download notification images

- common/src/main/res/values/strings.xml
Noticed quickly when setting up the app for the first time, and wanted to fix the typo myself.
N/A
N/A
N/A
> Fix typo on location tracking description

- common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorWorkerBase.kt
Resolves #2164, part 2: `SensorWorker`.
The `SensorWorker` currently always starts as a foreground service, which may not be allowed on Android 12 and newer. Because it can also work in the background catch a `ForegroundServiceStartNotAllowedException` if it is thrown, to update the sensors as much as possible instead of failing/no update.
We could build a complicated check to determine if it is likely that the app will be allowed to start a foreground service, but there don't appear to be any negative consequences for only catching the exception.
While running this build over the last ~8 hours I didn't notice a substantial difference in update frequency when compared to the (also battery optimized) stable version of the app. In one update it didn't allow the stable version to start a …
> Handle foreground service restrictions for SensorWorker

- app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
Noticed that we were updating the Geocoded state `unknown` even when accuracy has not been met, just like location updates we should skip these updates completely instead of sending this state.
I also noticed that we did no time evaluation on the report, so also doing a 5 minute check here as well.
> Only update geocode sensor if accuracy and time are valid, like location updates

- common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt
- common/src/main/res/values/strings.xml
Fixes: #2796 by adding a new sensor which takes in the current and voltage and sends the wattage back to HA with current and voltage as the attributes.
Discharging:
Charging via USB;
Fast charging:
Documentation: home-assistant/companion.home-assistant#793
> Add a battery power sensor

- app/src/main/res/xml/changelog_master.xml
Small update this week as most changes are bug fixes with the exception of the Geocoded sensor which had some logic changes so best to call it out in case a users automation no longer works.
> Update changelog week of 8/19

- app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearLandingView.kt
- app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorListView.kt
- app/src/main/java/io/homeassistant/companion/android/settings/views/SettingsRow.kt
- common/src/main/res/values/strings.xml
Small UI update of the landing page for Wear OS settings in the phone app. This brings the style more in line with the rest of the settings pages
> Update companion settings landing page for Wear settings

- app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
Fixes the following error, by passing in the `sensorDao` variable instead of relying on the lateinit modifier. I was able to reproduce the error by force stopping the app and opening it again. Must be an edge case where we update location before we update sensors completely and initialize the variable.
```
[08-06 11:26:33.414 26944:11135 E/LocBroadcastReceiver]
Could not update location.
kotlin.UninitializedPropertyAccessException: lateinit property sensorDao has not been initialized
at io.homeassistant.companion.android.common.sensors.SensorReceiverBase.getSensorDao(SensorReceiverBase.kt:57)
at io.homeassistant.companion.android.common.sensors.SensorReceiverBase.updateSensor(SensorReceiverBase.kt:340)
at io.homeassistant.companion.android.common.sensors.SensorReceiverBase$updateSensor$1.i …
```
> Fix sensorDao not initialized error after geocoded update

- app/src/main/res/xml/changelog_master.xml
First update for the next release.
I opted to mention the template widget update as a breaking change in case there are other templates that needed to be adjusted like mine.
Also attempting to give a bit more info on the changes, not too much but hopefully enough to answer some more questions regarding the breaking changes.
> Update change log week of 9/2

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Fixes #2885 by allowing users to use an intent scheme URI or an app link so the app can handle these actions after user interaction as opposed to them happening as soon as they are received on the device via `command_activity` and `command_broadcast_intent`.
```
service: notify.mobile_app_pixel_6_pro
data:
message: test
data:
actions:
- action: URI
title: test
uri: "intent://scan/#Intent;scheme=zxing;package=com.google.zxing.client.android;end"
```
```
service: notify.mobile_app_pixel_6_pro
data:
message: test
data:
clickAction: "intent://scan/#Intent;scheme=zxing;package=com.google.zxing.client.android;end"
```
for deep link testing I used our own internal `homeassistant://navigate` as I dont know of any apps I have installed that do deep links 😂 
```
service: …
```
> Add support for intent scheme URI and deep links in clickAction and actionable notifications

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
- common/src/main/res/values/strings.xml
* The TTS error called out `title` which is no longer correct so updated the message to not confuse users. Also `tts_text` does not sound right so made the error more generic.
* Noticed we said `Changelog` in one place when all others are `Change Log`
* `screenlock` > `screen lock`
* Removed unused strings that I can think of
* Minor cleanup
> Change TTS error message and clean up some other strings

- common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
Fixes #2889 
- If the app checked for an active subscription [right in between removing the flow and removing the subscription ID](https://github.com/home-assistant/android/blob/8713bb9678a967d69932dd0b85e34428ce1385fa/common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt#L240), this could result in an invalid state where the app thinks there is a flow for the subscription but there isn't. To prevent this, use the same Mutex that is used for obtaining the subscription when unsubscribing so that it is either completely removed or not removed at all.
- Remove non-null assertion `!!` for the returned flow, at this point it is better to not return a flow (`null`) like for regular websocket errors than to crash.
n/a
n/a
To test, introduce …
> Fix another race condition in websocket unsubscribe/resubscribe

- app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconMonitor.kt
- app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconNameFormat.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
Fixes: #2908 by adding the `major` and `minor` for the beacon.
Listing as a breaking change since the attribute is changing
Tested using the BLE transmitter on other devices to make sure it continues to work and supply valid data.
> Breaking Change: Add major and minor to UUID for beacon attribute in beacon monitor

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 9/24

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 10/1

- app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconNameFormat.kt
- app/src/main/res/xml/changelog_master.xml
Fixes: #2928 by updating the format to have underscores instead of a space and period
HA Core PR: https://github.com/home-assistant/core/pull/79220
Discussion: https://discord.com/channels/330944238910963714/1012073425638015037/1024719158199468042
> Update iBeacon format to have underscores

- app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt
- common/src/main/res/values/colors.xml
If the `icon` attribute is present then the app will use that icon to display in device controls. The color of the icon is controlled by the state of the entity in an effort to match device type behavior.
> Show custom icon if set for the entity in device controls

- app/build.gradle.kts
- build.gradle.kts
- common/build.gradle.kts
- wear/build.gradle.kts
Bump all the Hilt deps.
N/A
N/A
> Bump Hilt version to 2.44

- app/src/main/res/xml/changelog_master.xml
Bumps release to 2022.10.1 in case we release again this month, resets the changelog for next release.
> Update change log week of 10/1 for beta

- app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt
Only adds the custom icon if it is available in the library, otherwise we stick to the cast icon
> Set the media player widget icon if available, otherwise default to cast icon

- common/src/main/res/values/strings.xml
- wear/src/main/java/io/homeassistant/companion/android/sensors/OnBodySensorManager.kt
- wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
A new hardware sensor thats specific to Wear OS. Unlike the other hardware sensors for this one I opted to keep the listener registered all the time so we can send updates as and when they happen. I figure out of all the sensors this one is most important to keep up to date.
https://developer.android.com/reference/android/hardware/SensorEvent#sensor.type_low_latency_offbody_detect: (may need to scroll down to the Values section the copied link seems odd)
https://developer.android.com/reference/android/hardware/Sensor#TYPE_LOW_LATENCY_OFFBODY_DETECT
Documentation: home-assistant/companion.home-assistant#836
I pulled in the sensor manager display fix from #2956 so this one can be ready to merge as well
I am not 100% sold on the name but also calling the sensor "on wrist" doesn't make that …
> Add On Body sensor for Wear OS

- app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearMainView.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardApp.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingHeaderView.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingViewModel.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryFragment.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryView.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationView.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupView.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/notifications/NotificationPermissionView.kt
- common/src/main/res/values/strings.xml
As previously suggested in #2682, the onboarding design could do with a few tweaks to make it use a consistent style on all screens that is also better aligned with the Material guidelines. This PR provides those tweaks.
Not doing much more right now as a bigger redesign [might come in the future](https://discord.com/channels/330944238910963714/377667559303938050/1006211970728476712)...
Welcome/notifications haven't changed. 
|Light|![Discovery, light mode](https://user-images.githubusercontent.com/8148535/196815662-1ed51ae6-f0bc-40be-93c2-26a5333062d6.png)|![Manual URL, light mode](https://user-images.githubusercontent.com/8148535/196815670-44a48e81-c674-44ff-be43-504121f2c240.png)|![Integration, light mode](https://user-images.githubusercontent.com/8148535/196815677-441ce091-46fd-4253-86 …
> Tweak onboarding design to be more unified

- app/src/main/res/xml/changelog_master.xml
> Change log 10/21

- app/build.gradle.kts
- app/src/full/java/io/homeassistant/companion/android/onboarding/WearOnboardingListener.kt
- app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
- app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/HomeAssistantApis.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepository.kt
- wear/build.gradle.kts
- wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt
Small change to use Kotlin coroutines in place of some callbacks from Play Services.
> Convert Play tasks to coroutines

- wear/src/main/java/io/homeassistant/companion/android/home/views/DetailsPanelView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/EntityListView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/RefreshIntervalPickerView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SensorManagerUi.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SensorUi.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SensorsView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SetTileShortcutsView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/TemplateTileSettingsView.kt
- wear/src/main/java/io/homeassistant/companion/android/home/views/TimeText.kt
- wear/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt
Adds some previews for some of our Wear OS compose files, also sorts sensors by the name
> Add previews to Wear OS compose and sort sensor by name

- app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationView.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupView.kt
Makes sure that all onboarding screens are scrollable. Fixes #2986.
n/a, no major visual changes
n/a
> Make more onboarding screens scrollable

- app/build.gradle.kts
- app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
The new dependency deprecated the `LocationRequest` build method in favor of `LocationRequest.Builder` so updated to the new format.
https://developers.google.com/android/guides/releases#october_13_2022
Ran some tests locally on my pixel 7 pro and updates were still coming in as expected.
> Bump play services location tracking and move away from deprecated methods

- .github/workflows/pr.yml
An attempt at implementing database checks for submitted PRs / #2411 with minor changes that should make it work reliably and adds error messages to make it easier to fix the issue.
You can find tests/examples of scenarios and both succesful and failed runs in my fork's repository https://github.com/jpelgrom/home-assistant-android/pulls
<details>
<summary>Example failures</summary>
```
common/schemas/io.homeassistant.companion.android.database.AppDatabase/25.json
❌ Existing database schema modified, please increase the database version instead
Error: Process completed with exit code 1.
```
```
?? common/schemas/io.homeassistant.companion.android.database.AppDatabase/26.json
❌ Found uncommitted changes in database schema directory, please make sure to include all changes in your commit(s) …
```
> Add database checks to PR workflow

- app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconMonitor.kt
- app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconNameFormat.kt
- app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconTransmitter.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorSettingsViewModel.kt
- app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorListView.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/CheckRateLimits.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/RateLimitResponse.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/RegisterDeviceRequest.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/RegisterDeviceResponse.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/GetConfigResponse.kt
- common/src/main/java/io/homeassistant/companion/android/database/authentication/Authentication.kt
- common/src/main/java/io/homeassistant/companion/android/database/notification/NotificationDao.kt
- common/src/main/java/io/homeassistant/companion/android/database/sensor/Attribute.kt
- common/src/main/java/io/homeassistant/companion/android/database/sensor/Sensor.kt
- common/src/main/java/io/homeassistant/companion/android/database/sensor/SensorWithAttributes.kt
- wear/src/main/java/io/homeassistant/companion/android/data/SimplifiedEntity.kt
Replaces `var`s with `val`s and cleans up some functions to use shorter variants
N/A
Documentation: N/A
> Remove unused setters

- app/src/main/res/xml/changelog_master.xml
> Update change log 10/28

- wear/src/main/java/io/homeassistant/companion/android/sensors/BedtimeModeSensorManager.kt
- wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt
- wear/src/main/java/io/homeassistant/companion/android/sensors/OnBodySensorManager.kt
- wear/src/main/java/io/homeassistant/companion/android/sensors/TheaterModeSensorManager.kt
- wear/src/main/java/io/homeassistant/companion/android/sensors/WetModeSensorManager.kt
Changes the documentation links to point to the new location
N/A
> Change DocsLink in Wear OS Sensors

- app/build.gradle.kts
Fixes: #3034 by reverting the dependency change until its fixed upstream: https://github.com/aclassen/ComposeReorderable/issues/191
Tested by adding favorites and editing to ensure there are no crashes.
> Revert reorderable bump until upstream issue is fixed

- wear/build.gradle.kts
This should've been removed when we bumped Kotlin earlier this week but I had missed it.
> Remove unneeded kotlin option

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
As discussed in Discord https://discord.com/channels/330944238910963714/377667559303938050/1039300917410942996
we can now remove the comment about deprecation because Home Assistant has fixed the issue with Core 2022.10.0
Lamest PR ever 😆 
Documentation: home-assistant/companion.home-assistant#857
> Remove quick bar deprecation comment

- common/src/main/res/values/strings.xml
- wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt
Add 3 new sensors from Health Services:
* daily calories - measured in kcal
* daily distance - measured in meters
* daily steps
Documentation: home-assistant/companion.home-assistant#859
> Add Daily Calories, Distance and Steps sensors for health services

- app/build.gradle.kts
Very minor dependency update: https://developers.google.com/android/guides/releases#november_3_2022
> Bump location dependency

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 11/11

- common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
Make sure that the `activeMessages` map that tracks the active messages/subscriptions on the websocket is thread-safe to prevent exceptions and incorrect responses when it is read/modified from different coroutines. Fixes #3059.
n/a
n/a
I'm not using `ConcurrentHashMap` as the crash in the original issue showed that the app was modifying while iterating, and I want to prevent consistency errors. Wrapping map access in a `Mutex` isn't possible as it is also modified [from a `synchronized` block](https://github.com/home-assistant/android/blob/65df31816104fb76a677586e995a6afbc1a6910c/common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt#L387-L396). As the map should be fairly small (a few messages at a time, maybe 15 at most) blocking …
> Make active websocket message tracking thread-safe

- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
- wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt
forgot we have a device class for this :)
https://www.home-assistant.io/integrations/sensor/#device-class
https://developers.home-assistant.io/blog/2022/09/28/new_sensor_device_classes
> Add proper device class for daily distance sensor on Wear OS3

- .github/actions/create-release-number/action.yml
- .github/workflows/beta.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
We are using several deprecated Github Actions, this should resolve those issues.
N/A
N/A
> Update a bunch of Github Actions

- app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
Self explanatory, solves one of the two suggestions discussed in https://github.com/home-assistant/android/issues/3093. 
N/A
> Button Widget: Hide label if empty or null

- app/src/main/java/io/homeassistant/companion/android/sensors/AppSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/AppSensorManagerBase.kt
- wear/src/main/java/io/homeassistant/companion/android/sensors/AppSensorManager.kt
- wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Just realized that the current version sensor was impacted by the move to the `common` module and no longer reports the flavor but instead reports the version code. This PR fixes this by moving the update function to the appropriate location so the flavor is pulled correctly.
> Fix current version sensor so it properly reports the flavor

- wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt
> Add some debug logs for heart rate sensor

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 12/3

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 12/16

- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/DisplaySensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/KeyguardSensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/LastRebootSensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/LightSensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/MobileDataManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/PhoneStateSensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/PressureSensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/ProximitySensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/StorageSensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/TimeZoneManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/TrafficStatsManager.kt
- wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Add more sensors to the Wear OS app (if supported):
- Display Sensorss
- Keyguard sensors
- Last reboot
- Light sensor
- Mobile data
- Phone state
- Pressure
- Proximity
- Storage
- Time zone
- Traffic stats
Documentation: home-assistant/companion.home-assistant#866
> Migrate more sensors to Wear OS

- .github/workflows/beta.yml
- .github/workflows/release.yml
On release publish our Amazon listing as well.
N/A
N/A
> Add support for publishing to Amazon on release.

- .github/workflows/beta.yml
What I just moved to is not maintained either....
> Migrate to more recently updated Action.

- app/src/main/res/xml/changelog_master.xml
> Update change log 12/19

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
- Fix the app lock bypass when on home WiFi notification command (was discovered by @dshokouhi but haven't seen a PR to fix it)
- Fix code style for app lock notification commands
n/a
n/a
> Fix app lock bypass on home WiFi command, code style

- app/build.gradle.kts
- app/src/full/AndroidManifest.xml
- app/src/full/java/io/homeassistant/companion/android/CrashHandling.kt
Fixes: https://github.com/home-assistant/android/issues/3188
N/A
N/A
> Sentry Config

- app/src/main/res/xml/changelog_master.xml
Last changelog update for the year!
I did purposely leave the Wear OS section as the app will receive a small version bump with no actual changes.
> Update changelog week of 12/31

- wear/build.gradle.kts
Update to the latest beta dependency released today
https://developer.android.com/jetpack/androidx/releases/health#health-services-client-1.0.0-beta02
> Update health services dependency

- app/build.gradle.kts
- common/build.gradle.kts
- wear/build.gradle.kts
> Bump a bunch of dependencies.

- .github/workflows/beta.yml
- app/src/full/java/io/homeassistant/companion/android/vehicle/HaCarAppService.kt
- app/src/full/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
- app/src/full/java/io/homeassistant/companion/android/vehicle/MapVehicleScreen.kt
- common/src/main/res/values/strings.xml
Enhance loading and state syncing.
Prompt for login when appropriate.
Add ability to navigate to entities with locations.
Add icons to main view.
Make sure we only have one Playstore publish running at once.
N/A but soon...
> Bunch of Android Auto enhancements

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 1/13

- common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/ConversationSpeechResponse.kt
Fixes: #3230 by using `Any` instead of `String`.
Here is the response when sending "Turn on kitchen lights"
```
2023-01-15 20:48:15.723 27879-28137 WebSocketRepository     io....stant.companion.android.debug  D  Websocket: onMessage (text: {"id":36,"type":"result","success":true,"result":{"response":{"speech":{"plain":{"speech":"Turned Kitchen Lights on","extra_data":null}},"card":{},"language":"en","response_type":"action_done","data":{"targets":[],"success":[{"name":"Kitchen Lights","type":"entity","id":"light.kitchen_lights_level"}],"failed":[]}},"conversation_id":null}})
```
Here is the response when sending "testing"
```
2023-01-15 20:51:57.648 28665-28733 WebSocketRepository     io....stant.companion.android.debug  D  Websocket: onMessage (text: …
```
> Fix conversation data response type

- README.md
- app/build.gradle.kts
- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
- common/build.gradle.kts
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/DeviceRegistration.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
- common/src/main/java/io/homeassistant/companion/android/common/notifications/NotificationFunctions.kt
- wear/build.gradle.kts
- wear/src/main/AndroidManifest.xml
- wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
- wear/src/main/java/io/homeassistant/companion/android/notifications/FirebaseCloudMessagingService.kt
- wear/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
- wear/src/main/java/io/homeassistant/companion/android/onboarding/MessagingToken.kt
- wear/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
- wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt
This PR adds initial support for `message` and `title` only as there is a lot to move and test. The goal here is to get notifications sending to the watch directly as an MVP. 
I tried to keep the changes minimal here but I am sure there will be room for improvements.
```
message: Message
title: Title
```
Documentation: home-assistant/companion.home-assistant#884
More than likely the next PR after this will be to add device commands for the BLE sensors as those are probably going to be the most important here :)
Its important to note that this will not be testable using the debug APKs as they are from FCM. I have not given too much thought about the warning pop-up we do but given all Wear OS devices will have FCM I don't think it will be too much of a concern. If FCM does not work then …
> Initial commit of notification support on Wear OS

- wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
Fix build after merging #3233 and #3241 within several minutes, causing a conflict as a new feature is using preferences that were moved at the same time.
n/a
n/a
> Fix conversation tile vibrate after settings split

- common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
Fixes #3249
- Scenes need to be turned on [1](https://github.com/home-assistant/frontend/blob/522c7c08a9b20260750b7a05be3007a20841c7a3/src/state-summary/state-card-scene.js#L27) -> [2](https://github.com/home-assistant/frontend/blob/522c7c08a9b20260750b7a05be3007a20841c7a3/src/data/scene.ts#L68)
- Scripts need to be turned on and off [1](https://github.com/home-assistant/frontend/blob/522c7c08a9b20260750b7a05be3007a20841c7a3/src/state-summary/state-card-script.ts#L29)
n/a
n/a
> Fix scene and script Android Auto actions

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 1/20

- app/src/main/res/xml/changelog_master.xml
> Change log week of 1/25

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/notifications/NotificationFunctions.kt
- common/src/main/java/io/homeassistant/companion/android/common/util/NotificationManagerExtensions.kt
- common/src/main/java/io/homeassistant/companion/android/common/util/TextToSpeech.kt
- wear/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Moves the TextToSpeech code so it can be shared with Wear OS. There is some delay in the speech processing on a wearable but thats due to the device, on a phone its still pretty quick.
Documentation: home-assistant/companion.home-assistant#892
> Add TTS notifications to Wear OS

- .github/ISSUE_TEMPLATE/Bug_report.md
Some minor updates to request phone and watch info. Also requesting YAML when troubleshooting notifications. Updates traceback section so users will always add logs instead of us always requesting them.
> Update issue template to be more specific

- wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
Based on some feedback in #3323  adding the app version to the bottom of the settings page
> Show version number in Wear OS settings

- app/src/main/java/io/homeassistant/companion/android/nfc/NfcViewModel.kt
- app/src/main/java/io/homeassistant/companion/android/nfc/TagReaderActivity.kt
Fixes two issues that appeared after merging multiserver for scanning NFC tags.
- Fix scanning tag not completing due to activity finishing early, `launch` does not wait for a result
- Fire events to all servers from settings to match normal scanning (review comment)
n/a
n/a
> Multiserver NFC tag fixes

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 2/17

- app/src/main/java/io/homeassistant/companion/android/settings/server/ServerChooserFragment.kt
- app/src/main/java/io/homeassistant/companion/android/settings/server/ServerChooserView.kt
- app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsFragment.kt
- app/src/main/java/io/homeassistant/companion/android/util/compose/ModalBottomSheet.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
- app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
- app/src/main/res/values-v27/styles.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/xml/preferences_server.xml
- common/src/main/res/values-night/colors.xml
- common/src/main/res/values/colors.xml
- common/src/main/res/values/strings.xml
Make switching between multiple servers faster with gestures when using the webview (same as on iOS):
- Swipe left/right to go to the previous/next server in the list
- Swipe up to open a server chooser where you can select one from the list
(The server chooser is set up to be used in multiple places, but it's only being used for this gesture right now.)
|Swiping up shows the new server chooser|![Home Assistant interface with a bottom sheet on top titled 'Select server' visible, with two options 'Home' and 'Dev', light mode.](https://user-images.githubusercontent.com/8148535/219802926-cdb60c37-012d-4f5e-9b28-bb41edbdbfa0.png)|![Home Assistant interface with a bottom sheet on top titled 'Select server' visible, with two options 'Home' and 'Dev', dark …
> Server gestures and chooser

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 2/25

- wear/src/main/res/drawable/splash_background.xml
Updates the Wear splash screen to comply with the new requirements (https://developer.android.com/docs/quality-guidelines/wear-app-quality#upcoming)
This should also Fix #3350
> Update Splash Screen due to new requirements

- app/build.gradle.kts
- wear/build.gradle.kts
Update various Google dependencies that aren't picked up by dependabot to their latest stable versions. Did a local build and didn't encounter any issues.
https://developers.home.google.com/thread/release-notes#2023-02-27
https://firebase.google.com/support/release-notes/android#messaging_v23-1-2
https://github.com/google/ExoPlayer/releases/tag/r2.18.3
https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.4.3
n/a
n/a
> Google dependency bumps

- app/src/main/res/xml/changelog_master.xml
Highlighting the camera widget changes on purpose as it may be seen to some as a breaking change 
> Update change log week of 3/3

- common/src/main/java/io/homeassistant/companion/android/common/notifications/DeviceCommands.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/BluetoothSensorManager.kt
Fixes: #3384 by updating sensors anytime the command is processed 
> Update sensors when BLE transmitter turned on and off

- common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
We show entity icons in more and more places, so time to catch up with frontend changes for default entity icons :)
Notably, as we now have complications on Wear which can show any entity, I've also included:
- Dynamic binary sensor icons
- Dynamic sensor icons
- Dynamic weather icons
n/a, now better matches frontend
n/a
> Update default entity icons

- .github/ISSUE_TEMPLATE/config.yml
- Disable blank issue option
- Add link to companion docs issues and Discord [like frontend](https://github.com/home-assistant/frontend/blob/dev/.github/ISSUE_TEMPLATE/config.yml)
n/a
> Update issue template selection

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 3/10

- common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationRepositoryImpl.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationService.kt
Update `revokeSession()` function to use the 'new' `auth/revoke` endpoint introduced in home-assistant/core#76880
n/a
n/a
> Use new auth/revoke endpoint

- .github/actions/inflate-secrets/action.yml
> Make sure release keys are inflated.

- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/AndroidOsSensorManager.kt
- common/src/main/res/values/strings.xml
- wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
New sensors for Android OS build information.
Documentation: home-assistant/companion.home-assistant#934
> Add Android OS sensors

- app/build.gradle.kts
- common/build.gradle.kts
- wear/build.gradle.kts
Bumps several app dependencies. For the moment I am skipping the `automotive` module while it gets worked on.
https://developer.android.com/jetpack/androidx/releases/lifecycle#2.6.1
https://developer.android.com/jetpack/androidx/releases/recyclerview#recyclerview-1.3.0
https://developer.android.com/jetpack/androidx/releases/fragment#1.5.6
https://firebase.google.com/support/release-notes/android#2023-03-28
https://developer.android.com/jetpack/androidx/releases/webkit#1.6.1
https://github.com/google/ExoPlayer/releases/tag/r2.18.5
https://developer.android.com/jetpack/androidx/releases/compose#2023.03.00 (tested against this version, did not realize `04` was also released recently so will bump later)
https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.4.4 …
> Bump a few app dependencies

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 4/7

- app/src/main/res/xml/changelog_master.xml
Technically not new but I didn't have a chance to update it last week 😂 
> Update change log week of 4/14

- app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt
Missed in #3439: this still used an implicit server where it should be using a specific one.
n/a
n/a
> Fix Wear OS template tile preview server

- app/src/full/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
Declare executing state of an entity based on verb states.
This allows Android Auto scenarios to show that the entity is loading and provid
`
fun <T> Entity<T>.isExecuting()=  state.endsWith("ing")
`
e feedback for the user about the state on which the entity is in.
> Set Loading State for Entities

- app/src/main/res/xml/changelog_master.xml
Changelog update for 5/20
N/A
N/A
> Changelog for 5/20

- app/src/main/res/xml/changelog_master.xml
Bump date to June, no additional changes
> Update change log for June

- app/src/full/AndroidManifest.xml
- automotive/src/full/AndroidManifest.xml
Updating the manifest per https://developers.home.google.com/matter/apis/home#calling_other_android_apps. I haven't noticed anything failing and both packages [are `forceQueryable`](https://developer.android.com/training/package-visibility/automatic#system-packages-visible-automatically) for me, but maybe it depends on the device/will change in the future?
n/a
n/a
> Update manifest for Matter commissioning

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 6/23

- common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
- wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationActivity.kt
- wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
- wear/src/main/java/io/homeassistant/companion/android/conversation/views/AssistMessage.kt
- wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt
This PR updates Assist on watches with more functionality, closely matching the implementation in the main app but with a watch-specific UI. STT/TTS via the pipeline will be added later, this PR is about updating the interface to support pipelines (user visible, not just in the background).
- Allow continuing conversation by adding a mic input button at the bottom of the screen, no need to close the app if you want to follow up
- Allow changing pipelines when on a supported core version
Tapping 'Home Assistant' at the top will show a list of pipelines/assistants (on core <2023.5 this item won't be shown):
Video showing how switching pipelines works:
https://github.com/home-assistant/android/assets/8148535/cd2d4091-edd0-40d4-9b49-c7997f0a388a
n/a
> Update Wear Assist with continued conversations, pipelines

- .gitignore
I believe this is the last of the files I need to ignore to make the build clean for releases.
> Make sure our credential files are ignored from SCM.

- app/build.gradle.kts
- automotive/build.gradle.kts
- build.gradle.kts
- common/build.gradle.kts
- wear/build.gradle.kts
> Bump dependency versions.

- .github/workflows/monthly.yaml
The latest commit was tagged `7.7.0` instead of the expected `2023.7.0`, use year instead of month twice.
n/a
n/a
> Fix monthly tag

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 7/7

- app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearActivity.kt
Permanent fix for: https://github.com/home-assistant/companion.home-assistant/issues/952
related: https://github.com/home-assistant/companion.home-assistant/pull/953
> Fix broken Wear OS docs link in settings

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 7/14

- app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearFavoritesView.kt
- app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
- app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/views/ManageShortcutsView.kt
- app/src/main/java/io/homeassistant/companion/android/util/compose/SingleEntityPicker.kt
- common/src/main/res/values/strings.xml
Use the new entity picker from #3653 for more settings as it provides a better experience.
|Shortcuts with entity picker, entity ID was renamed entity to reflect this|![Shortcut setting with a text field + dropdown for entity instead of a basic button only showing IDs, light mode](https://github.com/home-assistant/android/assets/8148535/4cfd365b-cbf4-4a43-95a3-2cd956f61e77)|![Shortcut setting with a text field + dropdown for entity instead of a basic button only showing IDs, dark mode](https://github.com/home-assistant/android/assets/8148535/f8e3e41b-35cb-4e3b-9361-2ab7034c2e50)|
|Wear favorite management now uses the entity picker instead of a very long list of all entities with checkmarks|![Favorite entities screen with 'Add favorite' text field at …
> Use new entity picker for more settings

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 7/21

- app/build.gradle.kts
Might as well keep them all on the same version, automotive already does so.
> Match android auto dependency versions

- .github/workflows/onPush.yml
The new release model #3597 removed `version_code.txt`, which [broke F-Droid's update detection](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/io.homeassistant.companion.android.minimal.yml?ref_type=heads#L416). We could tell them to update to use our version names and `version.txt` but this is easier as this file was specifically added for them.
n/a
n/a
> Fix version code for F-Droid builds

- app/build.gradle.kts
- automotive/build.gradle.kts
- wear/build.gradle.kts
https://developer.android.com/jetpack/androidx/releases/health#health-services-client-1.0.0-rc01
https://developer.android.com/jetpack/androidx/releases/recyclerview#recyclerview-1.3.1
https://developer.android.com/jetpack/androidx/releases/fragment#1.6.1
https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.5.1
> Bump some project dependencies

- app/src/main/java/io/homeassistant/companion/android/settings/vehicle/ManageAndroidAutoViewModel.kt
- app/src/main/java/io/homeassistant/companion/android/settings/vehicle/views/AndroidAutoFavoritesView.kt
- app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
- app/src/main/java/io/homeassistant/companion/android/vehicle/MapVehicleScreen.kt
- Allow navigation entities to be added to favorites
- Convert navigation screen from list to grid items
> Add navigation entities to favorites and convert nav screen to grid

- app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
Improve the check to ensure the selected server has favorites in order to prevent loading the domain list and adding all entities at the same time.
> Show favorites only if selected server has favorites

- app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearMainView.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardApp.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingViewModel.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryFragment.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/HomeAssistantInstance.kt
- app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/HomeAssistantSearcher.kt
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
- Hide already added instances when adding another server to the app when found in discovery
- Show already added instances with their external URL in discovery when logging in a Wear OS device
n/a
n/a
> Smarter discovery for already added instances

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 7/28

- app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
Fixes favorites entity state not updating in the interface for Android Auto when their state changes, a bug [first mentioned here](https://github.com/home-assistant/android/pull/3732#issuecomment-1656804554). This is because the home screen only invalidated when domains change.
Discussed with @dshokouhi via DMs. `favoriteEntities` isn't used and also complicates things so merge/remove it with the other variable for entities of favorites.
n/a
n/a
> Invalidate Auto home on favorite state change

- .github/workflows/pr.yml
Don't create a release number and release notes for PRs
- release number is unused
- release notes requires a token with write access which should not be given to forks and without it the action will fail, so remove step
n/a
n/a
> Don't create release number/notes for PRs

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/notifications/DeviceCommands.kt
- wear/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Adds `command_update_sensors` to Wear OS
Documentation: home-assistant/companion.home-assistant#970
Ref: https://discord.com/channels/330944238910963714/562408603345092636/1138926251986407507
> Add update sensors notification command to Wear OS

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 8/11

- app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Fixes: #3797 by trying to parse the URI and catching the errors. Will use the default action when URI fails to parse.
> Catch errors when intent URI is not valid

- app/src/main/res/xml/changelog_master.xml
> Update Changelog for 2023.8.3

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 8/25

- app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Check if the entity ID matches the expected format to prevent typos from throwing errors when using the [`entityId:domain.entity` url](https://companion.home-assistant.io/docs/notifications/notifications-basic?_highlight=entityid%3A#opening-a-url).
n/a
n/a
> Prevent entity ID typos throwing errors

- .github/ISSUE_TEMPLATE/Bug_report.md
small change to include the new location
> Update readme to include new logs location

- common/src/main/java/io/homeassistant/companion/android/database/server/ServerConnectionInfo.kt
Defensive parsing of URL for account for cases where strings are not valid URLs (for instance an empty string)
Fixes https://github.com/home-assistant/android/issues/3845
> Fix crash on empty URL strings

- .github/workflows/release.yml
We forgot to inflate the secrets so we couldn't promote the beta -> production.
N/A
N/A
> Fix production promotion.

- app/src/main/res/xml/changelog_master.xml
> Change log week of 9/8

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 9/29

- gradle/wrapper/gradle-wrapper.properties
Update gradle to 8.3 which also helps solve some errors in our `build.gradle.kts` files
> Update gradle to 8.3

- app/src/main/res/values/arrays.xml
Prevents the following crash by allowlisting this host:
```
10-13 19:20:26.579 10697 10697 E IGNITE.CA.HOST: CarApp.H.Tem - Error: [app: ComponentInfo{io.homeassistant.companion.android.minimal/io.homeassistant.companion.android.vehicle.HaCarAppService}, type: null, cause: null, debug msg: java.lang.IllegalArgumentException: Unknown host 'com.harman.ignite.car.app.host.tml', uid:1110229
10-13 19:20:26.579 10697 10697 E IGNITE.CA.HOST: 	at androidx.car.app.CarAppBinder.onHandshakeCompleted(CarAppBinder.java:273)
10-13 19:20:26.579 10697 10697 E IGNITE.CA.HOST: 	at androidx.car.app.ICarApp$Stub.onTransact(ICarApp.java:191)
10-13 19:20:26.579 10697 10697 E IGNITE.CA.HOST: 	at android.os.Binder.execTransactInternal(Binder.java:1159)
10-13 19:20:26.579 10697 10697 E IGNITE.CA.HOST: 	at …
```
> Add Harman template host to car service allowlist

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 10/13

- gradle/libs.versions.toml
Missed a dependency version grouping.
> Bump okhttp and merge deps.

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 10/20

- app/src/main/res/xml/changelog_master.xml
All bug fixes and dependency updates this week, including all approved PRs :)
> Update change log week of 10/27

- common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
While working on Assist, I was facing issues with the conversation not working correctly. It turns out this was because while the websocket was sending conversation data correctly, it was being received/processed by the viewmodel _out of order_.
Example below. The events are received from the websocket as `stt-end > intent-start > intent-end > tts-start > tts-end > run-end`, but are received [in the viewmodel](https://github.com/home-assistant/android/blob/15574f7531f3024aa8b4c7eb2562dbe9f6fba52d/common/src/main/java/io/homeassistant/companion/android/common/assist/AssistViewModelBase.kt#L94) as `run-end > stt-end > intent-end > tts-start > intent-start > tts-end`.
```
2023-11-01 21:17:21.590 19028-19188 WebSocketRepository     io....stant.companion.android.debug  D  Websocket: onMessage …
```
> Websocket `onMessage`: prevent out of order delivery due to `launch`

- .github/actions/create-release-notes/action.yml
> Hopefully Escape quotes in changelog.

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 11/3

- .github/workflows/onPush.yml
- .github/workflows/pr.yml
Builds are failing because our runner is running out of memory.  This is a fast and dirty potential solution to get builds flowing again.
> Try to build each module individually to help on runner memory.

- common/src/main/java/io/homeassistant/companion/android/common/data/HomeAssistantApis.kt
Use a Better Wear Check, based on features.
N/A
N/A
N/A
> Better Wear Check

- app/src/main/res/xml/changelog_master.xml
1 new addition this week
will update again if we merge #4027
> Update change log week of 11/24

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 12/15

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 1/5

- wear/src/main/java/io/homeassistant/companion/android/home/views/RefreshIntervalPickerView.kt
Use more precise padding per [comment](https://github.com/home-assistant/android/pull/4119#issuecomment-1879599617) which results in the picker looking scrollable
> Use horizontal padding on refresh interval per review comment

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 1/12

- app/src/main/res/xml/button_widget_info.xml
> Fix button widget on Samsung devices

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 2/2/24

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 2/23

- gradle/libs.versions.toml
> Bump altbeacon to 2.20.4

- app/src/main/java/io/homeassistant/companion/android/util/vehicle/GridItems.kt
- app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
- app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
Fixes: #4247 by filtering entities that are marked as hidden from the navigation screen
> Hide hidden navigation entities in android auto

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 3/15

- gradle.properties
Hopefully fix the running out of heap.
> Increase heap from 2gig to 4gig

- app/src/main/res/xml/changelog_master.xml
wording the chronometer PR was fun, open to suggestions on that one 😅
> Update change log week of 3/22

- .github/workflows/release.yml
Trying to resolve the Amazon App Store submission error for new production releases, Fastlane currently gives the error:
```
[18:57:24***: No value found for 'client_id'
```
and the weekly tag pushing metadata seems to work OK, so copying what's there.
n/a
n/a
> Set Amazon secrets on release workflow

- common/build.gradle.kts
- common/src/main/java/io/homeassistant/companion/android/common/util/AudioRecorder.kt
- common/src/main/java/io/homeassistant/companion/android/common/util/AudioUrlPlayer.kt
- common/src/main/java/io/homeassistant/companion/android/common/util/UtilModule.kt
- gradle/libs.versions.toml
Implements #4282 
- Request exclusive focus for Assist voice input (no other applications allowed to playback)
- Request focus with ducking allowed for Assist voice output
No visual changes, and I don't want to deal with a video with music because of copyright
n/a
> Request audio focus for Assist voice input + output

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 4/6

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 4/20

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 5/3

- app/src/main/res/xml/changelog_master.xml
> Update changelog version 2024.6.1

- app/src/main/java/io/homeassistant/companion/android/assist/AssistViewModel.kt
- wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
For received Assist pipeline text messages from the server, trim what is displayed in the app to avoid messages with additional empty lines as seen in the latest HA core beta [1](https://discord.com/channels/330944238910963714/427516175237382144/1246264565264814130) [2](https://discord.com/channels/330944238910963714/427516175237382144/1246349248342134785)
Untested so not available but should be like the linked screenshots without an empty line at the end
n/a
> Trim Assist pipeline text messages

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 6/14

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 7/5

- common/src/main/java/io/homeassistant/companion/android/util/UrlUtil.kt
> Include path fragment (#something) when handling relative URLs for WebViewActivity

- app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
Harmonize icons between android and ios
> Update Detected activity sensor icon based on state

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 7/12

- app/src/full/java/io/homeassistant/companion/android/sensors/AndroidAutoSensorManager.kt
Adding state based icon to the sensor, servers as visual aid.
> Update Android Auto sensor icon based on state

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 7/17

- app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
Use a compat function for the quick settings tiles launch API (tile not configured click) to prevent a crash when we start targeting the next API level (https://developer.android.com/about/versions/14/behavior-changes-14#tiles-launch-api).
n/a
n/a
> Use compat function for tiles launch API

- .github/workflows/onPush.yml
Adds app bundle artifact file to the push action on GitHub, so we can manually resubmit on the Play Store console if required. I don't believe there's anything sensitive in the file that we shouldn't publish.
n/a
n/a
> Add aab artifact to push action

- app/src/full/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Our releases are stuck in a weird place given health connect approval is taking longer than anticipated and the required SDK bump deadline has passed.
For now lets temporarily comment out the code for permissions and health connect sensors while we satisfy the SDK requirements. Once completed and reviewed we should revert this change and try again for approval.
more details: https://github.com/home-assistant/android/pull/4452#issuecomment-2321697048
> Temporarily disable health connect to satisfy play console

- .kotlin/errors/errors-1725594042147.log
- app/src/main/res/xml/changelog_master.xml
> Update Change log week of 9/6

- app/src/main/AndroidManifest.xml
- common/src/main/AndroidManifest.xml
- common/src/main/java/io/homeassistant/companion/android/common/sensors/PhoneStateSensorManager.kt
- common/src/main/res/values/strings.xml
- wear/src/main/AndroidManifest.xml
Fixes: #4572 by adding 4 new sensors for signal strength and data network type for each SIM slot
Documentation: home-assistant/companion.home-assistant#1094
> Add signal strength and data network type sensors

- gradle/libs.versions.toml
Tested briefly and did not encounter any build issues on my device, should help satisfy the build failure in #4633 
> Bump compile SDK to 35

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 9/13

- .gitignore
.gitignore update to not include .kotlin/ generated folder into git changes
> Updates .gitignore to not include .kotlin/ changes into git

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 9/20

- common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt
These 2 sensors are not instant (and would be crazy if they actually were) so we should properly identify them.
> Fix update type identification on some network sensors

- README.md
Adds the OHF badge to the README
> Add OHF logo to README

- app/src/full/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Reverts home-assistant/android#4610
we should be able to continue and try again after the next release to prod 🤞
> Revert "Temporarily disable health connect to satisfy play console"

- common/src/main/res/values/strings.xml
> Fix inconsistent MAC address capitalization

- app/build.gradle.kts
- app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
- app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
- app/src/minimal/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
- automotive/build.gradle.kts
We don't expose Health Connect on minimal because it [effectively requires Play Services](https://developer.android.com/health-and-fitness/guides/health-connect/develop/frequently-asked-questions#play-services), so don't include the library dependency.
n/a
n/a
> Don't include Health Connect library in minimal

- app/src/full/AndroidManifest.xml
- app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
- app/src/full/java/io/homeassistant/companion/android/settings/sensor/HealthConnectPermissionActivity.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
- Add documentation
- Improve availability check (also not available in profiles, only checking for API version is not enough)
- Safely get client as it may throw exceptions
- Don't create client when requesting sensor update if no HC sensors are enabled
- Update permission usage activity: activity should have permission according to docs, Android <13 was misplaced, don't put it in non-full
- Clean up empty lines and update types that match default
n/a
Documentation: home-assistant/companion.home-assistant#1118
> Improve Health Connect code quality

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 10/11

- app/src/full/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
- app/src/main/res/xml/changelog_master.xml
> Disable Health Connect due to policy rejection

- app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
- common/src/main/res/values/strings.xml
Add a car range sensor
Documentation: home-assistant/companion.home-assistant#1121
> Add a car range remaining sensor

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 10/18

- app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
This should be a sensor and not diagnostic
> Correct sensor identification for car speed sensor

- app/src/full/AndroidManifest.xml
- app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Just keep going until we get it? 😄 
> Enable Health Connect again to retry for approval

- app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
- update weight icon to be more correct
- Add state class total increasing for total calories as the sensor resets at midnight and accumulates until then
- Add package as an attribute so users can understand from where the data came from
> Add package name to health connect sensors, additional sensor tweaks

- app/src/full/AndroidManifest.xml
- app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
- common/src/main/res/values/strings.xml
Adds heart rate sensor from Health Connect
Documentation: home-assistant/companion.home-assistant#1133
Adding 1 sensor for now as this was tested earlier and probably a good idea to check the new flow after adding 1 sensor. I assume the action will fail and the declaration needs to be updated and submitted with the APK uploaded again. If that is the case then we know larger PRs are necessary to ease the approval process.
> Add heart rate sensor for Health Connect

- app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/DisplaySensorManager.kt
- wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt
- Add duration device class to Sleep segment sensor
- Add unit and device class to screen timeout as it is duration
- Add total increasing state class to all health services sensors that reset at midnight 
> Fix some sensor configurations to be more precise

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 11/8

- app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
Fixes https://github.com/home-assistant/android/issues/2537#issuecomment-2466971586 by allowing the conversion to be done by core.
Thanks @dshokouhi https://github.com/home-assistant/android/issues/2537#issuecomment-2469114799 - but we don't need to wait :)
n/a
n/a
> Add device class to blood glucose sensor

- app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt
- common/src/main/java/io/homeassistant/companion/android/common/notifications/NotificationFunctions.kt
- common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorWorkerBase.kt
- common/src/main/res/values/strings.xml
Fixes: #4826 by ensuring we always set the latest channel name
> Use translated channel name strings where possible to update them when language changes

- app/src/full/AndroidManifest.xml
- app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
- common/src/main/res/values/strings.xml
Re-arranges the code to make some things easier to find. I am sure some of the names/descriptions/icons will need to be reconsidered.
Adds:
- Basal metabolic rate
- Body temperature
- Bone mass
- Diastolic blood pressure
- Height
- Lean body mass
- Oxygen saturation
- Respiratory rate
- Systolic blood pressure
- VO2 max
Documentation: home-assistant/companion.home-assistant#1140
Tested against my own data and also health connect toolbox
> Add 10 more health connect sensors

- common/src/main/res/values/strings.xml
See title - not sure how often people see this but still nice to fix.
n/a
n/a
> Fix typo: security vulnerably -> security vulnerability

- app/src/main/res/xml/changelog_master.xml
last change log update for the year 😝
> Update change log week of 12/27

- app/src/main/res/xml/changelog_master.xml
> Update change log for 2024.12.7

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 1/4

- app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidViewModel.kt
- app/src/main/java/io/homeassistant/companion/android/settings/ssid/views/SsidView.kt
> Avoid duplicate LazyColumn SSID keys

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 1/17

- app/src/full/AndroidManifest.xml
- app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
Try again for 
- blood glucose
- blood pressure
- heart rate
- weight
small list because we have doubts
maybe best to wait for actual beta approval?
🤞 
should we try to appeal if rejected? not sure which i am leaning on this lol
> Try for more health connect sensors again

- app/src/main/res/xml/changelog_master.xml
This PR updates the app version mentioned in the changelog to the next release, difference is getting quite big.
n/a
n/a
> Bump changelog to 2025.3.1

- renovate.json
Add missing config for other repos.
> Add missing requestLimit for other repo

- .github/workflows/pr.yml
This way the test matches the other _tests_ that we have
Old
New
Ref: https://github.com/home-assistant/android/pull/4835/files/1ef05830290d4305cda4e7c2fe6bc0dc8996181f#r2017548272
> Move screenshot test to be later in the flow

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 3/28

- .github/actions/create-release-notes/action.yml
- .github/workflows/onPush.yml
- .github/workflows/pr.yml
- .github/workflows/weekly.yml
In order to move from `master` to `main`. This PR makes the necessary changes. We are following this https://github.com/github/renaming
> Replace all usage of master with main

- gradle.properties
- settings.gradle.kts
This reverts commit af42dcdd9f37a7a2cc10e754fff6195c3e90c277.
https://github.com/home-assistant/android/pull/5211#issuecomment-2804196360
> Revert "Enable Gradle Configuration cache (#5211)"

- .github/pull_request_template.md
This PR has been created after https://github.com/home-assistant/developers.home-assistant/pull/2626#discussion_r2023416703 on the need to add the `beta` flag in the companion app documentation. I took the opportunity to add more details and look at what we have in core [repository](https://github.com/home-assistant/core/blob/323c459442dd17dc042935f8d7c4dc711c537328/.github/PULL_REQUEST_TEMPLATE.md).
> Update pull request template to add more information

- gradle/libs.versions.toml
Now that we have libraries starting to require it we should bump this now.
> Bump compile SDK to 36

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 4/18

- app/src/main/res/xml/changelog_master.xml
just to clear it out for the next cycle
> Update change log week of 4/25

- app/src/main/res/xml/changelog_master.xml
> Update change log week of 5/2

- common/src/main/kotlin/io/homeassistant/companion/android/common/data/websocket/WebSocketRequest.kt
- common/src/main/kotlin/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketCoreImpl.kt
- common/src/test/kotlin/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketCoreImplTest.kt
This is the follow up of the changes introduced in #5197 and #5215. It proposes fixes for the TODO CRITICAL and some other improvements needed. All of the changes are controlled with unit tests but should also be checked manually.
> Improve websocket active messages management

- common/src/main/kotlin/io/homeassistant/companion/android/common/data/websocket/WebSocketCore.kt
- common/src/main/kotlin/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketCoreImpl.kt
After refactoring the `WebSocketCoreImpl` implementation I took some notes and I think the information about the implementation should be summarize and available within the code. The goal here it have a brief overview of the behavior of the implementation. This documentation is not in `WebSocketCore` since it's specific to this implementation.
> Add more documentation for the websocket implementation

- app/src/main/kotlin/io/homeassistant/companion/android/widgets/todo/TodoWidgetConfigureActivity.kt
- app/src/main/kotlin/io/homeassistant/companion/android/widgets/todo/TodoWidgetConfigureViewModel.kt
- common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/IntegrationDomains.kt
- common/src/main/kotlin/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
After the migration to Glance in https://github.com/home-assistant/android/pull/5252. The error were not properly handled anymore. The default theme was DAYNIGHT but should have been DYNAMICCOLOR from the start.
I would like feedback on how we should handle in Compose error from the viewModel back in compose.
Small improvements on how we handle `domains`, by creating a `IntegrationDomains` object that should holds the strings of the `domains` to avoid duplicates.
> Todo widget configure improvements

- .idea/kotlinc.xml
There was an issue in the configuration of the IDE that was making kotlinc using previous version. This PR is made from the updated settings to make sure it uses the right version of Kotlin.
This might happen again when we are going to update Kotlin again.
> Properly setup kotlinc for 2.1.20

- .idea/kotlinc.xml
Fix version after update of Android Studio
> Fix version of Kotlin in idea config to 2.1.21

- app/src/main/kotlin/io/homeassistant/companion/android/settings/server/ServerSettingsFragment.kt
- app/src/main/kotlin/io/homeassistant/companion/android/settings/server/ServerSettingsPresenter.kt
- app/src/main/kotlin/io/homeassistant/companion/android/settings/server/ServerSettingsPresenterImpl.kt
- app/src/main/res/menu/menu_fragment_share.xml
- common/src/main/res/values/strings.xml
Add a  share button in the server settings screen. 
Should be merged after https://github.com/home-assistant/android/pull/5425
> Add share server to server settings fragment using my website

- .github/ISSUE_TEMPLATE/config.yml
Add few sections to try to redirect our users to the right place instead of creating issues that are not releated to this repository directly.
I did pin some issues and lock them. 
I wanted to replicate https://github.com/godotengine/godot/issues but I did not manage to make a top banner.
> Add more choices in issues to improve the creation of issues

- common/src/main/kotlin/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketCoreImpl.kt
We want to investigate a bit more why sometimes the `messageQueue` is not able to proceed with a message. To do so I've used the `FailFast` API instead of a simple log and I've added more information to the message.
> FailFast when WS message were not proceed properly

- app/src/main/res/xml/changelog_master.xml
> Update changelog for 2025.6.6

- app/src/main/kotlin/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
- app/src/test/kotlin/io/homeassistant/companion/android/sensors/GeocodeSensorManagerTest.kt
This pull request adds handling of the GPS week number rollover in the minimal flavour. The problem that was present is described in this issue comment:  https://github.com/home-assistant/android/issues/1511#issuecomment-2946265967
> Handle GPS week rollover

- .git-blame-ignore-revs
https://github.com/home-assistant/android/pull/5529 Introduced a lot of changes that doesn't need to be visible while blaming.
> Ignore ktlint last change from blame

- app/lint-baseline.xml
- automotive/lint-baseline.xml
- common/lint-baseline.xml
- common/src/main/kotlin/io/homeassistant/companion/android/database/location/LocationHistoryDao.kt
- lint/src/main/kotlin/io/homeassistant/lint/room/CoroutineDaoFunctionsIssue.kt
- lint/src/test/kotlin/io/homeassistant/lint/room/CoroutineDaoFunctionsIssueTest.kt
Only `add` was not suspensive, the rest is using `PagingSource` that is the correct way to get a page using coroutine. I adjusted the lint rule to support this case.
Part of https://github.com/home-assistant/android/issues/5520
I did not re-generated the baseline. I'll do it once all the PRs about DAO are merged.
> Make location history dao suspensible

- app/src/main/kotlin/io/homeassistant/companion/android/HomeAssistantApplication.kt
- app/src/main/kotlin/io/homeassistant/companion/android/util/IgnoreViolationRules.kt
- common/src/main/kotlin/io/homeassistant/companion/android/common/util/HAStrictMode.kt
- wear/src/main/kotlin/io/homeassistant/companion/android/HomeAssistantApplication.kt
This PR improve the general architecture of the usage of `StrictMode` to allow us to define ignore rules. It also fix an issue that `stacktrace.fileName` can be null and add a new ignore rule for the BarecodeActivity (refer to this issue https://github.com/journeyapps/zxing-android-embedded/issues/762)
The architecture will most probably continue to evolve to allow ignore rules into the thread policy, but for now it was not needed.
> Fix strict mode issues

- .github/workflows/onTag.yml
I made a mistake while creating `onTag.yml` I assumed that it was possible to use a full regex in the tag matching. Only a subset of operations are possible https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet This PR replace the complex pattern by a simpler one that should work (we will see next week).
> Simplify pattern matching for onTag workflow

- app/lint-baseline.xml
- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/io/homeassistant/companion/android/widgets/BaseWidgetConfigureActivity.kt
- app/src/main/kotlin/io/homeassistant/companion/android/widgets/BaseWidgetProvider.kt
- app/src/main/kotlin/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
- app/src/main/kotlin/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
- app/src/main/kotlin/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt
- app/src/main/kotlin/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt
- app/src/main/kotlin/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
- app/src/main/kotlin/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
- app/src/main/kotlin/io/homeassistant/companion/android/widgets/mediaplayer/MediaPlayerControlsWidget.kt
- app/src/main/kotlin/io/homeassistant/companion/android/widgets/mediaplayer/MediaPlayerControlsWidgetConfigureActivity.kt
- app/src/main/kotlin/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
- app/src/main/kotlin/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
- automotive/lint-baseline.xml
- automotive/src/main/AndroidManifest.xml
- common/src/main/kotlin/io/homeassistant/companion/android/database/widget/ButtonWidgetDao.kt
- common/src/main/kotlin/io/homeassistant/companion/android/database/widget/CameraWidgetDao.kt
- common/src/main/kotlin/io/homeassistant/companion/android/database/widget/MediaPlayerControlsWidgetDao.kt
- common/src/main/kotlin/io/homeassistant/companion/android/database/widget/StaticWidgetDao.kt
- common/src/main/kotlin/io/homeassistant/companion/android/database/widget/TemplateWidgetDao.kt
- common/src/main/kotlin/io/homeassistant/companion/android/database/widget/TodoWidgetDao.kt
- common/src/main/kotlin/io/homeassistant/companion/android/database/widget/WidgetDao.kt
This is a follow up of #5628 for all the other widgets that are not using Glance API.
This PR contains a lot of duplicate but it didn't want to refactor more than what I currently doing in the scope of this PR.
Fix https://github.com/home-assistant/android/issues/5349
> Fix background widget creation

- app/src/main/res/xml/changelog_master.xml
We are going to make another release to fix the settings issue and slow startup, this PR brings back the changelog from the previous version since it's still relevant.
> Bring back previous changelog for quick release

- app/src/main/kotlin/io/homeassistant/companion/android/HomeAssistantApplication.kt
- wear/src/main/kotlin/io/homeassistant/companion/android/HomeAssistantApplication.kt
…tarts
In order to have a better clarity on the logs when a user is sending us a file I've added a small log when the app starts with the version of the app and the current Android SDK.
> Log current version of the app and current Android SDK at startup

- app/src/main/kotlin/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
Fixes #5744. There is a race condition when opening the template widget screen where the server ID may not be set in time before rendering the widget, which this PR handles by:
- setting the server ID early, instead of waiting for the server list to load (which uses the ID we got from the database anyway, if present)
- catching that the server ID is `null` before trying to do a network call and logging a more meaningful error
n/a
n/a
> Fix race when opening template widget screen for rendering template

- .github/actions/create-release-notes/action.yml
- .github/actions/setup-build-env/action.yml
- .github/actions/upload-sarif-results/action.yml
- .github/workflows/monthly.yml
- .github/workflows/onPush.yml
- .github/workflows/pr.yml
- .github/workflows/prepareNextRelease.yml
- .github/workflows/release.yml
- .github/workflows/updateScreenshot.yml
- .github/workflows/weekly.yml
Pinning Github Actions for enhanced security:
* Done by a tool https://github.com/Skipants/update-action-pins
* Actions from gradle/actions have been done manually
* Actions from within the action folder have been done manually
> Pin SHA for all Github Actions

- onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/manualserver/ManualServerScreen.kt
- onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/nameyourdevice/NameYourDeviceScreen.kt
Set the maxLines to 1 for the URL in ManualServerScreen and the NameYourDeviceScreen.
> Set maxlines to 1 in manual server and name your device screens

- app/src/main/kotlin/io/homeassistant/companion/android/util/vehicle/GridItems.kt
- app/src/main/kotlin/io/homeassistant/companion/android/util/vehicle/TemplateComponents.kt
- app/src/main/kotlin/io/homeassistant/companion/android/vehicle/ChangeServerScreen.kt
- app/src/main/kotlin/io/homeassistant/companion/android/vehicle/DomainListScreen.kt
- app/src/main/kotlin/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
- app/src/main/kotlin/io/homeassistant/companion/android/vehicle/LoginScreen.kt
- app/src/main/kotlin/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
- app/src/main/kotlin/io/homeassistant/companion/android/vehicle/MapVehicleScreen.kt
- automotive/lint-baseline.xml
This PR updates functions used to build the header of screens in the vehicle templates (Android Auto/Automotive driving mode UI) to a new, non-deprecated version.
Tested using the desktop head unit to confirm the header is visually and functionally the same.
n/a, no visual difference
n/a
> Update (deprecated) vehicle template header builder

- .github/workflows/pr.yml
For now I decided to not store the APK generated since ppl might install them and we don't want people to install the app from a PR they should do it from the release.
> Build release APK on PR
