app/src/main/java/io/homeassistant/companion/android/util/DataUriDownloadManager.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
common/src/main/java/io/homeassistant/companion/android/common/util/AppNotifChannels.kt
common/src/main/res/values/strings.xml

If the frontend is going to provide data URIs as downloads, the app should try to support them. Unfortunately the WebView won't give the suggested file name in the download callback, so a more generic one is used instead.
Fixes #2711
If the app receives a download request for something that is not supported (not http, https or data) it will now forward it to the system instead of crashing.
A notification will be posted that is very close to the system download manager in appearance and behavior.
|Light|Dark|
|-----|-----|
|![A notification by the Home Assistant app: 'Unnamed file - Download complete.', light mode](https://user-images.githubusercontent.com/8148535/181115963-9605748d-cc51-4223-bc6c-1c03e3a72323.png)|![A notification by the Home Assistant app: 'Unnamed file - Download …

Support downloading data URIs

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingViewModel.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/HomeAssistantSearcher.kt

After complaining on Discord that discovery of Home Assistant instances on Android wasn't working for me most of the time, it turns out the solution was a quick search away. Some devices, most notably Google Pixels, require manually requesting a multicast lock in order for DNS-SD to work reliably (see [this comment](https://github.com/andriydruk/RxDNSSD/issues/38#issuecomment-392206040)). After including this change, it now works 100% of the time for me, hopefully also for others.
n/a, discovery isn't a new interface
n/a

Improve discovery reliability for some devices

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
common/schemas/io.homeassistant.companion.android.database.AppDatabase/31.json
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
common/src/main/java/io/homeassistant/companion/android/database/sensor/Sensor.kt
common/src/main/java/io/homeassistant/companion/android/database/sensor/SensorDao.kt

Fixes #2733
I added a `forceUpdate: Boolean` flag to `Sensor`, and `NotificationSensorManager` sets it to `true` when a notification is received. The flag is cleared after an update (in `SensorDao::updateLastSentStateAndIconAndClearForceUpdateFlag(...)`).

Fix Last Notification sensor not updating when notification is repeated with the same content

---

app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
wear/src/main/java/io/homeassistant/companion/android/tiles/TemplateTile.kt

In #2653 it was discovered that templates can be valid and return `null`, and some simple changes were made to handle it.
This PR builds on it and addresses a comment [by another user](https://github.com/home-assistant/android/issues/2714#issuecomment-1200244780):
>> The app presents `null` as "Error in template".
>
> IMO, that message is not correct given the template is syntactically valid and doesn't throw an exception: `null` is a perfectly valid, if not intended, result here. If I didn't know this now, I'd have been going over the template for syntax errors and ripping my hair out wondering why I couldn't find any; `null` would tell me that it's working, just not giving me the info I want. That said, this could've already been hashed out elsewhere and decided on already so I end my …

Remove error message on null template

---

app/src/main/res/xml/backup_rules.xml
app/src/main/res/xml/backup_rules_android12.xml
wear/src/main/AndroidManifest.xml
wear/src/main/res/xml/backup_rules.xml
wear/src/main/res/xml/backup_rules_android12.xml

A user on Discord mentioned that [they were automatically logged in on a new device](https://discord.com/channels/330944238910963714/562408603345092636/1003940648157708288) which surprised them. Session data is device specific and shouldn't be restored or transferred, so this PR excludes session data from the automatic backup/transfer.
Not including the session data will also show onboarding on start, which prevents issues with re-using the mobile app integration registration.
n/a
n/a

Don't include session in backup/transfer

---

app/src/full/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt

Minor clean up to stop using a deprecated method and inappropriate blocking call. We already had a proper method in place so using that here.

Switch to non-deprecated method to get FCM token during registration resync

---

app/src/main/java/io/homeassistant/companion/android/widgets/BaseWidgetProvider.kt
app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt

When a widget is added or edited, the system will send a broadcast to _a new instance_ of the widget class (this is easy to spot when debugging or adding additional logging). Because there is a websocket connection to keep widgets updated, we should use a singleton variable to only start a subscription in one of these instances + subscribe for screen off broadcasts in that instance. This will stop the connection from staying active after the screen is turned off due to multiple instances of the class listening and only one receiving screen off events.
When the screen is turned on, only one instance of the widget provider is needed to update all existing widgets and created by the [initial broadcast receiver in the app class](https://github.com/home-assistant/android/blob/90a9a27e5e371445f7 …

Fix websocket stays subscribed after widget edit due to multiple instances

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

Should hopefully fix #2681 and fix #2720 by evaluating how much time has passed since `lastLocationReceived`. If background location updates are supposed to be on we will check `lastLocationReceived` with the addition of double the max wait time. If high accuracy mode is on we will double the amount of time for the defined interval. If we detect too much time has passed we will stop services and start them again shortly thereafter.

Restart location updates if we detect too much time passed since last update

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt

Noticed that we had some code to update the geocoded sensor but it only updated the DB and did not update HA. Moved the logic to only update the sensor if location is being sent to HA instead of when it was just received. Also only sending the state if it has changed since the last update so we don't send too many updates like in high accuracy mode.
As this sensor should be kept updated with location updates it made sense to only update this one sensor. Updating all sensors when high accuracy mode is on does not sound like something that would be battery friendly. Updating 1 sensor since we are awake and sending an update should have minimal impact.

Update geocode location sensor with location updates that are sent to HA

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt

Wear OS 3 devices use a dedicated companion app instead of one app by Google (like Wear OS 1/2). Due to how the HA app is setup, it only queries for packages at first to show the settings item. This PR updates the list of packages for the first non-Samsung, very expensive Wear OS 3 smartwatch.
n/a
n/a

Update Wear OS companion app packages

---

common/src/main/java/io/homeassistant/companion/android/common/data/keychain/KeyChainRepositoryImpl.kt

Fixes #2707 by returning `null` when unable to load the certificate chain or private key. This will result in a system prompt to select a valid, available certificate that is installed, instead of a crash. The error will also be logged.
Both of these functions specify `throws InterruptedException, KeyChainException`. Although I wasn't able to manually trigger them for testing purposes (the system returned `null` each time), the linked issue suggests it can happen.
n/a
n/a

Fix potential client certificate crashes

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Fixes the following sentry crash that is reproduced by sending `channel: ""` as part of a notification. We now default to `General` if the string is not provided or blank.
```
java.lang.IllegalArgumentException: null
at android.os.Parcel.createExceptionOrNull(Parcel.java:3027)
at android.os.Parcel.createException(Parcel.java:3007)
at android.os.Parcel.readException(Parcel.java:2990)
at android.os.Parcel.readException(Parcel.java:2932)
at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:4397)
at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:960)
at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:948)
at androidx.core.app.NotificationManagerCompat.createNotificationChannel …
```

Only change channel if variable actually provided

---

app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt

Fixes the following sentry errors:
```
java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:167)
at android.widget.Toast.getLooper(Toast.java:265)
at android.widget.Toast.<init>(Toast.java:250)
at android.widget.Toast.makeText(Toast.java:865)
at android.widget.Toast.makeText(Toast.java:853)
at android.widget.Toast.makeText(Toast.java:892)
at io.homeassistant.companion.android.qs.TileExtensions$tileClicked$2.invokeSuspend(TileExtensions.kt:152)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
at …
```

Fix unable to Toast on QS tiles being clicked error

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

This PR fixes downloading notification videos from servers that have enabled TLS client certificate authentication, [a bug reported in a comment on a related bug here](https://github.com/home-assistant/android/issues/2706#issuecomment-1207245382).
The app will now handle the downloading so that it is possible to provide the necessary authentication, instead of asking the system to do it. The file is removed as soon as the frames are extracted.
n/a, notifications will show videos again instead of not including them
n/a
cc @Rogue136198, as you reported this bug I'd appreciate it if you could also verify that the change works

Use OkHttpClient to download notification videos

---

app/src/main/java/io/homeassistant/companion/android/launch/my/MyActivity.kt

Fix #2778 by going back to the default webview instead of the app's version. my.home-assistant.io doesn't need certificate authentication so instead of adding `@AndroidEntryPoint`, it is better to remove the dependency to keep this as fast as possible.
n/a
n/a

Fix opening my.home-assistant.io links

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

This PR attempts to fix #2774 by keeping track of the `lastResponse` so we can unsubscribe with the correct response ID.

Save the last response so we can properly unsubscribe from events when the response ID has changed

---

app/src/main/java/io/homeassistant/companion/android/settings/websocket/WebsocketSettingFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/websocket/views/WebsocketSettingView.kt
app/src/main/java/io/homeassistant/companion/android/util/compose/HaAlert.kt
app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt
common/src/main/java/io/homeassistant/companion/android/common/util/AppNotifChannels.kt
common/src/main/res/values/colors.xml
common/src/main/res/values/strings.xml

Resolves #2164, part 1: Persistent Connection.
When trying to start the `WebsocketManager` as a foreground service, catch a `ForegroundServiceStartNotAllowedException` that may be thrown due to restrictions and show the user a notification to fix it. Tapping it will open the settings in the app, where a new alert is shown when the websocket is enabled but the app is not exempt from background restrictions (same colors as frontend alerts).
While the connection can technically be established without being a foreground service, it is unreliable so to offer a good experience it will stop trying to set up a connection when this exception is caught.
Example of notification posted:
Updated settings screen:
|Light|Dark|
|-----|-----|
|![The Persistent Connection settings screen, showing an alert …

Handle foreground service restrictions for persistent connection

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Was looking at some logs shown by a user in Discord and noticed one of our error messages not being meaningful so decided to expand it.
```
08-15 09:10:52.945 18360 18360 E WebviewActivity: onReceivedHttpError: android.webkit.WebResourceResponse@232afd0
```

Expand the error so its more meaningful

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

Found the following sentry error so avoiding the unsubscription when the ID is null
```
at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$subscribeToEventsForType$2$1$1$1.invokeSuspend(WebSocketRepositoryImpl.kt:206)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at …
```

Don't attempt to unsubscribe from event when the ID is null

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsViewModel.kt
app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt

We had a few closed issues and user complaints before and I was just reading the description for this flag and its behavior works well with our webview intents which require a new task to be created in order to properly load and change the URL. I don't think there are any other places to add this. In device controls we use a different flag so it is not impacted by showing multiple activities in recent apps.
I decided against adding this to sensor detail intent as I figured those users may actually need to navigate back to sensor settings faster if they need to make any further changes outside of granting permissions.

Add exclude recents flag to avoid showing multiple open activities in recents

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

This is the best of what I could come with to solve my issue of this app crashing.
It happens when I have WiFi and mobile date turned off and I turn on the screen.
I also came into a conclusion that the culprit is my temperature widget, though it's nothing out of ordinary.
The error I got:
> java.net.UnknownHostException: Unable to resolve host "\<my domain\>": No address associated with hostname at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124) ... and so on
I think it would be better to check for internet access before even doing the request but that's beyond my java skills.

Fix crash on widget update when internet is not connected

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/TemplateUpdatedEvent.kt

This PR updates the app's websocket implementation to support multiple subscriptions of the same type, and partially implements #2769.
**1. Websocket update**
The app will now not only track the `type` of a subscription but also any additional data, in order to support multiple subscriptions where the type is the same but the data is not (like templates, or specific entity updates). 
The logic for these subscriptions is the same as before: if an identical subscription already exists, it will return the existing Flow instead of starting another subscription.
**2. Template widget update**
The changes mentioned above are used to implement the first part of #2769: template widgets now use a subscription for the template instead of refreshing on any state change. Because there might be …

Support multiple subscriptions of same type in websocket and use in template widget

---

app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidgetConfigureActivity.kt

I noticed that adding a media player widget from the app's settings didn't work and failed with a Toast "Unable to create widget.", while it did work when added from the home screen.
This is because the list used to check that entities have been selected isn't updated immediately, but only on load or in a callback after pinning the widget. To work around this, manually check it before pinning the widget from app settings as well.
n/a
n/a

Fix adding media player widget from settings

---

common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/DetailsPanelView.kt

This PR changes the number of steps shown on the detail page of a fan entity because the default number of nine steps wouldn't work for fan entities with some percentage step size. This new function will calculate an optimal number of steps based on the percentage step size of the fan with a maximum of nine steps.
**Before**:
**After**:
**Before:**
**After:**
This fixes #2815

Calculate fan speed step count

---

app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt

Fix useless "Unable to open connection to Home Assistant" notifications caused by cancelled jobs for the WebsocketManager; fixes #2830.
(What the app really wants to catch is `ForegroundServiceStartNotAllowedException`s, but that was added in API 31 which is why it is using the closest exception class that is available on all supported API levels.)
n/a
n/a

Don't notify about cancellations in WebsocketManager

---

app/src/main/java/io/homeassistant/companion/android/notifications/NotificationDeleteReceiver.kt
common/src/main/res/values/strings.xml

Removes the toast notification when we fail to send a notification clear event.
I'm sending this out to see if there is interest in doing this. Here is my thinking for removing this notification:
For people that don't expose HA to the internet but still receive notifications there's no reason to continually show a toast every time a notification is swiped away. I personally feel a log is good enough (which the codebase already has) whereas a toast constantly gets in the way. If there was no other means of logging this then I could see the reasoning for having a toast.
My personal situation is nearly identical to the above. I don't expose anything out to the internet, instead I VPN back home when needed. I receive notifications from …

Remove toast when failing to send notification clear event

---

app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt

Noticed the following sentry error generating about 10k events, not really sure what triggers it as I could not reproduce but I also don't think we should be passing a `null` control over.  Assuming of course the `control` in this case is null. Ran some tests in the emulator and was able to add controls so probably just a sane null check is all that is needed 😃 
FWIW this error was first discovered in 2022.1.1
```
android.os.DeadObjectException: null
at android.os.BinderProxy.transactNative(BinderProxy.java)
at android.os.BinderProxy.transact(BinderProxy.java:584)
at android.service.controls.IControlsSubscriber$Stub$Proxy.onNext(IControlsSubscriber.java:183)
at android.service.controls.ControlsProviderService$SubscriberProxy.onNext(ControlsProviderService.java:292)
at …
```

Only add next subscription if control is not null

---

common/src/main/java/io/homeassistant/companion/android/common/data/authentication/AuthenticationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationRepositoryImpl.kt
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt

[While helping a user with problems in their Wear app](https://discord.com/channels/330944238910963714/562408603345092636/1012391255671591013), it became clear that the app provides almost no options to do anything and is easy to crash if the server can't be reached. This PR aims to address that.
- Catch exceptions thrown when executing calls to change an entity state instead of crashing the app. No visual feedback is provided as the app always shows the live state, so the lack of a visible change should be enough to indicate failure.
- Allow opening Settings when loading entities failed to make it possible to sign out.
- When logging out from the app fails during `revokeSession`, instead of crashing catch it and continue with logout in the app as the server might no longer be available. …

Prevent crashes on Wear when offline / server no longer available

---

common/src/main/java/io/homeassistant/companion/android/common/data/HomeAssistantVersion.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/SocketResponse.kt

Implement support for home-assistant/core#77238. Core will now combine multiple responses in 1 single websocket message if it's faster. Translation: it might return a JSON array of objects instead of a single object.
The logging for websocket has also been adjusted to handle these changes. To keep the logs readable and better match 'normal' network requests, it will no longer print the entire body on non-debug builds.
Example output (debug):
```
2022-08-27 18:10:52.323 28760-28760/io.homeassistant.companion.android.debug D/WebSocketRepository: Sending message 1: {type=supported_features, id=1, features={coalesce_messages=1}}
2022-08-27 18:10:52.332 28760-28760/io.homeassistant.companion.android.debug D/WebSocketRepository: Sending message 2: {type=config/device_registry/list, id=2} …
```

Support websocket message coalescing

---

app/build.gradle.kts
app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearFavoritesView.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/controls/ManageControlsSettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/controls/ManageControlsViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/controls/views/ManageControlsView.kt
app/src/main/java/io/homeassistant/companion/android/util/compose/EntityInfo.kt
app/src/main/res/drawable/ic_home_variant_outline.xml
app/src/main/res/xml/preferences.xml
common/build.gradle.kts
common/src/main/java/io/homeassistant/companion/android/common/data/integration/ControlsAuthRequiredSetting.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/res/values/strings.xml
wear/build.gradle.kts

Add support for using device controls while the device is locked on Android 13. By default this is enabled, as I feel like this is what most users expect and the system level setting for this was enabled by default on upgrade for me.
Because this is Home Assistant, users can enable/disable it for all entities or control the setting for individual entities. When enable/disable all has been used new entities will follow this setting, when individual entities have been adjusted new entities are enabled by default.
To make this possible this PR bumps the `compileSdk` to `33` (Android 13). The change in `GeocodeSensorManager` is because of this, as the function that is used was changed to be nullable.
Fixes #2381
A demo of the functionality, showing a locked device where you can use one …

Support device controls on locked Android 13 device

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Fixes #2834: the media notification command code is using `command` to check if the command data is included but `media_command` to do the actual command. Changed to use `media_command` everywhere to match the documentation.
n/a
n/a, now the code will match the documentation

Fix media notification command

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt
common/src/main/res/values/strings.xml

Fixes: #2846 by adding a setting so the user can adjust the divisor for the units their device supplies. Seems we have may have at least 3 different units even though android documentation says the value will be in micoramps.
Documentation: home-assistant/companion.home-assistant#804

Add a setting to battery power sensor to convert current when it is not in microamps

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/EntityRegistryUpdatedEvent.kt

Fixes #2853; the type for changes is usually a String but [not always](https://github.com/home-assistant/core/blob/73ba7a989b0cae6fba3564947d819e1eeb423f54/homeassistant/helpers/entity_registry.py#L107). Change the type to `Any` to handle this (even though the app currently never uses the changes).
n/a
n/a

Fix entity registry change type / crash

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

If the app tried to start a new websocket subscription before the last one with the same message/data was properly unsubscribed, the app would return a flow that is `null` and crash. To prevent this, change the unsubscribe logic to immediately remove the subscription ID (the confirmation isn't used). This will allow the app to start a new subscription and create a new flow even if the previous unsubscribe hasn't yet fully finished.
More info and reproduction steps in the original issue, which this PR fixes: #2852
n/a
n/a

Fix race condition in websocket unsubscribe/resubscribe

---

app/src/main/java/io/homeassistant/companion/android/qs/Tile10Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile11Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile12Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile1Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile2Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile3Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile4Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile5Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile6Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile7Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile8Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile9Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragmentFactory.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
common/schemas/io.homeassistant.companion.android.database.AppDatabase/33.json
common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
common/src/main/java/io/homeassistant/companion/android/database/qs/TileEntity.kt
common/src/main/res/values/strings.xml

This PR bundles a few improvements to the quick settings tiles setup process:
- Instead of disabling a tile in the QS panel when it hasn't been setup, make it inactive and deeplink to the specific tile's settings when tapping it. This makes it easier to set up the tile if you haven't browsed the app settings, and also helps with the Toast message not appearing / being hidden behind the QS panel on recent Android versions.
- When using Android 13, [use the new quick settings placement API](https://developer.android.com/about/versions/13/features#quick-settings) to allow adding a tile from the app's settings. If the tile was already added it will update like before.
- Don't show the tile subtitle option on Android versions before 10, as it simply isn't available for those versions.
A tile …

Improve adding quick settings tile

---

wear/src/main/java/io/homeassistant/companion/android/views/ExpandableListHeader.kt

If there is only one collapsible list, the app shouldn't collapse it by default as the app may not use a collapsible header in that case. Fixes #2858.
n/a
n/a
cc @leroyboerefijn somehow we missed this in #2804

Don't collapse lists by default if there's only one list

---

app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt

Instead of receiving all state changes when the device controls are open, only receive state changes for entities that were added as controls. This potentially reduces the amount of data used while controls are open (mostly saved by no changes for irrelevant entities, the change messages itself are similar in size).
n/a
n/a

Only subscribe to state changes for added controls

---

app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/TemplateUpdatedEvent.kt

Fixes #2865 by handling templates that return `null`, which is a valid result. These will, like in the preview and developer tools, show up as the string "null" on the widget.
(A similar change was previously made for the preview, but somehow this wasn't considered for subscriptions 🙃)
n/a
n/a

Fix template widgets that render null in websocket subscription

---

app/src/main/java/io/homeassistant/companion/android/controls/CameraControl.kt

Resolves #2870 by seting the thumbnail template for the camera control to active as long as the camera isn't `unavailable` and the app was able to download an image. This change aims to show the camera image more often and better match the frontend.
It depends on the device how controls are shown, this is on the Android 13 emulator.
Note the idle 'camera' that is now visible (showing [a weather map](https://www.home-assistant.io/integrations/buienradar/)). In the current version of the app both of these tiles would look like the unavailable camera in the screenshot.
n/a

Tweak camera control active state: true if not unavailable

---

app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt

Was helping a user on discord who mentioned they did not see all notification data in the attributes for active notification sensor, turns out we need to add the ID as well to keep the attributes unique otherwise they will overwrite each other.
Ref: https://discord.com/channels/330944238910963714/562408603345092636/1016456857574985738

Add item ID to active notification attributes to keep them unique

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/main/res/xml/changelog_master.xml

There has been a large increase in data traffic from the app to HA since the last release. This PR now requires a new notification parameter to be set so the app can send the received event. Users will need to set `confirmation: true` for the notification they wish to get confirmation the notification was received. This will allow us to cut down on traffic and let the user specify which notifications they actually want the event for.
example:
```
message: Test
data:
confirmation: true
```
Documentation: home-assistant/companion.home-assistant#818
FCM: https://github.com/home-assistant/mobile-apps-fcm-push/pull/92

Breaking Change: Only send notification received event if a notification wants the confirmation

---

wear/src/main/AndroidManifest.xml

Now that #2838 has been merged we need to update our manifest to mark the app as non-standalone since we no longer conform to the requirements.
https://developer.android.com/docs/quality-guidelines/wear-app-quality#best
`If the app is identified as standalone, it must be functional without requiring a phone for authentication or operation.`
https://developer.android.com/training/wearables/overlays/standalone-apps#identify
```
Standalone: completely independent app that does not require a phone app for core features including authentication; a phone app would provide only optional features.
Non-standalone: dependent app that requires a phone app or another device for core features including authentication.
```

Mark Wear OS app as non-standalone since we use phone for sign in now

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/res/values-v27/styles.xml

Fixes: #2876 by using the [recommended methods](https://developer.android.com/develop/ui/views/layout/immersive) from Google, most likely these were updated after we had this code. Changed the theme to reflect for displays with cutouts too based on [updated recommendation](https://developer.android.com/develop/ui/views/layout/display-cutout).
Tested on my pixel 6 pro by enabling the setting and also keeping the setting disabled and take a video into full screen. Also tested on an android 7 device to ensure the changes still work on older devices.
FWIW current code still continues to work on android 7 devices so this issue seems to impact newer version of android.

Fix full screen mode for all devices

---

app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/ssid/views/SsidView.kt
common/src/main/java/io/homeassistant/companion/android/common/data/url/UrlRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/url/UrlRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/wifi/WifiHelper.kt
common/src/main/java/io/homeassistant/companion/android/common/data/wifi/WifiHelperImpl.kt

Add support for entering BSSIDs to use for detecting when the internal connection URL should be used. These are entered and saved like any regular SSID, but contain the prefix "BSSID:". The SSID settings screen will recognize the prefix and apply some formatting to make it easier to see that they've been recognized.
Fixes #2880
The Home Network WiFi SSID screen with a BSSID alongside a regular SSID. It will remove the "BSSID:" prefix and instead shows the value in a monospace font. Active network detection (blue icon) still works.
|Light|Dark|
|-----|-----|
|![The Home Network WiFi SSID screen as described above, light mode.](https://user-images.githubusercontent.com/8148535/190478125-ed3755db-67ea-437d-9f49-280502d7897e.png)|![The Home Network WiFi SSID screen as described above, dark …

Add support for using BSSIDs for internal connection

---

app/src/main/java/io/homeassistant/companion/android/sensors/DynamicColorSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/DynamicColorsSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
common/src/main/res/values/strings.xml

Fixes: #2085 by adding a new sensor that gets the accent color from the dynamic color used. The state is in a hexadecimal format and an attribute is also provided for `rgb_color` in case a user wanted to use it for the `light.turn_on` service call. This sensor will only be available for devices that support dynamic color.
Documentation: home-assistant/companion.home-assistant#814

Add a dynamic color sensor for accent color

---

app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconMonitor.kt

Noticed the below sentry error in the latest beta so preventing accessing an index that will not exist so the app does not crash. I thought the [`assert()`](https://github.com/home-assistant/android/blob/1fb159999720b6065a3feb8198b344e267765750/app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconMonitor.kt#L61)  above would take care of this but I guess not? Do we need that check?
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.get(ArrayList.java:437)
at io.homeassistant.companion.android.bluetooth.ble.IBeaconMonitor.setBeacons(IBeaconMonitor.kt:64)
at io.homeassistant.companion.android.bluetooth.ble.MonitoringManager$startMonitoring$2.invokeSuspend$lambda-0(MonitoringManager.kt:53)
at …
```

Only check for beacons if the index is present

---

app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconMonitor.kt

Fixes a bug introduced in #2909 where the app keeps thinking there are new beacons because it is only checking for the UUID while the app now stores beacons using UUID+major+minor.
n/a
n/a

Fix BLE monitor new beacon check

---

app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt

Noticed the following error spamming logcat while testing other PR fixes so adding in the permission to avoid that.
```
2022-09-25 08:59:35.789  2898-3408  BeaconParser            io....stant.companion.android.debug  D  Cannot read device name without Manifest.permission.BLUETOOTH_CONNECT
```
Marking as a breaking change as the sensor may not be enabled if permissions are not granted.

Breaking Change: Add bluetooth connect permission to beacon monitor to prevent log spam from library

---

app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
common/src/main/res/values/strings.xml

To cut down on the amount of updates the app sends by default I am adding a setting for keeping the geocoded sensor update with location updates. This setting defaults to `off` which is previous app before behavior 2022.8.
Marking as a breaking change as the behavior is changing.
Documentation: home-assistant/companion.home-assistant#823

Breaking Change: Only update geocoded sensor with location if the setting is turned on

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRequest.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

This PR fixes a potential race condition for subscriptions on the websocket, where the first message might be dropped if it is delivered very soon after the subscription confirmation because the `eventSubscriptionFlow`/`eventSubscriptionProducerScope` haven't been set up yet. While not new, it is more likely to happen after #2829 because the server can send messages faster.
As this issue also applied to the notification flow, **I've merged the notification subscription logic with the more general subscription logic in this PR** so it can also receive the fix without duplicating code.
Inspired by [home-assistant-js-websocket](https://github.com/home-assistant/home-assistant-js-websocket), the app will now set up the response + subscription handlers immediately after _sending_ the initial …

Fix websocket subscription race/dropping first message

---

app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationFragment.kt
app/src/main/java/io/homeassistant/companion/android/themes/ThemesManager.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/res/values/arrays.xml
common/src/main/res/values/strings.xml

This PR simplifies themes by:
- **Merging the 'Follow Home Assistant' and 'Follow System Settings' theme options**
This was originally introduced in #1501 to be able to control the system bar colors, but that functionality was removed in #1950. As the two options currently behave identically and there haven't been any complaints, I'm merging them back in to one setting 'Follow System Settings'.
The merged option will be called 'Follow System Settings' because 'Follow Home Assistant' makes it sound like the app will use the theme setting from the frontend/profile which is not correct.
- **Removing webview force dark settings**
While the developer documentation [suggests that you use these 'force' settings](https://developer.android.com/develop/ui/views/layout/webapps/dark-theme), they are …

Simplify themes

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Following discussion in PR #2906, this PR adds two new options to the command_high_accuracy_mode notification which are useful if there are bluetooth or zone constraints set up.
- force_on: behaves as turn_on does currently; it turns on the highAccuracyModeSetting and sets an internal flag which forces high accuracy mode even if the constraints aren't currently met.  The flag is cleared when a force_off is received, or the constraints act to turn on high accuracy mode anyway.
- force_off: this does not alter the highAccuracyMode setting but sets an internal flag which forces high accuracy mode off even if the constraints are such that it would normally be on.  The flag is cleared if force_on (or turn_on) is receieved, or the constraints are such that high accuracy mode would be off …

Add new force_on and force_off options to command_high_accuracy_mode.

---

app/build.gradle.kts
app/src/full/AndroidManifest.xml
app/src/main/AndroidManifest.xml
build.gradle.kts
common/build.gradle.kts
common/src/main/AndroidManifest.xml
gradle/wrapper/gradle-wrapper.properties
wear/build.gradle.kts
wear/src/main/AndroidManifest.xml

Resolves #2886 failing to build
- Update Gradle to latest version (7.5.1)
- Update Android Gradle plugin to latest version (7.3.0)
- Move package out of manifest into gradle build files namespace as recommended (Android Studio: "Move package from Android manifest to build files: Declaration of a project's namespace using the package attribute of the Android manifest is deprecated in favour of a namespace declaration in build files.")
n/a
n/a

Update Gradle to 7.5.1, Android Gradle plugin to 7.3.0

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Default back to the app icon if the MDI icon does not exist in the library.

Default to app icon if icon is not available for notification

---

app/build.gradle.kts
app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt
app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearMainView.kt
app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardApp.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingViewModel.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationView.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/notifications/NotificationPermissionFragment.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/notifications/NotificationPermissionView.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/res/drawable/ic_notification_off.xml
app/src/main/res/xml/preferences.xml
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt

This PR includes updates to handle the [notification changes in Android 13](https://developer.android.com/about/versions/13/changes/notification-permission). It will also change the app's target Android version to Android 13, as being able to request notification permission when we want instead of when Android decides to, requires targeting Android 13.
A new screen is added to onboarding that requests the user to grant the notification permission on Android 13+ or when using the minimal version, and the app settings have also been updated to check if notifications are enabled on Android 8+.  I've opted to show the screen in onboarding to minimal version users on _all_ Android versions; on Android 13 denying the notification permission will also turn off the websocket service, so to …

Android 13 notification changes + target

---

app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/CompressedEntity.kt

This PR adds support for the `subscribe_entities` websocket subscription which delivers state + changes in a compressed format to reduce data usage, supposedly [by 35-90% depending on the message](https://github.com/home-assistant/core/pull/67891).
Device controls have been updated to use the new subscription on supported Home Assistant versions. 
Because `subscribe_entities` combines initial states + state changes in a single subscription, it is **not** a drop-in replacement for existing entity state changes subscribers, as those only deliver changes. Because the app re-uses subscriptions with the same request message users also have to be mindful of potential re-use, as they may not get the initial states if they are not the first subscriber.
n/a
n/a
Testing note: I don't think the …

Use compressed entity changes for device controls

---

wear/src/main/AndroidManifest.xml
wear/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SensorUi.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SensorsView.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

Adds permissions requests to Wear OS when a user enables a sensor, also adds Network Sensors as a start.
WTH: https://community.home-assistant.io/t/wth-dont-we-have-more-sensor-in-wear-os/469354
Documentation: home-assistant/companion.home-assistant#834
This was a "quick and dirty" approach to just get some more sensors added as permissions is holding up adding some of the sensors.  Some of this code may be stale but wanted to get some extra eyes on this.

Add permissions requests to wear OS sensors and add network sensors

---

app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearDetection.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/minimal/java/io/homeassistant/companion/android/settings/wear/SettingsWearDetection.kt

As Wear OS 3 watches are going to use an unique app for each brand, the HA app should use the Google APIs for detecting watches instead of hardcoding a list of companion apps to be more future-proof.
I have only tested this with an emulator (and without an emulator, for when there is no watch) which works well, but I'd appreciate it if anyone with a real watch could test it as well.
n/a
n/a

Don't use a hardcoded list of apps for Wear OS detection

---

app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearMainView.kt
app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Update the use of `onBackPressed` functions which have been deprecated to use the new `OnBackPressedDispatcher` and `OnBackPressedCallback`. This also makes it possible for the app to support the upcoming [predictive back gesture](https://developer.android.com/guide/navigation/predictive-back-gesture?hl=en).
No visible change, unless you have enabled support for the predictive back gesture in developer settings in which case you can see the home screen when there is no more going back in the app:
https://user-images.githubusercontent.com/8148535/194703057-583366c6-6da5-454c-a0eb-9ac36db1db86.mp4
n/a

Update deprecated onBackPressed, support predictive back gesture

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/DisplaySensorManager.kt
common/src/main/res/values/strings.xml

Fixes: #2948 by providing a new Screen Off Timeout sensor as well as a command to control its value. During testing I noticed that any value below 10000 was still treated as such, I imagine other devices may have a different limit. I also don't see a way to detect the limit so made sure to mention in the docs.
```
service: notify.mobile_app
data:
message: command_screen_off_timeout
data:
command: 15000
```
Documentation: home-assistant/companion.home-assistant#835
FCM: https://github.com/home-assistant/mobile-apps-fcm-push/pull/94

Add a screen off timeout sensor and command for control

---

wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt

Implements #2850: the settings chip is now visible in the Wear app while loading, in addition to when the app is ready or loading failed.
The aim is to have settings accessible, but not as a primary action. I have added an artificial delay to loading data for these videos.
With a favorite:
https://user-images.githubusercontent.com/8148535/195820324-3c8b51b2-1d77-4da1-8269-d30f138b7749.mp4
Without favorites:
https://user-images.githubusercontent.com/8148535/195820347-4af47d2f-5d21-4a35-a094-23df483cb70d.mp4
If you open the settings while the app is still loading, favorite editing is disabled to prevent the app showing an empty list (all other settings should be fine while still loading):
n/a

Show settings chip while loading Wear app

---

app/src/main/java/io/homeassistant/companion/android/sensors/MobileDataManager.kt

Fixes: #2977 by using the proper API when the device supports it.  Marked as a breaking change since the sensor now requires a permission to be granted

Breaking Change: Fix mobile data roaming sensor after target SDK change

---

app/src/main/AndroidManifest.xml

On the Onboarding activity change the status and navigation bar color to white to match the rest of the app. This screen wasn't using `Theme.HomeAssistant.Config` like most of the activities.
Before & After (light mode)
Before & After (dark mode) No difference

Fix navigation bar color on OnboardingActivity

---

app/build.gradle.kts

The removed dependecy was causing us to declare the `com.google.android.gms.permission.AD_ID` permission.  Since we don't actually use the permission and you need to manually declare it if used we are removing it.
N/A
N/A

Remove dependency that caused beta to fail to publish.

---

common/src/main/res/values/strings.xml
wear/src/main/AndroidManifest.xml
wear/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/WetModeSensorManager.kt

Adds a Wet Mode sensor to Wear. This is a special mode where the user must press and hold the crown/power button for 2 seconds to re-enable touch. May also be referred as Touch Lock or Water Lock.
Documentation: home-assistant/companion.home-assistant#845

Add Wet Mode Sensor

---

common/src/main/res/values/strings.xml
wear/build.gradle.kts
wear/src/main/AndroidManifest.xml
wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

Adds the first of [many](https://developer.android.com/reference/kotlin/androidx/health/services/client/data/DataType#public-companion-properties_1) sensors for the new Health Services API. For this first sensor I chose activity state as I know a lot of users want to know when they fall asleep so hopefully this works fast enough for them.  I ran some tests using the synthetic method Google [recommended](https://developer.android.com/training/wearables/health-services/synthetic-data#enable) and the state updates as expected. Will need to consider a good way to register and unregister for updates as a user enables or disables the various sensors they can have from this manager.
This sensor has 4 possible states: asleep, exercise, passive or unknown
Documentation: …

Add user activity sensor from health services for Wear OS

---

wear/src/main/res/layout/activity_onboarding.xml

This sets focus to the `WearableRecyclerView`. This makes the view scrollable on a rotary input (like the crown for the pixel watch). See [here](https://developer.android.com/training/wearables/user-input/rotary-input) for reference
Tested that on my own device, scrolling via crown worked afterwards

Set focus for onboarding activity to support rotary input

---

common/src/main/res/values/strings.xml
wear/src/main/AndroidManifest.xml
wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

Adds a hardware sensor to get the current heart rate. I think if we stream the heart rate data that may be really bad on battery life. With health services we do get heart rate updates however we have no control over how often they show up and from what I saw on my Pixel Watch it was a non-stop stream. Its better to use a hardware sensor here where we have more control over when the updates happen.
Documentation: home-assistant/companion.home-assistant#852

Add a heart rate sensor to Wear OS

---

app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/ssid/views/SsidView.kt
common/src/main/AndroidManifest.xml
common/src/main/java/io/homeassistant/companion/android/common/data/DataModule.kt
common/src/main/java/io/homeassistant/companion/android/common/data/url/UrlRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/wifi/WifiHelper.kt
common/src/main/java/io/homeassistant/companion/android/common/data/wifi/WifiHelperImpl.kt

Add a check to the external/internal URL logic to make sure that the device is not only connected to a Home Wi-Fi network, but is also using that network for data for using the internal URL. This better matches the expected behavior. Inspired by #3006. 
A device can be connected to Wi-Fi but may be using a different (usually mobile) network for data for example if the internet is down or the network is considered "low quality". Expected log output in these situations is something like:
```
2022-10-29 15:32:21.317 11938-12081 UrlRepository           io....stant.companion.android.debug  D  localUrl is: true, usesInternalSsid is: true, usesWifi is: false
2022-10-29 15:32:21.318 11938-12081 UrlRepository           io....stant.companion.android.debug  D  Using external URL
```
n/a
n/a
Testing …

Only use internal URL when data is also using Wi-Fi

---

app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt

Fix #3019 by switching from `Error` to `Exception` on Geocoder errors which will be caught.
`Error` [directly extends `Throwable`](https://developer.android.com/reference/kotlin/java/lang/Error?hl=en). On older APIs an `IOException` will be thrown.
n/a
n/a

Catch Geocoder exceptions on Android 13

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

Fix #3018 by checking if the continuation can be resumed before trying to resume it. If it was already resumed, the app isn't waiting for another message so discarding it should be OK.
n/a
n/a

Only resume once for websocket message responses

---

common/src/main/java/io/homeassistant/companion/android/common/data/url/UrlRepositoryImpl.kt

If home wifi SSID is empty then do not bother checking the connected SSID or BSSID as we don't need to access the data.
Ref: https://discord.com/channels/330944238910963714/562408603345092636/1036401886842064956

Don't check Wifi SSID when home wifi list is empty

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Increase (up to 2x!) the length of the GIF created for video attachments in notifications as the [Android 13 bug that limited this](https://issuetracker.google.com/issues/239945905) has been resolved shortly after release.
(Not sure why `if Android 13 short/else longer` wasn't added for this in #2657, but anyway it is no longer required.)
n/a, it's more of the same
n/a
cc @Rogue136198

Increase notification video attachment GIF length

---

common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/UpdateLocationRequest.kt

It turns out that #2969 breaks location updates for people on core <2022.2, which wasn't intended. This PR fixes that.
Always including `location_name` breaks compatibility with previous versions as it will reject updates: `Received invalid webhook payload: string value is None for dictionary value @ data['location_name']. Got None`. Updates would look like this:
```json
{"type":"update_location","data":{"gps":[1, 2],"gps_accuracy":13,"location_name":null,"speed":0,"altitude":47,"course":7,"vertical_accuracy":1}}
```
Now, updates on core <2022.2 and when using the 'Exact' setting look like this (again):
```json
{"type":"update_location","data":{"gps":[1, 2],"gps_accuracy":13,"speed":0,"altitude":47,"course":7,"vertical_accuracy":1}}
```
And 'Zone name only' updates will only include the …

Fix location updates on core <2022.2

---

app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearDetection.kt

If no Wear app is installed on a device, checking for nodes will throw an exception that the API is unavailable. This is an expected error, don't log it so users aren't confused / share an incorrect error for other issues.
```
2022-11-02 21:33:09.626 25472-25472 SettingsWearDetection   io....stant.companion.android.debug  E  Exception while discovering nodes
com.google.android.gms.common.api.ApiException: 17: API: Wearable.API is not available on this device. Connection failed with: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@18.0.1:3)
at com.google.android.gms.common.internal.zap.onComplete(com.google.android.gms:play-services-base@@18.0.1:4)
at …
```

Don't log full exception with no Wear app installed

---

app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/StepsSensorManager.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/OnBodySensorManager.kt

Noticed at times some hardware sensors would get its state stuck and thus needing a force stop of the app to reset the variable to continue to register for updates. I realized the state is stuck because other sensors were updating its state but these ones were not. So now adding a check where if 1 minute has passed and we are still registered on the next sensor update to reset the variable so we can get new updates.

Track time between hardware sensor updates to restart the listener as needed

---

wear/src/main/AndroidManifest.xml

Noticed that we forgot to add permissions for the boot completed intent so adding them here.
https://developer.android.com/reference/android/content/Intent#ACTION_BOOT_COMPLETED
The phone version also has this permission.

Add missing boot completed permission for Wear OS

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

Fix #3038 by not crashing the app when the connection is closed while a message was still being sent on the websocket, and instead returning `null` like what is done for invalid messages.
(Yes there should probably be better error handling but that also applies to returned messages/could be encapsulated in `SocketResponse` in the future. This PR simply provides a quick fix.)
n/a
n/a

Catch exceptions while sending websocket messages

---

wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt

Fixes: #3014 by converting our external collections (flows) from using `viewModelScope` to `lifecycleScope` and to only run while the state is `RESUMED`
These changes allow for initial data to load just like before but updates will only take place while the screen is on and app is in the foreground. When screen is off or app is in background the flows will stop.
<details>
<summary>Example logs where screen turns on/off and app goes in background/foreground with subscription stopping/starting as expected</summary>
```
---------------------------- PROCESS STARTED (5495) for package io.homeassistant.companion.android.debug ----------------------------
2022-11-07 08:10:43.850  5495-5548  WebSocketRepository     io....stant.companion.android.debug  D  Websocket: onOpen
2022-11-07 08:10:43.857 …
```

Switch from `viewModelScope` to `lifecycleScope` for external collections

---

app/build.gradle.kts
common/build.gradle.kts
wear/build.gradle.kts

Revert #3048 as Jackson 2.14 [increases the minimum SDK version to 26](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.14#compatibility-min-android-sdk), while the app has a minimum of 21 and this will currently result in crashes on versions <26.
n/a
n/a
[Short discussion with two crash logs on Discord](https://discord.com/channels/330944238910963714/377667559303938050/1042478429607579728)

Revert jackson-module-kotlin bump to fix compatibility on older Android version

---

wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt

We had a user mention on [discord](https://discord.com/channels/330944238910963714/562408603345092636/1042882512789176320) that their heart rate sensor will show a value of `-1` so lets skip any value below `0` as we are measuring in `bpm` so `0` will be the lowest acceptable value.
Hopefully we don't have to account for a crazy high value 😆 

Skip heart rate value updates when below 0

---

app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconMonitor.kt
app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailViewModel.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
wear/src/main/AndroidManifest.xml
wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/OnBodySensorManager.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

I have been noticing at times when the app is not on the doze whitelist that sometimes the sensor worker will not start/update, even when we open the app.
WorkManagers `doWork()` function calls `JobScheduler.schedule()` I noticed the following note in the docs:
`
Note: Scheduling a job can have a high cost, even if it's rescheduling the same job and the job didn't execute, especially on platform versions before version [Build.VERSION_CODES.Q](https://developer.android.com/reference/android/os/Build.VERSION_CODES#Q). As such, the system may throttle calls to this API if calls are made too frequently in a short amount of time.
`
Sure enough when the issue was happening on my Pixel Watch the worker calls were always immediately being canceled up until I would force stop the app.  I believe …

Reduce usage of job scheduling to avoid throttling

---

app/src/main/res/layout/widget_button.xml
app/src/main/res/layout/widget_static.xml

Button widget had asymmetrical top and bottom spacing. This PR tries to fix that.
Related issue: https://github.com/home-assistant/android/issues/3093
Portrait:
Landscape:
- The icon named old is from stock Home Assistant App kept for comparison with the newer ones.
- The only small downside of this approach is that on multiline text the icon becomes slightly smaller as compared to stock multi line icon (BTW stock multiline widget is not present in the screenshots above)
In order to fully solve this only downside with even better but complex approach is to use multiple layouts:
https://developer.android.com/develop/ui/views/appwidgets/layouts#provide-responsive-layouts

Button Widget: Uniform Spacing

---

app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesFragment.kt

Add support for toggling automations from the quick settings tiles, resolves #3095. The states are `on`/`off` and the service to call is `automation.toggle` so it only needs to be added to the list of supported domains.
(This was already supported in device controls.)
Documentation: home-assistant/companion.home-assistant#864

Support automation entities in quick settings tiles

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

When enabling a sensor on the server that requires additional permissions, the app will post a notification to let you know that it needs to be enabled from the app. The main app added an intent to that notification to open the sensor's settings when tapped, this PR adds a similar intent to the Wear OS app.
The notification that is posted when a sensor requires additional permissions (this isn't new):
It now includes an intent which will show up as a 'Open on watch' button (using the Wear OS 3 emulator):
Tapping on it will open the sensor manager's settings screen where the sensor can be enabled and permission(s) can be granted.
n/a
Testing note: after launching the app from the notification, the app in the recents screen seems to use this intent for subsequent launches until launched …

Add deeplinks to Wear OS sensor sync notifications

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

When trying to forward a download intent to the system catch the exception that is thrown if the system can't handle it to prevent a crash.
This should close #3098 as explained in my [comment on the issue](https://github.com/home-assistant/android/issues/3098#issuecomment-1328061532).
The app will show a toast to indicate the download is not supported when an exception is caught, for example when trying to use a blob URL:
https://user-images.githubusercontent.com/8148535/204135215-1ac23461-8cec-456b-91d5-8db46412760e.mp4
n/a

Don't crash when system is unable to handle download intent

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Only request the use of multiple tasks for intents from notifications when dealing with the Home Assistant app. For other apps, allow the app to decide how to handle this to better match user expectations (for example other apps with notifications and the launcher) - in most cases the intent will add to an existing task.
Fixes #2976 as tabs are now always added to the existing set of tabs.
n/a
The app behavior for notification actions isn't documented and as I think this better matches expectations a docs PR seems unnecessary.

Only request multiple tasks for HA notification intents

---

app/src/main/java/io/homeassistant/companion/android/nfc/NfcViewModel.kt
app/src/main/java/io/homeassistant/companion/android/nfc/views/NfcEditView.kt
app/src/main/java/io/homeassistant/companion/android/nfc/views/NfcNavigationView.kt

Due to the bugfix in home-assistant/core#82820, tag scanned events will now use HA's device ID instead of the Android's device ID. The in-app NFC settings show sample YAML code for when a tag is scanned, including the device ID. As Home Assistant's device ID only appears to be exposed via the device registry `identifiers` which is a [minefield](https://github.com/home-assistant/android/issues/2123#issuecomment-1007439106) I propose removing this sample on core >= 2022.12. 
Users that want to automate based on device can still get this ID from the developer tools or URL, as mentioned in the general tag docs.
|Light|Dark|
|-----|-----|
|![NFC tag settings in the Android app showing only one YAML sample, light mode](https://user-images.githubusercontent.com/8148535/204380135-e816a6d1-a905-481 …

Remove NFC tag sample YAML for 'scanned by this device' on 2022.12+

---

app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt

Fixes: #3120 by switching to state change trigger subscription for the tile. We are still doing an initial state update to make sure the state is current when the tile is first in view.  These tiles will now always have its active state in sync with the state of the entity, even when interacting with them.

Update quick setting tiles with state updates

---

.github/workflows/beta.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/weekly.yaml

Reverts home-assistant/android#3129
This is fun...
https://github.com/actions/setup-java/issues/422

Revert "Bump actions/setup-java from 3.6.0 to 3.7.0"

---

app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
common/schemas/io.homeassistant.companion.android.database.AppDatabase/35.json
common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
common/src/main/java/io/homeassistant/companion/android/database/qs/TileEntity.kt
common/src/main/res/values/strings.xml

Fixes: #3119 by introducing a new per tile setting (off by default) so the user can turn on vibration. As soon as the tile is clicked we will vibrate, then if the call fails we will vibrate again for longer.
Documentation: home-assistant/companion.home-assistant#868
Leaving as a draft until after #3121  to avoid a conflict. Submitting early to get feedback.

Add new option to vibrate when quick settings tile is clicked

---

wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt

This is an attempt to fix #3112 by keeping track of the last update received and restarting health services if its been 30 minutes since an update. I feel 30 minutes will be a good time period as there are really no other ways to detect the updates stopping. More than likely if a user only has User Activity State they will probably see the callback registering more frequently as a result of this change. I suspect when this issue occurs it impacts all things registered with the callback so best to include activity state.

Restart health services if no updates received in 30 minutes

---

app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml

Signed-off-by: Tamás Nagy (T-bond) <tbondvagyok@gmail.com>
Closes: #3130
Fix monochrome icon not showing on supported launcher and OS, according to Android Developers documentation:
[Adaptive icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)
Not relevant
I did not update the debug icon with the same change, for it to be easily differentiable from the normal application.
(Maybe an updated icon for example with a `DEV` label on it would be sufficent?)

Fix monochrome icon on Android 13+

---

app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
common/build.gradle.kts
common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/complications/EntityStateDataSourceService.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt
wear/src/main/java/io/homeassistant/companion/android/views/ChooseEntityView.kt

When creating quick settings tiles they will now show the entity icon by default. Users can still set a custom icon but using the same icon as setup in Home Assistant makes it easier to use and better matches expectations. Implements #3155.
The code to get the icon for an entity based on the domain is based on the frontend and was already used in the Wear app, I've moved it to the `common` module in this PR and added missing domains for quick settings tiles.
|The tile icon will match the domain or any custom icon set on the server|![Tile settings with an input boolean entity selected and a matching icon, light mode.](https://user-images.githubusercontent.com/8148535/208266568-e0d8c3ad-12d5-47f4-aef1-ce714c4059bf.png)|![Tile settings with an input …

Use entity icon for quick settings tiles by default

---

.github/workflows/beta.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/weekly.yaml

AdoptOpenJDK has moved to the Eclipse Foundation and now distributes binaries under the new name "Eclipse Temurin"

Migrate setup-java action to use Temurin

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/main/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt
common/src/main/java/io/homeassistant/companion/android/database/notification/NotificationDao.kt

Fixes #3150 by updating notifications with their replies [as documented](https://developer.android.com/develop/ui/views/notifications/build-notification#:~:text=After%20you%E2%80%99ve%20processed%20the%20text%2C%20you%20must%20update%20the%20notification%20by%20calling%20NotificationManagerCompat.notify()%20with%20the%20same%20ID%20and%20tag%20(if%20used).) instead of cancelling them (which the system mostly ignored), allowing users to continue manipulating notifications after a reply. 
To make this possible I've added a new "source" for notifications which reads an existing notification from the database and adds the provided data to it - these 'updated' notifications are not stored in the database.
n/a
n/a

Update instead of cancel notification on replies

---

app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
common/schemas/io.homeassistant.companion.android.database.AppDatabase/36.json
common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
common/src/main/java/io/homeassistant/companion/android/database/qs/TileEntity.kt
common/src/main/res/values/strings.xml

Add option to quick settings tile to only allow interacting with it when the device is unlocked, similar to device controls on Android 13. Fixes #3183.
Following the user suggestion for UI in the issue. Toggle is off by default to match behavior of system-provided tiles.
|Light|Dark|
|-----|-----|
|![Settings for a tile in the app with a new option "Requires unlocked device" switched on, light mode.](https://user-images.githubusercontent.com/8148535/210108624-e183e053-706f-4664-a3ce-e8905b5493ee.png)|![Settings for a tile in the app with a new option "Requires unlocked device" switched on, dark mode.](https://user-images.githubusercontent.com/8148535/210108628-1c8a8914-f110-4c0f-b91e-b3e6fb493848.png)|
Documentation: home-assistant/companion.home-assistant#880

Add option for unlocked only quick settings tiles

---

wear/src/main/AndroidManifest.xml

Fixes: #3197 as I had forgotten to add this permission to the Wear manifest

Add missing phone permission to Wear manifest

---

app/src/full/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
app/src/full/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt

- Fix low res entity icons
- Fix domains not being translated
- Add support for `input_button`, as `button` was already supported
- Use domain extension property
The increased icon resolution is clearly visible:
|Before|After|
|-----|-----|
|![An input button entity with a fuzzy, low resolution icon in the Android Auto emulator](https://user-images.githubusercontent.com/8148535/212158520-00520128-aafb-48a9-814a-3490fe9bb052.png)|![An input button entity with an icon that is as sharp as other icons/text on the Android Auto emulator](https://user-images.githubusercontent.com/8148535/212158393-df66bc4d-1b29-42b4-9eff-b1fcc6a53134.png)|
n/a (but shouldn't Android Auto support in general be documented?)

Minor Android Auto improvements

---

common/src/main/AndroidManifest.xml
common/src/main/java/io/homeassistant/companion/android/common/bluetooth/ble/IBeaconMonitor.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/BluetoothSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorUpdateReceiver.kt

Fixes: #3215 which was introduced after #3168 created a new class in `common` so we can actually send updates as it was not being sent before as `SensorReceiverBase` is abstract and cannot be instantiated. I am not sure if I should include all sensor managers in common here or only bluetooth as it is the only method using this type of update.

Fix beacon monitor not updating after move to common

---

app/build.gradle.kts
app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningActivity.kt
app/src/full/java/io/homeassistant/companion/android/matter/views/MatterCommissioningView.kt
app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearHomeView.kt
app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
app/src/main/java/io/homeassistant/companion/android/nfc/NfcSetupActivity.kt
app/src/main/java/io/homeassistant/companion/android/nfc/TagReaderActivity.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationFragment.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryFragment.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupFragment.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/notifications/NotificationPermissionFragment.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/notifications/NotificationPermissionView.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/welcome/WelcomeFragment.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/welcome/WelcomeView.kt
app/src/main/java/io/homeassistant/companion/android/settings/controls/ManageControlsSettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationChannelFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationDetailFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorSettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorUpdateFrequencyFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/url/ExternalUrlFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/websocket/WebsocketSettingFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/widgets/ManageWidgetsSettingsFragment.kt
app/src/main/res/values/styles.xml

With the latest dependency bumps the Compose Material (Components) Theme Adapter has moved to another package, update it to get rid of all the warnings while building. Also removed the dependency for appcompat theme adapter as it isn't needed.
```
compose-theme-adapter is deprecated.
The API has moved to accompanist/themeadapter/material.
For more information, please visit https://google.github.io/accompanist/themeadapter-material
```
n/a
n/a

Update Compose theme adapter dependency

---

app/src/full/java/io/homeassistant/companion/android/sensors/AndroidAutoSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
app/src/minimal/java/io/homeassistant/companion/android/sensors/AndroidAutoSensorManager.kt
common/src/main/res/values/strings.xml
wear/src/main/java/AndroidAutoSensorManager.kt

Add a binary sensor indicating if the device is connected to Android Auto.
Fixes: https://github.com/home-assistant/android/issues/2367
Fixes: https://github.com/home-assistant/android/issues/1516
Documentation: https://github.com/home-assistant/companion.home-assistant/pull/885

Add and Android Auto sensor!

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Fixes: #2684 by skipping the connection prompt when the loaded URL is either `local` or `api` as these pages will not have external bus communication.

Skip showing connection prompt when loaded URL is local or api path

---

common/src/main/res/values/colors.xml
wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationActivity.kt
wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt

A few more improvements to the conversation tile.
*  Added speech bubbles to align the text more like a conversation
*  If haptic feedback is enabled we will vibrate upon displaying the response
*  Close the activity when the screen turns off and we have received a response
*  Adds a preview of the speech bubbles

Conversation tile design changes

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt

This request addresses 2 issues at once, because they are interconnected:
1) Using wifiManager.scanResults to get signal strength is very unreliable. I often see "-1" on some devices even if Wi-Fi is connected. Use conInfo.rssi for a reliable result.
Also, wifiManager.scanResults is not available if Location is disabled on a device, but conInfo.rssi is available in such case.
2) There is an issue on devices running Android 10+ (tested on various Android 10 and Android 11 devices). If Wi-Fi is connected, but Location is disabled on a device,  getNetworkId() returns -1 and Home Assistant app thinks that we are not connected. But some information - IP address, link speed, frequency, signal strength (via getRssi()) is actually still available. If NetworkId == -1, we can additionally check …

Wi-Fi sensor improvements

---

wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

Forgot to add these skippable intents to Wear OS when the sensors were migrated over.

Add bluetooth skippable intents in case sensor is not enabled

---

common/src/main/java/io/homeassistant/companion/android/common/data/authentication/AuthenticationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationRepositoryImpl.kt
wear/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingPresenterImpl.kt
wear/src/main/java/io/homeassistant/companion/android/onboarding/manual_setup/ManualSetupPresenterImpl.kt

Fix #3242 by:
- allowing the library to insert the redirect URI in the OAuth request automatically, which will allow for using the China version `https://wear.googleapis-cn.com/3p_auth/io.homeassistant.companion.android`
- catching any exceptions that might be thrown when building the OAuth request instead of crashing
Because the server verifies if the request URI is valid, actually using the China version of the redirect URI requires changes in core (offline) and on the website (online), changes have been submitted which mention this PR (see below).
n/a
n/a

Set Wear OAuth redirect URI automatically and catch exceptions

---

app/src/full/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt

Improve how states for entities are displayed in the Android Auto interface
- Use string resources for common states to allow for translation
- Format timestamps to a relative time (if recent) to make it easier to read
n/a

Improve state for Android Auto: translate, timestamps

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
common/src/main/java/io/homeassistant/companion/android/common/notifications/DeviceCommands.kt
common/src/main/java/io/homeassistant/companion/android/common/notifications/NotificationFunctions.kt
wear/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Begins the migration process of notification commands to work on Wear OS. I do not expect many of the commands to carry over to Wear OS. A lot of the commands require special permissions  that simply don't exist in Wear OS nor is there an activity to let the user grant the permission. Commands should be accepted on a case by case basis if they will work.
In this PR I have moved over `command_ble_transmitter` and `command_beacon_monitor` I have also moved over the command data checks so they can reused by phone and watch.
Documentation: home-assistant/companion.home-assistant#889

Add ble transmitter and beacon monitor notification commands to Wear OS

---

wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt

Sometimes upon initial launch when the device is running slow the error message for not supported setup shows up briefly. This is due to the condition. Adding in a variable to keep track of the support check so we only show the error when we have completed the check. The default message when starting up should now be `...`.
Some design tweaks based on feedback around spacing to reduce scrolling to see the full response

Only show not supported error after support check is complete and design tweaks

---

app/src/full/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt

I originally thought that it was any entity but now I realize we limited the domains. Adding in `sensor` domain in case a user has a sensor or created a template sensor so it can also be navigated to.
Documentation: home-assistant/companion.home-assistant#896

Allow navigation to sensors in android auto if they contain proper attributes

---

app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt

Fixes: #3280 by invalidating the URL before updating the image

Invalidate cache before updating camera widget

---

wear/src/main/AndroidManifest.xml
wear/src/main/java/io/homeassistant/companion/android/complications/AssistDataSourceService.kt
wear/src/main/java/io/homeassistant/companion/android/complications/ComplicationReceiver.kt

Adds a watchface complication for Assist so users can quickly interact with it directly from the watchface.
Documentation: home-assistant/companion.home-assistant#898

Add a watchface complication for Assist

---

common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/SensorRequest.kt

Fix #3265, fix home-assistant/core#86875 by sending `null` when the state is not set or a blank string. This will prevent core errors about invalid state types because of the device class/state class/unit.
Tested with 2023.1 and 2023.2, and based on a quick check of the integration code `None` (in Python, so `null` in JSON) has always been accepted as a state.
n/a
n/a

Send sensor state as `null` if not set or blank

---

app/src/main/res/xml/changelog_master.xml

Update change log week of 2/3

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/PhoneStateSensorManager.kt

Had a user point out that their e-SIM was showing `unavailable` despite using a SIM. Turns out there is data but the `displayName` is `null` so now we will default to the `carrierName` instead of showing `unavailable`
We may need to mark this as a breaking change due to this behavior change.
Ref: https://community.home-assistant.io/t/e-sim-support/483806/17?u=dshokouhi

Default to carrier name when SIM sensor display name is null

---

app/src/full/AndroidManifest.xml

Indicate to Play Services that the app would like to have Matter support. While Android Studio cannot find the class, I suspect this will allow Matter support to be installed without requiring the user to have the Google Home app installed (but this isn't documented anywhere). [Based on the official sample app.](https://github.com/google-home/sample-app-for-matter-android/blob/264c8404cac2b5d1e4195adb6cea4caf12c812bc/app/src/main/AndroidManifest.xml#L71-L79)
n/a
n/a
Following a comment in home-assistant/home-assistant.io#26165

Add Matter module preferred to manifest

---

app/src/full/AndroidManifest.xml

Reverts home-assistant/android#3319
This caused us to be unable to upload the app to the Play Store or Firebase.

Revert "Add Matter module preferred to manifest"

---

app/src/main/java/io/homeassistant/companion/android/authenticator/Authenticator.kt
app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt

Fix #3299 by allowing device credentials in addition to (weak) biometrics when enabling app lock. [`canAuthenticate()`](https://developer.android.com/reference/kotlin/androidx/biometric/BiometricManager?hl=en#canAuthenticate()) has always required biometrics based on what I can find so this issue must not have been noticed before.
n/a
n/a

Allow device credential for app lock setup

---

app/build.gradle.kts
app/src/full/AndroidManifest.xml
app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningActivity.kt
app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningViewModel.kt
app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
app/src/main/java/io/homeassistant/companion/android/matter/MatterFrontendCommissioningStatus.kt
app/src/main/java/io/homeassistant/companion/android/matter/MatterManager.kt
app/src/main/java/io/homeassistant/companion/android/thread/ThreadManager.kt
app/src/main/java/io/homeassistant/companion/android/thread/ThreadModule.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
app/src/minimal/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/ThreadDatasetResponse.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/ThreadDatasetTlvResponse.kt
common/src/main/java/io/homeassistant/companion/android/common/util/TextUtil.kt

When starting Matter commissioning, automatically check if there are Thread datasets on the device or in core but not the other, and if so sync them. This new dataset should be marked as 'preferred' by Play Services/core as it is the only dataset available.
The app currently doesn't try to update or delete datasets automatically, for now this should be handled from the Thread config panel (not yet implemented).
There are no visible changes for importing a dataset to the device / exporting from Home Assistant, this happens in the background.
When exporting a dataset from the device / importing into Home Assistant, a permission dialog will be shown.
Frontend flow: see [the blog post about Thread earlier this month](https://www.home-assistant.io/blog/2023/02/08/state-of-matter-and-thread/#thr …

Sync Thread datasets when starting Matter commissioning

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorSettingsViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
app/src/main/res/drawable/ic_unfold_less.xml
app/src/main/res/drawable/ic_unfold_more.xml
app/src/main/res/menu/menu_activity_settings.xml
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
common/src/main/java/io/homeassistant/companion/android/database/sensor/SensorDao.kt
common/src/main/res/values/strings.xml

Allow users to enable/disable sensors (including location tracking) on a server level. By default sensors are the same on all servers, and I expect this will be fine for the majority of users, but it is a nice feature to have.
Syncing enabled state from the server (obviously) works. This change also speeds up sensor updates when one of the servers is down, as it doesn't have to wait on each server to check enabled before sending the state.
When using multiple servers, a new icon will be added to the toolbar to expand the settings which will show toggles for each server. If not all servers are using the same enabled state, it will always be expanded.
|Light|Dark|
|-----|-----|
|![Sensor settings screen for 'Detected Activity' with no major changes, two arrows pointing away from another are …

Enable/disable sensors per-server

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt

Enable the toggle for location tracking in onboarding when adding additional servers (when using the full flavor). This was previously disabled as sensors were shared between all servers but the app supports server-level sensor enabling now.
It's the same toggle as in initial onboarding
n/a, covered by note about multi-server sensors

Enable location tracking toggle in additional server onboarding

---

app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupView.kt
app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/url/views/ExternalUrlInputView.kt
wear/src/main/res/layout/activity_manual_setup.xml

Noticed that our input text fields for URLs (onboarding and server info) do not stop auto suggest from doing its thing. This has an undesirable effect of changing `homeassistant` to `home assistant` so if a user tries to type in `http://homeassistant.local` they may end up with `http://home assistant. local` or something similar. So disabling auto suggest on these fields to prevent that issue from occurring.

Disable auto suggest on input fields for URLs

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsPresenter.kt
app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsPresenterImpl.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebView.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

Update the app lock feature to work properly with multiple servers:
- In the webview activity, update locked state when switching servers using gestures or the chooser
- In the settings activity
- Check locked state before allowing access to servers with app lock enabled
- When resuming, update locked state for the active server (the one you would see if you go back to the webview) _and_ the visible server (if on the settings page for another server)
n/a
n/a

Multiserver app lock

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt

Prevent the `SensorWorker` runs from taking a long time if a server is offline when the app version changes due to re-registration of all sensors (~15 min, runs sequentially), by skipping these re-registrations if one fails with an exception that indicates the server can't be reached.
This isn't a new issue but more obvious with multiserver as it is more likely to have a server that is frequently offline/unreachable. The app version doesn't change with debug builds so this was spotted by @dshokouhi with updates on the internal test track :)
n/a
n/a

Improve sensor re-registration on app version change for offline server

---

wear/src/main/res/layout/activity_integration.xml
wear/src/main/res/layout/activity_manual_setup.xml
wear/src/main/res/layout/activity_onboarding.xml
wear/src/main/res/layout/view_loading.xml

This update is to meet upcoming play policy requirements where all backgrounds should be black on a wearable. I noticed the background was not exactly black so now forcing it for all the onboarding screens.
`Use a black background for all apps and tiles.`
https://developer.android.com/docs/quality-guidelines/wear-app-quality#upcoming
Before
After

Use a black background for Wear OS onboarding screens

---

common/src/main/res/values/strings.xml
wear/src/main/AndroidManifest.xml
wear/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
wear/src/main/java/io/homeassistant/companion/android/onboarding/phoneinstall/PhoneInstallActivity.kt
wear/src/main/java/io/homeassistant/companion/android/onboarding/phoneinstall/PhoneInstallView.kt

Push Wear OS users to install the Home Assistant app on their phone if they don't already have it, as the sign in experience is a lot better and less sensitive to errors. Allow using 'Advanced' if the user cannot or doesn't want to install the app on their phone.
The app's onboarding will open with this screen if the Wear app doesn't detect the phone app:
Scrolling down you get the option to refresh (= returns to the list with servers and manual URL, which will now open the phone app) or open an advanced option (= manual URL entry without app)
n/a

Push Wear users to install app on phone

---

app/src/main/java/io/homeassistant/companion/android/launch/LaunchPresenterBase.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsPresenterImpl.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

Noticed a crash when removing a server that wasn't there before, turns out there are possible race conditions as we usually remove a server and at the same time or immediately after that finish an activity or do something else that tries to update the active server, which now no longer exists. Catch exceptions in these cases as they are expected to prevent a crash.
n/a
n/a

Fix (potential) crashes when deleting a server

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Fixes: #3400 by adding a new constant of `noAction` so the notification does nothing as it has no content intent.
```yaml
service: notify.mobile_app_pixel_7_pro
data:
message: test
data:
clickAction: noAction
```
Documentation: home-assistant/companion.home-assistant#922

Allow clickAction to be set to noAction to do nothing

---

common/src/main/java/io/homeassistant/companion/android/common/bluetooth/ble/IBeaconMonitor.kt
common/src/main/java/io/homeassistant/companion/android/common/bluetooth/ble/MonitoringManager.kt

This MR fixes a bug, where the beacon monitor lists iBeacons that are out of range after enabling.
https://github.com/home-assistant/android/issues/3010 

Fix listed beacons that are out of range after enable

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/notifications/NotificationDeleteReceiver.kt

Fixes a few ANRs I saw in the play console around geofence updates and notification cleared event.
Fixes some bugs around evaluating the incorrect sensor in geofence updates (discovered during testing of this PR)
Removes toast notification on failed events

Move away from runBlocking and fix some bugs in geofence updates and clearing notification

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

This PR starts while investigating the app crashing while trying to make a SIP call with the sip-hass-card (https://github.com/TECH7Fox/sip-hass-card/issues/96). After giving permissions to both microphone and camera, the app just crashes with the following log:
```
03-08 16:50:12.261  9201  9201 W System.err: java.lang.IllegalStateException: Either grant() or deny() has been already called.
03-08 16:50:12.262  9201  9201 W System.err:    at org.chromium.android_webview.permission.AwPermissionRequest.a(chromium-TrichromeWebViewGoogle.aab-stable-548115333:34)
03-08 16:50:12.262  9201  9201 W System.err:    at Wz0.grant(chromium-TrichromeWebViewGoogle.aab-stable-548115333:109)
03-08 16:50:12.262  9201  9201 W System.err:    at io.homeassistant.companion.android.webview.WebViewActivity$onCrea …
```

Properly handle multiple permissions requests

---

common/src/main/res/values/strings.xml
wear/src/main/AndroidManifest.xml

Drop 'tile' from the template tile name for consistency with other tiles and other apps - 0 of the other tiles available on my watch include the word "tile".
n/a
Not needed, docs refer to tiles as "The [name] tile"

Drop 'tile' from template tile name

---

app/src/full/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsPresenterImpl.kt
app/src/main/res/drawable/ic_settings_remote.xml
app/src/main/res/xml/preferences_server.xml
app/src/minimal/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

This PR adds a feature that allows you to (dis)trust a server, or as it is named in the app choose whether the server can remotely control the app & device.
With multiserver you might add servers to the app for convenient access or push notifications, but you don't want them to receive and manage (all) your sensors and device like for your primary server. You can already for example disable sensors for a particular server, but what is the point if you can turn them back on remotely? This could expose data you don't want to.
Disabling this option (default is enabled to match current behavior) will stop the following features:
- Use notification commands to manage device features and sensor settings
- Enable/disable sensors from the server
As an intended side effect, when you don't trust a …

Server trust feature

---

app/src/full/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
app/src/full/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt
app/src/full/java/io/homeassistant/companion/android/matter/views/MatterCommissioningView.kt
app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
app/src/minimal/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
common/schemas/io.homeassistant.companion.android.database.AppDatabase/39.json
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/CurrentUserResponse.kt
common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
common/src/main/java/io/homeassistant/companion/android/database/server/Server.kt
common/src/main/java/io/homeassistant/companion/android/database/server/ServerUserInfo.kt
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
wear/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingPresenterImpl.kt
wear/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupPresenterImpl.kt
wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt

Get informaton about the current user and cache it in the database alongside the server. Information is periodically updated, when the registration is synced.
Use information about whether the user is an admin or not to:
- Fix #3313 by falling back to subscribing to all state changes + filtering results when the user is not an admin (the 'proper' solution would be to use `subscribe_entities` here but that requires significantly more work to handle re-used subscriptions, for now a quick fix is needed)
- Block Matter/Thread functionality, as all required websocket APIs are restricted to admins
n/a
n/a

Get user information and prevent using admin-only calls

---

.github/actions/create-release-number/action.yml
.github/workflows/beta.yml
.github/workflows/pr.yml
.github/workflows/release.yml
app/src/full/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
app/src/main/java/io/homeassistant/companion/android/BaseActivity.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
automotive/build.gradle.kts
automotive/src/full/AndroidManifest.xml
automotive/src/main/AndroidManifest.xml
common/src/main/res/values/strings.xml
settings.gradle.kts

Creation of Android Automotive Module in order to compile and deploy home assistant into Android Automotive following 
https://developer.android.com/training/cars/apps/automotive-os
Update Base Activity to be able to transition from Full activity to Car App library.
No real changes on the app looks / interactions, this will launch Android Automotive Car App Activity as the launcher and its following the same execution path that is today for Android Auto.
Android Automotive IOT documentation: https://developer.android.com/training/cars/apps/automotive-os

Android Automotive Module

---

app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningViewModel.kt
app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
app/src/main/java/io/homeassistant/companion/android/thread/ThreadManager.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

Expand the automatic Thread dataset sync on Matter commissioning to also send the device-preferred Thread dataset if it's different from core (it will either receive something new or update).
Thread datasets are now synced:
- If the device has a preferred dataset that doesn't match the server (because it has nothing or a different one), send the device dataset to the server
- If the device doesn't have a preferred dataset and the server does, add the server dataset to the device
n/a
n/a

Send device-preferred Thread dataset if different from core

---

app/src/full/java/io/homeassistant/companion/android/sensors/AndroidAutoSensorManager.kt

The `CarConnection` class registers for intents using the provided context which is not always accepted, so switch to application context instead. [Object created here](https://android.googlesource.com/platform/frameworks/support/+/androidx-main/car/app/app/src/main/java/androidx/car/app/connection/CarConnection.java#94) -> [registers intent here](https://android.googlesource.com/platform/frameworks/support/+/androidx-main/car/app/app/src/main/java/androidx/car/app/connection/CarConnectionTypeLiveData.java#72). The docs mention this [limitation](https://developer.android.com/reference/android/content/Context#registerReceiver(android.content.BroadcastReceiver,%20android.content.IntentFilter)); by using the application context, it will be tied to the application object lifecycle instead. …

Fix Android Auto connected sensor intent crash

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Fixes notifications for missing notification command permissions crashing the app because there was no server ID included for the notification
```
FATAL EXCEPTION: main
Process: io.homeassistant.companion.android.debug, PID: 29759
java.lang.NullPointerException
at io.homeassistant.companion.android.notifications.MessagingManager.createOpenUriPendingIntent(MessagingManager.kt:1388)
at io.homeassistant.companion.android.notifications.MessagingManager.handleContentIntent(MessagingManager.kt:950)
at io.homeassistant.companion.android.notifications.MessagingManager.sendNotification(MessagingManager.kt:893)
at io.homeassistant.companion.android.notifications.MessagingManager.sendNotification$default(MessagingManager.kt:832)
at io.homeassistant.companion.android.notifications.MessagingManager$not …
```

Fix notification for missing notification command permissions

---

app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt
common/src/main/java/io/homeassistant/companion/android/common/data/authentication/AuthenticationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/util/WearDataMessages.kt
wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt

This PR fixes a mismatch between the Wear and main app server settings / fixes #3086 by sharing the Wear server's session with the main app, and adding it as a temporary server to the main app to be used in the Wear device settings screen. This ensures both devices use the same information and authorizations.
n/a
n/a

Share Wear session with main app to fix mismatch

---

common/src/main/res/values/strings.xml
wear/build.gradle.kts
wear/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt
wear/src/main/java/io/homeassistant/companion/android/tiles/ConversationTile.kt
wear/src/main/java/io/homeassistant/companion/android/tiles/LoggedOutTile.kt
wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt
wear/src/main/java/io/homeassistant/companion/android/tiles/TemplateTile.kt

This PR adds a generic tile design to be used when the Wear app isn't logged in based on the [Dialog design as recommended](https://developer.android.com/training/wearables/design/tiles#dialogs): "In some cases, the user needs to (...) sign in (...) to see content on a Tile. Use dialogs to prompt users to take an action.".
Implements #3383
|Assist|Shortcuts|Template|
|![A tile titled 'Assist', 'Log in to Home Assistant to start using Assist', with a button 'Login'](https://user-images.githubusercontent.com/8148535/228345235-9112e7bc-e5b7-4ea5-ba94-772b4dc3ec49.png)|![A tile titled 'Shortcuts', 'Log in to Home Assistant to add your first shortcut', with a button 'Login'](https://user-images.githubusercontent.com/8148535/228345341-74f4ad01-3cd4-4ccf-975b-3a2c7a9c4092.png) …

Add logged out state to Wear tiles

---

app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt
app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearFavoritesView.kt
app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearHomeView.kt
app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearLandingView.kt
common/src/main/java/io/homeassistant/companion/android/common/util/WearDataMessages.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt

Improve the (perceived) responsiveness of onboarding a watch via the phone by showing a loading indicator after submitting to indicate it's doing something, and Snackbars for success/error.
On failure, sending the stacktrace over to the phone is also useful, for now I'm just printing to the log. Example:
```
2023-04-02 17:14:16.333 22245-22245 SettingsWearViewModel   io....stant.companion.android.debug  E  Watch was unable to register: java.lang.Exception
at io.homeassistant.companion.android.phone.PhoneSettingsListener$login$1.invokeSuspend(PhoneSettingsListener.kt:148)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:938)
at …
```

Improve phone feedback for Wear onboarding

---

wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt

Fixes the 'favorites only' setting staying enabled on Wear watches after removing all favorites, which blocked the user from turning the setting off.
n/a
n/a

Disable favorites only view on Wear if all favorites are deleted

---

app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt

Fixes: #3443 by resizing the camera images to the screen width to help preserve the image proportions and reduce the size of the image.
~~We should get some users in the issue to confirm the fix as my cameras and phone do not hit any limit set by the system.~~
Confirmation its working: https://github.com/home-assistant/android/issues/3443#issuecomment-1496232675

Resize camera widget images to screen width

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

Noticed the following JSON while trying to reproduce another issue:
```json
{"type":"fire_event","data":{"event_type":"android.zone_entered","event_data":{"accuracy":21.372,"altitude":47.274253209390835,"bearing":0.0,"latitude":0,"longitude":0,"provider":"fused","time":1680622928882,"vertical_accuracy":1,"zone":"27_zone.home","device_id":"bd78a79654bb7d61"}}}
```
The zone ID sent to the server includes the server ID, which could break automations listening for the zone ID (server ID isn't intended to be exposed). Update to remove it.
n/a
n/a

Fix zone event zone ID including server ID

---

app/build.gradle.kts
common/build.gradle.kts
common/schemas/io.homeassistant.companion.android.database.AppDatabase/40.json
common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
common/src/main/java/io/homeassistant/companion/android/database/wear/EntityStateComplications.kt
common/src/main/res/values/strings.xml
wear/build.gradle.kts
wear/src/main/AndroidManifest.xml
wear/src/main/java/io/homeassistant/companion/android/complications/ComplicationConfigActivity.kt
wear/src/main/java/io/homeassistant/companion/android/complications/ComplicationConfigViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/complications/ComplicationReceiver.kt
wear/src/main/java/io/homeassistant/companion/android/complications/EntityStateDataSourceService.kt
wear/src/main/java/io/homeassistant/companion/android/complications/views/ComplicationConfigMainView.kt

This PR includes multiple small improvements to the entity state complication to make it more flexible to use and hopefully take away some frustrations.
- Support the `LONG_TEXT` complication type. Implements #3463.
The watchface is responsible for choosing the type of complication that is used. As a result, the complication could change for some if it is in a slot where the watchface thinks long text is a better fit than short text. See [this codelab](https://developer.android.com/codelabs/data-sources#5):
> Keep in mind the watch face itself specifies the data types that a complication supports, and the order of preference of those types.
- Use the `friendlyState` function instead of raw state to support translation and datetime states.
- Add option to show/hide entity friendly name, as …

Entity state complication improvements (more flexibility)

---

common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/DetailsPanelView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
wear/src/main/java/io/homeassistant/companion/android/util/ColorTemperature.kt

When using at least HA 2022.11, use Kelvins for the color temperature instead of mireds to match the frontend.
n/a

Use Kelvin for light color temperature if available

---

common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt

Only change the time for when the session expires if the app is in use, otherwise the new session expires timestamp might unlock the app.
Fixes #3501
n/a
n/a

Fix app lock 'retry' unlocking app

---

app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailViewModel.kt

Fix #3486: zone entity ids can contain underscores, only split on underscores once to keep those that belong to the entity id (string is `serverid_entityid`).
(The data was stored correctly, the bug is only for how settings are displayed.)
n/a
n/a

Fix dialog options for high accuracy zone constraint entity id

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

When checking if an expanded zone geofence should be created include the server ID in the comparison as that is what is used everywhere else. Otherwise expanded zones are never added, and as a result high accuracy mode won't work as expected.
The setting in the database looks like `1_zone.work, 1_zone.treehouse` which is converted to the list `highAccuracyZones`. So when comparing we should add `1_` before the zone ID we're looking for :)
~~Marked as draft because I want to get some feedback from users in #3445 first, I normally don't use this feature.~~ 3 users in the linked issue indicate this resolves the issue.
n/a
n/a

Fix expanded zone id for high accuracy zone constraint

---

app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt

Fixes #3484 - it looks like I accidentally deleted reading stored service data for button widgets when editing them and didn't notice when adding multiserver 😬 This PR restores functionality based on the code before multiserver (6b06e0d8a8f7a451af3dcf4dc00444600aca8364).
n/a
n/a

Restore reading service data for configured button widgets

---

common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/AssistPipelineEvent.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationActivity.kt
wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt

This PR adds a basic level of support for the [Assist pipeline](https://developers.home-assistant.io/docs/voice/pipelines/) in core >= 2023.5, and updates the Wear OS app Assist implementation to use it instead of the conversation API. There should be enough pieces in place to start doing more with the pipeline in the future :)
The first commit of this PR updates the app's websocket message handling. Currently, all received messages are processed asynchronously, which means they can be delivered to subscribers in a different order than received. This can be a problem for the Assist pipeline, which receives multiple messages almost instantly. The commit changes processing to process multiple messages for a single request in the order they're received, other requests are still processed …

Add support for Assist pipeline, update Wear implementation

---

common/src/main/java/io/homeassistant/companion/android/util/FlowUtil.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt

In order to improve performance on Wear OS, throttle/debounce getting registry data when the websocket subscription tells the app there is an update to it. This significantly reduces network traffic and background work for displaying the UI when there are a lot of changes in a short amount of time, and also lightens load on the server. [The frontend also does this](https://github.com/home-assistant/frontend/blob/4e390b4c5707bcd1d769217d87fd250d1b1af68f/src/data/entity_registry.ts#L199).
Example: with a period of 1000ms and 110 events 10ms apart, only event 1, 100 and 110 are emitted.
Scenarios where this can happen: logging in to the app for the first time (device registration + sensor registrations), or adding new integrations on the server, or lots of changes like updates.
I've placed …

Add throttling/debouncing on Wear OS for registry updates

---

app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesViewModel.kt

Prevent unnecessary changes to the selected entity when changing servers, if an entity exists on both servers. It already didn't clear everything like title/icon override, just the selected entity! The app is still calling `selectEntityId` in case the icon is different.
Resolves #3529
There is a video showing the selected entity not changing when selecting a server in the linked issue.
n/a

Don't reset QS tile entity when changing servers if existing on new server

---

app/src/full/AndroidManifest.xml
app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningActivity.kt
app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningViewModel.kt

It looks like fast pair/shared Matter devices now re-use the commissioning activity if it is still open in the background. Set the launch mode to single top to be able to use `onNewIntent` and get data for new devices.
n/a; the flow will restart if a new intent is delivered
n/a

Handle updated intents for Matter commissioning

---

automotive/src/main/AndroidManifest.xml

Automotive OS requires applications to declares uses-features as false, for more information please see https://developer.android.com/training/cars/apps/automotive-os

Manifest Changes per Automotive documentation.

---

app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsPresenter.kt
app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsPresenterImpl.kt
app/src/main/java/io/homeassistant/companion/android/settings/websocket/WebsocketSettingFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/websocket/views/WebsocketSettingView.kt
common/src/main/java/io/homeassistant/companion/android/common/data/DataModule.kt
common/src/main/java/io/homeassistant/companion/android/common/data/wifi/WifiHelper.kt
common/src/main/java/io/homeassistant/companion/android/common/data/wifi/WifiHelperImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt

Fix #3536 by gracefully handling no `WifiManager` and hiding related options and features.
Unable to test this as all my devices and emulators have Wi-Fi, but manually changing things to false seems to work as expected.
|Settings for internal connection + networks, app lock bypass on internal network are removed|![Settings screen without the mentioned settings, light mode](https://github.com/home-assistant/android/assets/8148535/58324181-6ba4-4b69-b1e9-9ed6c510513f)|![Settings screen without the mentioned settings, dark mode](https://github.com/home-assistant/android/assets/8148535/f0d9d671-6ece-4595-853c-48c48b96d7d0)|
|Setting for persistent connection on home Wi-Fi is removed|![Persistent connection settings with only Never, While screen is on, …

Handle no `WifiManager` and prevent crash

---

app/build.gradle.kts
app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
automotive/build.gradle.kts
build.gradle.kts
common/build.gradle.kts
wear/build.gradle.kts

This PR:
- aligns dependency versions between projects (for example, the app was using two different Kotlin patch releases) / modules (`automotive` was behind on dependencies already increased in `app`), and
- updates Google dependencies that are not picked up by dependabot.
Noteworthy changes:
https://developer.android.com/jetpack/androidx/releases/compose-compiler support for Kotlin 1.8.21
https://developer.android.com/jetpack/androidx/releases/compose-runtime#1.4.3 fixes a "potential deadlock in snapshot list and map" which may be what I was encountering with the ANR (see below)
https://firebase.google.com/support/release-notes/android no cloud messaging changes
These changes also seem to resolve a frequent ANR after load I'm facing with the latest beta for the Wear app and wasn't able …

Align dependency versions and bump Google dependencies

---

common/src/main/java/io/homeassistant/companion/android/database/server/ServerConnectionInfo.kt

While doing performance tracing on a Pixel 4a, I noticed that when launching the app it takes on average 75-100ms to read server data. Almost all of that time is spent getting a Jackson `ObjectMapper` to convert the database value for internal SSIDs to a list...
... which if empty `"[]"` is a huge waste of time. So this PR adds a simple string comparison before getting Jackson to speed up startup. This performance improvement is even nicer on watches which are usually slower and will **never** have SSIDs.
It might be easier to compare the `setContent` function in the trace, reading from the database is now negligible:
Jackson will be used later for network but at that point the app isn't waiting on it to continue launching.
Modern phones don't take quite as long to get Jackson but it …

Speed up cold start by skipping Jackson ObjectMapper if possible

---

wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/DetailsPanelView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/EntityListView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SensorManagerUi.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SensorsView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetTileShortcutsView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/TemplateTileSettingsView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/TimeText.kt
wear/src/main/java/io/homeassistant/companion/android/onboarding/phoneinstall/PhoneInstallView.kt

- Add a `Scaffold` which provides a `PositionIndicator` while scrolling and `TimeText` to screens which didn't have them. This also contributes to the upcoming app quality requirement 'Visual quality: Show time (apps)':
> We recommend that you display the time of day at the top of all activities except dialogs and confirmation screens.
- Change `TimeText` to only show up at the top of the screen contents instead of at the top of the screen, in line with other Material 3 Google apps.
Time and scrollbar on a screen that previously didn't have it:
A screen that is scrolled down now doesn't show the time at the top of the screen:
n/a

Update Wear Scaffold usage to be more consistent

---

wear/src/main/java/io/homeassistant/companion/android/onboarding/phoneinstall/PhoneInstallView.kt
wear/src/main/res/layout/activity_integration.xml
wear/src/main/res/layout/activity_manual_setup.xml
wear/src/main/res/layout/activity_onboarding.xml
wear/src/main/res/layout/view_loading.xml
wear/src/main/res/values/colors.xml

I noticed that the background for Assist on watches was still dark grey instead of black. It's black in most other activities because of Compose's `SwipeToDismissBox` adding it for us, or because we manually added it.
This PR sets the theme default to black to match the [app quality guidelines](https://developer.android.com/docs/quality-guidelines/wear-app-quality#upcoming) + removes activity/view specific backgrounds that are black and no longer needed.
|Before|After|
|-----|-----|
|![Assist activity with a dark grey background](https://github.com/home-assistant/android/assets/8148535/40bea696-2c02-440d-8733-0cb519695a77)|![Assist activity with a black background](https://github.com/home-assistant/android/assets/8148535/af86e4ac-baf5-4b8a-8c10-0a5800817a73)|
n/a
> Visual quality | Black …

Set Wear theme background color to black

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

While working on other code I noticed that the documentation for websocket Matter/Thread functions was misplaced in the `WebSocketRepositoryImpl` class, hiding it from outside. Moving it to the interface to expose it 'publicly' and allow it to e.g. show up in IDE tooltips.
n/a
n/a

Expose docs for websocket Matter/Thread functions

---

wear/src/main/AndroidManifest.xml

Add assistant app intent filter to the Assist activity in the Wear OS app to allow the app to be registered.
This may or may not allow the app to be launched when using the watch's assistant key/shortcut. For example, on my Galaxy Watch 4 the companion app allows choosing between Bixby and Google Assistant, which when set to Google Assistant fires the intent `android.intent.action.VOICE_ASSIST` which will now include HA and show a 'Complete action using' dialog.
n/a
n/a

Add intent filter for button to Wear Assist activity

---

.github/actions/create-release-notes/action.yml
.github/actions/create-release-number/action.yml
.github/workflows/monthly.yaml
.github/workflows/onPush.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/weekly.yaml
.gitignore
README.md
app/build.gradle.kts
automotive/build.gradle.kts
build.gradle.kts
common/build.gradle.kts
settings.gradle.kts
wear/build.gradle.kts

Attempting to simplify the release cycle and hopefully improve our review times with Google.  Our weekly play store release will now be tagged and ready for promotion rather than needing another review.

First attempt at a new release model.

---

app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt

Fixes the below crash:
```
FATAL EXCEPTION: main
Process: io.homeassistant.companion.android, PID: 9353
java.lang.RuntimeException: java.lang.IllegalArgumentException: The title cannot be null or empty
at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:154)
at androidx.car.app.utils.RemoteUtils$$ExternalSyntheticLambda1.run(Unknown Source:6)
at androidx.car.app.utils.ThreadUtils.runOnMain(ThreadUtils.java:39)
at androidx.car.app.utils.RemoteUtils.dispatchCallFromHost(RemoteUtils.java:146)
at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$1(RemoteUtils.java:185)
at androidx.car.app.utils.RemoteUtils$$ExternalSyntheticLambda2.run(Unknown Source:8)
at android.os.Handler.handleCallback(Handler.java:942)
at …
```

Supply entity ID if friendly name is empty in android auto

---

app/src/main/java/io/homeassistant/companion/android/vehicle/MapVehicleScreen.kt

Just a small clean up PR. I think if you have a lot of devices that are at home and have a device tracker it may seem a bit redundant to list them all. One example is if a user has wall mounted tablets with the app installed.
I decided not to touch `person` entity as you may not care if they are home or not, you just want to navigate to them.
sensors and zones are left untouched as sensors may not have an expected state and zones should always be shown like person.
Documentation: home-assistant/companion.home-assistant#949

Hide devices that are home from the android auto navigation screen

---

app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt

Based on feedback received we need to hide native mode for now in the automotive play store builds. The automotive minimal version is not impacted by these changes.
- Upon app launch and completing onboarding the template grid screen will load
- Native Mode button is hidden
I have done testing in an emulator using the full version

Hide native mode UI from automotive play store builds

---

app/src/main/java/io/homeassistant/companion/android/assist/AssistActivity.kt
app/src/main/java/io/homeassistant/companion/android/assist/AssistViewModel.kt
app/src/main/java/io/homeassistant/companion/android/assist/ui/AssistSheetView.kt
common/src/main/res/values/strings.xml

By request from @balloob, add a 'Manage assistants' link to the assistant dropdown in native Assist when launched from the frontend.
|Light|Dark|
|-----|-----|
|![Option 'Manage assistants' as the last Assist dropdown item, light mode](https://github.com/home-assistant/android/assets/8148535/929173d8-6184-4e71-be2b-63f34b74cffa)|![Option 'Manage assistants' as the last Assist dropdown item, dark mode](https://github.com/home-assistant/android/assets/8148535/abc7a563-be59-4594-ab6a-0a10f8c24f91)|
n/a

Add 'Manage assistants' button to native Assist

---

.github/actions/download-translations/action.yml
.github/workflows/onPush.yml
.gitignore

Make sure we have a clean workspace for our tagging.

Fix dirty SCM

---

app/src/full/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt
app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearDetection.kt
app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/DataModule.kt

Hides a few features that depend on GMS APIs currently unavailable on Automotive according to this list: https://developer.android.com/training/cars/google-services. Including the dependencies in the app doesn't cause the crash considering the current release so a simple check will be enough and keeps manifest/dependencies the same for `app` and `automotive`.
(activity sensors are in `com.google.android.gms.location` weirdly enough, so not hiding those for now)
With the native interface now hidden it doesn't really matter that much but still nice to be prepared.
n/a
n/a

Hide a few GMS features unavailable on Automotive

---

app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/EntityRegistryResponse.kt
wear/src/main/java/io/homeassistant/companion/android/complications/EntityStateDataSourceService.kt

Fix #3397 by switching the entity state widget to use the friendly state (= formatted and translated), which now uses the entity registry options for more formatting.
Because friendly state is used to fix this, it also means:
- the Wear entity state complication also receives this fix
- state should now be displayed the same for the main app widget and Wear entity state complication
This sensor has a state of `52.94685`, options `display_precision` `null` and `suggested_display_precision` `2`. The stable app ignores all this, the updated app formats the number as shown in the frontend.
n/a

Support sensor display precision

---

app/src/main/res/xml/changelog_master.xml

Update change log week of 6/30

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsHomeSuggestion.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenter.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsSuggestionPreference.kt
app/src/main/res/drawable/ic_comment_processing_outline.xml
app/src/main/res/drawable/preference_suggestion_background.xml
app/src/main/res/layout/preference_suggestion.xml
app/src/main/res/xml/preferences.xml
common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepositoryImpl.kt
common/src/main/res/values/colors.xml
common/src/main/res/values/strings.xml

Add a suggestion area to the top of the main app settings screen where _very_ important settings can be promoted. Inspired by the contextual suggestions in the stock settings app, M3. Only one suggestion will be shown (at random from all available suggestions) to prevent too much clutter.
This PR includes two settings to start - more can be added later but we should try to keep it to a minimum, only for core functionality.
- Set Home Assistant as an assistant app
- Enabling the notification permission
|----|----|----|
|Assist suggestion|![A 'bubble' with the Assist icon, 'Use Assist from anywhere: Set Home Assistant as your assistant app' at the top of the settings screen, light mode](https://github.com/home-assistant/android/assets/8148535/eb96bb3a-ce3c-405c-a6ec-8a1e86 …

Implement suggestion area in app settings

---

app/src/main/java/io/homeassistant/companion/android/vehicle/LoginScreen.kt
common/src/main/res/values/strings.xml

The car interface login screen is quite basic and doesn't give any feedback after pressing login for Auto users, trying to improve it a bit and make it more consistent with the normal onboarding because it is the first screen Automotive users see.
|Before|After|
|-----|-----|
|![Home Assistant title in the top bar with a text 'Not logged in', button 'Login'](https://github.com/home-assistant/android/assets/8148535/f365cb48-b622-4f57-a556-a7f77e79d4c5)|![Centered Home Assistant logo with the text 'Welcome to Home Assistant Companion!' and a button 'Login on your phone'](https://github.com/home-assistant/android/assets/8148535/b74a06e0-846f-41ab-b366-ad8a4e2b5af6)|
n/a

Minor update to Auto(motive) login screen

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt

Minor fix for the settings suggestion:
- Don't suggest setting HA as the assistant app on Android L as this setting doesn't exist yet
- Allow suggesting setting HA as the assistant app on Android M as this setting was added in M
n/a
n/a

Don't show assistant app suggestion on L, show on M

---

app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt

Fixes: #3648  by forcing updates of the sensor when a media session is in progress. I chose to go by `Unavailable` state as that particular state should only get 1 update.

Force update on media session sensor when a session is in progress

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt

It looks like not all devices keep the original settings names, fallback to the 'manage default apps' intent if we cannot directly open the screen for the assistant app setting.
Play Console, Android 13, various devices (mostly Samsung):
```
Exception android.content.ActivityNotFoundException:
at android.app.Instrumentation.checkStartActivityResult (Instrumentation.java:2203)
at android.app.Instrumentation.execStartActivity (Instrumentation.java:1841)
at android.app.Activity.startActivityForResult (Activity.java:5616)
at androidx.activity.ComponentActivity.startActivityForResult (ComponentActivity.java:754)
at android.app.Activity.startActivityForResult (Activity.java:5569)
at androidx.activity.ComponentActivity.startActivityForResult (ComponentActivity.java:735)
at …
```

Assistant app intent fallback to 'safe' intent if not found

---

app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
app/src/main/java/io/homeassistant/companion/android/util/compose/SingleEntityPicker.kt
common/src/main/res/values/strings.xml

Adds a new Composable `SingleEntityPicker` which aims to provide a text input with autocomplete search for entities like the frontend, where you can pick one and easily see which one was picked. This will be useful to have in various places.
Replaced the picker in tiles for now as an example of how it would be used to [resolve this unsubmitted feature request](https://discord.com/channels/330944238910963714/562408603345092636/1127934779426353322). I'll follow up with another PR implementing it in more places if this is accepted.
The frontend includes full fuzzy searching which I'm not going to attempt in the first PR, starting with a search based on friendly name and entity ID, sorting results based on friendly name starts with > entity ID starts with > friendly name to hopefully show the …

Implement a frontend-like single entity picker

---

app/src/full/java/io/homeassistant/companion/android/sensors/AndroidAutoSensorManager.kt

Hide the android auto sensor section on devices that don't support it. The list was already empty so users could not enable it but good to clean up the UI as the section is not needed to be displayed on those devices anyways.

Hide android auto sensor section from devices that do not support it

---

common/src/main/res/values/strings.xml
wear/src/main/AndroidManifest.xml
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt

Adds a toggle for enabling/disabling the option to use Assist as an assistant app (= intent filter on Assist activity), as users may not be able to change the app used after choosing 'Always' and Wear OS 2 doesn't ask the user which app to use, and users can't change the default assistant app, which can result in Assist instead of the Google Assistant being forced.
Also reported in [this forum post](https://community.home-assistant.io/t/wearos-companion-issues/592070) and [these Discord messages](https://discord.com/channels/330944238910963714/562408603345092636/1129914534732243085).
Ironically, this is best visible when you can choose the assistant app, as you will see Home Assistant show or hide depending on the setting:
|Setting in app|On: HA available|Off: HA removed| …

Add toggle for Assist as assistant app on Wear

---

app/src/main/java/io/homeassistant/companion/android/assist/AssistActivity.kt
app/src/main/java/io/homeassistant/companion/android/assist/AssistViewModel.kt
app/src/main/java/io/homeassistant/companion/android/widgets/assist/AssistShortcutView.kt
common/src/main/java/io/homeassistant/companion/android/common/assist/AssistViewModelBase.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt

Update native Assist to better match frontend Assist behavior:
- default to the last used pipeline if not specified instead of the preferred pipeline
- allow the frontend to choose between `last_used`, `preferred`, or a specific pipeline -> requires home-assistant/frontend#17329 / 2023.8
Breaking change, matching frontend: Assist shortcuts will open last used pipeline by default instead of preferred. To use preferred, recreate the shortcut.
|Assist shortcut options updated with 'Last used assistant' (default)|![Assist shortcut options menu for 'Assistant', now includes an option 'Last used assistant', light mode](https://github.com/home-assistant/android/assets/8148535/4abf3b99-38f8-4c5a-a581-4935a2b8df75)|![Assist shortcut options menu for …

Breaking change: support last_used/preferred pipeline IDs and use last_used by default

---

app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
app/src/main/java/io/homeassistant/companion/android/settings/developer/DeveloperSettingsPresenterImpl.kt
app/src/main/java/io/homeassistant/companion/android/thread/ThreadManager.kt
common/src/main/res/values/strings.xml

The Thread credential sync currently only adds the HA credentials once; once added it is not updated or removed.
This PR updates the sync to update or remove the HA credential if detected that the device prefers a credential added by the app, but it isn't the same one preferred by the server.
This might also resolve the error from https://github.com/home-assistant/android/issues/3582#issuecomment-1633618476, but not 100% sure.
n/a
n/a

Update Thread network sync to update/delete HA networks

---

app/build.gradle.kts
automotive/build.gradle.kts
build.gradle.kts
common/build.gradle.kts
wear/build.gradle.kts

Because the Kotlin DSL doesn't support variables we need to up manually bump them at once, really annoying.
N/A

Hilt Dependency Update

---

app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
common/src/main/res/values/strings.xml

- Send state based on reported status so users know if a sensor is not implemented  
- Apply `Car` prefix to sensor names for consistency and easy identification.
- Add some more logging for troubleshooting
- Minor clean-up
Add some debug logging around car data as I am only seeing Car Name being pulled in, even after going for a drive increasing odometer and decreasing fuel.
CC: @drosoCode in case you have any ideas on why some data is not retrieved.

Send state based on reported status, apply car prefix to car sensors, add some logging around new car sensors

---

app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorListView.kt

Noticed that sometimes we were showing unit of measurement when the state was not numeric, so now we will hide the units to show the string properly.

Only show unit of measurement if we have it and if the state is not a string while managing sensors

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Fixes #3667 as mentioned in [my last comment](https://github.com/home-assistant/android/issues/3667#issuecomment-1642751512) - Android Auto shows group summary notifications and the individual notifications, which is not expected, so don't mark the summary notification as available on cars to prevent this.
Group summary notifications still appears on phone:
But not in the Android Auto interface, only the two individual notifications:
I don't think this is needed, the docs already mention not all features are supported and this change will make it better match expectations.

Don't send group summary notifications to Android Auto

---

app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/MapVehicleScreen.kt

Fixes: #3479 by only adding up to the allowed limit of entities.  It does not seem like we will always hit this issue as my own production instance goes over the limit however there are cases obviously where we add too many.
```
Grid limit (100) reached, not adding more entities (106) for Switches
```
Docs: https://developer.android.com/training/cars/apps#constraint-manager
Documentation: home-assistant/companion.home-assistant#962

Only add up to the allowed limit of list items to android auto

---

app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
common/src/main/res/values/strings.xml

2 new sensors
- Report connected cars EV connector types
- Report connected cars fuel types
Documentation: home-assistant/companion.home-assistant#963

Add sensors to report car energy profile

---

app/build.gradle.kts
app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearFavoritesView.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/vehicle/ManageAndroidAutoSettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/vehicle/ManageAndroidAutoViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/vehicle/views/AndroidAutoFavoritesView.kt
app/src/main/java/io/homeassistant/companion/android/util/compose/FavoriteEntityRow.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/HaCarAppService.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
app/src/main/res/drawable/ic_car.xml
app/src/main/res/xml/preferences.xml
common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepositoryImpl.kt
common/src/main/res/values/strings.xml

Fixes: #3219 by adding a favorites category at the top to include a user selected list of entities on a per server basis.
Did some minor refactoring to make the favorite entity row shareable to Wear. Also makes use of the new simple entity picker!
Documentation: home-assistant/companion.home-assistant#961
I opted to place the category at the top of the list for now as this PR is already pretty big. I think in the future a tabbed template might be a good fit for a redesign but a bit out of scope for this PR.

Add favorites selection for Android Auto

---

app/src/main/java/io/homeassistant/companion/android/assist/AssistActivity.kt
app/src/main/java/io/homeassistant/companion/android/assist/AssistViewModel.kt
wear/src/main/AndroidManifest.xml
wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationActivity.kt
wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt

Fixes #3690 - if the Assist activity receives a new intent voice input should resume. This can happen when:
- the Assistant gesture/button is invoked while the activity is already open
- the Assist activity was paused, and is now resumed using the Assistant gesture/button, a shortcut, tile or complication (user pressed home after using Assist)
n/a
n/a

Resume Assist voice input on new intent (as assistant app/brought to front)

---

common/src/main/java/io/homeassistant/companion/android/common/data/wifi/WifiHelperImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt

Fix #3704 / SSID and BSSID functionality on Android 12+ by using deprecated APIs when we need this information instantly and/or without network changes, as explained in my comment on the issue.
n/a
n/a

Use WifiManager deprecations again for instant 'location' info

---

common/src/main/res/values/strings.xml

Fixes the following crash I noticed while trying to view more details for a light on my watch. Looks like a merge conflict was resolved incorrectly in #3631 causing it to crash (the original PR #3477 had already changed it to `%1$s`).
```
2023-07-24 22:26:17.035  9557-9557  AndroidRuntime          io....stant.companion.android.debug  E  FATAL EXCEPTION: main
Process: io.homeassistant.companion.android.debug, PID: 9557
java.util.IllegalFormatConversionException: d != java.lang.String
at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4408)
at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2890)
at java.util.Formatter$FormatSpecifier.print(Formatter.java:2844)
at java.util.Formatter.format(Formatter.java:2535)
at …
```

Fix Wear more details crash with Kelvin light temperature

---

common/schemas/io.homeassistant.companion.android.database.AppDatabase/42.json
common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
common/src/main/java/io/homeassistant/companion/android/database/wear/EntityStateComplications.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/complications/ComplicationConfigViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/complications/EntityStateDataSourceService.kt
wear/src/main/java/io/homeassistant/companion/android/complications/views/ComplicationConfigMainView.kt

Show the measurement unit of entities in Wear OS watch face complications to make the value easier to understand. Fixes #3613.
Bottom left/right complications are from the current Google Play store stable HA version. Top left/right is from a version built from this PR.
Documentation: home-assistant/companion.home-assistant#965

Show measurement unit in Wear OS complication

---

app/src/main/java/io/homeassistant/companion/android/util/vehicle/GridItems.kt
app/src/main/java/io/homeassistant/companion/android/util/vehicle/NativeModeActionStrip.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/BaseVehicleScreen.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/DomainListScreen.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/HaCarAppService.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepositoryImpl.kt

The default home screen now uses `GridTemplate` instead of `ListTemplate` to allow for more domains and buttons to be shown. My Subaru has a giant 11" screen, `ListTemplate` shows a total of 10 items but `GridTemplate` shows 15 before needing to scroll.
When favorites are defined we will now show the entity grid screen with the user defined favorites. We will also add Navigation, All entities and Change servers (if applicable) to the grid view.
If favorites are defined but user has multiple servers they will continue to see all domains listed
Documentation: home-assistant/companion.home-assistant#964

Android auto: Switch to GridTemplate for home screen and default to favorites if defined

---

app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt

Update sensors when the driving interface is open/resumed.
There really is no `onResume` method so need to use a separate launch method with the lifecycle set to resumed. Attempted to use this when the screen is created but that only gets called once and not on resume. Also attempting to move the method to `onGetTemplates` triggers the intent twice so this seemed the best fit.
This also matches existing behavior in the main/wear app
This should help users see updates from car sensors too 🤞 (for whoever they actually work for 😂 )

Update sensors when driving interface is open or resumed

---

common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/servers/ServerManagerImpl.kt

While testing the navigation entities in Android Auto PR I noticed the 'All entities' button showing up while also showing the domains list. It turns out this was because my preference still held some favorites, but they were for servers that had been deleted.
_(icon cut off at the bottom is 'All entities')_
When deleting a server most of the server-specific stuff is already deleted, but app-level preferences that reference a server aren't updated. This PR fixes that and adds a function to clean up any server references there might be in the app-level preferences.
n/a / above screenshot will change but that is because it fixes the described bug
n/a

Fix old server references in app-level preferences

---

wear/src/main/java/io/homeassistant/companion/android/views/ChooseEntityView.kt

It should be possible to choose an unavailable entity for display on a complication or tile, as you can with favorites, and even entities that are available now can become unavailable later.
|Before|After|
|---|---|
|![List of entities, entity named 'Do not disturbed' is greyed out and disabled](https://github.com/home-assistant/android/assets/8148535/153c46e8-9d95-4899-993d-6da87910c6a9)|![List of entities, entity named 'Do not disturbed' is enabled like others around it](https://github.com/home-assistant/android/assets/8148535/82cf5f2f-12c0-42c6-9ff0-72b2b2b1f272)|
n/a

Allow selecting unavailable entities for complications/tiles

---

app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/LastAppSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/DNDSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/NextAlarmManager.kt

Hide some sensors that simply won't work in Automotive. Also hide battery manager if the device has no battery.
As these devices do not support the sensor they also wouldn't support for any registered intent so should be safe to continue hiding.

Hide some sensors from unsupported devices

---

.gitignore
fastlane/Fastfile

We need a clean directory when we release otherwise the builds will fail.  This is ignoring the files that were created when fastlane was run.
https://github.com/home-assistant/android/actions/runs/5728645711/job/15523661247
```
git status
shell: /usr/bin/bash -e ***0***
env:
JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.7-7/x6[4](https://github.com/home-assistant/android/actions/runs/5728645711/job/15523661247#step:16:4)
JAVA_HOME_17_X[6](https://github.com/home-assistant/android/actions/runs/5728645711/job/15523661247#step:16:6)4: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/1[7](https://github.com/home-assistant/android/actions/runs/5728645711/job/15523661247#step:16:7).0.7-7/x64
##[endgroup***
On branch master
Your branch is up to date with 'origin/master'.
Untracked …
```

Ignore ruby files that were generated in CI.

---

.github/actions/create-release-notes/action.yml
.github/workflows/onPush.yml
.github/workflows/pr.yml

The new release model #3597 dropped tags on every release + `beta` in tags for beta releases. Switch to GitHub generated release notes to get them back + consistency with 'normal' releases.
(this PR is #3656 in this repo instead to be able to change permissions which is required for it to work)
n/a
n/a

Update release notes action for new release model

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Fixes command not working, first described in #3752
n/a
n/a

Fix persistent connection notification command

---

app/src/main/java/io/homeassistant/companion/android/vehicle/HaCarAppService.kt

I noticed that my car info based sensors seemed a bit stuck. In fact I think the expectation is that the state should reset once you are no longer in the car. So now we will actively set the variable to `null` so we can set the state appropriately.

Reset carInfo when our session is destroyed since data will be stale

---

app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt

Fixes #3756 by keeping track of when we first load domains so we only show the loader for a brief period of time instead of endlessly when a user has no entities that are considered actionable by the app.
at a minimum users will have 1 person entity so we should expect once domains are loaded that we have all entities

Keep track of adding domains to remove loader when user has no actionable entities

---

app/src/main/res/xml/changelog_master.xml

Change log week of 8/4

---

app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
common/src/main/res/values/strings.xml

Fixes #3762 
When a sensor has a unit of measurement HA will expect certain states if non-numerical otherwise the sensor will not be added.
By default when we do not have `carInfo` the state will be `unavailable`. After the app is open user will either see the real state or `unknown` if the status is not `success`.  All sensors will show the `status` attribute which will show  the status of the sensor.
As the sensors get triggered by a listener we can safely call `forceUpdate = true` we either get a real state or we are getting a real status of the value to send to the user.
Removed the old string because we actually should not translate the states that we send, missed this in the original review 😬
Documentation: home-assistant/companion.home-assistant#969

Set car sensors state appropriately if sensor registers with unit of measurement

---

app/src/main/java/io/homeassistant/companion/android/util/vehicle/DomainChecks.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
common/src/main/res/values/strings.xml

Fixes: #3710 
We will show Alarm Control Panels as a supported domain because they are important enough IMO.
Only if we detect a code is not required will a user be able to click on it, otherwise it will be non-actionable.
Given the use case we will either `disarm` or `arm_away` the alarm, the other arming options don't feel as if they would be used as much as `armed_away`
Used the same icons from the frontend: https://github.com/home-assistant/frontend/blob/858dd738684b604b7861ccb9e2c449f9280f8723/src/common/entity/alarm_panel_icon.ts#L15-L36
Documentation: home-assistant/companion.home-assistant#968
After going on the first road trip this weekend the question of "did we turn on the alarm" came while in the car and it would've been easy to answer that 😂

Add support for alarm control panels in android auto

---

app/src/main/java/io/homeassistant/companion/android/util/vehicle/GridItems.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/DomainListScreen.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt

While testing another PR came across an issue where if user had multi server and a server was down we would show all entities and the domain list would never load as a result. So handle loading domains like the other screen, add some checks to only show all entities if we can and add an empty message just in case.

Hide all entities when we dont have domains to show, show empty message just in case

---

app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt

When changing servers the Auto interface (should) reload some server related stuff: the device registry and entities. In this PR:
- actually reload the entity registry instead of keeping the registry for the first server
- show a loading indicator while changing servers and loading registry/entities, instead of the screen for no entities while loading
n/a, it is like the first load
n/a

Auto: reload entity registry, show loading when changing servers

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
wear/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Fix crash 1 from #3708 ([link to line for version in issue](https://github.com/home-assistant/android/blob/f4eb29cee32b971d4e1005cb59b02a49976e090c/app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt#L304)). `IllegalArgumentException` suggests the server for the ID doesn't exist, which can only happen if a notification is received while not registered (as it already falls back to the default server if there is no server found for the webhook ID). As a lot of features depend on having a server for notifications discard them.
I guess people are sending notifications after logging out? (Note that the notification data is still saved to the database so not completely lost and available for troubleshooting if required.)
n/a
n/a

Discard notifications when not registered to prevent crash

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/PhoneStateSensorManager.kt

Fixes #3801. The change to a non-deprecated API means the sensor was limited to calls placed linked to a specific subscription, which causes inconsistency between Android versions and also might not be desired (for example, in case of multi SIM usage or non-telephony calls with VOIP apps).
n/a
n/a

Fix phone state sensor only considering 1 subscription's calls

---

app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetDynamicFieldAdapter.kt

Fix #3812 and two other bugs found while working on it:
- Fix RecyclerView not setting fields to empty when no value is present, potentially showing input from other recycled fields if the field doesn't have any value.
- Fix adding a new custom field destroying any input currently held in the views by using a specific insertion method instead of all changed, which will reset the values.
n/a
n/a

Fix restoring custom fields in service button widget

---

gradle/libs.versions.toml
wear/build.gradle.kts
wear/src/main/java/io/homeassistant/companion/android/tiles/ConversationTile.kt
wear/src/main/java/io/homeassistant/companion/android/tiles/LoggedOutTile.kt
wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt
wear/src/main/java/io/homeassistant/companion/android/tiles/TemplateTile.kt
wear/src/main/res/layout/view_loading.xml

After bumping Kotlin/Compose dependencies in another big PR, this one bumps the remaining dependencies. More renaming for changed packages and a bug fix for loading during Wear onboarding included.
androidx.wear:wear 1.3 updates the appearance of confirmation overlays for Wear to something more modern:
n/a

More dependency bumps

---

app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
app/src/main/java/io/homeassistant/companion/android/thread/ThreadManager.kt
app/src/minimal/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/ThreadDatasetResponse.kt

Updates to the Thread credentials sync:
- Home Assistant core 2023.9 will expose the border agent ID for networks meaning we can finally move away from the placeholder ID if provided, otherwise continue using the placeholder ID.
- Improve multiserver handling. Because there is no UI provided by Play Services to select a Thread network to use, to prevent confusion the app needs to make sure only one HA credential is added. This means deleting orphaned/old credentials and credentials from other servers on sync, before adding the server preferred credential.
n/a
n/a

Thread updates: add border agent ID, multiserver improvements

---

app/src/main/java/io/homeassistant/companion/android/launch/my/MyActivity.kt

Prevent unexpected behavior when using `MyActivity` outside the happy flow.
n/a
n/a

Improve handling my link when not logged in

---

app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/controls/CameraControl.kt
app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/LastAppSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/AndroidOsSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/AudioSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/BluetoothSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/DNDSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/LastRebootSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/NextAlarmManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/PhoneStateSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/util/States.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt

Breaking change: `Unavailable` is now `unavailable` and `Unknown` is now `unknown` for all sensors that report those states. Phone SIM, Next Alarm, Media Session, Geocoded location
- Noticed in a few places our casing was off causing issues in the frontend not showing unavailable entities properly
- Use a consistent variable in all places where we send or evaluate the state to avoid mistakes. In some places this is kept for function consistency purposes like when comparing multiple states.

Use unavailable and unknown states consistently when dealing with sensors and entities

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt

fixes #3824 by partially reverting #3698 and using the deprecated method as we don't know the type of value we are pulling

Fix last update sensor intent not retrieving value

---

app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt

Core border agent IDs use a hex-encoded string (length 32), whereas the app assumed 'normal' strings (length 16). Check to make sure we use the correct conversion.
Fixes:
```
08-28 22:33:07.782 19429 19429 E ThreadManagerImpl: Thread update device failed
08-28 22:33:07.782 19429 19429 E ThreadManagerImpl: java.lang.IllegalArgumentException: Invalid length of the ID (length = 32, expectedLength = 16)
08-28 22:33:07.782 19429 19429 E ThreadManagerImpl: 	at com.google.android.gms.common.internal.Preconditions.checkArgument(com.google.android.gms:play-services-basement@@18.1.0:3)
08-28 22:33:07.782 19429 19429 E ThreadManagerImpl: 	at com.google.android.gms.threadnetwork.ThreadBorderAgent$Builder.<init>(com.google.android.gms:play-services-threadnetwork@@16.0.0:1)
08-28 22:33:07.782 19429 …
```

Fix Thread border agent IDs encoded as hex

---

app/src/main/java/io/homeassistant/companion/android/util/vehicle/GridItems.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/MapVehicleScreen.kt
wear/src/main/java/io/homeassistant/companion/android/complications/EntityStateDataSourceService.kt
wear/src/main/java/io/homeassistant/companion/android/complications/views/ComplicationConfigMainView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetShortcutsTileView.kt
wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt
wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt
wear/src/main/java/io/homeassistant/companion/android/views/ChooseEntityView.kt

After #3816 there was an update to `entity.getIcon()` that made it non-nullable so cleaning up the left over code as a result of that change

Clean up some left over code after update to getIcon

---

app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/views/ManageShortcutsView.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebView.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
common/src/main/java/io/homeassistant/companion/android/util/UrlUtil.kt

I noticed that when editing a shortcut, it was relatively easy to enter incorrect data. This PR updates the keyboard + handling of shortcut to hopefully prevent input errors.
No app UI changes but the on screen keyboard should now be optimized for URI entry.
For example Gboard shows a `/` key for me instead of `,`:
n/a

Shortcut path input improvements

---

app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt

Core border agent IDs use a hex-encoded string (length 32), whereas the app assumed 'normal' strings (length 16). Check to make sure we use the correct conversion when adding new new dataset as well.
```
09-01 08:33:24.959 26648 26648 E ThreadManagerImpl: Thread update device failed
09-01 08:33:24.959 26648 26648 E ThreadManagerImpl: java.lang.IllegalArgumentException: Invalid length of the ID (length = 32, expectedLength = 16)
09-01 08:33:24.959 26648 26648 E ThreadManagerImpl: 	at com.google.android.gms.common.internal.Preconditions.checkArgument(com.google.android.gms:play-services-basement@@18.1.0:3)
09-01 08:33:24.959 26648 26648 E ThreadManagerImpl: 	at com.google.android.gms.threadnetwork.ThreadBorderAgent$Builder.<init>(com.google.android.gms:play-services-threadnetwork@@16.0.0:1) …
```

Fix Thread border agent IDs encoded as hex second instance

---

app/src/main/res/xml/changelog_master.xml

Couple breaking changes this week

Change log week of 9/1

---

app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt

A few changes to improve troubleshooting sync with border agent IDs.
- Always try to delete border agent with ID `0000000000000001` before syncing if all servers are updated to 2023.9 or later
- Adding a log statement for app preferred dataset with name, PAN ID and extended PAN ID to help with troubleshooting
- More detailed log statement for app dataset update with details to match UI
- Fixing a bug that might be deleting more datasets on sync than intended
n/a
n/a

Thread sync BA ID troubleshooting updates

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/controls/HaControlsPanelActivity.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/controls/ManageControlsSettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/controls/ManageControlsViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/controls/views/ManageControlsView.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepositoryImpl.kt
common/src/main/res/values/strings.xml

Implements #3566
|Device controls panel|Settings*, light mode|Settings*, dark mode|
|![Device controls panel showing the Home Assistant app with a dashboard, instead of the previous built-in style](https://github.com/home-assistant/android/assets/8148535/e84010d4-528f-46fd-9af9-1ec6aaca0d87)|![Home Assistant app 'Manage device controls' screen, with two radio buttons: Built-in and Dashboard, allowing the user to choose between them, light mode](https://github.com/home-assistant/android/assets/8148535/aec2a562-04c2-49db-a5de-9565f21f595e)|![Home Assistant app 'Manage device controls' screen, with two radio buttons: Built-in and Dashboard, allowing the user to choose between them, dark mode](https://github.com/home-assistant/android/assets/8148535/c52a0c0c-8cd1-4477-bdc7- …

Add Android 14 device controls panel

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

Prevent the following exception from occuring, which can happen when the app gets no zones like in case of no connectivity or a broken webhook. The exception was already caught but even better to handle it so the behavior is expected :)
```
09-11 16:41:21.779 24666 28243 E LocBroadcastReceiver: Issue requesting zone updates.
09-11 16:41:21.779 24666 28243 E LocBroadcastReceiver: java.lang.IllegalArgumentException: No geofence has been added to this request.
09-11 16:41:21.779 24666 28243 E LocBroadcastReceiver: 	at com.google.android.gms.common.internal.Preconditions.checkArgument(com.google.android.gms:play-services-basement@@18.1.0:2)
09-11 16:41:21.779 24666 28243 E LocBroadcastReceiver: 	at com.google.android.gms.location.GeofencingRequest$Builder.build(com.google.android.gms:play-serv …
```

Prevent GeofencingRequest exception on no zones

---

app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetDynamicFieldAdapter.kt

Fix #3715 by relaxing string conversion to boolean as this breaks other use cases. The app isn't a full YAML parser, and doesn't need to be as the user can enter true/false in the same text field.
This will _not_ be a breaking change as existing widgets have already had their `on`/`yes`/`y`/`off`/`no`/`n` strings* converted to `true`/`false`, which will continue to work.
\*Depending on the YAML version these weren't a valid boolean anyway so confusion everywhere.
n/a
I couldn't find documentation about Home Assistant's YAML version or parsing anywhere so I think it's OK not to mention this anywhere.

Don't force on/yes/y/off/no/n to booleans for service button

---

app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationFragment.kt

Noticed that during onboarding if a user enters a URL with say the lovelace path like a dashboard from a bookmark then the frontend will not present the correct login screen. This in turn means the app does not save any data upon exit and the user needs to onboard again. Even the Companion App menu item is missing.
example: `https://example.com/lovelace/home`
With this change we now force the URL to be just the base URL, there may be a better way to construct the actual base URL but this is what I found as of now :)
Fixes: #2220
Ref: https://community.home-assistant.io/t/new-android-device-does-not-keep-connection-info-between-uses-with-the-companion-app/382766/25?u=dshokouhi
CC: @bramkragten - I am not sure if its correct that the …

Only use the base URL during onboarding if the URL is Nabu Casa

---

app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt

Missed this one before: the extended PAN ID logged during Thread sync is a `byte[]`, which needs converting to a string to be readable in a log statement as you'll get object hashes otherwise:
```
09-15 13:17:13.623  4934  4934 D ThreadManagerImpl: Thread device prefers app added dataset: home-assistant (PAN 16530, EXTPAN [B@d4f921c)
```
n/a
n/a

Thread debug log: make extended PAN ID more readable

---

app/src/full/java/io/homeassistant/companion/android/notifications/FirebaseCloudMessagingService.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
wear/src/main/java/io/homeassistant/companion/android/notifications/FirebaseCloudMessagingService.kt

After helping a few users recently with broken webhooks causing issues, as the app appears to be working but anything depending on the webhook doesn't, I decided to implement an automatic fix for this. It's easy to recognise in the log files so it also should be easy to handle with code:
- HTTP 200 with empty body: direct connection broken webhook
- HTTP 404: broken cloudhook
- HTTP 410: no config entry (and as a result, also a broken webhook)
By doing a new registration we get a new webhook. Removes the need for the user to log out and back in again.
[The iOS app does something very similar](https://github.com/home-assistant/iOS/blob/e065d9bfe05bf1a179a729c3f63ec7745f5b3446/Sources/Shared/API/HAAPI.swift#L184-L197).
n/a
n/a

Automatically fix broken registrations/webhooks

---

gradle/libs.versions.toml
wear/build.gradle.kts
wear/src/main/java/io/homeassistant/companion/android/views/ThemeLazyColumn.kt

This pull request adds smooth scrolling for rotary input. That's especially important on Galaxy Watch Classic models, since it has "low-res" input.
Unfortunately, unlike views, Compose for Wear OS still doesn't have smooth scrolling for lists by default, but there's a [horologist](https://github.com/google/horologist) library by Google, which has an implementation of it. That's what I used.
https://github.com/home-assistant/android/assets/18244287/97b950a1-d886-4e2d-9b32-49e86e1dee3f

Add smooth scrolling for rotary input

---

common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt

Lock entity should be active when locked, inactive otherwise
*irrelevant*
*irrelevant*
A recent PR (#3816) made changes to how different entities and their states are represented. This change caused the locks to be represented by active (on) tiles when *unlocked*, and inactive (off) tiles when locked. This new representation is counter-intuitive, and contradicts the lock representation in tiles provided by other home automation software (e.g. Google Home).
This PR reverts this change at its core (the logic of `isActive` for lock entities), while keeping the rest of the changes in #3816 intact.

Fix isActive for locks

---

gradle/libs.versions.toml
wear/build.gradle.kts
wear/src/main/java/io/homeassistant/companion/android/home/views/RefreshIntervalPickerView.kt
wear/src/main/java/io/homeassistant/companion/android/views/ThemeLazyColumn.kt

The recent switch to Horologist modifiers for rotary input in #3876 broke rotary input after the first screen, presumably because of manual focus requesting, and the refresh interval picker in general. This PR fixes it by removing manual focus requesting (like in the Horologist sample) and also switches the refresh picker to a Horologist modifier.
Tested it on a Galaxy Watch 4 where now screens after the first one seem to work again.
Closes #3879, the dependency bump was required to get the rotary scroll adapter function for pickers.
n/a
n/a

Fix rotary input after first screen & for picker

---

app/src/main/res/xml/changelog_master.xml

Hope I captured everything past 2 weeks :)

Update change log week of 9/22

---

wear/src/main/java/io/homeassistant/companion/android/views/ListHeader.kt

Prevent text from being cut off abruptly in the `ListHeader`s used in the app (on almost every screen) by calculating the number of lines that fit based on text size + overflow with ellipsis + centering text.
|Before|After default size|After very large size (title only)|
|![Wear screen with text in title showing 2.5 lines (text cut off)](https://github.com/home-assistant/android/assets/8148535/8ff1f883-21fa-4d85-8d55-0e3791ee8659)|![Wear screen with text in title showing 2 lines, ending in ellipsis](https://github.com/home-assistant/android/assets/8148535/d03d18ec-5898-4c3e-a7e7-167379b47749)|![Wear screen with large text in title showing 1 line, ending in ellipsis](https://github.com/home-assistant/android/assets/8148535/edda4dea-8ec7-430e-9c41-1c8fe93f353a)|
n/a

ListHeader: fix text cut off

---

wear/src/main/java/io/homeassistant/companion/android/home/views/DetailsPanelView.kt

Updates the more details screen on a watch to prevent content from being cut off. The entity title and toggle were forced onto one line, so with longer entity names and/or larger text sizes it would get cut off.
New design prominently shows the entity icon, which can be tapped to toggle, and the entity title on another line (which can wrap / limit length). Design is very similar to the frontend tile card and default Wear round buttons with icons, so hopefully familiar to users. Colors are not dynamic - on is always yellow, matching the vehicle interface.
|Before|After, off|After, on|After, no toggle*|
|-----|-----|-----|-----|
|![More details screen with text and toggle immediately at the top cut off by the round screen](https://github.com/home-assistant/android/assets/8148535/2c89bdac-caa …

Update Wear more details screen to prevent cut off

---

gradle/libs.versions.toml
wear/build.gradle.kts
wear/src/main/java/io/homeassistant/companion/android/complications/views/ComplicationConfigMainView.kt
wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/DetailsPanelView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/EntityListView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/RefreshIntervalPickerView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SelectCameraTileView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SelectShortcutsTileView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SensorManagerUi.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SensorUi.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SensorsView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetShortcutsTileView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/TemplateTileSettingsView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/TimeText.kt
wear/src/main/java/io/homeassistant/companion/android/onboarding/phoneinstall/PhoneInstallView.kt

Noticed that our preview device was deprecated so switching to the actual preview device we should be using.

Switch to Wear Device specific preview

---

gradle/libs.versions.toml
wear/build.gradle.kts
wear/src/main/AndroidManifest.xml
wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationActivity.kt
wear/src/main/java/io/homeassistant/companion/android/splash/SplashActivity.kt
wear/src/main/res/drawable/splash_background.xml
wear/src/main/res/drawable/splash_background_assist.xml
wear/src/main/res/values/dimens.xml
wear/src/main/res/values/styles.xml

We had another review failure for the splash screen this time. Turns out there is a new library and recommendation to follow. This PR implements: https://developer.android.com/training/wearables/apps/splash-screen
BEFORE
AFTER
ASSIST
Side Note: I dont quite notice a difference 🤷‍♂️

Use recommended splash screen library for Wear OS

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NfcSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/NfcSensorManager.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

Add a new `binary_sensor` which represents whether the device has its NFC sensor enabled or not.
I added the new `NfcSensorManager` class to the `common` module, so it also works on Wear OS! I tested it on Wear OS 3.5.
The sensor reacts to changes immediately by subscribing to `NfcAdapter.ACTION_ADAPTER_STATE_CHANGED`.
Documentation: home-assistant/companion.home-assistant#992

Add NFC state sensor

---

wear/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationActivity.kt
wear/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupActivity.kt
wear/src/main/java/io/homeassistant/companion/android/util/OnboardingPadding.kt
wear/src/main/res/layout/activity_integration.xml
wear/src/main/res/layout/activity_manual_setup.xml

Noticed when largest font size is used and user attempts to manually enter the URL using Advanced option when app is not installed the next button overlaps the text field.
Moved to `ScrollView` to allow the screen to be scrollable.
Increased min height so the tap area is larger per recommendation in android studio
Used the same manual URL string as the phone app as the current string was odd
Add padding if the device is round based on: https://stackoverflow.com/a/49338298
BEFORE
AFTER

Update manual onboarding screens to prevent the button from overlapping elements

---

wear/src/main/java/io/homeassistant/companion/android/home/views/RefreshIntervalPickerView.kt

On some devices with imprecise rotary input, such as the Galaxy Watch 4 I personally use, the picker items were too small resulting in skipping every other item which is impractical (you could only select odd-indexed items using touch). This PR updates the picker design to [the design guidelines](https://developer.android.com/design/ui/wear/guides/components/pickers), which fixes this issue as the items are now larger. Code for style based on Horologist's DatePicker.
|Before|After|
|-----|----|
|![A Picker with smaller text, normal font weight and different color depending on position](https://github.com/home-assistant/android/assets/8148535/0e053e23-3e4c-43e8-b7f3-fc9d788935d6)|![A Picker with larger text, bold and all the same color](https://github.com/home-assistant/android/assets/81485 …

Fix Picker rotary input on some devices and update design

---

common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt

Remove some redundant strings so the page is more friendly

Shorten some settings strings

---

wear/src/main/java/io/homeassistant/companion/android/home/views/DetailsPanelView.kt
wear/src/main/java/io/homeassistant/companion/android/theme/Color.kt
wear/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt

Migrates `ToggleButton` to `IconToggleButton`
Add container color to slider
Add size constraint to slider icons
Add additional previews

Fix detail pane after material 3 migration, add additional previews

---

app/src/main/res/xml/changelog_master.xml

Change log week of 10/6

---

wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
wear/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt
wear/src/main/java/io/homeassistant/companion/android/util/WearToggleChip.kt

Update the entity chips/buttons to use Material 3 styling. Unfortunately our backgrounds which show position prevent changing it to a `ToggleButton`, but we can change the styling to match what the M3 theme does.
|     |     |
|-----|-----|
|button with position + color (dimmable color light)|![image](https://github.com/home-assistant/android/assets/8148535/bcb72a8f-fb7d-4939-8d11-2779bc25b54d)|
|button with color only (on/off color light)|![image](https://github.com/home-assistant/android/assets/8148535/727f8bc3-159d-4912-9430-65547057f455)|
|button with position only (fan with speed)|![image](https://github.com/home-assistant/android/assets/8148535/a0ac6e65-1e3d-4675-89b4-8748849015ce)|
|button off|![image](https://github.com/home-assistant/android/assets/8148535/352ab0ca-cc07-41e5-9fba- …

Update entity button with toggle styling to match M3 components

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Fix #3926 by automatically replacing ` ` in URLs with the encoded character `%20`. Not replacing any other characters as that might break URLs including already encoded URLs. (This feels like a 'safe' change to automatically handle common user errors.)
Without this change, a notification attachment containing a space will fail the URL validation. Because of that failure it returns the base URL and downloads it (= the login page), which then cannot be processed as an image/video.
n/a
n/a

Prevent notification attachments failing due to spaces ( ) in url

---

wear/src/main/java/io/homeassistant/companion/android/tiles/CameraTile.kt

Following reports by @dshokouhi in chats and [on Discord](https://discord.com/channels/330944238910963714/562408603345092636/1162095891210063883) of camera tiles resetting unexpectedly or not being removed from the app, I tested adding/removing camera tiles again.
For camera tiles resetting, this can be caused by `onTileAddEvent` or `onTileRemoveEvent`. This PR updates `onTileAddEvent` to not overwrite tile data if it already exists, hopefully fixing this (remove+add is annoying, the app would have to add soft delete).
For camera tiles sticking around, during testing I noticed that the system was often destroying the service almost immediately after the add/remove events were sent. As a result, code started in the service's coroutine was cancelled before completing, and a camera tile …

Improve camera tile add/remove event handling

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
common/src/main/java/io/homeassistant/companion/android/common/notifications/NotificationFunctions.kt
wear/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Move the `clear_notification` command to common extensions and add support in the Wear OS app. 'Fixes' #3952.
Tested it with a simple notification message + tag, followed by `clear_notification` + tag, and it seems to work correctly - not sure why it wasn't added before.
Existing notifications with the tag will now be cleared instead of receiving a notification with the `clear_notification` message on the watch.
Documentation: home-assistant/companion.home-assistant#1000 (🎉)

Add clear_notification support to Wear OS

---

wear/src/main/java/io/homeassistant/companion/android/home/views/SensorUi.kt

Show sensor states in the UI to help with troubleshooting states in app compared to what HA core has. Adds more preview data to view different combination of states.
I am also considering in the future to move to `SplitToggleButton` so we can have a sensor detail screen to show attributes and sensor settings.

Show sensor state in secondary label in Wear OS sensor UI

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt

Fixes: #3969 by defaulting to the old deprecated method in case `WifiInfo` returns as null. The 4 sensors mentioned use the new method but Wifi SSID and BSSID use the old method which in this case still works.

Use deprecated wifi method in case WifiInfo is null

---

wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt

Follow-up to #3954: updates the shortcut tile's handling of add/remove event + destroying the service, just like the camera tile, to prevent the service scope being cancelled while the app is still storing tile added/removed and ending up with 'ghost tiles'.
(this service already didn't overwrite existing tile data when `onTileAddEvent` was called again)
n/a
n/a

Update shortcut tile add/remove + destroy handling

---

common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/tiles/TileViews.kt

There was another review failure about text sizes on Wear, and after playing with some string lengths I found it was possible to have text cut off on the logged out state for tiles (but only after making strings longer - maybe Google has an extremely small test device?). This PR limits length of logged out state string to the recommendation to prevent text cut off, and shortens strings to help with translations.
(Also a minor related fix for inconsistent shortcuts tile name usage.)
|Before (forced)|After|
|-----|-----|
|![Tile with a 4th line of text barely visible and cut off by button](https://github.com/home-assistant/android/assets/8148535/dd51e241-9373-45cc-b707-88b8ed561231)|![Tile with only 2 lines of text, all visible](https://github.com/home-assistant/android/assets/8148535/0881cb …

Update tiles logged out state to prevent cut off overflow, shortcuts tile label

---

common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/SensorRequest.kt

Fixes #3202, fixes home-assistant/core#102853
Always send the values for `device_class` and `entity_category` when registering sensors to make sure they match the app value. Some sensors were changed in the past based on feedback, but users with existing registrations wouldn't have seen this updated in core as the app didn't send `null` values instead of sending that it should be `null`. To make this possible, registrations and updates need to be split as the app currently depends on using `null` as "don't send".
Example before/after payloads:
```
{"type":"register_sensor","data":{"unique_id":"battery_state","state":"discharging","type":"sensor","icon":"mdi:battery-minus","attributes":{},"name":"Battery state","entity_category":"diagnostic","disabled":false}} …
```

Always send sensor registration device class + entity category to prevent errors due to old registration

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
common/src/main/res/values/strings.xml

[By suggestion](https://github.com/home-assistant/android/issues/3979#issuecomment-1792538021): show the server name instead of a generic "Home Assistant" to prevent confusion when the app cannot connect in the `WebViewActivity`, when using multiserver.
Adding a button to switch servers here would probably also be a nice improvement, but that doesn't fit and this dialog currently is used for a lot of things so let's not try to do everything in one PR. (Switching now requires going to Settings or dismissing the dialog and using swipe gestures.)
Server name: Home
|Light|Dark|
|-----|-----|
|![Dialog for connection issues titled 'Unable to connect to Home', light mode](https://github.com/home-assistant/android/assets/8148535/2a6a65b5-bae8-4372-af9c-071a40ec968c)|![Dialog for connection …

Show server name in "Unable to connect to Home Assistant" dialog

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt
common/src/main/res/values/strings.xml

This adds a new binary_sensor displaying if the WiFi hotspot is enabled.
Documentation: home-assistant/companion.home-assistant#1005
This feature had to use reflection, which usually isn't recommended. But this is the only method to check if a hotspot is enabled.
The sensor will only display if the private function exists, to prevent issues in the future.

Added a sensor to detect if the hotspot is enabled.

---

app/src/full/java/io/homeassistant/companion/android/location/HighAccuracyLocationService.kt
app/src/full/java/io/homeassistant/companion/android/onboarding/WearOnboardingListener.kt
app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
app/src/full/java/io/homeassistant/companion/android/sensors/AndroidAutoSensorManager.kt
app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearActivity.kt
app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt

This is an attempt to fix #3060 based on the [recent comment](https://github.com/home-assistant/android/issues/3060#issuecomment-1813814320) and linked [internal issue](https://issuetracker.google.com/issues/257765160)
The idea is that any play services call that involves settings up the client like `getNodeClient` or `getFusedLocationProviderClient` can all fail and crash the app if there was a connection error. So now I have done a wide range search to look for all potential errors. We did not have try/catch blocks everywhere but we did in a few places.

Catch potential play services errors

---

app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt

Fix wrong attribute name for the target temperature step.
Correct one is target_temp_step (which is returned by the API) instead of target_temperature_step.
Currently it is not possible to adjust the temperature of a thermostat in the Android device controls to a step size smaller than 1.

Fix target temperature step attribute name error

---

app/src/main/java/io/homeassistant/companion/android/controls/HaControlsPanelActivity.kt

When using the device controls panel instead of individual/native controls on Android 14, also check the system setting for using device controls while the device is locked and if not allowed, block the panel (as the frontend doesn't have a read only mode).
I tried requesting unlocking the device when the panel is opened by using [`KeyguardManager.requestDismissKeyguard`](https://developer.android.com/reference/kotlin/android/app/KeyguardManager?hl=en#requestdismisskeyguard) to make the experience smoother, but that doesn't play nice with the activity transition used by the app and will result in the user seeing their home screen/last app instead of Home Assistant after unlocking.
|Light mode|Dark mode|
|-----|-----|
|![White screen with a lock icon and the text 'Requires unlocked …

Check controls while locked setting when using panel

---

app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt
app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearMainView.kt
app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardApp.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingViewModel.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationFragment.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationView.kt
app/src/main/java/io/homeassistant/companion/android/util/TLSWebViewClient.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
common/src/main/java/io/homeassistant/companion/android/common/data/DataModule.kt
common/src/main/java/io/homeassistant/companion/android/common/data/TLSHelper.kt
common/src/main/java/io/homeassistant/companion/android/common/data/keychain/KeyChainRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/keychain/KeyChainRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/keychain/KeyStoreImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/keychain/KeyStoreRepositoryImpl.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt

Wear OS does not currently allow the user to install certificates to the system-wide KeyChain for TLS CCA support. This commit adds support for using certificates from the app-specific Android KeyStore with UI for setting up a certificate during the Wear OS onboarding process. The manual step in the onboarding process is required since we cannot transmit certificates of the Android KeyChain because they are not extractable.
In particular, this commit adds the following changes:
* KeyStoreImpl as an additional KeyChainRepository interface implementation for loading and storing keys to the application's KeyStore. TLSHelper uses KeyStoreImpl as a fallback key manager.
* UI for selecting a certificate file with GET_CONTENT intent during Wear OS onboarding in OnboardingActivity if it is …

Add Wear OS TLS client certificate authentication (TLS CCA) support

---

app/build.gradle.kts
automotive/build.gradle.kts
common/build.gradle.kts
gradle.properties
wear/build.gradle.kts

Addresses the following warning during build:
> The option setting 'android.defaults.buildfeatures.buildconfig=true' is deprecated.
> The current default is 'false'.
> It will be removed in version 9.0 of the Android Gradle plugin.
> You can resolve this warning in Android Studio via Refactor > Migrate BuildConfig to Gradle Build Files
Each module uses the `BuildConfig` class so it's added everywhere.
n/a
n/a

Migrate BuildConfig to Gradle Build Files

---

app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetAuthenticationActivity.kt

Fixes #3893: prevent the button widget authentication dialog automatically being dismissed when triggered on Android 14 QPR1+, because the window was not in the foreground. It looks like the framework check for this was bugged before QPR1, and the Home Assistant app was showing the authentication dialog before the window (which is transparent) was in the foreground.
More details about how I found this in my last comment on the issue.
No visual changes except maybe you have to wait 50-100ms longer for the window to get to the foreground compared to older versions?
https://github.com/home-assistant/android/assets/8148535/d526e696-9a98-4a0a-9cfe-47f6bce48ae7
n/a

Fix button widget authentication dismissed due to non-foreground window

---

app/src/full/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt
app/src/main/java/io/homeassistant/companion/android/matter/MatterManager.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
app/src/minimal/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt

By request from the Matter/Thread developers: prevent the system's Matter device discovery bottom sheet from showing up while the Home Assistant app is opened.
This change will prevent the following from happening:
https://github.com/home-assistant/android/assets/8148535/0a4c732c-71b1-4e36-8cc6-b0052ce41ce4
n/a

Suppress system Matter device discovery bottom sheet

---

app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningService.kt
app/src/full/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt
app/src/main/java/io/homeassistant/companion/android/matter/MatterManager.kt
app/src/minimal/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

Requires: home-assistant/core#106237
When using `matter/commission_on_network` (commissioning started from the frontend), also send the IP address returned by the system to the server in order to fix home-assistant-libs/python-matter-server#463. Read the issue + linked PR for more details.
The websocket message will now look like this:
```
{
"id": 3,
"type": "matter/commission_on_network",
"pin": 1234,
"ip_addr": "fd82:c9e9:5cb7:1:2c5c:ed99:ecf:4460"
}
```
n/a
n/a

Send IP address of Matter device for on network commissioning

---

wear/src/main/java/io/homeassistant/companion/android/home/views/RefreshIntervalPickerView.kt

We got a review failure from Google with a screenshot this time!
Adding padding to this screen to prevent the text from getting cut off like that. I tried to move to `ThemeLazyColumn` however the rotary input does not play nice so the best option seemed to be adding some sane padding
After fix using largest font size in Pixel Watch (one side effect of this change is that not many elements are visible in the picker however we do need to push things down a bit so this might be expected in larger screen sizes):
Still behaves fine in default text size:

Add padding to refresh interval to avoid text getting cut off

---

app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningViewModel.kt
app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
app/src/main/java/io/homeassistant/companion/android/matter/MatterFrontendCommissioningStatus.kt
app/src/main/java/io/homeassistant/companion/android/settings/developer/DeveloperSettingsPresenterImpl.kt
app/src/main/java/io/homeassistant/companion/android/thread/ThreadManager.kt
app/src/main/java/io/homeassistant/companion/android/webview/MatterThreadStep.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
app/src/minimal/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
common/src/main/res/values/strings.xml

Support the frontend `thread/import_credentials` action, shown as a button on the Thread config page, which will export the preferred Thread credential from the device (if the device doesn't prefer a HA credential) to the server.
This partially re-uses the existing Thread credential sync logic from Matter commissioning.
Video showing the flow, first denying the permission/failure and then success:
https://github.com/home-assistant/android/assets/8148535/183adc05-837f-4db1-8512-5815032f4af9
n/a

Support for Thread "import credentials" from frontend

---

wear/src/main/java/io/homeassistant/companion/android/home/views/RefreshIntervalPickerView.kt

To (hopefully) finally address review failures about text being cut off on round screens replace it with an icon. Same icon as used in the previous screen so should be pretty clear.
As a reminder, the preference chip:
n/a

Replace 'Refresh interval' title with icon

---

app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningViewModel.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

After discussion with @agners, remove Thread credential syncing from the start of the Matter commissioning flow. There are 2 major reasons for this:
* it significantly slows down the flow while only being useful some of the time (initially, and on Thread network/BR changes)
* the results have limited usefulness because the API limits how much Home Assistant can influence the device data
The alternative for the user is to use the manual 'import credentials' button in the frontend (matching iOS), or access the sync option in the app settings > troubleshooting menu.
This should result in a more reliable user experience when using Matter and prevents unstable/unfinished Thread work on the core and app side 'polluting a real device'. Adding a comment in the code in case/when we revisit this in …

Remove Thread credential sync from start of Matter commissioning flow

---

app/src/main/java/io/homeassistant/companion/android/settings/widgets/views/ManageWidgetsView.kt
app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt
common/src/main/res/values/strings.xml

Fixes #4139:
- Allow selecting image entities in the camera widget
- Rename camera widget to picture widget to better reflect camera + image entity support
|    |Light|Dark|
|----|----|----|
|Widget config showing `image` entity|![image](https://github.com/home-assistant/android/assets/8148535/15a960d1-94ff-45a8-acd6-8346450cf824)|![image](https://github.com/home-assistant/android/assets/8148535/f385cdd7-9af5-40a2-9c8a-9af702d0b4fa)|
|App settings list now shows Picture widget|![image](https://github.com/home-assistant/android/assets/8148535/0b50723a-4165-4421-aa22-8da89c9bff9d)|![image](https://github.com/home-assistant/android/assets/8148535/b4eb04e3-0005-46d1-8b0c-c585a5fb9bd1)|
(widget appearance itself did not change)
Documentation: home-assistant/companion.home-assistant#1023

Support image entity in camera widget (now renamed picture widget)

---

app/src/main/res/xml/changelog_master.xml

Update change log week of 1/26

---

wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationActivity.kt
wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt

Wear Assist changes to address Google's latest ~~nitpicking~~ review failure:
- Update Assist on Wear to automatically open the login screen when logged out, instead of asking the user to close and login, to prevent text being cut off issues
- Add another item at the top of Assist on Wear to allow the pipeline selector to be scrolled into the center of the screen (the first item cannot be scrolled into the center of the screen)
n/a, now more centered possible but contents are the same
n/a

Wear Assist: show login when logged out, scroll first item into view

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/AudioSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorUpdateReceiver.kt
wear/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

Audio volume sensors weren't updating instantly, so a new broadcast Intent subscription has been introduced in this PR to improve this.
How I tested these changes:
Enabled all audio-related sensors, and tried modifying the volume on the device several times, and the new values were reflected nearly instantly on the server. I did this testing for both the Android and Wear OS apps.
Documentation: home-assistant/companion.home-assistant#1025
The broadcast is `android.media.VOLUME_CHANGED_ACTION`, and it is undocumented. No official Android documentation mentions it.

Make volume sensors update instantly by subscribing to a broadcast

---

common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt

Fixes the following lint warning x23: 
`/home-assistant-android/common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt:838:34 The corresponding parameter in the supertype 'Migration' is named 'db'. This may cause problems when calling this function with named arguments.`
n/a
n/a

Fix lint warning for database/db function parameter name

---

common/src/main/res/values/strings.xml

Fixed some common grammatical errors:
a) Compound verbs misspelled as one word: When used as a noun, they are one word (e.g. "Enter your login when prompted"), bus when used as a verb, they are two words (e.g. "Log in to your account").
b) Comma splice: A comma can not be used to join two complete sentences into one sentence (without a conjunction) -- they need to written as two separate sentences.

Fixed spelling of compound verbs "set up", "log in", and "log out". Fixed "comma splice". Fixed double space.

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt
common/src/main/res/values/strings.xml

This PR is intended to address #4198: Adds a new network sensor to detect ipv6 addresses and list them as attributes
Documentation: home-assistant/companion.home-assistant#1031
I'm still trying to figure out how best to test this. As such I'm leaving this as a draft for now

add new sensor for ip6 addresses

---

app/src/main/java/io/homeassistant/companion/android/controls/CameraControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultButtonControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSliderControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaFailedControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LockControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/VacuumControl.kt

The ClimateControl right now doesn't cycle through modes (toggle in case it's a normal heating) when clicking on it within "Device controls" on Android which means more hassle when trying to change modes, as I would have to go into the app and in general it requires more clicks.
[Screencast from 2024-01-17 20-23-47.webm](https://github.com/home-assistant/android/assets/16007727/bc6be879-4084-4d85-8475-78842b3c55b5)
None so far. If that is needed, please come back to me.
Didn't know whether I should create an issue for that just to have the implementation directly around and decided against that. In case I missed some workflow feel free to reach out to me. Would be happy to see this change merged

Add ability for ClimateControl Card to cycle through entity states

---

app/src/main/java/io/homeassistant/companion/android/assist/AssistActivity.kt
app/src/main/java/io/homeassistant/companion/android/assist/AssistViewModel.kt

Fixes #4211 (in later comment), fixes #4231
Update the flags for showing the Assist dialog when locked to:
- prevent unintentional resuming in a different locked state (= was unlocked and Assist open, lock, keyguard should be on top)
- clear contents when resumed in a different locked state intentionally (assistant intent action)
n/a
n/a

Update Assist dialog state when transitioning locked<>unlocked

---

app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt

Catch exceptions thrown while loading all available controls (= adding a new control) on a server level, instead on a higher level/all servers, to make sure that an issue with one server doesn't prevent data from other servers from showing.
This should fix #4246 - I've not been able to reproduce the issue but based on the description and that it was 'fixed' by removing the offline server, this suggests one server throwing an unexpected exception before the service returned controls, resulting in the error shown by the system in the screenshot.
n/a
n/a

Controls: prevent individual server error from blocking all others

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

"timeout" is relative, but "when" is absolute by default.
It is now possible to synchronize timers in seconds without time difference:
```yaml
timeout: 120
chronometer: "true"
when: 120
when_relative: "true"
```

Notification: "when_relative" for "chronometer"

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

This adds support for saving a gif that is sent as a notification image locally so that it can be loaded using a content uri which enables the notification to show the gif as animated including all frames.
Should be noted that this only is only supported on Android 14+, for previous versions the behavior and handling will remain the same where only the first frame of the gif is shown.
https://github.com/home-assistant/android/assets/14866235/7e3c579a-4a03-440d-b961-9bb05184687c
Documentation: https://github.com/home-assistant/companion.home-assistant/pull/1047
closes https://github.com/home-assistant/android/issues/1270

Support showing all frames of animated gif image in Android 14+

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

This fixes the case where a user is on Android 14+ and sends a normal image that is not a gif.

Fix normal images not working after gif changes

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

When determining whether the WebView should be reloaded with the current server URL, also check that the protocol (http/https) and port (8123, 443, ...) match and if not reload.
Should fix #4294 as the only difference between the user's URLs is the port and it works correctly when closing/reopening the app which forces a reload with the current URL to use for the webview. This has nothing to do with Cloudflare or the needlessly complicated network setup.
n/a
n/a

Check protocol/port when determining reload for WebView

---

app/build.gradle.kts
app/src/main/java/io/homeassistant/companion/android/assist/AssistActivity.kt
automotive/build.gradle.kts
gradle/libs.versions.toml

This PR removes the [deprecated Accompanist System UI controller](https://google.github.io/accompanist/systemuicontroller/) used to go edge to edge and set system bar appearance, and replaces it with functionality in the core AndroidX libraries to simplify code :)
Tested and I didn't notice any difference - edge to edge works, and the system/Accompanist were already applying a scrim with 3 button nav and on older API versions.
n/a

Remove deprecated Accompanist System UI controller

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt
common/src/main/res/values/strings.xml

Fix #4286 by adding a setting to the battery power sensor to set the battery voltage divisor. Like the current, I guess we can't trust anything.
This fix is in line with the existing setting for current, but maybe we can detect this automatically in the future based on expected values? (eg voltage should always be in range x...y, but the tricky part is what to do when it is close to 0)
|Light|Dark|
|----|----|
|![Sensor settings in the Home Assistant app with an option 'Battery voltage divisor', value 1000, light mode](https://github.com/home-assistant/android/assets/8148535/4ec76955-09c0-48aa-983c-29d6b7126b92)|![Sensor settings in the Home Assistant app with an option 'Battery voltage divisor', value 1000, dark mode](https://github.com/home-assistant/android/assets/8148535/97d97e19-668a- …

Add battery voltage divisor setting

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

'Fix' #3343 by allowing `command_webview` to create multiple, new tasks. This allows launching the webview to work reliably irrespective of how the app was originally started.
While this behavior may not be perfect in my opinion (you end up with hidden tasks which can be unpredictable), all app features that allow you to navigate to a specific page the webview such as shortcuts, tapping on notifications, device controls long press, etc. use this to reliably load the frontend with a specific page. Different behavior for this specific feature (which as a result didn't always work) doesn't make a lot of sense.
n/a
Docs don't mention anything about tasks/recents so let's not complicate things
Based on [these specific reproduction steps](https://github.com/home-assistant/android/issues/3343#iss …

Allow multiple tasks for `command_webview`

---

app/src/main/res/xml/changelog_master.xml

Update change log week of 3/29

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/AudioSensorManager.kt
wear/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt

Noticed we got new Audio Manager modes for our sensor so adding in the new possible states
https://developer.android.com/reference/android/media/AudioManager#MODE_COMMUNICATION_REDIRECT
https://developer.android.com/reference/android/media/AudioManager#MODE_CALL_REDIRECT
I also noticed that our mic muted SDK condition was incorrect so split it up to be correct.
Documentation: home-assistant/companion.home-assistant#1059

Add some missing states for audio sensor and correct mic muted intent condition

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSliderControl.kt
app/src/main/java/io/homeassistant/companion/android/settings/language/LanguagesManager.kt
app/src/main/java/io/homeassistant/companion/android/themes/ThemesManager.kt
app/src/main/java/io/homeassistant/companion/android/util/ChangeLog.kt

I found a few occasions where the runBlocking coroutine builder is called from within other coroutines. This can affect performance since it blocks the thread that is shared among coroutines, and can in some cases lead to the infamous nested runBlocking deadlock. Often an easy fix is to turn the containing function into a suspend function.
Let me know if I missed something! 
Cheers

Fix runBlocking in coroutines

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorWorkerBase.kt
common/src/main/java/io/homeassistant/companion/android/database/sensor/SensorDao.kt

Fix #4028's most likely cause (see steps in issue) by preventing a race on logout from the frontend between updating the sensors and deleting the server data, causing stale sensor entries;
and fix it for existing users/create a workaround for any missed cases by cleaning up any orphaned sensor entries there might be during periodic sensor updates.
n/a; there are no longer toggles for non-existent servers
n/a

Prevent race creating + clean up sensor entries for old/deleted servers

---

app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/AppSensorManagerBase.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/AudioSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/BluetoothSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/DNDSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/PhoneStateSensorManager.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt

Fixes #4393 
the device class is only set for when the new device class was added.
i decided to keep the options for all users as I can personally see value in it for user on older versions.
i reviewed all our sensors and these ones have a defined list in our code.

Use device class enum where possible and supply possible states for those sensors

---

app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/mediaplayer/MediaPlayerControlsWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/AudioSensorManager.kt

Resolve a few warnings visible when compiling which are easily fixed. 
- 'getter for isSpeakerphoneOn: Boolean' is deprecated. Deprecated in Java
- Unnecessary safe call on a non-null receiver of type Intent
- The corresponding parameter in the supertype 'BaseWidgetConfigureActivity' is named 'savedInstanceState'. This may cause problems when calling this function with named arguments.
n/a
n/a

Quick fix minor warnings from Android Studio

---

.github/actions/create-release-notes/action.yml

Addresses the warning about an old github-script action as we were using v6 in release notes but v7 for the weekly workflow, so dependabot didn't tell us about updates as it was up-to-date in one place.
```
Play Publish
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/github-script@v6. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
Github, Firebase, and Sentry Release
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/github-script@v6. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
n/a
n/a

Update github-script action to latest version everywhere

---

app/build.gradle.kts
automotive/build.gradle.kts
build.gradle.kts
common/build.gradle.kts
gradle/libs.versions.toml
wear/build.gradle.kts

When building the app with Kotlin 2.0, we get the following warning: `w: Kapt currently doesn't support language version 2.0+. Falling back to 1.9.`. This appears to be harmless, but considering kapt has been in [maintenance mode](https://kotlinlang.org/docs/kapt.html) for a couple of years and even Google samples are now using ksp for Hilt (where it is stable, even though Dagger itself still considers it 'alpha') this seems like a good time to migrate. After migrating Hilt there is nothing left using kapt so it is removed, and the warning resolved.
Did a build + run trying to hit most places where we inject things which seems to work fine. Not seeing any of the promised build speed improvements :(
n/a
n/a

Use ksp instead of kapt for Hilt

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Problem-Error:
```
'if' must have both main and 'else' branches if used as an expression :467
```

Remove "No unique cases found to override" log (not specific enough)

---

.github/workflows/release.yml
README.md

The Amazon App Store submission in production releases is currently failing with <details><summary>error</summary>
```
[20:19:40***: The amazon_app_submission plugin is working!
[20:19:40***: Fetching app access token
[20:19:40***: Getting current edit
[20:19:41***: Get current apk id
[20:19:41***: Get current apk ETag
[20:19:42***: Replacing the apk with apk from 
+------------------------------------------+
|               Lane Context               |
+------------------+-----------------------+
| DEFAULT_PLATFORM | android               |
| PLATFORM_NAME    | android               |
| LANE_NAME        | android submit_amazon |
+------------------+-----------------------+
[20:19:42***: No such file or directory @ rb_sysopen - 
```
</details>
It appears that the current flow of prepare …

Remove broken Amazon App Store production deploy

---

common/src/main/java/io/homeassistant/companion/android/common/data/keychain/KeyChainRepositoryImpl.kt

Closes #4449 by catching `AssertionError`s for the KeyChain, as we want it to transparently fail (prompt the user again if required, or give an error message in the WebView). Looking at the source for [KeyChain](https://cs.android.com/android/platform/superproject/+/main:frameworks/base/keystore/java/android/security/KeyChain.java) it can also wrap `CertificateException`s in these `AssertionError`s so this may be relevant for more use cases.
Note this does not fix why the KeyChain is unavailable, I believe that is outside the scope of the app.
n/a
n/a

Catch AssertionError when loading certificates/private key (mTLS)

---

app/src/main/java/io/homeassistant/companion/android/webview/WebView.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

Hide the 'Wait' button in WebViewActivity errors if the error is not due to an external bus timeout, but a more general loading error where there's nothing to wait for. The PR also slightly updates what the refresh button does to ensure loading errors on refresh trigger immediately (instead of waiting for a timeout) + uses the URL it says on the button text.
This PR was inspired by the [(previously unheard) confusion here](https://github.com/home-assistant/android/pull/4358#discussion_r1592796669), and looking back perhaps also by [this suggested change](https://github.com/home-assistant/android/pull/4358/files#diff-76bbedb2918a5db79c7070e9bb2e01d9241388745f60b0719c0d1f74123d89bdR1439) in there (although that change wasn't explained, and incomplete).
You get a smaller dialog without a …

Hide 'Wait' if WebViewActivity error is not due to external bus timeout

---

common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt

Updates icons based on entity domain or data in the app with two new ones:
- Added new `tag` and `notify` entity
- Added `open` and `opening` states for the `lock` entity, now matching core icon
Icons match frontend
n/a

Add tag/notify entity icon, add open/opening lock entity icon

---

app/src/full/java/io/homeassistant/companion/android/sensors/AndroidAutoSensorManager.kt

This PR will add the Device Class 'Connectivity' to the Android Auto Sensor and therefore, will then use the correct state translation

Adds Device Class "Connectivity" to the AndroidAuto Sensor

---

app/src/main/java/io/homeassistant/companion/android/nfc/NFCUtil.kt
app/src/main/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt
app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationDetailFragment.kt
app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/mediaplayer/MediaPlayerControlsWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt

While reviewing the recent camera widget PR I noticed the following nice inline function, which I wanted to add/use in other places where we currently have an if/else for the type in extras:
https://github.com/home-assistant/android/blob/e52593524a58dae69a45679a9f0905759bb77d60/app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt#L270-L277
It turns out Google was one step ahead of us and actually added compat classes that do this, so in this PR all relevant usages (including the camera widget inline function) are replaced with the compat functions, to clean up the code a bit.
n/a
n/a

Code quality: use compat functions for Android 13 type extras

---

common/schemas/io.homeassistant.companion.android.database.AppDatabase/47.json
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/GetConfigResponse.kt
common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
common/src/main/java/io/homeassistant/companion/android/database/server/Server.kt

When running Assist pipelines, include the device ID if we have it so users can do location based Assist requests. Requires home-assistant/core#121496 (core 2024.7.2+). Fixes #4158.
n/a
n/a
I basically copied @bgoncal's iOS work here

Add device id to Assist pipeline runs

---

app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
common/src/main/res/values/strings.xml

Currently, the Active Notification Sensor attaches the content of all notifications in the sensor attributes. I think this has two problems:
1. The fact that, this sensor also includes all notification content in addition to the count is not intuitive judging only based on the sensor's name, and can surprise users (including myself).
2. It can increase power and data consumption.
And these could surprise the user, maybe in a negative way.
So here comes a new toggle setting for the Active Notification Count sensor to the rescue: `Include content from all notifications as sensor attributes`
Documentation: https://github.com/home-assistant/companion.home-assistant/pull/1077
Please check [this comment](https://github.com/home-assistant/android/pull/4516/files#r1677876942).

Add setting to control inclusion of all notification contents as attributes in the Active Notification Count sensor

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

The pop-up does not show after returning from SETTINGS or another application.

Checking the connection after switching windows

---

app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingViewModel.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryFragment.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryView.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/HomeAssistantSearcher.kt
common/src/main/res/values/strings.xml

Based on a failed automotive review, two improvements to the discovery screen during onboarding:
- If discovery is taking longer than expected, add a message to check power/network and emphasize the manual option (the text and placement of 'Not finding your server?' is taken from iOS, but a bit less obvious because discovery is strongly preferred and generally works)
- If discovery fails show a persistent error instead of a toast with no changes in the discovery UI
Video showing change 1 (longer than expected means: 10 seconds)
https://github.com/user-attachments/assets/dbaad84a-19da-4849-aea9-3979ed6f4df6
n/a

Improve onboarding discovery feedback

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/DNDSensorManager.kt

Adding icons based on DND sensor state. Makes for easier visual aid.

Update DND sensor icon based on state

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

Fixes: #4544 by only setting the variables IF the call was successful
Brief testing looks to be ok, I dont recall why we had these variables before understanding if the call was successful or not.

Only update location sent variables when successful

---

app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultButtonControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSliderControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LockControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/VacuumControl.kt
app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/common/ActionFieldBinder.kt
app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetDynamicFieldAdapter.kt
app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/mediaplayer/MediaPlayerControlsWidget.kt
app/src/main/res/layout/widget_button_configure.xml
common/src/main/java/io/homeassistant/companion/android/common/data/integration/Action.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/ActionData.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/ActionFields.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/ActionRequest.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/DomainResponse.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt

Renames services to actions as thats happening in the next HA release. I don't think we should worry about changing the UI based on the version of HA core as even HA documentation is being updated now.
Initially I started off only changing the strings but then I changed the string names for uniformity and that led to updating the rest of the code  as I felt it would help with code readability. I did make an attempt at updating the button widget database to reflect the new name but the automigration was not playing nice so I left it alone as its only referenced in a handful of places.

Rename services to actions

---

wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
wear/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationActivity.kt
wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt

To prepare for the API 33 targeting of Wear (#4500), add handling around the notification permission to the Wear app. This should only apply to watch notifications, not bridged notifications*, but it is nice to have if possible so:
- Ask for notification permission immediately after completing onboarding (Android 13+ only)
- Add a settings item to open the watch settings to grant permission (any Android version)
|Permission prompt after logging in|Settings item if notifications are disabled for the app|Tapping the setting open the system notifications settings**|
|----|----|----|
|![A screenshot of a dialog with the question 'Allow Home Assistant to send you notifications?', a bell icon, an obscured button near the bottom.](https://github.com/user-attachments/assets/9d8eb9e2-78e8-4657-8803 …

Handle notification permission on Wear

---

wear/src/main/AndroidManifest.xml
wear/src/main/java/io/homeassistant/companion/android/home/views/SensorUi.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt

Update the permission requirements for the heart rate sensor on Wear OS 4+ to handle the new behavior when targeting it. These permissions need to be requested in two stages like background location. Any user with the sensor currently enabled on Wear OS 4+, will need to re-enable it after updating.
n/a
~~Documentation: home-assistant/companion.home-assistant#1087~~ n/a

Breaking Change: Update heart rate sensor for Wear OS 4+ target

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/nfc/NfcSetupActivity.kt
app/src/main/java/io/homeassistant/companion/android/sensors/QuestSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/widgets/BaseWidgetProvider.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
wear/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt

For dynamically registered receivers, add whether or not they are exported to prevent a crash due to a [behavior change when we start targeting Android 14](https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported). Exported or not depends on the list of system intents (not on list = exported to be safe): https://developer.android.com/about/versions/12/reference/broadcast-intents-31.
n/a
n/a

Add (NOT_)EXPORTED to registerReceiver for Android 14 target

---

app/src/full/AndroidManifest.xml
app/src/full/java/io/homeassistant/companion/android/location/HighAccuracyLocationService.kt
app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/util/ForegroundServiceLauncher.kt
app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt
automotive/src/full/AndroidManifest.xml
automotive/src/main/AndroidManifest.xml
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorWorkerBase.kt
wear/src/main/AndroidManifest.xml

Adds information about the foreground service type as this is required when targeting Android 14 and will otherwise throw exceptions: https://developer.android.com/about/versions/14/changes/fgs-types-required.
WorkManager jobs that run in the foreground are handled by `androidx.work.impl.foreground.SystemForegroundService`. I'm using the following types:
- [`dataSync`](https://developer.android.com/about/versions/14/changes/fgs-types-required#data-sync) for the sensor worker
- [`remoteMessaging`](https://developer.android.com/about/versions/14/changes/fgs-types-required#remote-messaging) for the persistent websocket connection, as it handles notifications which is somewhat like messaging
Google also [requires a lot of details about these services for the Play Store including videos …

Add foreground service types for Android 14 target

---

app/src/main/java/io/homeassistant/companion/android/assist/AssistActivity.kt
common/src/main/java/io/homeassistant/companion/android/common/assist/AssistViewModelBase.kt
wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt

If Assist is opened (via the default assistant app shortcut), but the app is not yet registered, send the user to onboarding to skip having to close + open app manually. This matches [the app's Wear OS behavior](https://github.com/home-assistant/android/blob/2279d5d7dfb6151a0b4c3ac4ccdb60f251bc2056/wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationActivity.kt#L57).
Setting HA as the assistant app while not logged in, then triggering it by holding the power button on my device:
https://github.com/user-attachments/assets/8d7ca092-e13a-4ce6-8cc2-16a439715734
n/a

Open onboarding when Assist is launched when not registered

---

app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt

When tapping a sensor setting, load setting dialog entries asynchronously to prevent the app getting an ANR. Show a nice loading dialog as well after a second.
Fixes #4513; tested by manually adding a delay to the loading call.
Loading indicator if loading takes >1s:
|Light|Dark|
|---|---|
|![Dialog titled 'Allow list' for a sensor setting, with an indeterminate loading indicator in the center, light mode](https://github.com/user-attachments/assets/b54e1e8c-417b-4cd2-889f-9b18307f402e)|![Dialog titled 'Allow list' for a sensor setting, with an indeterminate loading indicator in the center, dark mode](https://github.com/user-attachments/assets/72f13125-e660-4d82-9fa2-6462ee879e48)|
n/a

Load sensor setting dialog entries async

---

app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetUtils.kt
app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/mediaplayer/MediaPlayerControlsWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/mediaplayer/MediaPlayerControlsWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
app/src/main/res/layout/widget_media_controls_configure.xml

Add support for the media widget to support transparent background. Particularly when nothing is playing the widget is playing it blocks a lot of the wallpaper.
| Dark Theme  | Light Theme |
| ------------- | ------------- |
| ![Screenshot_20240908_192143](https://github.com/user-attachments/assets/8e0f3fee-b9ea-4c33-9ac4-d156675858c4)  | ![Screenshot_20240908_192224](https://github.com/user-attachments/assets/68803ac2-000a-4d8f-a961-1bb56d6b51b1)  |
Sometimes the text might not have a high enough contrast ratio with the background.  I considered making the text colour customisable. This may require some additional (I see a number have already been defined) custom attributes for the views as `android.R.attr.textColorPrimary` doesn't appear to be available for the widget.

add transparent background to media widget

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
app/src/main/res/drawable/ic_zoom_in.xml
app/src/main/res/xml/preferences.xml
common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepositoryImpl.kt
common/src/main/res/values/strings.xml

Implements #4571 - allow overriding the default WebView zoom level.
|Light|Dark|
|---|---|
|![Settings row titled 'Page zoom', '100% (default', magnifying glass with plus icon, light mode](https://github.com/user-attachments/assets/52ca67fa-f58b-4494-9e13-1d4d4cc4a73f)|![Settings row titled 'Page zoom', '100% (default', magnifying glass with plus icon, dark mode](https://github.com/user-attachments/assets/b2ef94ee-a841-44e6-936e-6eef8d8b31a9)|
|![Dialog with options for 50%, 75%, 85%, 100% (default), 115%, 125%, 150%, 175%, 200% page zoom options, light mode](https://github.com/user-attachments/assets/833ffe85-07a7-4075-a74e-18b1f847f641)|![Dialog with options for 50%, 75%, 85%, 100% (default), 115%, 125%, 150%, 175%, 200% page zoom options, dark …

Add Page zoom setting

---

.github/workflows/onPush.yml

While watching the CI pushing the latest PR to the Play Store I noticed tasks for building the `minimal` flavor. We don't need those so only build the `full` flavor (there is a different task in the workflow that handles releases with apks, all flavors).
n/a
n/a

Don't build minimal flavors for Play Publish workflow task

---

common/src/main/java/io/homeassistant/companion/android/common/notifications/DeviceCommands.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/BluetoothSensorManager.kt

Implements: #3290
example service call:
```
service: notify.mobile_app_pixel_8_pro
data:
message: command_ble_transmitter
data:
command: ble_set_measured_power
ble_measured_power: "-10"
```
The field is validated that its not blank and that it is a negative number
Documentation: home-assistant/companion.home-assistant#1086
FCM PR: https://github.com/home-assistant/mobile-apps-fcm-push/pull/150

Allow measured power to be updated via notification command

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRequest.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

Prevent the crash outlined in #3338. Coroutines continuations can only be invoke once, see CancellableContinuation. Use atomic boolean to ensure the continuation is called only once in a thread safe way. While this does not fix the underlying cause it will prevent any more crashes. 
We could log the stack trace whenever the continuation is invoked a second time in order to help identify where the second call comes from.

Prevent socket response continuation being called multiple times (#3338)

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/PhoneStateSensorManager.kt

should've added these initially, oops
now we get graphs in the UI and the sensor is properly identified

Add unit of measurement and device class for signal strength sensors

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

This shouldve been done in https://github.com/home-assistant/android/pull/2999 however I just now noticed the mistake while reviewing the code to see why sometimes updates are just randomly delayed. I am not sure if this is the case but I wanted to use the correct API here. I am also ok with removing this line as well and not having any batching if that is what we would like to do. Apparently it was not working for a while 😬 
Ref of old API used: https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest#setMaxWaitTime(long)

Use correct location batching call

---

common/src/main/java/io/homeassistant/companion/android/common/data/servers/ServerManagerImpl.kt

If `getServer` is unable to get the server from cache it is directly read from the database. When that happens and returns a result, make sure the WifiHelper is available like when cached.
Fixes the following crash observed in the Play Console:
```
Exception kotlin.UninitializedPropertyAccessException:
at io.homeassistant.companion.android.database.server.ServerConnectionInfo.getWifiHelper (ServerConnectionInfo.kt:34)
at io.homeassistant.companion.android.database.server.ServerConnectionInfo.isInternal (ServerConnectionInfo.kt:97)
at io.homeassistant.companion.android.database.server.ServerConnectionInfo.getUrl (ServerConnectionInfo.kt:80)
at io.homeassistant.companion.android.database.server.ServerConnectionInfo.getUrl$default (ServerConnectionInfo.kt:75)
at …
```

Make WifiHelper available in getServer fallback

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Fixes the below play console error by applying the null check to the entire condition.
```
Exception java.lang.NullPointerException: null cannot be cast to non-null type android.widget.FrameLayout
at io.homeassistant.companion.android.webview.WebViewActivity.onPictureInPictureModeChanged (WebViewActivity.kt:1192)
at android.app.Activity.dispatchPictureInPictureModeChanged (Activity.java:9320)
at android.app.ActivityThread.handleWindowingModeChangeIfNeeded (ActivityThread.java:6799)
at android.app.ActivityThread.performActivityConfigurationChanged (ActivityThread.java:6599)
at android.app.ActivityThread.performConfigurationChangedForActivity (ActivityThread.java:6574)
at android.app.ActivityThread.handleActivityConfigurationChanged (ActivityThread.java:6966)
at …
```

Correct null check to avoid errors in pip

---

app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidViewModel.kt

As for issue #3354 this changes allow the use of just spaces in wifi ssid

Allow only spaces SSID when configuring home network wifi (#3354)

---

app/src/main/java/io/homeassistant/companion/android/util/DataUriDownloadManager.kt

Fixes the following crash for data URI downloads (= automation traces from frontend) on Android 14+ devices. The download itself actually still works, but the app crashes when creating a notification to tell you it's done. I've done a quick check and think this is the only instance of an implicit intent that was mutable.
```
2024-10-02 20:01:23.453 12827-12827 AndroidRuntime          io....stant.companion.android.debug  E  FATAL EXCEPTION: main
Process: io.homeassistant.companion.android.debug, PID: 12827
java.lang.IllegalArgumentException: io.homeassistant.companion.android.debug: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security …
```

Fix data URI download notification on Android 14+

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/MobileDataManager.kt

Improve gathering data for sensor mobile_data. 
The currently used API for the mobile_data sensor is marked as  ```@UnsupportedAppUsage``` and is therefore not supported on newer devices (e.g. Pixel 9).
As of SDK 26 there is an API ```TelephonyManager#isDataEnabled``` that is supported on all devices.
Frontend not affected due to this change.
Documentation: home-assistant/companion.home-assistant#435
The existing documentation introduced with above pull request is still fully valid.

Breaking change: Improve sensor mobile_data

---

app/src/full/java/io/homeassistant/companion/android/matter/views/MatterCommissioningView.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingViews.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryView.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationView.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupView.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/notifications/NotificationPermissionView.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/welcome/WelcomeView.kt
app/src/main/java/io/homeassistant/companion/android/util/compose/Theme.kt

Quick improvements to the onboarding for wide screens:
- Center align text on the initial screen to prevent odd alignment of a single line
- Limit the content width on onboarding screens to 600dp centered, like other step flows/bottom sheets (still wide-ish but let's stay consistent)
- Update padding values on initial onboarding screen to match 8dp grid used in all other places
|Before|After|
|----|----|
|![Very wide initial screen with text on the left](https://github.com/user-attachments/assets/39f05a80-8582-4f4b-9c72-19e3c05edc80)|![Less wide initial screen with centered text wrapping onto a second line](https://github.com/user-attachments/assets/467241ac-2bda-460c-b88f-705c666453e8)|
|![Very wide discovery screen with server name left and an arrow for that row all the way to the …

Wide screen onboarding: center text, limit width

---

app/src/main/res/xml/changelog_master.xml

Update change log week of 10/4

---

app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt

Noticed that before I got my scale there was an error because we had no records, so like the active calorie sensor we will return if there is no data to avoid the error. I dont have the old error anymore because I now have records.

Skip weight records update if empty

---

app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt

- Add energy device class to sensors which report calories, which was[ added in core 2024.10](https://www.home-assistant.io/blog/2024/10/02/release-202410/#:~:text=We%20now%20have%20a%20new%20unit%20of%20measurement%20for%20energy%20entities%3A%20calories.)
- Fix Wear daily calories [unit](https://developer.android.com/reference/kotlin/androidx/health/services/client/data/DataType#CALORIES_DAILY()) - it looks like core will just accept the new unit without messing up the history
n/a
n/a

Add energy device class to (kilo)calories sensors

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/DisplaySensorManager.kt
common/src/main/res/values/strings.xml

Fixes: #2440 by adding 2 different sensors to capture the various states.
- Orientation sensor - Displays orientation typically portrait vs landscape
- Rotation sensor - Displays device rotation degree angle based on the natural orientation (i.e. a phone will be portrait 0 while a tablet will be landscape 0)
2 different sensors because the states can all be independent of each other.
Originally I tried to be fancy with reverse portrait states however I realized the angles are dependent on the device in question and theres too much for account for when you consider all the different types of screens like on a watch, car etc...
The intent that is added only fires while the screen is on and if the screen has to redraw teh UI so battery impact is very minimal  here.
Documentation: …

Add 2 different display sensors around various screen states

---

app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/BaseVehicleScreen.kt

Allows automotive sensors to be enabled in the play store build by enabling via the server side
User will get a notification to enable and will then be prompted to enable and grant permission upon selecting the notification.
Also catches the below crash I experienced using a new automotive emulator
```
2024-09-18 16:30:23.491 12966-12966 AndroidRuntime          io....stant.companion.android.debug  E  FATAL EXCEPTION: main (Ask Gemini)
Process: io.homeassistant.companion.android.debug, PID: 12966
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.car.drivingstate.CarUxRestrictions.isRequiresDistractionOptimization()' on a null object reference
at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:153) …
```

Catch automotive exception and allow sensors to be enabled via server side

---

.github/workflows/pr.yml

GitHub Actions is currently failing for steps:
```yml
name: Set up JDK 17
uses: actions/setup-java@v4.4.0
with:
distribution: 'adopt'
java-version: '17'
```
with:
```
Run actions/setup-java@v4.4.0
Installed distributions
Trying to resolve the latest version from remote
Error: Could not find satisfied version for SemVer '17'. 
```
These were migrated to use a supported distribution in #3172 but it looks like we missed two jobs. This PR fixes that. (The failure is probably temporary but still a good idea to migrate those as well.)
n/a
n/a

Migrate setup-java action to use Temurin (two more)

---

app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetDynamicFieldAdapter.kt

- Added a check in the `toJsonType` method to preserve leading zeros in strings.
- This ensures that strings starting with a leading zero are treated as strings rather than numbers, preventing unwanted data conversion.

Fix leading zero handling in toJsonType method

---

app/src/full/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
automotive/src/main/AndroidManifest.xml
common/src/main/res/values/strings.xml

Adds a car speed sensor whose state will contain display speed in meters per second, Attributes for raw speed and also the display units are supported (untested due to head unit emulator limitations). The values can be either positive, negative or 0 depending on vehicle movement (driving, reverse, stopped)
Documentation: home-assistant/companion.home-assistant#1119

Add car speed sensor

---

app/src/main/java/io/homeassistant/companion/android/improv/ImprovRepositoryImpl.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Prevent the app crash when Improv scanning fails in any way by catching the exceptions, we should always fail silently here. Also added a quick check in case the issue is caused by no BLE support but that seems unlikely.
Fixes:
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.le.BluetoothLeScanner.startScan(java.util.List, android.bluetooth.le.ScanSettings, android.bluetooth.le.ScanCallback)' on a null object reference
at com.wifi.improv.ImprovManager.findDevices (ImprovManager.kt:243)
at io.homeassistant.companion.android.improv.ImprovRepositoryImpl.startScanning (ImprovRepositoryImpl.kt:65)
at io.homeassistant.companion.android.webview.WebViewPresenterImpl$startScanningForImprov$1$1.invokeSuspend (WebViewPresenterImpl.kt:488)
at …
```

Prevent crash due to any Improv scanning failure

---

common/src/main/java/io/homeassistant/companion/android/common/util/DisabledLocationHandler.kt
common/src/main/res/values/strings.xml

Fixes #4739 (it is not always possible, but we can simplify the sentence a bit to give translators more room to work with)
n/a
n/a

Avoid (s) in strings if possible

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/widgets/BaseWidgetProvider.kt
app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt

As normal app widgets dont exist in automotive we should not register the screen on intent nor should we show the widget option in settings.
Should prevent below crash from unsupported device:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int[] android.appwidget.AppWidgetManager.getAppWidgetIds(android.content.ComponentName)' on a null object reference
at io.homeassistant.companion.android.widgets.button.ButtonWidget$updateAllWidgets$1.invokeSuspend(ButtonWidget.kt:97)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at …
```

Hide widgets from automotive build and prevent intent registration too

---

app/src/main/java/io/homeassistant/companion/android/util/vehicle/DomainChecks.kt

Adds the fan domain to the supported android auto domains allowing fan entities to be selected for favorites view in android auto
Documentation: home-assistant/companion.home-assistant#1129

Allow fan domain to be selected for android auto favorites list

---

README.md

I noticed that the title/header in the README looks weird:
In this PR I propose to show the status of the [On Push](https://github.com/home-assistant/android/actions/workflows/onPush.yml) pipeline instead (which seemed to match the old "Beta Deploy" the closest):
N/A
~~Documentation: home-assistant/companion.home-assistant#~~

Fix pipeline badge in the header of README.md

---

README.md

As the title says, I tried to improve wording, grammar, and punctuation in `README.md`. Feel free to modify any of my changes to your liking.
N/A
~~Documentation: home-assistant/companion.home-assistant#~~

Improve wording, grammar, and punctuation in README.md

---

app/src/main/java/io/homeassistant/companion/android/sensors/DevicePolicyManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorManager.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/sensors/WetModeSensorManager.kt

Closes #4755 by:
- setting the default tracking value for the work profile sensor to `null`, and only updating the sensor if the value is not `null`, so it is not overwritten if we have not received the intent
- adding a new "intent only" update type for sensors which we cannot read the state for or reliably expect to receive a value in the callback quickly after registering, which mentions in the UI that we need updates from the system and the state may get out of sync
|Chip for new update type|![A chip with the text 'Updates instantly, only on changes', light mode](https://github.com/user-attachments/assets/599ef49f-fb80-466f-8398-e269cd2e91a2)|![A chip with the text 'Updates instantly, only on changes', dark …

Don't reset work profile state on app restart and add "intent only" update type

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/main/java/io/homeassistant/companion/android/notifications/NotificationAction.kt
app/src/main/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt
app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt

Fix #3503 by supporting the use of `behavior: textInput` on a notification action to trigger the reply action. This allows you to use the `action` key to differentiate the different actions, which is already possible on iOS.
n/a
Documentation: home-assistant/companion.home-assistant#1130
FCM changes: home-assistant/mobile-apps-fcm-push#170
cc @bgoncal

Support behavior: textInput key on notification action for reply actions

---

app/src/main/java/io/homeassistant/companion/android/BaseActivity.kt
app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/main/java/io/homeassistant/companion/android/util/FlashlightHelper.kt
app/src/main/java/io/homeassistant/companion/android/util/PermissionRequestMediator.kt

I added the `command_flashlight` notification command. It accepts two values in the `command` field: `turn_on` or `turn_off`.
Currently, my implementation only supports API 23 and above, while the app has `minSdkVersion = 21`. The main reason is my ~~laziness~~ lack of time, and because the Camera2 API is available starting from API 23, and I haven't found a trivial `...Compat` solution. If someone mentions needing this on API 21-22, it can be implemented as a separate feature request. Please let me know if this approach is OK for you.
The PR is marked as a draft because I still have to implement requesting the Camera permission, but I first wanted to ask for your advice on it. The problem is that in `MessagingManager` only so-called "special permissions" are being requested, and there …

Add notification command for turning the flashlight on/off

---

app/src/full/AndroidManifest.xml
app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
common/src/main/res/values/strings.xml

- Body fat
- Blood glucose (tested with the [toolbox](https://developer.android.com/health-and-fitness/guides/health-connect/test/health-connect-toolbox)) 
- Distance
- Elevation gained
- Floors climbed
- Sleep duration
- Steps
This also fixes the attribute for total calories burned to display the current timestamp as it is an accumulated value, currently for me the timestamp on the attribute there is off by the UTC offset. UTC offset is meant for sensors with the timestamp device class.
Documentation: home-assistant/companion.home-assistant#1134
With the exception of `exercise` this is all the data I have for myself in Health Connect.

Add several more health connect sensors

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Added `progress`, `progress_max` and `progress_indeterminate` to the notification manager to allow [progress bars](https://developer.android.com/develop/ui/views/notifications/build-notification?hl=de#progressbar) in notifications.
FCM Push: home-assistant/mobile-apps-fcm-push#173
Documentation: home-assistant/companion.home-assistant#1136

Added support for progress notifcations

---

wear/src/debug/res/drawable/ic_lightbulb.xml

noticed this one was missing the red icon and needed to scroll up to see that the debug build is listed first 🙈 

Use a red icon for Wear OS debug build entity complication to make it distinguishable

---

app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt

Skip the system generated `ranker_group` from sending a meaningless update to HA as it prevents the actual notification data needed.
In my own data I can see that this "special" group is quite meaningless as it has no text or anything other than the app posted a notification
we can see the previous notification had no group however the notification that was desired got skipped due to the `ranker_group` superseding the update
testing locally with the HA prod and debug app side by side with each app listening for the others notification. Sending a message with "test" followed by "test2" results in "test" being sent and then the ranker_group for prod. The debug build with this change shows the expected sequence of "test" followed by "test2" instead of the ranker_group.
Documentation: …

Skip ranker_group notifications as they are meaningless and system generated and prevent valid notification data from sending

---

app/src/main/java/io/homeassistant/companion/android/improv/ui/ImprovPermissionDialog.kt
app/src/main/java/io/homeassistant/companion/android/improv/ui/ImprovPermissionView.kt
app/src/main/java/io/homeassistant/companion/android/improv/ui/ImprovSetupDialog.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingViews.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/notifications/NotificationPermissionView.kt
app/src/main/java/io/homeassistant/companion/android/settings/server/ServerChooserFragment.kt
app/src/main/java/io/homeassistant/companion/android/util/FragmentExtensions.kt
app/src/main/java/io/homeassistant/companion/android/util/compose/ModalBottomSheet.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepositoryImpl.kt
common/src/main/res/values/strings.xml

Based on feedback: add a dialog explaining why the app is about to request permissions for scanning for Improv devices. This should prevent users from denying it because it is not understood. Note that the 2nd prompt may not actually result in a system prompt if it is auto-denied.
Moves some code from onboarding views and bottom sheet dialogs to utility files where it is now used in more places.
|Light|Dark|
|-----|-----|
|![Add integration with a bottom dialog sheet titled 'Search devices', light mode](https://github.com/user-attachments/assets/f7e4618b-3436-4e33-ba43-02808059b8cc)|![Add integration with a bottom dialog sheet titled 'Search devices', dark mode](https://github.com/user-attachments/assets/211b13bd-c36f-46cb-bb58-57251433aa39)|
n/a
related to home-assistant/iOS#3104

Add dialog before prompting for Improv permissions

---

app/src/main/res/xml/changelog_master.xml

Update change log week of 11/22

---

app/src/main/java/io/homeassistant/companion/android/util/vehicle/NativeModeActionStrip.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/DomainListScreen.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/HaCarAppService.kt
app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt

If the HA app starts without internet access (e.g., when the car is in an underground garage, as in my case), the list of domains/entities remains empty. Currently, there's no way to refresh it without killing the app. For example, Volvo AAOS doesn't have an option to force-stop apps, so I end up having to restart the car.
This PR adds a refresh button to the main screen header to solve this issue.

AAOS/Android Auto: Add a button to refresh the main screen entity list

---

app/src/main/java/io/homeassistant/companion/android/improv/ui/ImprovSetupDialog.kt
app/src/main/java/io/homeassistant/companion/android/improv/ui/ImprovSheetState.kt
app/src/main/java/io/homeassistant/companion/android/improv/ui/ImprovSheetView.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebView.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
common/src/main/res/values/strings.xml

- Updates how discovered Improv devices are handled to submit info to the frontend so it can show a frontend discovery box, and the frontend can directly trigger the Connect to Wi-Fi screen of the native setup. Requires 2024.12+ / breaks backwards compatibility.
- Fix permission explanation dialog showing even if all permissions are granted
- Don't start Improv scanning while the app is in the background
Short video showing that after tapping on Devices & services, the device is discovered in a frontend discovery box, and tapping Add will trigger the native flow starting from the Wi-Fi step:
https://github.com/user-attachments/assets/211e8327-a6c2-4446-aa53-df393c44c904
n/a

Implement native Improv discovery with frontend flow

---

app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorSettingsViewModel.kt

- Prevent the list being filtered again every time something in the database is changed but the values don't change
- Perform filtering of the sensors list on the IO thread instead of the main thread
Fixes #4808. A trace showed me a lot of time spent on filtering the list which shouldn't happen when toggling the sensor setting:
n/a but it is noticeable when using the list
n/a

Optimize sensor list performance

---

app/src/main/java/io/homeassistant/companion/android/onboarding/welcome/WelcomeView.kt
app/src/main/java/io/homeassistant/companion/android/settings/controls/views/ManageControlsView.kt
app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/views/ManageShortcutsView.kt
app/src/main/java/io/homeassistant/companion/android/settings/url/views/ExternalUrlInputView.kt

Updates to handle the following two minor Compose deprecations that appeared recently:
- `constructor(capitalization: KeyboardCapitalization = ..., autoCorrect: Boolean, keyboardType: KeyboardType = ..., imeAction: ImeAction = ..., platformImeOptions: PlatformImeOptions? = ..., showKeyboardOnFocus: Boolean? = ..., hintLocales: LocaleList? = ...): KeyboardOptions' is deprecated. Please use the new constructor that takes optional autoCorrectEnabled parameter.`
- `ClickableText(text: AnnotatedString, modifier: Modifier = ..., style: TextStyle = ..., softWrap: Boolean = ..., overflow: TextOverflow = ..., maxLines: Int = ..., onTextLayout: (TextLayoutResult) -> Unit = ..., onClick: (Int) -> Unit): Unit' is deprecated. Use Text or BasicText and pass an AnnotatedString that contains a …

Handle two recent Compose deprecations

---

app/build.gradle.kts
app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/common/RemoteViewsTarget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/mediaplayer/MediaPlayerControlsWidget.kt
automotive/build.gradle.kts
gradle/libs.versions.toml

Replaces the deprecated Picasso library with Coil, which at the same time:
- fixes #4909 by using the `OkHttpClient` used elsewhere which handles mTLS
- fixes #4469 by enabling Coil's optional support for it
n/a, in my testing it worked the same
n/a

Migrate from Picasso to Coil

---

app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
app/src/main/java/io/homeassistant/companion/android/controls/MediaPlayerControl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt

Adds support for media player entities in device controls.
Toggle control will play/pause, active state is only if `playing`
Slider control for volume if media player supports setting the volume
Behavior designed to match frontend as close as possible due to conversions for volume
Documentation: home-assistant/companion.home-assistant#1149
Ref: https://community.home-assistant.io/t/wth-why-cant-media-player-entities-be-added-to-android-device-controls/813242
The actions accept any value, we don't particularly need to round things but good to keep things clean i think. Tested with a few of my media players.

Add support for media players in device controls

---

common/src/main/res/values/strings.xml

Fix #4840 (people didn't use the tag :( ). Note that the event is called in `onStop` and it depends on the system whether or not it is triggered, so start and open are both not 100% correct but at least the setting title is now the same as the description.
...
n/a

Update text for go to first view in onStop setting

---

app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt

Add the magic code* so manually casting the result from `buildReadRecordsRequest` is no longer needed and quite a large list of compilation warnings for this class like below is resolved:
```
/app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt:474:102 Unchecked cast of 'androidx.health.connect.client.request.ReadRecordsRequest<out androidx.health.connect.client.records.Record>' to 'androidx.health.connect.client.request.ReadRecordsRequest<androidx.health.connect.client.records.ActiveCaloriesBurnedRecord>'.
```
\* similar to line 984
n/a
n/a

Fix casting for Health Connect buildReadRecordsRequest result

---

.github/workflows/onPush.yml

Currently releases don't include artifacts and fail with ([example](https://github.com/home-assistant/android/actions/runs/12471370823/job/34808200161)):
```
👩‍🏭 Creating new GitHub release for tag 2024.12.5...
⬆️ Uploading app-full-release.apk...
⬆️ Uploading app-minimal-release.apk...
⬆️ Uploading version_code.txt...
⬆️ Uploading wear-release.apk...
⬆️ Uploading automotive-full-release.apk...
⬆️ Uploading automotive-minimal-release.apk...
##[error***Request body length does not match content-length header
```
Needs softprops/action-gh-release#562 for fix so revert while it is not released.
n/a
n/a

Revert "Bump softprops/action-gh-release from 2.1.0 to 2.2.0 (#4896)"

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

Adds a log statement with the app's decision to an Improv scan request to help with #4936, where nothing appears to happen.
Why: I expected the app requirements to be simple enough to verify and the library simply throws exceptions if things don't work, but right now it's unclear why nothing is happening. The line `D WebviewActivity: External bus {"type":"improv/scan","id":4}` should be followed by [`I ImprovManager: Find Devices`](https://github.com/improv-wifi/sdk-android/blob/2b7e2d892862a541f576f05ed0867f35f3072e90/library/src/main/java/com/wifi/improv/ImprovManager.kt#L240), if not something between the external bus and library seems to decide not to work and these lines should tell if that is the app.
n/a
n/a

Log action for external bus improv/scan command

---

app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt
common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/BluetoothSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/database/server/ServerConnectionInfo.kt

Fixes a regression in home network checks introduced by expanded home network indicators (ethernet, VPN) by making the internal URL check part optional. (Previously, they used `isHomeWifiSsid()` which does not consider the internal URL.)
Fixes #4934, confirmed [on the forums](https://community.home-assistant.io/t/companion-app-not-recognizing-home-wi-fi/816994/3?u=jpelgrom).
n/a
n/a

Fix home network checks without internal URL

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

Fixes #4936. The issue is caused by the following combination:
1. from the Nearby devices permission group _a_ Bluetooth permission is granted, so the system settings show the permission as on, but not _all_ permissions are granted
2. the in-app permission prompt was shown at least twice so it is not shown again
It results in the user thinking everything is good, while the app doesn't continue and doesn't request additional permissions -> confusion why nothing is discovered.
This PR tries to fix it by checking when 1) not all permissions are granted and 2) the prompt was shown at least twice, if we need just _one_ Bluetooth permission, and if so always requesting that permission. Because Improv needs _two_ Bluetooth permissions that means something from the Nearby devices group was …

Always request Bluetooth permission for Improv if 1/2 is granted

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
automotive/src/main/AndroidManifest.xml

Remove the option to set Home Assistant/Assist as the assistant app or trigger it with the voice command button on Automotive. Some manufacturers want an overhaul of the UI, or break the UI, and it generally isn't designed for hands-free usage.
(Assist is still available via other routes on Automotive such as from the frontend.)
n/a
n/a

Remove assistant app/Assist with button on Automotive

---

app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt

This PR adds support for specifying the server to navigate to when using `homeassistant://navigate` deeplinks, creating feature parity with iOS. See [docs](https://companion.home-assistant.io/docs/integrations/url-handler#specify-server-to-navigate-to) and [iOS source](https://github.com/home-assistant/iOS/blob/e880f9784c01525c5dcefdabaf4f9df16d154eb1/Sources/App/WebView/WebViewWindowController.swift#L216-L244).
n/a, chooser is skipped
Documentation: home-assistant/companion.home-assistant#1161

Support ?server=name in homeassistant navigate deeplink 

---

.github/workflows/onPush.yml
.github/workflows/pr.yml

This adds the Gradle build action to all Gradle workflows to speed up
builds using caching.
This replaces the Github action cache as well as the Gradle Wrapper
Validation action since the Gradle Build action [performs the same
validation](https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#gradle-wrapper-validation)
As an example: ktlint on this PR took just 56 seconds (compared to 2:30 on other PRs) due to partial caching since the Gradle Build Action is already enabled for some workflows.

Use Gradle Build Action

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt
common/src/main/res/values/strings.xml

This PR adds a new sensor for the [battery cycle count](https://developer.android.com/reference/android/os/BatteryManager#EXTRA_CYCLE_COUNT).
The intent extra is available on Android 14+, but also requires devices to support it. Looking at this open source app that was one of the first to expose the info that support is far from guaranteed, so I've added a note in the description about it: https://gitlab.com/narektor/batt/-/blob/main/app/src/main/java/com/porg/batt/CompatChecker.kt?ref_type=heads
|Light|Dark|
|----|----|
|![In-app sensor screen for a sensor named 'Battery cycle count', state 375, light mode.](https://github.com/user-attachments/assets/ed8ce031-18c8-4592-9f5e-7a5fac0f8f3e)|![In-app sensor screen for a sensor named 'Battery cycle count', state 375, dark …

Add battery cycle count sensor

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt

Fix #4979 by only calculating battery power if the input values are valid; if not the state will be unavailable (individual attributes still added so you can find out which is faulty).
- For current: the docs mention "If the property is not supported or there is any other error, return (a) 0 if targetSdkVersion < VERSION_CODES.P or (b) Integer.MIN_VALUE if targetSdkVersion >= VERSION_CODES.P.".
- For voltage: treat the fallback value of 0 as an error, because a real battery should never have no voltage.
n/a
n/a

Validate input for battery power sensor

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

Noticed that we had a few places to clean up and remove overlapping suspend calls
also added in a flush location call to only be called when we need to restart location services to clear out the queue, its also recommended we call it as we use `setMaxWaitTime()` so this felt like the most appropriate place to call it.
geofences are also limited to 100 per app so adding in 2 condition checks there. Probably needs a docs update for this one and combined with high accuracy expanded mode will be fun to write 🙃 
https://developer.android.com/develop/sensors-and-location/location/geofencing
Documentation: home-assistant/companion.home-assistant#1141
Tested these changes overnight to ensure it all still works as expected

Clean up location manager after making updates suspend

---

wear/src/main/java/io/homeassistant/companion/android/home/views/SelectShortcutsTileView.kt
wear/src/main/java/io/homeassistant/companion/android/theme/Color.kt

In the settings screen for the shortcuts tile, replace the checkbox with a switch for the option to show names on the tile. A switch is the correct control here instead of a checkbox, because it is a standalone (and the only) option and not something to select in a list. See the Material guidelines: https://m3.material.io/components/switch/guidelines#6add393e-e4e8-41b6-862b-5ebffb894f72.
This PR also removes the checkbox button colors function because this was the last usage of it.
(the preview doesn't render the icon correctly, but that doesn't matter here)
n/a

Replace checkbox with switch in shortcuts tile name on/off

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/qs/TilePreferenceActivity.kt
automotive/src/main/AndroidManifest.xml

Shows the more info dialog when long pressing on a quick settings tile (if setup; otherwise redirects to settings or onboarding). This implements #4955 partially - but this is the minimum to start, and personally I'm not sure we should allow more configuration here.
Short clip showing long press opening frontend, more info (Android doesn't really have a smooth transition here):
https://github.com/user-attachments/assets/5133cdc6-4988-41b8-a392-7ddfebe6a037
I don't think this is necessary right now

Show more info on QS tile long press

---

app/src/main/java/io/homeassistant/companion/android/improv/ui/ImprovSheetView.kt

Attempt to fix #5018 by not requiring a WiFi password to connect an Improv device.
I have not tested this at all; it's just a wild guess.

Do not require a wifi password to connect Improv.

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Fix #5024 by converting floats to longs if it isn't a long, so the user doesn't have to think too much about it.
n/a
n/a

Convert floats to longs for `when` in notification data

---

common/src/main/java/io/homeassistant/companion/android/common/data/servers/ServerManagerImpl.kt

#4650, #4975
This PR updates `serverManager::isRegistered()` which is used in many places as a general "does the app have a server" check, to also check that the server _session_ is good to use (which internally checks the webhook/install ID existing and being valid).
The install ID is random and [excluded](https://github.com/home-assistant/android/blob/cb99f4c4dad4a8a2112c4b28cd9ce51c52faf229/app/src/main/res/xml/backup_rules.xml#L5) from backups and transfers to avoid using the same registration/tokens on another device, which can resolve the issues if used at the correct time. However, it was only checked when [launching the app](https://github.com/home-assistant/android/blob/cb99f4c4dad4a8a2112c4b28cd9ce51c52faf229/app/src/main/java/io/homeassistant/companion/android/launch/LaunchPrese …

Check session state in registered check to avoid using transferred servers more

---

app/src/main/res/xml/changelog_master.xml

Update change log week of 2/8

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Fixes #5038 
Previously FCM would omit blank keys. This was changed and is now in line with websocket notifications, but in some places the behavior might be unexpected. This PR ignores a couple more keys if blank (like we already do for many) where it seems safe to do so.
n/a
n/a
Testing note: if you try to send nothing from dev tools it will send a string `null`, so send a blank string `""` instead

Skip some more notification data items if they are blank

---

.github/workflows/onPush.yml

The gradle components don't automatically get detected upon build. Use the dependency-submission API to enable this dependency tracking.
Documentation explaining this:
https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/dependency-graph-supported-package-ecosystems#package-ecosystems-supported-via-dependency-submission-actions
That article links to this action:
https://github.com/marketplace/actions/build-with-gradle#the-dependency-submission-action
The GitHub front end will change :smile: It currently only displays GitHub and Ruby dependencies, not Gradle.
N/A
This is only for housekeeping / dependencies. I wasn't able to test the action easily due to app secrets, but it should work.

GitHub: Add dependency uploading

---

build-logic/convention/build.gradle.kts
build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
build-logic/convention/src/main/kotlin/AndroidCommonConventionPlugin.kt
common/build.gradle.kts
gradle/libs.versions.toml

This is a follow up of https://github.com/home-assistant/android/pull/5078 to avoid duplication in common gradle module.
The Application convention module does call this new module directly and `:common` call it too.

Add new android common gradle convention plugin and update common module

---

renovate.json

In order to exclude wear from androidx and compose group. I've update the grouping in renovate config. We want to avoid this https://github.com/home-assistant/android/pull/5100
This is PR is going to be merge so that we can test if it works.

Exclude androidx wear package from compose and androidx groups

---

renovate.json

Renovate is failing to properly verify all our dependencies because it is doing too many request at once on the public maven repo. 
The value picked should avoid this issue and keep the check reasonable in time.
While looking at the logs of renovate it seems that it was not searching within the gradle plugin repo nor jitpack so I've added the missing registry URLs.

Update renovate config to avoid 429

---

renovate.json

It seems that the package rules for jitpack was not working properly. So I've moved jitpack into the global list of repositories.

Add jitpack to global list of repositories

---

build-logic/convention/build.gradle.kts

The initial fix after updating typesafe plugin was not great it added an explicit lint between this plugin and ktlint tasks. The author of the plugin proposed another solution cleaner. https://github.com/radoslaw-panuszewski/typesafe-conventions-gradle-plugin/issues/34

Remove gradle tasks dependency to ktlint for typesafe plugin in builld-logic

---

app/src/main/kotlin/io/homeassistant/companion/android/assist/AssistViewModel.kt
common/src/main/kotlin/io/homeassistant/companion/android/common/assist/AssistViewModelBase.kt
common/src/main/kotlin/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
common/src/main/kotlin/io/homeassistant/companion/android/common/data/websocket/impl/entities/AssistPipelineEvent.kt
wear/src/main/kotlin/io/homeassistant/companion/android/conversation/ConversationViewModel.kt

`intent-progress` allow streaming the answer of a LLM, right now it is not playing the sound before the text is fully written but that's a limitation of the API nothing we can do in the app.
This PR is inspired by iOS PR https://github.com/home-assistant/iOS/pull/3483 and the frontend PR https://github.com/home-assistant/frontend/pull/24143
The frontend is handling the `role` but it seems that in our case we don't need for now at least.
I took the liberty to replace the callback with unnamed arguments with a sealed class for better usability and evolution.
[demo_stream.webm](https://github.com/user-attachments/assets/a1c84199-e97a-4777-bd6d-b1d9cd9ac8a5)
It only works with ChatGPT integration for now.

Support intent-progress for Assist

---

automotive/build.gradle.kts

After merging https://github.com/home-assistant/android/pull/5139 master build started to fail. The issue was link to `lint` for release buildType of automotive
```
* What went wrong:
Execution failed for task ':automotive:lintVitalReportFullRelease'.
> A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintTask$AndroidLintLauncherWorkAction
> There was a failure while executing work items
> A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintWorkAction
> Path variable $***:automotive*fullDebug*MAIN*sourceProvider*0*javaDir*5*** referenced in $***:automotive*fullDebug*MAIN*sourceProvider*0*javaDir*5***/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt not provided to serialization
```
While …

Disable lint tasks in release for automotive module

---

.github/workflows/pr.yml
gradle/libs.versions.toml

Now that we are using lockfiles sometimes we forget to update them, which lead to issues that are not easy to associate with a missing update of the lockfile. In order to explicitly spot a missing update I've added a new job that checks if we forget to push the updated lockfiles.
If it is the case it will block the CI and send an error message in the PR code.
This is the message you are getting when you forget to update the lockfile.
To make more sense into our workflow I propose this new graph

Detect missing lockfile update on CI

---

.editorconfig

Kotlin coding [conventions](https://kotlinlang.org/docs/reference/coding-conventions.html#trailing-commas) leaves the choice of the developer to choose or not to have trailing comma. I think that we should do the same. In some cases it makes the review clearer to have a training comma since next modification are not going to modify a line just to add a comma.
This question arise from this PR https://github.com/home-assistant/android/pull/5169 after this PR KTlint won't complain anymore about the trailing comma and won't add any automatically.

Allow trailing comma but do not enforce it to follow Kotlin coding conventions

---

renovate.json5

This PR tries to 'fix' #5165, with Renovate trying to update our Guava dependency from `version-android` to `version-jre` because j > a. As we are building an Android app we should use the `-android` dependency so that change is unwanted.
Setting the `versionScheme` should prevent this based on [this comment](https://github.com/renovatebot/config-help/issues/232#issuecomment-491826549). Searching for code on GitHub shows the code submitted in this PR as more common than the one in the issue comment, so I picked the search results code.
n/a
n/a

Set Renovate versioning for Guava to use -android and ignore -jre

---

renovate.json5

The PR https://github.com/home-assistant/android/pull/5183 was an attempt to fix the auto update of `guava` but I've made a mistake in the regex that led to the strip of `-android` when renovate is looking for new version. It led to this logs 
```
DEBUG: GET https://repo1.maven.org/maven2/com/google/guava/guava/33.4.6/guava-33.4.6.pom = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=404 retryCount=0, duration=4)
DEBUG: Rejected release
{
"datasource": "maven"
"packageName": "com.google.guava:guava"
"registryUrl": "https://repo1.maven.org/maven2/"
"version": "33.4.6"
}
```
I'm not 100% sure this PR is going to fix the issue but I need this on main to validate my theory.

Ensure -android is part of the version capturing group

---

.github/workflows/onPush.yml

It seems that since 2022 we are not getting any crash from Sentry because on release pipeline is missing some on env variable. This PR fix this issue. I managed to debug this easily thanks to https://github.com/home-assistant/android/pull/5200 and I also tested the update of sentry to 8.7.0 so I can say it is working and we can proceed with the update (current PR from renovate needs to be updated since it targets 8.6.0).
This is the manifest of a beta build took from Github Action.
And here a screenshot after the fix

Release builds are missing DSN secret

---

app/src/debug/AndroidManifest.xml
app/src/debug/kotlin/io/homeassistant/companion/android/developer/DevPlaygroundActivity.kt
app/src/debug/res/values/strings.xml
app/src/debug/res/xml/shortcuts.xml
app/src/main/kotlin/io/homeassistant/companion/android/util/CrashSaving.kt

This PR introduce a new activity meant for developer while developing. This activity is only accessible in debug and through a static shortcut.
For now it only has one button that crash the app with a DummyException. It is meant to test the crash reporting. We could use this activity to actually validate that an update of Sentry is not breaking the upload of the crash.
Documentation: home-assistant/developers.home-assistant#2642

Introduce DevPlayground

---

gradle.properties
settings.gradle.kts

This PR does the following
* bumps the Reckon plugin to add support for the configuration cache. https://github.com/ajoberstar/reckon/issues/202 (full changes https://github.com/ajoberstar/reckon/compare/0.19.1...0.19.2)
* enables configuration cache
* Add metaspace heap arguments to avoid bug in Gradle: https://github.com/gradle/gradle/issues/19750

Enable Gradle Configuration cache

---

gradle.properties

Closes #5222 by bumping the JVM max metaspace to 1g.

Bump JVM max metaspace size to 1g

---

app/src/main/kotlin/io/homeassistant/companion/android/settings/notification/NotificationHistoryFragment.kt
common/src/main/kotlin/io/homeassistant/companion/android/database/AppDatabase.kt
common/src/main/kotlin/io/homeassistant/companion/android/database/notification/NotificationDao.kt

Fixes two sets of lint/ksp warnings related to the database
> w: [ksp] The nullable `Array` (kotlin.Array<io.homeassistant.`companion`.android.database.notification.NotificationItem>?) return type in a DAO function is meaningless because Room will instead return an empty `Array` if no rows are returned from the query.
These can be non-null.
> w: file:///home/runner/work/android/android/common/src/main/kotlin/io/homeassistant/companion/android/database/AppDatabase.kt:211:18 'fun fallbackToDestructiveMigration(): RoomDatabase.Builder<AppDatabase>' is deprecated. Replace by overloaded version with parameter to indicate if all tables should be dropped or not.
Losing data is not acceptable, and we have migrations for all current versions + require new migrations using GitHub Actions, so remove …

Fix database-related lint/ksp warnings

---

common/src/main/kotlin/io/homeassistant/companion/android/common/assist/AssistViewModelBase.kt
common/src/main/kotlin/io/homeassistant/companion/android/common/data/websocket/impl/entities/ConversationSpeechPlainResponse.kt
common/src/main/kotlin/io/homeassistant/companion/android/common/data/websocket/impl/entities/ConversationSpeechResponse.kt

Fixes #5167 by allowing more nullability in the Assist `intent-end` events [matching the frontend](https://github.com/home-assistant/frontend/blob/ab415188babbe04ae0f2ae04ff2847e6e6327364/src/components/ha-assist-chat.ts#L375-L378):
- `response.speech` can be null (JS `?`)
- `response.speech.plain` can be null (JS `if` checks for null, and the cause of the crash)
If there is no text, the dialog will keep showing "..." as the response to the request, which should match frontend behavior.
n/a
n/a
Also includes a one line fix for an unnecessary `!!` that I noticed scrolling down in the file.

Handle null speech in Assist intent-end event

---

.idea/codeStyles/Project.xml

I recently added `.idea/codeStyle/Project.xml` in https://github.com/home-assistant/android/pull/5216 but I made a mistake in the configuration of the imports order, that I didn't spot at first.
The issue appear if you are using an alias like `import io.homeassistant.companion.android.common.R as commonR` it would put it at the end of the imports. This is not compliant with our current KTLint configuration.

Remove alias import different ordering in Android Studio

---

app/src/main/kotlin/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/res/values/arrays.xml
app/src/main/res/xml/preferences.xml
common/src/main/res/values/strings.xml

The switch for the theme was not working because it was using values from `strings.xml` in one side (from the xml arrays) and harcoded values in ThemeManager. Because of that when the translation of the values where different than the hardcoded value it was always defaulting to `AppCompatDelegate.MODE_NIGHT_NO`.
I decided to rename the strings of the values used in the arrays to avoid any issues, when we are going to download the translation for the next release.
⚠️ I need to check that after this PR is merged we are not pushing the new keys into Localize again otherwise the issue will happen again later when someone will translate it again.
I decided to also apply this to the screen orientation that was built the same way. Even if the issue is not as obvious, the issue is only visible if …

Remove value strings of preference arrays from Lokalise

---

app/src/main/kotlin/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/kotlin/io/homeassistant/companion/android/webview/externalbus/ExternalBusMessage.kt

Fixes #5297, by using the new `navigate` external message introduced in https://github.com/home-assistant/frontend/pull/25516
I kept the old implementation but it only works with old version of the frontend. It means that this feature won't work if you have a version of core that is between the two implementation.
To test it you need a frontend dev environement or wait for the next release of core.
Ideally the message sent to the external bus should be strongly typed so I decided to create a dedicated class for this new message.
The current implementation doesn't erase the backstack, but only replace the head of the backstack. It leads to a weird behavior in the navigation depending on where you were before putting the app in background. To avoid this we could have a command to the …

Fix always show first view when opening the app

---

settings.gradle.kts

Closes #5220 by only configuring Reckon to use the stage-based versions when running in CI, and using snapshot versions when running locally.
This is a choice that removes some information, but I feel after this many years with Reckon the value of the timestamps in versions locally is too limited to be worth the performance loss, especially considering more frequent builds for previews etc. For builds on GitHub Actions, where this information can be useful, it is unchanged and continues to use stages.
Using the `CI` environment variable to detect running in CI [seems](https://github.com/detekt/detekt/blob/f2ef08bb8d3b4f49d0dc2402109044fefdd2002a/build-logic/build.gradle.kts#L30) [to be](https://github.com/pinterest/ktlint/blob/96ce4a13838ffae670ddfa9e462a12aa38592456/settings.gradle.kts#L2 …

Use snapshot version scheme locally to allow for better caching

---

app/src/main/kotlin/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/res/xml/changelog_master.xml

The latest frontend release randomly added an official option to open the more info dialog programmatically, [using a query paramater](https://github.com/home-assistant/frontend/pull/25733), after we have been unable to get such a frontend change for the app's deeplinks for years. Better late than never, I guess.
This PR switches from the workaround to the new query parameter to open more info, if the server version is recent enough.
Using two examples, but this obviously applies to all. Also confirmed it works correctly if you changed the default dashboard/url. Really nice how responsive this now feels!
- From a push notification
https://github.com/user-attachments/assets/0604d1be-2bf6-409c-8f27-2edc04f3c0fc
- From device controls …

Use new frontend entity more info deeplink

---

app/src/main/kotlin/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/kotlin/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
app/src/main/res/xml/preferences.xml

The new feature about being able to use HA as a launcher was not properly setup in the SettingsFragment. It was enabled by default where it should have been disabled by default.
We also don't want to expose this feature in the automotive variant of the app.
CC @fpetrovski

Disable ha_launcher by default and hide it in automotive

---

common/src/main/kotlin/io/homeassistant/companion/android/common/data/websocket/impl/entities/CompressedEntity.kt
common/src/test/kotlin/io/homeassistant/companion/android/common/data/websocket/impl/entities/CompressedEntityTest.kt

After migrating to Kotlinx serialization the initialization of the classes are more strict than before. So a field that doesn't have a default value needs to be present in the JSON while decoding. In this case it is possible that the field `attributes` is empty or null (for reference see iOS impl https://github.com/home-assistant/HAKit/pull/49/files#diff-becad62c1e040b15f3ebfefa6bb6d7bc25de151dcc3eddc1599d27d76bb11f69).
I saw a `!!` while converting to an `Entity` and I changed it to `checkNotNull` for more readability if it ever happens.
I'm wondering if we actually should support `null` for the `state` I'm going to follow up with core on this.

Handle missing field exception in CompressedEntityState

---

app/src/main/AndroidManifest.xml
app/src/main/kotlin/io/homeassistant/companion/android/HomeAssistantApplication.kt
build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
gradle.properties
wear/src/main/kotlin/io/homeassistant/companion/android/HomeAssistantApplication.kt

In order to prepare ourselves from the changes that Google is going to push in the new version of Android, but also detect potential issues. I've enable some flags in DEBUG from `StrictMode`.
I enabled Intent matching in the manifest from this issue https://github.com/home-assistant/android/issues/5330.
This flags only impacts the API 36, I did some testing and it seems to work properly.
Developer Documentation: home-assistant/developers.home-assistant#2719
Enabling all the checks is making the app crashing from the beginning about the socket that does network call without being properly tags. I only picked some flags that I found useful.
Closes #5330

Support strict intent matching

---

settings.gradle.kts

Our current configuration was causing this warning
> WARNING: This build (:build-logic) is being evaluated before the parent build. If you import any external version catalogs or use VersionCatalogBuilder API, those catalogs won't be available in this build. Consider moving includeBuild(...) outside the pluginManagement { ... } block in settings.gradle.kts of the parent build. To suppress this warning, set typesafeConventions.suppressPluginManagementIncludedBuildWarning = true. Read more at: https://github.com/radoslaw-panuszewski/typesafe-conventions-gradle-plugin?tab=readme-ov-file#known-limitations
This PR apply the suggestion and everything works as it should.

Move includeBuild outside of pluginManagement

---

app/src/main/kotlin/io/homeassistant/companion/android/settings/SettingsFragment.kt

We were using `Intent.ACTION_MAIN` for opening the settings but it was not the action that is defined in the manifest of the activity https://cs.android.com/android/platform/superproject/main/+/512046e84bcc51cc241bc6599f83ab345e93ab12:packages/apps/Settings/AndroidManifest.xml;l=1204
It was causing StrictMode to trigger. To be future proof this PR fix this.

Change action for ManageAssistActivity

---

app/src/main/kotlin/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
app/src/main/kotlin/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
app/src/main/kotlin/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt
app/src/main/kotlin/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
app/src/main/kotlin/io/homeassistant/companion/android/widgets/mediaplayer/MediaPlayerControlsWidgetConfigureActivity.kt
app/src/main/kotlin/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
common/src/main/kotlin/io/homeassistant/companion/android/database/widget/ButtonWidgetDao.kt
common/src/main/kotlin/io/homeassistant/companion/android/database/widget/CameraWidgetDao.kt
common/src/main/kotlin/io/homeassistant/companion/android/database/widget/MediaPlayerControlsWidgetDao.kt
common/src/main/kotlin/io/homeassistant/companion/android/database/widget/StaticWidgetDao.kt
common/src/main/kotlin/io/homeassistant/companion/android/database/widget/TemplateWidgetDao.kt

After enabling `StrictMode` in #5483 I found out that we are doing many db calls on the main thread where we shouldn't. It most probably causes some ANR. This PR is related to the Widget DAOs all the DAO methods should be marked as `suspend`. 
Part of https://github.com/home-assistant/android/issues/5520
In `ButtonWidgetConfigure` I introduce a regression when moving the `get` into the coroutine because it gets called multiple times and because of that it cause a concurrent modification of the item of the list of field and most of the time it result into a duplicate fields. To avoid this I've kept a reference to the currently running job and cancel any previous job before starting a new one.

Make Widget DAOs suspensible

---

app/src/main/kotlin/io/homeassistant/companion/android/webview/WebViewActivity.kt

Quick fix for an issue discovered while reviewing #5555 - see [comment](https://github.com/home-assistant/android/pull/5555#issuecomment-3110165265).
The webview's basic authentication handling used a variable which was updated anytime a new resource was loaded, introducing a race condition for getting/saving the authentication data where for me it always failed to work correctly. Change the function to take the needed information as arguments, and clean up code a bit based on Android Studio suggestions.
_We do not yet have a testing setup for the entire WebView + this requires framework code so not easily mocked, so I consider it out of scope for this PR. This feature should be rewritten to make it testable which I did not want to do right now (see below)._
_This is old crummy code I …

Fix webview basic authentication race

---

common/src/main/kotlin/io/homeassistant/companion/android/common/util/AudioUrlPlayer.kt
common/src/test/kotlin/io/homeassistant/companion/android/common/util/AudioUrlPlayerTest.kt

In some cases we were calling `resume` multiple times in `AudioUrlPlayer` which led to some crashes.
This PR make sure that we won't resume by checking if the continuation is still active.

Fix already resumed exception in AudioUrlPlayer

---

app/src/main/kotlin/io/homeassistant/companion/android/launch/LaunchActivity.kt

Deep link like `homeassistant://navigate/history?start_date=2025-08-08T11%3A00%3A00.001Z&end_date=2025-08-08T14%3A00%3A00.001Z` are not fully working since the parameters are not given when opening the webview activity we only give the `path`. This PR fix this by passing the whole URL instead.

Make sure Deeplink URL parameters is not stripped

---

.github/workflows/pr.yml

Now that we are targeting API 36 we should have instrumentation test running using this API. In order to save some resources I replaced the API 35 by 36.

Run instrumentation test on API 36 instead of 35

---

app/src/main/kotlin/io/homeassistant/companion/android/launch/LaunchPresenterBase.kt

We've recently introduced a checker when the app starts in https://github.com/home-assistant/android/pull/5581. It seems some users are noticing a slow down in the start of the app https://github.com/home-assistant/android/issues/5689. In order to debug I've added a small log that would help us to see if there are an issue with the network checker.

Add more logs to see current network state in launcher

---

common/src/main/kotlin/io/homeassistant/companion/android/common/compose/composable/HAButtons.kt

The links within the KDocs of the `HAButtons` was not correctly being displayed since it was not using markdown.

Fix links within documentation of HAButtons

---

app/src/main/res/xml/changelog_master.xml

Since Google is taking a lot of time to approve the last beta with the quick fix, we might push 2025.8.10 before the actual release of the beta. To avoid a situation where we ship a version without a changelog I decided to bring back the previous one.

Bring back changelog of 2025.8.9

---

app/lint-baseline.xml
app/src/main/kotlin/io/homeassistant/companion/android/util/vehicle/GridItems.kt
app/src/main/kotlin/io/homeassistant/companion/android/vehicle/DomainListScreen.kt
app/src/main/kotlin/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
app/src/main/kotlin/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
app/src/main/kotlin/io/homeassistant/companion/android/vehicle/MapVehicleScreen.kt
app/src/test/kotlin/io/homeassistant/companion/android/widgets/BaseGlanceEntityWidgetReceiverTest.kt
app/src/test/kotlin/io/homeassistant/companion/android/widgets/todo/TodoWidgetStateUpdaterTest.kt
app/src/test/kotlin/io/homeassistant/companion/android/widgets/todo/TodoWidgetToggleActionsTest.kt
automotive/lint-baseline.xml
common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/kotlin/io/homeassistant/companion/android/common/data/servers/ServerManager.kt
common/src/main/kotlin/io/homeassistant/companion/android/common/data/servers/ServerManagerImpl.kt
common/src/test/kotlin/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketCoreImplTest.kt
wear/src/main/kotlin/io/homeassistant/companion/android/home/HomePresenter.kt
wear/src/main/kotlin/io/homeassistant/companion/android/home/HomePresenterImpl.kt

Part of the effort describe in https://github.com/home-assistant/android/issues/5688 we should remove all the `runBlocking`. There was one in `ServerManager` to get the active server.

Remove runBlocking from ServerManager.activeServerId

---

app/src/full/kotlin/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt

Fixes #5286 
It seems that apps are writing daily totals records to Health Connects in two distinct ways:
- a record for every minute of data (for example, Garmin Connect and Fitbit)
- a record for the entire day which is updated throughout the day (for example, Samsung Health)
The app's aggregation request to get the "daily x" sensor worked fine with the first type, but not with the second type where the API would give x% of the value when x% of the day had passed instead of the actual value. By always asking for the aggregate of the full day, this issue is resolved.
Tested with apps writing both types of records, see screenshots below.
|     |One record per minute (example: Garmin Connect)|One record for the entire day (example: Samsung Health)|
|Current code|✅ OK …

Set end time for Health Connect aggregation request to end of day

---

app/src/main/kotlin/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/kotlin/io/homeassistant/companion/android/webview/WebViewPresenter.kt
app/src/main/kotlin/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

Part of the effort describe in https://github.com/home-assistant/android/issues/5688 we should remove all the `runBlocking`. The one in the WebViewPresenter are causing a lot (the most) of ANRs within the app. The changes are quite straightforward I tested the changes on Android 16 and 9. I didn't see any regression there.

Remove all runBlocking from WebViewPresenter

---

app/src/main/kotlin/io/homeassistant/companion/android/settings/controls/views/ManageControlsView.kt

Fixes #5747: the device controls selected server was 0 (none) instead of the default. Previously the default server was loaded and set as selected when the view was loaded, but because the default server ID is now loaded async we need to reset the selected server when the default server ID changes (= is loaded).
(The default server ID doesn't change while using this screen, so this won't cause any changes for the user.)
n/a
n/a

Fix device controls settings not selecting a server by default

---

app/src/main/kotlin/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/kotlin/io/homeassistant/companion/android/webview/externalbus/ExternalBusMessage.kt

In order to display the version of the application within the frontend we need to send the version through the external bus.
The frontend PR https://github.com/home-assistant/frontend/pull/27064
This PR also contains a new field added in https://github.com/home-assistant/frontend/pull/22675  about `downloadFileSupported`. For now it doesn't have a significant impact on our side, but for future evolution it is important to set the property since we support this feature.

Add appVersion and downloadFileSupported to external bus config response

---

app/lint-baseline.xml
app/src/full/kotlin/io/homeassistant/companion/android/settings/sensor/HealthConnectPermissionActivity.kt
app/src/full/kotlin/io/homeassistant/companion/android/settings/wear/SettingsWearActivity.kt
app/src/full/kotlin/io/homeassistant/companion/android/settings/wear/views/SettingsWearHomeView.kt
app/src/main/kotlin/io/homeassistant/companion/android/barcode/BarcodeScannerActivity.kt
app/src/main/kotlin/io/homeassistant/companion/android/nfc/views/NfcNavigationView.kt
app/src/main/kotlin/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
app/src/main/kotlin/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/kotlin/io/homeassistant/companion/android/settings/developer/location/views/LocationTrackingView.kt
app/src/main/kotlin/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
automotive/lint-baseline.xml

Fixing all of the `UseKtx` lint warnings in the `app` module and updating the lint baseline accordingly, as part of #5221.

Fix `UseKtx` lint warnings in `app` module

---

.github/workflows/updateScreenshot.yml

The screenshot update workflow needs to be able to write to a branch so it needs `content: write` permission.

Add missing content write permission for update screenshot workflow
