home-assistant/android

app/build.gradle
app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/res/values-it/strings.xml
app/src/main/res/values-nl-rNL/strings.xml
app/src/main/res/values-pl-rPL/strings.xml
app/src/main/res/values-ro/strings.xml
app/src/main/res/values/strings.xml
build.gradle

Adds the Lokalise SDK as [per their docs](https://docs.lokalise.com/en/articles/1400668-lokalise-android-sdk). Project ID and SDK token are baked in. SDK token is safe to be left in. It's in iOS as well.

Add Lokalise SDK

---

app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt

Remove the onResume because we have a button to retry if needed.
Fixes https://github.com/home-assistant/home-assistant-android/issues/89

Fix double application registration.

---

app/src/main/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
data/src/main/java/io/homeassistant/companion/android/data/integration/UpdateLocationRequest.kt
domain/src/main/java/io/homeassistant/companion/android/domain/integration/UpdateLocation.kt

Send 0 instead of null for vertical accuracy if we don't have real value.
Fixes: https://github.com/home-assistant/home-assistant-android/issues/111

Fix vertical accuracy.

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/util/PermissionManager.kt

ACCESS_BACKGROUND_LOCATION was used from API level 21, changed that to API level 29.
ACCESS_COARSE_LOCATION adds no permissions over ACCESS_FINE_LOCATION, so when using the latter the former has no purpose. Removed ACCESS_COARSE_LOCATION.
> If you are using both NETWORK_PROVIDER and GPS_PROVIDER, then you need to request only the ACCESS_FINE_LOCATION permission, because it includes permission for both providers. Permission for ACCESS_COARSE_LOCATION allows access only to NETWORK_PROVIDER.
https://developer.android.com/guide/topics/location/strategies.html#Permission
The permissions were not consistently used (one class only checked coarse, another all 3). I added a util class to keep the behaviour the same.

Location permission fixes

---

app/src/main/res/layout/fragment_manual_setup.xml
app/src/main/res/values/styles.xml

This PR fixes bug with "no button" in dialog https://github.com/home-assistant/home-assistant-android/issues/90
Basically it's not a good idea to set button style globally for whole theme, it can lead to such issues. Better set it explicitly in layouts.

Fix dialog button color in webview.

---

app/src/main/AndroidManifest.xml

It's look like impossible to keep the state of the webview. let's do it like this for now.
The configuration change should be handle properly for all other activity
c.f https://github.com/home-assistant/home-assistant-android/pull/20
Fixes #28

WebView rotation 

---

app/src/main/res/layout/activity_settings.xml
app/src/main/res/layout/fragment_manual_setup.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

Because `colorControlNormal` was set to white, the underline of a inactive textbox would be white. Making it hard to see where to input text.
Before:
After:
(nice and big screenshots 👎 )

Fix some styling

---

.travis.yml

The version code base on the commit number is not compatible with depth clone (The version code is stuck at 50)
`git clone --depth=50 --branch=master https://github.com/home-assistant/home-assistant-android.git `
https://docs.travis-ci.com/user/customizing-the-build/#git-clone-depth

[CI] Version Code

---

app/src/main/AndroidManifest.xml
app/src/main/res/xml/network_security_config.xml

This PR will bring all devices to the same base security level: https://developer.android.com/training/articles/security-config#base-config
Fixes: https://github.com/home-assistant/home-assistant-android/issues/184
Fixes: https://github.com/home-assistant/home-assistant-android/issues/171
Fixes: https://github.com/home-assistant/home-assistant-android/issues/48

Allow user certs imported into android to be accepted.

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Fixes: https://github.com/home-assistant/home-assistant-android/issues/75
Fixes: https://github.com/home-assistant/home-assistant-android/issues/117
After some testing I didn't see any calls to ```shouldOverrideUrlLoading``` from the application itself.  It appeared that all calls to this method are ones that we should let the OS handle not the webview.

Open urls that are outside the application correctly.

---

.travis/mock-google-services.json
app/build.gradle

This will allow developers to have both a local debug version of app and a production like instance of the application on device at the same time.  Making it easier to test multiple devices.

Add the ability to debug on same device as production application.

---

app/src/main/AndroidManifest.xml

This enables other apps to send a broadcast to the HA app to update the device tracker's location

Enable receiving broadcast to update location

---

.github/ISSUE_TEMPLATE/Bug_report.md

Now that we have some type of documentation we should direct users to check the docs for troubleshooting and configuration :)
Still got more to add but there is some guidance now to help with issues.

Add note to check companion docs

---

app/src/main/java/io/homeassistant/companion/android/widgets/WidgetDynamicFieldAdapter.kt

Fixes #347 by adding `all` as an option for any widget configuration fields that autocomplete with entity IDs.

Added all as an available entity_id for autocompletion

---

data/src/main/java/io/homeassistant/companion/android/data/url/UrlRepositoryImpl.kt

Fixes: https://github.com/home-assistant/home-assistant-android/issues/348

Make sure registration is required.

---

app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidget.kt

This is a potential fix for #365.  The crashing in that issue seems to be caused by the old widget service data string being loaded if the widgets were created pre-1.6.0, when the service data changed from being stored as a plain string that was assigned to `entity_id` to a JSON string that could handle multiple fields, not just `entity_id`.
Instead of just crashing, the widget will fail and display the "red X" negative feedback.

Moved JSON to HashMap cast into try-catch block

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt

Proposed resolution for #372 to add support for a large text box in the notification if the message length exceeds one line.
Reference: https://developer.android.com/training/notify-user/expanded#large-style
Please note: I was unable to figure out how to test notifications from the debug app through Android Studio using my own Firebase config. I'll reach out on Discord, but if anyone on here can point me in the right direction, I'd appreciate it.

Allow expandable notifications for long text messages.

---

app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidget.kt
app/src/main/res/drawable/ic_circle_green_24dp.xml
app/src/main/res/drawable/ic_circle_red_24dp.xml
app/src/main/res/drawable/ic_circle_white_24dp.xml
app/src/main/res/drawable/widget_button_background_green.xml
app/src/main/res/drawable/widget_button_background_red.xml
app/src/main/res/drawable/widget_button_background_white.xml
app/src/main/res/layout/widget_button.xml
app/src/main/res/xml/button_widget_info.xml

I have reworked the appearance of the widgets to not look like app icons.  They're a bit clunkier (imho), but will not be confused with app icons as in #299.  The widgets are also resizeable, though it just increases the size of the icon and doesn't actually add any functionality.  It does mean you can create more "bar"-like icons rather than just square/rectangular buttons.
This also allows for quite a bit more text -- I know the initial design was not great for the amount of text you could put, but this should allow quite a bit more, even without resizing.
Oh, and unlike the last large widget update, this is backwards-compatible and will not break old widgets - when the app updates, they'll just update their shapes.
If it's not obvious, I don't have a ton of graphic design sense, so …

Reworked widget appearance and added resizability.

---

app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/WidgetDynamicFieldAdapter.kt
app/src/main/res/layout/widget_button_configure.xml
app/src/main/res/values/strings.xml

See related conversation in #406.
These try/catch blocks should stop the widget configuration activity from crashing if a custom component with an incorrect `services.yaml` configuration is sent as a response to the integration services request.  Most of the additional changes in the `WidgetDynamicFieldAdapter.kt` file are accounting for the fact that `services` and `entities` might be empty.
In case the services fail to load, an error message is displayed for the user to indicate that services have failed to load.  This message does not show up if entities fail to load.
Also, a new `Add Field` button with associated AlertBox dialog has been created.  It will create a custom field and associated value input. _After you create the field, if you change the text of the service, it will …

Added catch blocks for bad custom component service data responses

---

.github/ISSUE_TEMPLATE/Bug_report.md

Lets start to request a screenshot of the issue so we can quickly determine what's going on.  I think this should be helpful in troubleshooting issues. 
We should also ask users not to delete the template.

Request a screenshot in the issue template and ask not to delete the template

---

app/src/main/java/io/homeassistant/companion/android/widgets/WidgetDynamicFieldAdapter.kt
app/src/main/res/layout/widget_button_configure_dynamic_field.xml

I have implemented the ability for widget service data to contain lists.  Lists are indicated by comma separations, and they ignore whitespace.
Additionally, the service data will parse into proper numbers, strings, and boolean values.  Any valid YAML boolean string is accepted, including on/off and yes/no.
Partial fix for #427.  It allows lists, but not full JSON objects.  I don't know if you want to allow a raw YAML editor mode or not.

Added ability for widget service calls to contain lists

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Activate full screen video : the video will be in full screen (navigation bar and status bar are hidden) even if the application is not in full screen mode
PIP mode : when video is in fullscreen, tap home button to enter PIP mode (like Chrome). PIP window 
PIP window is currently blocked programmatically in aspect ratio 16/9 because I can't find a way to get aspect ratio (or width and height) of video stream
This will solve issues : #447 & #267

Add fullscreen support for videos & PIP mode

---

app/src/main/res/layout/fragment_mobile_app_integration.xml

A bug was mentioned in the `android` channel on the discord by user filmgarage. If the text size set on the phone is too large, it will push the `FINISH` button offscreen when asking for permissions during the initial registration/integration setup.
I have been able to recreate the issue and this PR should fix the issue by making that one section of the integration setup to be scrollable.
Apologies for the commit - it looks like a mess but it's really only changing indentation on the lines, since they're nested now.  Split view shows the changes much sensibly than unified.  I've added a ScrollView wrapping the LinearLayout and changed the LinearLayout's margins to padding.
Bug (this screen is not scrollable):
Fix (this screen is scrollable):

Changed permissions request screen during setup to be scrollable

---

app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidDialogFragment.kt
app/src/main/res/drawable/ic_plus.xml
app/src/main/res/layout/dialog_ssid.xml

Fixes: #498 
Should have thought about this myself mb.
Extra options have been added to add a ssid to the list. a button that will add the ssid, but also as soon as the user clicks on save, the value that has been entered (but is not empty) will be added to the list.
Will now look like this:

Add additional input triggers for adding ssids

---

app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt

As proposed in #529, this PR adds a `battery_state` sensor.
The current `BatterySensor` enables a single `battery_level` sensor which contains different battery data, example:
With this change, there's now two sensors, `battery_level` and `battery_state`, similar to the sensors available when using the iOS application, example:

Add a seperate battery_state sensor

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt

Hi,
I am new here.
Had a quick go on notification channels in android. The solution is quite simple. 
I am checking a cannel parameter in the payload data. 
```
{
message: "something important",
channel: "Important"
}
```
This allows users to define channels in their automation. Then they are able to configure them with different sounds and priorities on their phones.
Still testing it, tough. Sofar I just implemented it and send a few test messages to the android emulator from the firebase console. That however worked already.
I am also still working on a way to remove channels.
Anyway, wanted to let you know I am working on this and looking forward to your feedback.
KR
**Update 1:**
Removing notification channels is working aswell. It requires a message like this:
```
{
message: …
```

Implementing Android notification channels

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenter.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt

Checks if panels are empty. This can be removed after core PR https://github.com/home-assistant/core/pull/34445 is merged and released to stable
Issue Ref https://github.com/home-assistant/android/issues/559#issuecomment-623579395

Disable setting if get_panels is not available or fails

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/res/layout/activity_settings.xml

Was causing crashes and I'm not sure if we need on the settings.  If you have gotten into the application we should assume you are totally authenticated.

Hot fix removing authentication from settings.

---

app/build.gradle.kts
app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidgetConfigureActivity.kt

Fixes #640 
Widget service calls will fail, if a number for any field is used.
Because the GSON parser will parse every integer to a double.
This is especially a problem on the service alarm_control_panel.alarm_disarm
which needs a code to disarm the alarm panel.
So every code will be converted to .0 (eg. 1234 would be 1234.0)
Solution: Use Jackson instead of gson
Jackson parses integers correctly
GSON problem described here:
https://github.com/google/gson/issues/1084

Fix widget service calls with numbers (#640)

---

app/src/full/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt

It was mentioned in https://github.com/home-assistant/android/issues/703#issuecomment-669636182 that we should be using `MINIMUM_ACCURACY` in place of `1` so just switching it back to what was previously expected.  Possibly introduced in #682 at least from what I can tell. This isn't tested but the accuracy of `<= 1` is probably a bit extreme 😆

Correct accuracy for location tracking

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

If a theme is using rgb instead of hex for color, the status wont be colored.
**Example:**
Does work:
```
Google` Dark Theme:
app-header-background-color: #171717
```
Does not work, because color is defined as rgb
```
Google` Dark Theme:
app-header-background-color: rgb(23, 23, 23)
```
**Solution:** 
Try to parse rgb color first. If not possible, parse hex color

Fix statusbar color if theme used rgb color instead of hex color

---

app/src/main/java/io/homeassistant/companion/android/webview/WebView.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

Fixes #433 
Fixes #524
Light theme:
Dark theme:

Fix statusbar not readable when using a light theme (#433)

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

The message is missing in collapsed state of the notification. The message is only shown in expanded state of the notification.
For some devices (at least for oneplus), we need to set also the content text additionally to the big text to show the message also in collapsed notification state.

Fix missing message if notification is collapsed

---

app/src/full/java/io/homeassistant/companion/android/sensors/AllSensorsUpdaterImpl.kt
app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmReceiver.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorComponent.kt
app/src/minimal/java/io/homeassistant/companion/android/sensors/AllSensorsUpdaterImpl.kt

This PR adds a next alarm sensor that utilizes androids [`AlarmManager`](https://developer.android.com/reference/android/app/AlarmManager) and fixes #56
The state is provided in UTC date format so the front end can translate it properly with device class `timestamp`
There are also attributes for local time and time in milliseconds.
The sensor will update anytime the alarm is updated.  The state will become `unavailable` when there is no next alarm.

Initial commit of next alarm sensor

---

app/src/main/res/layout/fragment_mobile_app_integration.xml
app/src/main/res/layout/widget_button_configure.xml
app/src/main/res/layout/widget_static_configure.xml

Fixes: #729 
Dark mode - service call widget
Light mode - service call widget
Dark mode - entity static widget
Light mode - entity static widget
Recommendation per: https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#widgets_and_custom_notification_views

Fix configure widget theme colors

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorComponent.kt
app/src/main/java/io/homeassistant/companion/android/sensors/WifiStateReceiver.kt

Use a broadcast receiver to update the wifi sensor whenever the state has changed. This includes enabling/disabling and network changes.
Adds `is_wifi_on` attribute to the sensor
Fixes: #429

Update wifi sensor on state changes

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/ChargingBroadcastReceiver.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt

Battery level sensor:
- Fix battery level icon so it matches battery state. This will align with the iOS app and fixes #536 
Battery state sensor:
- Add attribute for battery health
- Add intents for battery low and okay. Battery low triggers when the system alerts the user the battery is low. Okay triggers when it recovers from being low
- Add a second update when we receive a battery intent to update the charging state faster. As mentioned in #525 by @yoxjames without the battery changed intent the charging state won't fully update until the next sensor update.  This is because the device is verifying the charging status.  When we switch to battery intent the system sees several state updates which are a bit unnecessary.  Waiting 5 seconds to update the state again ensures we not only …

Battery and next alarm sensor improvements

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothReceiver.kt
app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorComponent.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
app/src/main/java/io/homeassistant/companion/android/util/PermissionManager.kt

Fixes: #452 
- The state of the sensor will be the total number of connected devices including both paired and not paired devices
- Attributes will be `connected paired devices` `connected not paired devices` `paired devices` all provided in a list with the devices mac address. `is bt on` will reflect the state of the bluetooth adapter.
- The sensor will update when bluetooth state changes as well as connection changes are broadcasted.
Connected but not paired devices will include devices like a Mi Band or any other device that pairs with their own app instead of the system itself.  Bluetooth headsets are always paired with the system and so we can see whether they are paired as well as if they are connected.  Bluetooth names are not always given for a device so I have not included them. …

Add Bluetooth sensor

---

app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt

Adds a storage sensor, the state will be the percentage of free space so we align with the iOS app.
Attributes will be as follows:
- Free internal storage in GB
- Total internal storage in GB
- Free external storage in GB
- Total external storage in GB
External storage will reflect `No SD Card` if the device does not have a SD card.
This sensor will only update during the sensor update interval.
Also a fix for the bluetooth sensor to avoid adding duplicate devices to the total count of connected devices, and a proper `unit_of_measurement`. See: https://github.com/home-assistant/android/pull/743#issuecomment-673578475
This also fixes an issue introduced in #752 where sensors were only updating when first registered.

Add storage sensor

---

app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

This PR adds a light sensor whose state will represent the current `lx` the device sees. If this sensor is enabled on a device that does not offer a light sensor the state will remain `unavailable`.
The light sensor will only update with the normal sensor update interval or when any other sensor that updates on a state change.
I did notice one odd issue in that on first launch the sensor may first show `unavailable` before updating to the actual value or we just need to restart the app.  This is a one time thing that I have noticed and once a real value gets reported those are what remain.  I suspect this is because these sensors require event listeners and we need to wait for them to be ready or we are reporting the value too early. This behavior is unlike what we see with the battery …

Add light sensor

---

app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt

Older android devices that did not have a light sensor was crashing, this now fixes the below crash
```
08-14 22:15:22.224 5657-5704/? E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: io.homeassistant.companion.android, PID: 5657
kotlin.TypeCastException: null cannot be cast to non-null type android.hardware.Sensor
at io.homeassistant.companion.android.sensors.LightSensorManager.getLightSensor(LightSensorManager.kt:51)
at io.homeassistant.companion.android.sensors.LightSensorManager.getSensorData(LightSensorManager.kt:42)
at io.homeassistant.companion.android.sensors.SensorManager$DefaultImpls.getEnabledSensorData(SensorManager.kt:71)
at io.homeassistant.companion.android.sensors.LightSensorManager.getEnabledSensorData(LightSensorManager.kt:12)
at …
```

Fix light sensor crash on older devices that don't have one

---

app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt

We were previously just using the default SD card path, unfortunately not all manufacturers use this path and override it.  To get around this we first grab all of the paths we can get, then we iterate through each one and check if its mounted and removable.  Only then will we send the data over on the SD card.
There is one caveat that if the user has a USB flash drive plugged in and a SD card then the reading may not be correct as the order in the array is never the same when it comes to external paths.  I think most users will only have a SD card inserted, I don't foresee having a flash drive plugged in while the phone is in the pocket.
I left some debug statements as well in case we don't capture all cases here so we can at least find a better solution.  Maybe dynamically add …

Attempt to fix SD card path in storage sensor

---

app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt

Fixes: #774 
Turns out not all apps provide the `package` in the AlarmClockInfo intent and thus fails the call.  Lets move `package` to the end of the logic so the state and other attributes populate accordingly.

Change order of package for apps that don't provide it

---

app/build.gradle.kts
app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
buildSrc/src/main/kotlin/Config.kt

With this PR is easier to use emojis in notification. 
Just use the emoji shortcode and it will be parsed to the correct unicode code.
It is also possible to use fitzpatrick modifiers to change the skin tone of an emoji.
| Modifier | Type     |
| :------: | -------- |
|    🏻    | type_1_2 |
|    🏼    | type_3   |
|    🏽    | type_4   |
|    🏾    | type_5   |
|    🏿    | type_6   |
`:santa|type_6:`
Example:
```
message: "Now you can easy use emojis :santa|type_6::frog::sparkling_heart: in your notifications :sunglasses::rocket:"
title: "Easier use of Emojis :grinning::thumbsup:"
```
More on the project site of the library which is used:
https://github.com/vdurmont/emoji-java
Here are a lists of emoji short codes:
https://emojipedia.org/

Add easier way to use of emoji in notifications

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
app/src/main/java/io/homeassistant/companion/android/sensors/StepsSensorManager.kt

This PR adds a steps counter based on the devices hardware.  There is one caveat in that android only resets the steps total when the device is restarted, for now we are providing the raw data.  This sensor also requires explicit permissions for Activity Recognition (just like #784 ) and is disabled until permissions are granted.  Once the sensor is enabled we will ask for permissions on devices that require it.  There is no receiver for this sensor so it will only update when other sensors are triggered or during the sensor update interval.

Add steps counter sensor

---

app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt

Fixes #768 
PR enhance current PhoneStateSensorManager with 2 new sensors SIM_1 and SIM_2. 
Sensors require api level 22 or above. Moreover attributes {"carrier id", "mcc", "mnc", "is opportunistic", "data roaming"} require api 29+
I didn't add OnSubscriptionsChangedListener so sensors will be updated only on regular basis

Enhance PhoneStateSensorManager with carrier information sensors

---

app/src/main/java/io/homeassistant/companion/android/sensors/LastRebootSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

This PR adds a last reboot sensor that is a timestamp of the time the device last booted up.  It was mentioned in #792 that steps are reset only during the last reboot so I thought this might be helpful.  To match the Next Alarm sensor attributes for local time and time in milliseconds are also provided.

Add last reboot sensor

---

app/build.gradle.kts
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/res/drawable/ic_baseline_fullscreen_24.xml
app/src/main/res/drawable/ic_baseline_fullscreen_exit_24.xml
app/src/main/res/drawable/ic_baseline_volume_off_24.xml
app/src/main/res/drawable/ic_baseline_volume_up_24.xml
app/src/main/res/layout/activity_webview.xml
app/src/main/res/layout/exo_playback_control_view.xml
buildSrc/src/main/kotlin/Config.kt

See also https://github.com/home-assistant/frontend/pull/6606
H.265 videos are not supported through Chromium or Webview on Android. We can work around this for Android by using Exoplayer which supports H.265 if the codecs are available on the device. This PR defines an Exoplayer view for the Android client and uses the externalApp interface to help call it from the frontend.

Add Exoplayer view and interface

---

app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/sensors/SensorComponent.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
app/src/minimal/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt

Fixes #758 
PR adds activity recognition sensor. Sensor uses Google Activity Recognition Transition API so it will work only in full flavor.
Possible states for sensor are:
IN_VEHICLE	The device is in a vehicle, such as a car.
ON_BICYCLE	The device is on a bicycle.
ON_FOOT	The device is on a user who is walking or running.
RUNNING	The device is on a user who is running.
STILL	        The device is still (not moving).
TILTING	        The device angle relative to gravity changed significantly.
UNKNOWN	Unable to detect the current activity.
WALKING	The device is on a user who is walking.
Sometimes it gets unknown state. Probably we will need to adjust update interval/confidence after additional testing.

Activity recognition sensor added

---

app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

This PR adds a pressure sensor based on the devices local sensor. Its a raw reading and we only round to the first decimal point since my Pixel 4 XL had 4-5.  Devices that do not have a pressure sensor will show `unavailable`.  This sensor only updates with the sensor update interval.

Add pressure sensor

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

Time for an audio sensor.
The state of the sensor will reflect the ringer mode of the device as we can listen to those changes immediately. Possible states are `normal`, `silent`, `vibrate` and `unknown`. The icon will reflect the state of the device.
Attributes:
- audio mode:  will show whether the device is `ringing`, `in_call` (identical to phone sensor), `in_communication` (using any other app for communication needs that uses audio/video), `normal` and `unknown`. In the next version of Android it will also be able to support whether a call is being screened.
- is headphones: boolean depending if headphones are plugged in, can be either USB headphones, headset or normal wired headphones, this will update immediately when connected/disconnected. Note: I did need to use a deprecated API …

Add audio sensor

---

app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

This PR adds a proximity sensor which will update during the sensor update interval. Based on the [docs](https://developer.android.com/guide/topics/sensors/sensors_position#sensors-pos-prox) not all devices report the actual distance in a real value. 
```
Note: Some proximity sensors return binary values that represent "near" or "far." In this case, the sensor usually reports its maximum range value in the far state and a lesser value in the near state. Typically, the far value is a value > 5 cm, but this can vary from sensor to sensor. You can determine a sensor's maximum range by using the getMaximumRange() method.
```
Some devices, like my Pixel 4 XL only report 2 values either `5` or `0` for `far` or `near` respectively. We account for this difference and the state will be `far` or …

Add proximity sensor

---

app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt

Was testing out the new sensor updates interval on the settings screen and noticed 2 sensors that were not updating unless the others had updates.  Added `latestContext` in the same places and it updated as I expected :) I basically copied what we did in the light sensor for these other hardware sensors.

Use latest context in pressure and proximity sensor

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/sensors/DNDSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

This PR adds a Do Not Disturb sensor that will update its state immediately upon a state change on Android 6.0+ devices. The initial state of the sensor will be `unavailable` for some devices that have never set their device into DND mode (I noticed my fire tablet on Android 5.0 experienced this behavior at first). When google first launched DND mode it was called interruptions and over time they had slowly made changes to its behavior.  This PR attempts to get the state from all supported Android versions, even the ones that don't support all the states like on Android 10.
State value are: `off`, `priority_only`, `total_silence`, `alarms_only` or `unknown` in addition to `unavailable` as mentioned up above.
On my pixel 4 xl the state is either `off` or `priority_only` I could not get it …

Add do not disturb sensor

---

app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

Fixes: #830 
Also fixes a edge case where sometimes we were sending an invalid `gps_accuracy` attribute which was less than 0.
Example error from HA: `Received invalid webhook payload: value must be at least 0 for dictionary value @ data['gps_accuracy']. Got -2147478` and `Received invalid webhook payload: value must be at least 0 for dictionary value @ data['gps_accuracy']. Got -2147471`
During these errors all updates do not come through so when we detect that accuracy >= 0 we will send the real value, otherwise we will send `0` which is the bare minimum that HA will accept

Fix geocoded crash, report expected minimum accuracy for location

---

buildSrc/src/main/kotlin/Config.kt

Noticed some of our dependencies had updates recently so lets bump them.  For the mentioned breaking changes I did a global search and I did not see us using those APIs.  I tested this in the emulator and on my Pixel 4 XL and did not see any real issues.  Most of these are bug fixes which are good things :)
Note: Kotlin and Coroutines have updates but were not bumped since I am not sure if they should be done yet.
* Dagger release notes https://github.com/google/dagger/releases
* Webkit is no longer in RC https://developer.android.com/jetpack/androidx/releases/webkit?hl=en
* work manager update https://developer.android.com/jetpack/androidx/releases/work?hl=en

Bump some app dependencies

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

Fixes: https://github.com/home-assistant/android/issues/861
* We now limit accurate background location requests to once per minute
* Duplicate GPS locations will not cause another update to Home Assistant
* Rather than pass context to every method store it as a variable
* Attempt to ensure that we only register once for location updates

Fix location Spam

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorWorker.kt
app/src/main/res/values/strings.xml

WorkManager offers the ability to use a foreground service to make sure updates become more reliable.  I have been testing this out all day and I can see better updates compared to the play store beta and I do not see any additional battery drain!  This is a temporary notification that will appear in the status bar only during a sensor update. The priority is set to low as that is expected behavior.  This uses its own notification channel so users can make changes if they like.  This is very similar to recent changes done to the Google Phone app where we temporarily see the voice-mail syncing notification. 
The notification:
Production app:
With this change:
Should fix: #848 and hopefully #551 🤞

Use a foreground service for the sensor worker to make updates more reliable

---

app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/StepsSensorManager.kt

A few fixes for the hardware sensors:
* Lets keep track of our listeners and only register once if we have not already registered.  If the app is killed by the user or the system these listeners are already removed, this is to prevent ourselves from registering again if we did not receive a `onSensorChanged` event.
* Adds some logging around when listeners are registered/unregistered. 
* Remove unused `context`

Only register once for hardware sensors

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

PR #863 had an attempt to ensure that we only register once for location updates.
However the variables were placed in the wrong place and the code didn't work. Actually we were re-registering every time because the variable was not static and every time defaulted to false. The PR fixed this.

Register only once for location updates

---

app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/DNDSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/LastRebootSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
app/src/main/java/io/homeassistant/companion/android/sensors/StepsSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt
app/src/minimal/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
app/src/minimal/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
app/src/minimal/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

Fixes: #867 & #856 
Now that we have a lot of sensors lets just allow sensible defaults so we don't overload new users. This really impacts onboarding more than current users.  For now battery sensors will be defaulted to true, location and network sensors will default to true only if given permission during onboarding.  Geocoded location will be false by default to allow it to be a opt-in sensor instead of opt-out (I know this goes against what #853 just did but we did have a specific request for Geocoded to be opt-in instead of opt-out #582 )
Are we ok with the defaults for new users?
One issue I saw which is purely cosmetic is that after enabling one sensor another sensor will briefly show the toggle enabled even though it is not enabled. Going back to the same screen will show the …

Allow sensors to be disabled by default until user enables them

---

app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/sensors/StepsSensorManager.kt

Now that sensors are disabled by default lets completely hide sensors that the device reports it does not have. One thing to note about this is that certain devices don't respect this API and still report they have a device when indeed they do not.  Our current null checks prevent that from being an issue anyways.
I was unable to add this check to the manager itself as we do not get context during this moment, I added this in the fragment to just completely hide it they are disabled anyways.  We can also use this for other sensors in the future that may exist in certain API levels too.  For now this change only impacts hardware sensors since not all devices have them.
Here we can see the emulator does not show the step sensor since it does not exist:
Here is a Fire HD8 that only has a …

Only show sensors that are available for the device

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

Fixes: #878
PR fixes 2 issues with sensors update:
1. We are still updating disabled but previously registered sensors with outdated data from from db.
2. We are calling `update_sensor_states: []` even when we have nothing to update. Like in #878 when all sensors are disabled.

Update sensors bugfix

---

app/src/main/res/values-de/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ko-rKR/strings.xml
app/src/main/res/values-nb-rNO/strings.xml
app/src/main/res/values-nl-rNL/strings.xml
app/src/main/res/values-pl-rPL/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sk/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/strings.xml

Right now the theme selector is broken for some languages,
because the internal options values were translated by mistake.
Marked them as untranslatable.
Hopefully lokalise.com does use the "untranslatable" attribute

Fix theme selector

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/database/sensor/SensorWithAttributes.kt
app/src/main/java/io/homeassistant/companion/android/sensors/PowerSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
app/src/main/res/values/strings.xml

3 new binary sensors, all disabled by default:
* Interactive  - Reflects the interactive state of the device, most typically when the screen turns on and off.  I have also added a broadcast receiver so the state updates immediately. We should look into adding this for the widgets, having them update when the screen turns on would add to the experience 👍 
* Doze mode!! Only available on Android 6.0+, will update immediately upon a state change.  One attribute of the sensor is `ignoring_battery_optimizations` for our application. Tested the state change using: https://developer.android.com/training/monitoring-device-state/doze-standby#testing_doze
* Power Save mode - Updates immediately when the device enters and exits power saving mode.

Add power sensors: Interactive, Doze, Power Save

---

app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

Do not trigger sensors update on alarm and bluetooth events if the corresponding sensor is disabled
Partially fixes #869. I wanted to implement some kind of filter, but this is discussable. So here is the easiest solution to get rid of spam just by disabling the corresponding sensor ;-0

Do not trigger sensors update on alarm and bluetooth events if the corresponding sensor is disabled

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

Fixes #872.
Discard duplicate locations coming within seconds of each other.
Do not discard subsequent regular updates (this is how I want it to work, if you prefer to discard same locations within 15 minutes interval, you are free to change the code).
The reason why algorithm introduced in #863 didn't work, is the race condition. Database was not yet updated at the moment when a duplicate was received. So it discarded regular updates coming some minutes after, but didn't discard real duplicates.
Look at the log, duplicate update coming just 2 ms after the first update gets discarded now.
Subsequent regular updates which we are subscribed for are not discarded because the time-frame for discarding is set to some seconds.
```
09-06 16:52:13.078 22794 22841 D SensorWorker: Updating all …
```

Discard duplicate locations coming within seconds of each other

---

app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
app/src/main/java/io/homeassistant/companion/android/database/sensor/Sensor.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

This PR is another breaking change....sorry about this but we need to cut down on the amount of updates we are sending when there is no new data.  I will need to submit a follow up PR splitting up the non-static attributes so until that point some of the attributes will be slower to update.  If you feel I should add them here to avoid that being a breaking change I can do so but this already feels like a big change in itself so I opted to keep them separate.  So far Audio Sensor (all attributes), Battery State (all attributes but they all update anyways due to plug/unplug events with the exception of `battery_health`), Bluetooth (only for `is_bt_on` the rest update with the state), Storage Sensor (external attributes should become their own sensor however its tough to create on the fly if …

Breaking Change: Only send updates when a state change has been detected

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

Found an issue with #891  with the help of @JBassett since sometimes the call to HA would fail however we still recorded the state change at that moment so we never sent the update back on the next attempt.  Now if we fail we set to `false` and then check it against the detection.

Fix state change when we fail to send data to HA

---

app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt
app/src/main/res/values/strings.xml

Now that #891 has been merged its time to begin part 1 of splitting the attributes.  Starting off with the battery state sensor.
This is a non-breaking change as the attributes have not been removed from the Battery State sensor, that will happen in part 2 at a later point in time.
`is_charging` is now a binary sensor
`charger_type` is now a sensor
`battery_health` is now a sensor
As these are battery sensors they are all enabled by default so users should be able to switch easily over to the new sensors.  They may need to adjust their name/ID if there is a conflict in the entity registry.

Split battery attributes, part 1

---

app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt
app/src/main/res/values-es/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-pl-rPL/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

Another part 1 split from #891 this time we are separating external storage from the storage sensor. The attributes for external storage will follow.  Unfortunately we can't just detect when a SD card is inserted to create the sensor so the behavior will remain the same with the exception that the default state is `0` if no SD card is detected.  So all devices will show both options and its up to the user to enable the external storage sensor.  Everything else remains the same here.

Split up external storage to its own sensor, part 1

---

app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
app/src/main/res/values/strings.xml

Following on from #891 we are splitting up one attribute from the bluetooth sensor.  Part 1 just creating the sensor and leaving the attribute where it is.
`is_bt_on` is now a binary sensor
This is the only attribute that updates outside of the state updates for the existing bluetooth connection sensor.  The other attributes only update when the state of bluetooth connection changes. Paired devices is a list of devices the user has paired to the android system, like wise those devices will only show up under connected paired devices.  Some devices may or may not pair with the system while also pairing with their stand alone app.  These devices are also caught and reported however they are either connected or not connected so they also update with the state regardless of where they are …

Split up bluetooth state into its own sensor, part 1

---

app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt
app/src/main/res/values/strings.xml

The final split after #891 the audio sensor
Now when I first setup this sensor I had originally set the `audio_mode` as the state however we did not have a broadcast receiver for it.  Since we grab the `ringer_mode` using `AudioManager` I switched to the ringer for faster state updates.  Now with this split I have properly named `Ringer Mode`, this does not impact existing users only new installations so should not be an issue.  I think its best we stick to the actual name and apologize for any confusion.
The following attributes are now a `binary_sensor`: `is_headphones` `is_mic_muted` `is_music_active` `is_speakerphone_on`
The following attributes are now a `sensor`: `audio_mode` `volume_level_alarm` `volume_level_call` `volume_level_music` `volume_level_ring`
Left a note for the …

Split up audio attributes, part 1

---

app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
app/src/main/res/values/strings.xml

Fixes: #882 
PR introduces recently requested public ip sensor as a part of NetworkSensorManager. Feature uses https://www.ipify.org/ service api to determine ip address so you should agree using it when enable sensor.
Sensor does not have any onChange event so it will be updated on regular basis and while wifi connection state changed so this should be enough.

Initial public ip sensor commit

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt

Noticed the following crash when I was changing the theme today on one of my devices. This was introduced in #895 sorry about that.
```
2020-09-09 15:18:13.074 19066-19066/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: io.homeassistant.companion.android, PID: 19066
java.lang.IllegalStateException: Fragment SettingsFragment{e5a9a78} (56e2a415-3ef5-4b23-a3d7-f29ccd276b8b)} not attached to a context.
at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
at io.homeassistant.companion.android.settings.SettingsFragment.disableInternalConnection(SettingsFragment.kt:151)
at io.homeassistant.companion.android.settings.SettingsPresenterImpl.handleInternalUrlStatus(SettingsPresenterImpl.kt:145)
at io.homeassistant.companion.android.settings.SettingsPresenterImpl$onCreate$1.invokeSus …
```

Fix settings crash

---

app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt

This manager should've been set to disable by default when I did the sensor split but I did not notice it until the public IP was enabled after the update.  Now things will behave as expected where only wifi connection becomes enabled if the user grants location permissions during onboarding.

Disable network manager by default

---

app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt

After #891 and splitting up some sensors I noticed we were leaving some stale icons because we no longer update them when the state has no changes. Lets now update the icons according to the state change.

Fix some stale icons

---

app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt

Noticed an error in my logs after #927 so fixing the broken icon/state change.
Also the states for charger type do not include `unknown` so I am replacing this with `none` this may be a breaking change for some users.
Fixes: #930

Fix wireless charging icon, replace unknown with none if no charger detected

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

The frontend may need to send additional options to the exoplayer/play_hls interface such as whether to be muted or not: https://github.com/home-assistant/frontend/issues/6857 . With that in mind it is probably better to use a JSONObject instead of a String for the payload.

Change exoplayer/play_hls payload type

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Was helping out a user in Discord who could not see the NFC option and it ended up being his HA version was not on 0.114 or higher.  While inspecting the code I noticed we do not check for NFC hardware when we look to make the option visible.  Now we will do a check with package manager and if successful we will continue with current logic looking at the HA version, if unavailable the option will be hidden.  Tested on my pixel 4 xl that has NFC support as well as 2 amazon tablets that do not have NFC, NFC remains hidden on tablets that don't have the hardware.

Hide NFC if the device reports it has no hardware

---

app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
app/src/main/java/io/homeassistant/companion/android/database/sensor/SensorDao.kt
app/src/main/java/io/homeassistant/companion/android/database/sensor/SensorWithSettings.kt
app/src/main/java/io/homeassistant/companion/android/database/sensor/Setting.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/sensor_detail.xml

This PR allows any sensor to have a custom setting to fit its need.  A table identical to attributes is created and most of the logic around the sensor detail fragment is the same too with the exception that we use a `EditTextPreference` to get the value for the manager to handle.  I chose to keep it separate from attributes since these are really more app specific but I think we can allow the managers to provide them as an attribute if we see the need.
With this PR each sensor manager is responsible for: 
* Updating its `BasicSensor.description` to describe each setting
* Creating the setting in the table and in proper order
* Handling null or unwanted values
* Setting `valueType: "number"` or `valueType: "string"` to handle a dynamic keyboard change
* Setting `valueType: "toggle"` if …

Allow sensors to have custom settings

---

app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt

This should fix the following sentry error, we do the same check for the widget migration:
```
java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetString(CursorWindow.java)
at android.database.CursorWindow.getString(CursorWindow.java:469)
at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
at io.homeassistant.companion.android.database.AppDatabase$Companion$MIGRATION_9_10$1.migrate(AppDatabase.kt:178)
at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:99)
at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:177)
at …
```

Only do the migration if we have rows to migrate

---

app/src/main/java/io/homeassistant/companion/android/sensors/LastRebootSensorManager.kt
app/src/main/res/values/strings.xml

Fixes: #910 
As we noticed that there may be a difference between cell phone and cell tower time lets add an `offset` for the last reboot sensor. The default value is set to `60000` or 1 minute, we can adjust it but I think this should fix the issue for most users.  Making it a setting in case they want to make the value larger or smaller.  The description has been updated to explain the setting and I have also moved some static strings to be constant values.

Add deadband setting for last reboot sensor

---

app/src/main/java/io/homeassistant/companion/android/widgets/StaticWidget.kt

Fixes the following sentry error:
```
kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.Map<*, *>
at io.homeassistant.companion.android.widgets.StaticWidget.resolveTextToShow(StaticWidget.kt:128)
at io.homeassistant.companion.android.widgets.StaticWidget$resolveTextToShow$1.invokeSuspend
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7697)
at java.lang.reflect.Method.invoke(Method.java)
at …
```

Catch the exception when we get null for attributes

---

app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidgetConfigureActivity.kt

Always show search bar for icon dialog independently of the phone language
Fixes: #946

Widget: always show search bar for icon dialog

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
app/src/main/java/io/homeassistant/companion/android/sensors/TrafficStatsManager.kt
app/src/main/res/values/strings.xml

4 new sensors, all disabled by default. Fixes: #950 
* Mobile Rx GB
* Mobile Tx GB
* Total Rx GB
* Total Tx GB
The mobile sensors are only visible on devices that have cellular data, it is safe to assume that all devices will report total data as they are online. I opted not to check if the device has phone capabilities so we can include tablets that have cellular data.  This check is done in `hasSensor` which gets called before the available sensors so we are hiding them properly.  Tested this in the emulator, my pixel 4 xl and a Android 5.1 tablet.
Data is converted from bytes to GB as that is what the world measures in data usage.  Set to 3 decimal places so people don't see 0.00 like I did 😛

Add traffic stat sensors mobile and total data usage for transmitting and receving

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt

I noticed a few issues while testing out the location settings
* If more than 1 sensor used the same setting name we were using the same preference, so now we set the `key` to include the `basicSensor.id`
* Settings were flipping back to default upon the next update (caused by `pref.text = setting.value` which is now only set if `pref.text == null`)
* Summary provider was showing `Not Set` when it was null (as a result of above changes) so if we are null then we default to showing the database value
I wonder if we should consider decreasing the refresh time here to make things look faster?

Fix settings getting overriden by default value, show summary provider if we have it as a result

---

app/src/main/java/io/homeassistant/companion/android/nfc/NFCUtil.kt

Relates to #876
This fixes an issue where on certain devices a dialog was showing up when scanning the NFC tags.
After this change, scanned NFC tags go directly into the home assistant android companion app.
I also tested on an iOS device to ensure the written NFC tag is correctly read.

Write application record to NFC tags.

---

app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt

Fixes the following Sentry error: 
```
java.lang.IllegalStateException: skip must not be null
at io.homeassistant.companion.android.onboarding.integration.MobileAppIntegrationFragment.showError(MobileAppIntegrationFragment.kt:164)
at io.homeassistant.companion.android.onboarding.integration.MobileAppIntegrationPresenterBase$onRegistrationAttempt$1.invokeSuspend(MobileAppIntegrationPresenterBase.kt:40)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:224)
at android.app.ActivityThread.main(ActivityThread.java:7562)
at …
```

Check if skip is not null before attempting to show the error

---

app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
app/src/main/res/values/strings.xml

Fixes: #748 
This implements `valueType: "list-apps"` which creates a MultiSelectListPreference that will list all installed packages on the users device.  Given that many alarm packages are also installed as a system app we cannot ignore them.  This list is then saved to the DB stripping away unnecessary characters to make the iteration easier with a `String.split` we also save the `value` as a String so this made the most sense to me.
I went with an Allow List because users know what app they set their alarm in, there are far too many apps out there (now and in the future) that can make use of the API so an Allow List makes the most sense.
Also given that we have a `package` attribute for users to identify the incorrect state I am listing the package itself instead of a friendly name so …

Add setting for next alarm allow list

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt

Noticed that the version name included the flavor so just stripping that out so users dont get hit with a 404.

Fix changelog link by removing full and minimal reference

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/res/values/strings.xml

This PR adds basic support to show the file chooser prompt when the webview calls for it (i.e. person image upload).
In this PR we are not restricting the file type nor do we show the camera, this is for basic file upload support.  Person image upload already looks for images and will reject any invalid selected file.
We will need to think about a better way to do things like #974 while still allowing the user to upload any file.  This consideration is important in case any add-on or future feature calls for more than just images.  Maybe we should consider looking at the URL to determine what type of file chooser to show?

Add file chooser to webview

---

app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/DNDSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/LastRebootSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/PowerSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/StepsSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/TrafficStatsManager.kt
app/src/minimal/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
app/src/minimal/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
app/src/minimal/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

PR adds feature to define requirred permission for single sensor rather than whole sensor manager.
It is required for new call numbers sensor. Also publicIp sensor does not require any permission.

Split permissions per sensor enity

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt

* On sensor details screen refresh data every 5 seconds instead of 10 to make it update faster for settings
* After user changes any setting we force the sensor to do an update immediately in `onPreferenceChangeListener` so the next refresh pulls correct data as sometimes we have to wait for the second update for the change to really take place.
These should make the page feel like it updates a lot faster than what it does today since at times there can be a 10-20 second delay depending on when you change a setting and when the last update ran.

Speed up sensor details screen

---

app/src/main/AndroidManifest.xml

Noticed an edge case where the sensor worker does not run if the app was updated and never restarted.  This PR adds a receiver for when the app is updated to start the sensor worker just like we do when the device has been booted and unlocked.

Start sensor worker when the app is updated

---

app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
app/src/main/res/values/strings.xml

* Add a destructive migration fallback so the app never ends in a state where the database will crash due to a missing migration, I know it may never happen but good to have a fallback just in case
* Replace `cursor.count > 0` with `cursor.moveToFirst()` which is a boolean that will return `true` only IF the cursor can move to the first row
* Place entire migration in try and catch block to catch any errors in the migration
* Keep track if migration was successful in order to move the data after we recreate the table
* Perform clean migration in case of bad data
* Creates high priority notification informing user of the database recreation so they can redo sensors and widgets
* Fires an event to HA to help automate the situation better
Should fix the following sentry errors:
This error …

Add migration fallback, improve crash handling

---

app/src/main/java/io/homeassistant/companion/android/sensors/KeyguardSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
app/src/main/res/values/strings.xml

Add sensors that represent the state from [Keyguard API](https://developer.android.com/reference/android/app/KeyguardManager)
* Device locked (requires API 22 or higher)
* Device secure (requires API 23 or higher)
* Keyguard locked
* Keyguard secure
Although they all sound the same they are actually a tiny bit different, and some update along with the screen on/off receivers.

Add keyguard sensors

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/sensors.xml

* Adds a new preference category for managing all sensors
* Tells the user who many total available sensors they have on that device
* Add a toggle to enable or disable all sensors (will remain `off` if all sensors are not enabled)
* Upon enabling requests all required permissions (any that are not granted results in those sensors not being enabled)
* Once enabled a list of all sensors with custom settings are listed to help raise visibility

Allow all sensors to be enabled or disabled at once

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

After re-reading [the documentation](https://developer.android.com/training/location/change-location-settings.html) around the fused location provider I saw this note:
> The priority of PRIORITY_HIGH_ACCURACY, combined with the ACCESS_FINE_LOCATION permission setting that you've defined in the app manifest, and a fast update interval of 5000 milliseconds (5 seconds), causes the fused location provider to return location updates that are accurate to within a few feet. This approach is appropriate for mapping apps that display the location in real time.
This is an attempt to request the updates quicker in an effort to get more accurate results.  This _should_ cause GPS to attempt a lock.

Attempt to request accurate location quicker.

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
app/src/main/res/values/strings.xml

This PR will speak a notification instead of posting it to the device.  For the first release we are not setting the locale so it will default to what the device has as a default.  As we already have commands that use the `message` we are going to use that here and the `title` is where the actual spoken text will reside.  In case of a blank title we have a default, in case of an error we will send a toast.
Example automation:
```
message: TTS
title: I am speaking
```
Fixes: #912 
Docs: https://github.com/home-assistant/companion.home-assistant/pull/351

Allow notifications to do TTS

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
app/src/full/java/io/homeassistant/companion/android/notifications/NotificationDeleteReceiver.kt
app/src/full/java/io/homeassistant/companion/android/notifications/ServiceComponent.kt
app/src/main/res/values/strings.xml

Fixes: #418 
When a notification is dismissed we will send `mobile_app_notification_dismissed` event along with the `message` as part of the event data.
Example data:
```
{
"event_type": "mobile_app_notification_dismissed",
"data": {
"message": "test",
"device_id": "DEVICE_ID"
},
"origin": "REMOTE",
"time_fired": "2020-10-06T05:36:12.864583+00:00",
"context": {
"id": "ID",
"parent_id": null,
"user_id": "USER_ID"
}
}
```
Docs: https://github.com/home-assistant/companion.home-assistant/pull/352

Send an event when a notification is dismissed

---

.github/stale.yml

We have been sitting at around a 100 issues for a while now.  While going through several of the older ones I released that they had been fixed.  By enabling stale bot we will be able to more easily see what is still affecting people.
Config stolen from core.

Enable Stale Bot

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenter.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
app/src/main/res/drawable/ic_notifications.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationService.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/CheckRateLimits.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/RateLimitRequest.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/RateLimitResponse.kt

Fixes: #531 
This PR adds a preference that contains the notification rate limit data.  This preference is only visible if the user is on the `full` flavor and if the call was successful.  One thing to note for some reason the call does not return any data when we first visit settings, its only subsequent visits does the call save.
Docs: https://github.com/home-assistant/companion.home-assistant/pull/353

Add notification rate limit info to settings

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt

Noticed that the Sensor Managers and Basic Sensors were out of order as we were sorting by the ID instead of the actual string.

Fix sorting of sensors on the manage sensor screen

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
app/src/main/AndroidManifest.xml

Fixes: #436 
This PR introduces a new device command `message: command_dnd` which takes a mandatory parameter set by the user as the `title`.  The only accepted titles are that which is of the DND sensor state: `off` `alarms_only` `priority_only` `total_silence` anything else that is provided results in the notification posting as normal. As DND control is only supported in Android 6+ if a command is sent to an unsupported device that device will also receive the notification as normal.
This type of command requires a special permission which we can only launch an activity.  This activity is launched when the user sends the first command if the permission has not already been granted.  Upon the next command received everything will process as usual.
Examples:
```
message: command_dnd …
```

Allow control of DND via notification

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/controls/ControlsComponent.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSliderControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
app/src/main/java/io/homeassistant/companion/android/nfc/TagReaderActivity.kt
app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/TrafficStatsManager.kt
buildSrc/src/main/kotlin/Config.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationService.kt

This is adding the foundation for power menu actions.  We currently support light, switch, input_boolean, and input_number domains.  More domains will be coming soon.

Initial Support for Android 11 Power Menu Actions

---

app/src/full/AndroidManifest.xml

After #1027 was merged I updated the production version where sentry is enabled.  The app immediately crashed and it turns out to be a known issue: https://github.com/getsentry/sentry-java/issues/904
Using the suggested workaround until Sentry fixes the issue: https://github.com/getsentry/sentry-java/issues/904#issuecomment-702033313
I can confirm this works on my physical device as I was able to reproduce the crash.

Fix sentry crash after target SDK change

---

README.md
common/build.gradle.kts
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
gradle.properties

This PR takes on @JBassett's [suggestion](https://github.com/home-assistant/android/pull/1010#pullrequestreview-502453327) to extract PUSH_URL in a properties file.
The same is done for RATE_LIMIT_URL.

Allow overriding PUSH_URL and RATE_LIMIT_URL in local.properties

---

app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/DNDSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/PowerSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

We had recently started to skip certain intents if the corresponding sensor was not enabled.  Lets add more to this list.  Pretty much any intent except for ones that are tied to more than one sensor are now skipped.  This should account for the majority of the events that are unwanted especially screen on/off.
Suppressing lint here is ok because we only register for receivers if the android version matches the intent.

More skippable intents

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

This PR introduces `message: command_ringer_mode` where the title can be set to `normal` `vibrate` or `silent` just like the ringer mode sensor states.  Any `title` that does not meet these will result in the notification posting on the device as usual.  Successful commands result in the appropriate ringer mode change
Devices that support DND changes must also have DND permissions as ringer mode states can also toggle DND states so we need them.  The permission check is handled like `command_dnd` where we request it on the first command if we don't have it.  For the other devices we will process the command as usual.
Docs: https://github.com/home-assistant/companion.home-assistant/pull/361
Depending if the other FCM PR gets accepted I may add this command to it to save the amount of PR's

Allow control of device ringer mode via notification

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

Was doing some more testing around TTS notifications.  Came to find out that by default they use the `MUSIC_STREAM` which means that they will ignore the devices ringer mode but not the volume level.  By using the `ALARM_STREAM` we use a separate volume level so it can bypass if media volume is off.
Example:
```
message: TTS
title: I am speaking
data:
channel: alarm_stream
```
`channel: alarm_stream` is only used to override the default stream.

Allow TTS notifications to use the alarm stream

---

app/build.gradle.kts

This PR allows to customize the path to the keystore used to sign release packages with a `KEYSTORE_PATH` environment variable.
I used to have a symlink from `app/release_keystore.keystore` to my local keystore file, but every once in a while, I commit that symlink into git...
Another option would be to add `app/release_keystore.keystore` to `.gitignore` but adding an environment variable fits well with the other aleady available variables (`KEYSTORE_PASSWORD`, `KEYSTORE_ALIAS` and `KEYSTORE_ALIAS_PASSWORD`).

Allow customizing keystore path with KEYSTORE_PATH environment variable

---

app/src/main/res/values-night/styles.xml
app/src/main/res/values/styles.xml

Without this change, floating popups like copy/paste actions that show when long clicking on text are masked, e.g. in the application configuration:
Light mode | Dark mode
------------ | -------------
With this change, text can be selected and copy/pasted properly:
Light mode | Dark mode
------------ | -------------
FWIW, I debugged this using [Android Studio's Layout Inspector](https://developer.android.com/studio/debug/layout-inspector) to understand what was masking the content of the dialog.
As noted [here](https://stackoverflow.com/questions/18346920/change-the-background-color-of-a-pop-up-dialog#comment92796502_37422953), [changing `android:background`](https://github.com/home-assistant/android/pull/1043/files#diff-1e051f2b0330608e92eba8edc616403ec7bdaa76e29ce0cfb794700686715925L42) …

Fix alert dialog background for light and dark modes

---

buildSrc/src/main/kotlin/Config.kt
settings.gradle.kts

To discover insights in to which dependencies are pulling in older versions of kotlin.
For example:
https://scans.gradle.com/s/l3vm2auntthac/dependencies?dependencies=reflect&expandAll&focusedDependency=WzAsMyw3MzcsWzAsMCxbMV1dXQ&focusedDependencyIncomingPathsToggled=W1sxLDAsMV1d&focusedDependencyView=versions

Add Gradle Build Scans

---

app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt

Noticed that the sliders were missing the numbers and we just needed to set `formatString` as expected instead of leaving it blank.  The button now updates as you would expect for the tile.  I have also converted `brightness` to a percentage to match Google Assistant.  I noticed not all lights have `brightness_pct` attribute so I figured this was good enough.
Mapped a few device classes to device types so we get some nice icons for everything. 
Set the status text to match the state.

Power Menu button enhancements

---

app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationPresenterImpl.kt

We should only hijack the navigation to a url if it starts with our auth callback. It is legit to redirect if the auth callback is in the url.
This _should_ (but I have not tested it yet) fix the Android app going back to the server selection screen if it hits Home Assistant while it's still serving the landing page.

Only check redirect uri if it starts with AUTH_CALLBACK

---

app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSliderControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/SceneControl.kt

Calls the webview with correct context and correct intent flag to properly load.  For now we load the default home page but hopefully soon we can load something more meaningful. 
Currently we get the below error when the black screen loads:
```
2020-10-21 14:19:38.441 17810-17810/? E/SurfaceView: Exception configuring surface
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
at android.app.ContextImpl.startActivity(ContextImpl.java:1018)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:425)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:425)
at android.window.TaskEmbedder.startActivity(TaskEmbedder.java:357)
at …
```

Fix power menu long press activity so it doesnt load black screen

---

app/src/main/java/io/homeassistant/companion/android/controls/DefaultSliderControl.kt

Should fix the following sentry error:
```
java.lang.IllegalArgumentException: stepValue=0,000000 <= 0
at android.service.controls.templates.RangeTemplate.validate(RangeTemplate.java:184)
at android.service.controls.templates.RangeTemplate.<init>(RangeTemplate.java:83)
at io.homeassistant.companion.android.controls.DefaultSliderControl$Companion.createControl(DefaultSliderControl.kt:37)
at io.homeassistant.companion.android.controls.HaControlsProviderService$createPublisherForAllAvailable$1$1.invokeSuspend(HaControlsProviderService.kt:85)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at …
```

Ensure that we default to expected values to meet requirements for android power menu

---

app/src/main/java/io/homeassistant/companion/android/database/sensor/SensorDao.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorWorker.kt

Creates a query to send us a count of enabled sensors, only then do we promote and run sensor updates.  Maybe there is a better way to do this but this will at least prevent the service from being promoted to the foreground when a user disables all sensors.

Only promote sensor worker to foreground service if there is at least 1 sensor enabled

---

app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
app/src/main/res/values/strings.xml

I figure we should give some type of response to the user when a widget fails upon an update so a toast seems best.  Like for example if the device does not have data or HA server is down. I can remove it from the button widget but I figure since we show a toast for all the others we might as well show a toast here too.
Also for entity state I have switched the call from `getEntities` to `getEntity` for the entity state widget.
This is only for when you tap to update a widget and that call fails for whatever reason.

Show a toast failure when widgets fail to get or send data

---

app/src/main/java/io/homeassistant/companion/android/database/widget/TemplateWidgetDao.kt
app/src/main/java/io/homeassistant/companion/android/settings/widgets/ManageWidgetsSettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/manage_widgets.xml

As we don't have labels for template widgets I opted to show the first 100 characters for the title.  Should be enough to show users which template it is.

Make template widgets editable

---

app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt

With this it's possible to start scripts via the new power menu controls and enable/disable automations.
I'm using the SceneControl for scripts because it's exactly what i need, but it might be an idea to rename that class to something like "RoutineControl"

Add automations and scripts to power menu controls

---

app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt

According to [the docs](https://www.home-assistant.io/integrations/sensor/) device class battery is something that represents `Percentage of battery that is left.`
This doesn't match the battery_state sensor. Therefore, this PR removes it

Remove device_class from battery state sensor

---

app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LockControl.kt
app/src/main/res/values/strings.xml

- Add locks to power menu
- Only show range slider for lights when lights actually support brightness (via supported_features)

Locks and better lights in power menu

---

buildSrc/src/main/kotlin/Config.kt

https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.3.9
https://github.com/google/dagger/releases/tag/dagger-2.29.1
https://github.com/material-components/material-components-android/releases/tag/1.2.1
https://developers.google.com/android/guides/releases#september_23_2020
https://firebase.google.com/support/release-notes/android#latest_sdk_versions
https://github.com/square/retrofit/blob/master/CHANGELOG.md#version-290-2020-05-20
https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-490
Looks like some of these resolve crashes too.  Ran this build for several hours and did not notice any issues and did not see any breaking changes for things we use.

Bump dependencies

---

app/src/main/java/io/homeassistant/companion/android/settings/widgets/ManageWidgetsSettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
app/src/main/res/layout/widget_button_configure.xml
app/src/main/res/layout/widget_media_controls_configure.xml
app/src/main/res/layout/widget_static_configure.xml
app/src/main/res/layout/widget_template_configure.xml
app/src/main/res/values/strings.xml

Fixes: #1108 
Adds a delete button when editing a widget for cases when widgets are lost such as when we refactor them or the launcher lost them. Since this is irreversible there will be an alert dialog to make sure this is what the user wants.

Allow deleting widgets from the manage widget screen in case the widget was lost

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt

Entity state, media player and template widgets will update when the screen comes on with this PR.  If those widgets don't exist the event is skipped.  This should help make them look more up to date when you grab your phone to check them quickly.

Update widgets with the screen on intent so they appear to be more up to date

---

app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt

Fixes: #1120 
No need to perform an update if we can't connect.

Skip widget updates if the network connection is not active

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

Noticed that if a user just disables background location but leaves zone tracking on we don't remove updates.  We only did the removal if both sensors were turned off.  With this change a user can leave zone tracking on without needing background location enabled to only get geofencing updates based on zones

Remove location request if background is disabled by itself

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SleepAsAndroidManager.kt
app/src/main/res/values/strings.xml

Fixes: #483 
Integrates with the Intent API from sleep as android: https://docs.sleep.urbandroid.org/devs/intent_api.html#events-emitted-by-sleep
If the app is not installed then the sensors will not show up and the user won't be able to enable them.  The intents that we register to are only for sleep as android so they do not cause any harm if the app is not installed or if the user decides not to enable them.  We will also only process these events from sleep as android as they are received, all other updates are ignored.
I picked Sleep tracking and Lullaby to be binary sensors as I can reliably turn them on and off.  All other events are one time based and are better suited for a sensor of its own.

Add sleep as android sensors for users that have the app

---

app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt

Fixes #1127 and adds some exception handling so the app doesn't crash if we get more unexpected instances.  I have an air purifier here as well and tested the change against `on` `off` and `unavailable` states.

Add exception handling and correct null values in fan control for power menu

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
app/src/main/res/values/strings.xml

Fixes: #1020 
We must set `message: command_broadcast_intent` and the `title` must contain the Action and `channel` must contain the Package name.
Format:
```
message: command_broadcast_intent
title: ACTION
data:
channel: PACKAGE_NAME
```
Tested with sleep as android API: https://docs.sleep.urbandroid.org/devs/intent_api.html#action-intents-to-control-sleep
Example:
```
message: command_broadcast_intent
title: com.urbandroid.sleep.alarmclock.STOP_SLEEP_TRACK
data:
channel: com.urbandroid.sleep
```
If `title` or `channel` is not provided we post the notification to the device as normal, otherwise if there is another failure we show a toast.
Docs: https://github.com/home-assistant/companion.home-assistant/pull/376
FCM: pending

Allow sending broadcast intents to other apps via notification

---

buildSrc/src/main/kotlin/Config.kt

The icon for the service button widget was coming in as light theme when the device theme was set to dark, reverting the library bump fixes the issue.  Seems the new library version introduced an issue where the night theme color is not being read properly.
Ref: https://discord.com/channels/330944238910963714/562408603345092636/772138149395824661

Revert material bump as it introduced a dark theme issue with the widgets

---

app/src/main/res/layout/widget_button.xml
buildSrc/src/main/kotlin/Config.kt

Fixes: #1132 which was actually introduced in #1083 and attempted to get fixed in #1130 
Dark theme:
Light theme:
Brings back the material library bump too.  Thanks for the good spot @JBassett !

Fixes button widget dark icon, really this time

---

app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt

Noticed the following sentry error so this is an attempt to solve it.  There should not be any blobs in the sensor database.
```
android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=8
at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:986)
at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:858)
at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
at …
```

Catch all cursor errors so migration can proceed

---

app/build.gradle.kts
app/src/full/AndroidManifest.xml
app/src/full/java/io/homeassistant/companion/android/CrashHandling.kt
app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/minimal/java/io/homeassistant/companion/android/CrashHandling.kt
buildSrc/src/main/kotlin/Config.kt

This should remove exceptions about being unable to connect home assistant instances.  This will greatly reduce the number of events in Sentry and help with diagnosing issues.
N/A
N/A
Sentry: ANDROID-1EB, ANDROID-1E6, ANDROID-1EK, ANDROID-1F3, etc

Sentry Filtering

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

Sometimes a user may find their device might be speaking too low due to the volume level.  Using TTS we are able to detect when a stream is going to start and when it has been completed.  We can then change the volume level and set it to the max and restore it once completed.  This can be useful for a user who wants an important notification spoken as loud as possible.
N/A
Documentation: home-assistant/companion.home-assistant#381
Example:
```
- service: notify.mobile_app_<your_device_id_here>
data:
title: "The house is on fire and the cat's stuck in the dryer!"
message: TTS
data:
ttl: 0
priority: high
channel: alarm_stream_max
```

Allow TTS notification to speak as loud as possible using alarm stream, then restore volume

---

app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt

Fixes the following error that appears during a database migration failure where the event to home assistant fails to send successfully.
```
RuntimeException
Can't toast on a thread that has not called Looper.prepare()
```
N/A
Documentation: home-assistant/companion.home-assistant#N/A

Fix toast message during database migration failure

---

app/src/main/java/io/homeassistant/companion/android/database/sensor/SensorWithAttributes.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt

The next alarm time sensors (and possibly others) has an attribute which is of type Long. This was being stored in the database with a value_type of "float" and converted to a Float when passed to Home Assistant, causing the value to change due to floating point conversion issues.
This PR changes the SensorManager to store Long attributes with a value_type of "long", which are converted to Long when passed to Home Assistant.

Fix for sensor attributes of data type Long

---

app/src/full/java/io/homeassistant/companion/android/CrashHandling.kt
app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
app/src/main/res/drawable/ic_android_debug_bridge.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
app/src/minimal/java/io/homeassistant/companion/android/CrashHandling.kt
common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepositoryImpl.kt

Allow users the option to opt out of Crash Reporting.
Fixes: https://github.com/home-assistant/android/issues/1140
N/A

Add ability to opt out of crash reporting.

---

app/src/main/AndroidManifest.xml

I realized after helping out #1155 that we are using the wrong intent 🙈 
This: https://developer.android.com/reference/android/content/Intent#ACTION_PACKAGE_REPLACED
Should've been: https://developer.android.com/reference/android/content/Intent#ACTION_MY_PACKAGE_REPLACED
n/a
Documentation: home-assistant/companion.home-assistant# n/a

Switch to proper package replaced intent to detect when the app upgraded

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

Hopefully fixes: #1159 by setting some additional audio attributes for the alarm, tested on my Pixel 4 XL and the alarm stream continues to work as expected.
The only other thing I can think of is the default alarm URI is coming in as blank, but I would suspect a crash report if that were the case.
N/A
Documentation: home-assistant/companion.home-assistant#N/A

Add some additional alarm stream parameters

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

Fixes: #1166 as we cannot detect when the sound is being made for the notification. The user will need to control the level, they should be able to restore it using the cleared event we have.  They can store the previous value by using the provided volume sensors.
We need to request DND permissions here because changing the volume level will have a direct impact on DND and ringer mode.  As there are 4 different audio streams we will use `channel` to dictate which audio stream is to be adjusted.  `title` will be used for the actual volume level.  If the volume level is higher than the streams maximum then we will use the maximum, anything below 0 will default to 0 for that stream.  We will support alarm, music, notification and ring streams.  Any invalid value will result in the …

Allow control of volume level for audio streams

---

app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSliderControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LockControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/SceneControl.kt
app/src/main/res/values/strings.xml

When you have a lot of entities it can become a bit difficult to determine what is what.  As we do not get `area` lets start to categorize by the `domain` so its easier to add more controls.  Especially useful if you use the same name for an entity against different domains like I do 😛  Using `setZone` only impacts the adding control part.
Before
After
Documentation: home-assistant/companion.home-assistant#N/A

Show the domain when adding power menu controls

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
app/src/main/java/io/homeassistant/companion/android/sensors/TimeZoneManager.kt
app/src/main/res/values/strings.xml

Fixes: #1174 by providing a sensor that represents the current time zone. There are also a few attributes to help describe the time zone such as if its currently observing day light savings time, the ID of the zone (similar to that of HA), the short name and also if the time zone will ever observe day light savings.
Documentation: home-assistant/companion.home-assistant#392

Add a time zone sensor

---

app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationDetailFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationHistoryFragment.kt

Fixes: #1165 by rendering `message` in HTML.  We will not render `data` to keep it as raw data.
Documentation: home-assistant/companion.home-assistant# n/a

Render HTML for the message in notification history

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

This PR wraps handling of chronometer notifications in a try/catch to prevent the app from crashing when invalid data is received.
This PR is pretty basic and only prevents a hard crash. There's definitely room for improvement regarding usability
It might make sense to mark invalid notifications in the notification log or something like that

Fix app crash on invalid chronometer notification data

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

This is an attempt to fix #979 from the app side.  I was looking at the WebView docs and it seems that webview itself can be paused and resumed as needed.  I think this might help out.  This is what I did for testing.
1. Ran `master` before these changes.  Loaded up a live view picture entity card, verified the camera was streaming.  Swiped to home screen.  Waited 10 minutes, came back to webview and it seemed like the video continued.  Performed a similar test with more info panel and saw the same results.
2. Ran these changes and did the same test.  After waiting 10 minutes and coming back to webview I noticed the whole page reloaded, I think this was caused by the connection restoring?  When I did the test on the more info popup I noticed that when I came back the video was paused at …

Pause and resume the webview as needed

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

Fixes the following sentry error by ensuring we properly set `null` when we can:
```
java.lang.NumberFormatException: For input string: "00:00:05"
at java.lang.Long.parseLong(Long.java:594)
at java.lang.Long.parseLong(Long.java:636)
at io.homeassistant.companion.android.notifications.MessagingService.handleTimeout(MessagingService.kt:668)
at io.homeassistant.companion.android.notifications.MessagingService.sendNotification(MessagingService.kt:415)
at io.homeassistant.companion.android.notifications.MessagingService$onMessageReceived$$inlined$let$lambda$6.invokeSuspend(MessagingService.kt:210)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
at …
```

Switch to toLongOrNull for timeout to prevent user error

---

app/src/main/java/io/homeassistant/companion/android/sensors/AppSensorManager.kt
app/src/main/res/values/strings.xml

Adds some app data sensors that represent how much data was sent and received by the app.  Stats reset on each device reboot.  These are similar to the Traffic Stat sensors we have however as these are more diagnostic sensors I felt they fit better under App Sensors.  As my app data usage is very low I opted for 4 decimal places.
There is also a sensor that represents how much memory has been used by the app and how much is available to it.
Documentation: home-assistant/companion.home-assistant#397

Add sensors for app data and memory usage

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

This reverts commit d99daecae511b1d3bf7eea3ac5644ef0cf266236.
Lets revert as its causing reconnection delays.

Revert "Pause and resume the webview as needed (#1194)"

---

app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt

Fixes: #1217 
We now set the climate range based on `min_temp` and `max_temp`.  For the current value we first try `temperature` then try `current_temperature` and then default to 0 if both are not provided.  My zwave thermostat does not have a `temperature` attribute when it is `off` but `current_temperature` is always there.  We also do a sanity check to ensure current value is always in the range to prevent loading errors.
N/A
Documentation: home-assistant/companion.home-assistant# N/A

Use min and max temp for climate range in power menu

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

We had a user on discord point out that when they had Google Maps or Wave navigation engaged all updates seemed to get skipped by the future check.  The user pointed out the consistency was within the second.  I ran a similar test and found all my updates to be within 2 seconds.   This PR adds a 5 second buffer for only the future time check to avoid skipping valid updates.
n/a
https://discord.com/channels/330944238910963714/562408603345092636/786337770305093652

Add a small buffer for the location future check to avoid skipping valid updates

---

app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt

The other day my internet went out and I started to see a lot of toast errors.  The error was expected since I could not connect to my HA instance.  The problem is the screen on intent can become a bit excessive with these errors and if you know your HA instance is down it can become annoying.  Lets only show the toast error when the user taps on the widget to update or its part of the normal update.  This way we provide feedback when they ask for an update and we can't give them instead of when we proactively update the widgets.
I also had a friend hit a similar issue where he was on a flight and was connected to wifi without full data access so the errors still became excessive then.
n/a
Tested on my dev instance by creating …

Don't show toast error for screen on intent as it can be excessive

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
app/src/main/AndroidManifest.xml

Adding a command to turn bluetooth on or off
```
message: command_bluetooth
title: turn_off
```
`title` can also be `turn_on` anything else the notification will post as normal
n/a
Documentation: home-assistant/companion.home-assistant#409
FCM PR: https://github.com/home-assistant/mobile-apps-fcm-push/pull/29

Add a command to control bluetooh

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt

Was looking at the Sentry logs and came across the following error, we probably want to make sure all supported versions have some location permission to check here:
```
kotlin.UninitializedPropertyAccessException: lateinit property permissionsToCheck has not been initialized
at io.homeassistant.companion.android.settings.SettingsFragment.onDisplayPreferenceDialog(SettingsFragment.kt:259)
at androidx.preference.PreferenceManager.showDialog(PreferenceManager.java:537)
at androidx.preference.DialogPreference.onClick(DialogPreference.java:257)
at androidx.preference.Preference.performClick(Preference.java:1182)
at androidx.preference.Preference.performClick(Preference.java:1166)
at androidx.preference.Preference$1.onClick(Preference.java:181)
at android.view.View.performClick(View.java:5204) …
```

Fix uninitialized property access error

---

app/src/main/java/io/homeassistant/companion/android/util/NotificationManagerExtensions.kt

Fixes the following sentry error by preventing the case entirely:
``` 
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
at io.homeassistant.companion.android.util.NotificationManagerExtensionsKt.cancelGroupIfNeeded(NotificationManagerExtensions.kt:56)
at io.homeassistant.companion.android.util.NotificationManagerExtensionsKt.cancel(NotificationManagerExtensions.kt:66)
at io.homeassistant.companion.android.notifications.MessagingService.clearNotification(MessagingService.kt:229)
at io.homeassistant.companion.android.notifications.MessagingService.onMessageReceived(MessagingService.kt:144)
at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(com.google.firebase:firebase-messaging@@20.3.0:74)
at …
```

Fix null pointer for canceling group

---

common/src/main/java/io/homeassistant/companion/android/common/data/wifi/WifiHelperImpl.kt

This fixes another sentry error that I saw, this may even already be addressed by the previous PR where we check location permission. I think it may be good to ensure we don't hit this error at all.  So instead of failing due to a null value we just ensure we always send a string even if its `null`
```
java.lang.NullPointerException: wifiManager.connectionInfo must not be null
at io.homeassistant.companion.android.common.data.wifi.WifiHelperImpl.getWifiSsid(WifiHelperImpl.kt:10)
at io.homeassistant.companion.android.common.data.url.UrlRepositoryImpl.isInternal(UrlRepositoryImpl.kt:108)
at io.homeassistant.companion.android.common.data.url.UrlRepositoryImpl.getUrl(UrlRepositoryImpl.kt:76)
at io.homeassistant.companion.android.common.data.url.UrlRepository$DefaultImpls.getUrl$default(UrlRepo …
```

Always send connection info as a string even if null

---

app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
common/src/main/java/io/homeassistant/companion/android/common/data/HomeAssistantRetrofit.kt

This is an attempt to fix #653 by adding a `callTimeout`
By default OKHTTP sets this timeout to `0` which means the call will forever try to complete.  I am not sure if 30 seconds is too long or if it should be 10 seconds however, I opted for 30 seconds to match the `readTimeout`.  There are other timeouts that we do not set like `writeTimeout` and `connectTimeout` that both default to 10 seconds.
https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/
https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/call-timeout/
I have also added some debug logs in case it does not fix the issue so we can at least look at the logs to get a better idea of why it keeps spinning.
Testing involved making a few different calls to HA server like loading App …

Add a call timeout and some debug logs

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt

Fixes: #653 for real this time
The actual issue was that the screen was turning off before the widget was reset.  This would cause the widget to get stuck in a state where the user can no longer interact with it.  Now we reset back to normal when the screen turns on to ensure it can be interacted with.
Going forward we should probably make sure all widgets get some type of needed update with the screen on intent to either update the state or set things back to normal.

Fix button widget view getting stuck when screen turns off

---

.github/ISSUE_TEMPLATE/Bug_report.md

Now that we have a proper guide to getting the crash logs lets make sure to link to this guide in the issue template
Ref: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs

Add link to getting crash logs in issue template

---

app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt

Fixes: #805 but instead of markdown we will render as HTML to better match the rest of the application like HTML formatted notifications.  The formatting will also render as a user builds the template so they can see what it can look like. 
Example: 
```
This is a <b><span style="color: red">HTML</span></b> <i>text</i><br><br>This is a text after a <h1>new</h1> <h3>line</h3>
```
Documentation: home-assistant/companion.home-assistant#419

Allow template widgets to render as HTML for formatting

---

app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt

We had a couple bug reports come in from what seems like integrations that don't respect the expected `brightness` range per the HA docs: https://developers.home-assistant.io/docs/core/entity/light as it should be between 0 and 255.  We do a conversion from brightness to brightness percentage so the slider works properly from 0-100% so its important the values are always as we expect.
See: #1179 and #1258 
We are going to put a sanity check in that always ensures current value is greater than or equal to min value and less than or equal to max value.
If we find any integration with an issue from this change then I think there is a bug with that integration in particular.

Ensure power menu light control values stays within range

---

common/src/main/java/io/homeassistant/companion/android/common/data/url/UrlRepositoryImpl.kt

This is an attempt to fix: #1078 I believe the issue here is that we still try to use the remote URL first even if we are local for when we decide to loop through all URL's.  We now change this logic to only include the local URL first, if we are connected to a home SSID. 
I can't really test the exact scenario in the issue but when I do a test in my own setup where locally I'm under `https` (which we know fails) I do see local being tried before remote.  The call in my case still ends up being successful despite failing locally first so we at least attempt the local URL if we can.  This change only impacts calls that make use of `getApiUrls` which doesn't impact the WebView but does impact calls such as NFC, sensors etc..

Try internal URL first if we can

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/sensors/AppSensorManager.kt
app/src/main/res/values/strings.xml

Fixes: #1288 by providing a sensor that can show the various states the app can be in.
Documentation: home-assistant/companion.home-assistant#427

Add app sensor to determine its importance

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/util/DisabledLocationHandler.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/res/values/strings.xml

Fixes #1311 
The message popup for disabled location can be quite annoying. With this PR the popup is replaced by a permanent notification message. 
Casual users will be still notified about the disabled location.
But power users can disabled the notification channel to ignore the warning.

Location disabled notification

---

app/src/main/java/io/homeassistant/companion/android/sensors/MobileDataManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values/strings.xml

New mobile data sensors to check whether some mobile data settings are enabled or not.
Documentation: home-assistant/companion.home-assistant#435
Used to remind family members to switch of mobile data when they are back home to save costs for prepaid data subscription.

Add mobile data sensors

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Fixes: #1294 
As per the steps given in a comment the issue only happens when the session timeout is changed from the default.  We now do an evaluation during `onResume` to set `unlocked = true` if the timeout has not been reached yet.

Fix frozen webview when lock app timeout is changed from the default

---

app/src/full/AndroidManifest.xml
app/src/full/java/io/homeassistant/companion/android/location/HighAccuracyLocationReceiver.kt
app/src/full/java/io/homeassistant/companion/android/location/HighAccuracyLocationService.kt
app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/bluetooth/BluetoothDevice.kt
app/src/main/java/io/homeassistant/companion/android/bluetooth/BluetoothUtils.kt
app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
app/src/main/res/values/strings.xml

Fixes #973
PR for mobile-apps-fcm-push https://github.com/home-assistant/mobile-apps-fcm-push/pull/35
To get accurate device tracking location results in home assistant you needed to use 3rd party apps like GPSLogger or Owntracks. To automate these apps (ex. Start GPSLogger when connected to car bluetooth) you needed also a 3rd party app like MacroDroid or Tasker. To top it off. Those apps are hard to configure for casual users.
So, to get accurate location results you need to install and configure two 3rd party apps for every smartphone in the household.
With this PR i tried to integrate those features into the companion app.
Everything is controlled in the background location sensor settings. 
If you enable _High accuracy mode_ the high accuracy location service will be started with the …

High accuracy mode for background location sensor

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

Adds support for `extras` by allowing users to enter them under the `group` parameter.  We will split the extras by a comma `,` and then split the key/values by the colon `:`.  This will allow users to add/remove fields dynamically in an automation using templates.
Example to turn on a sleep as android alarm labeled as `work`:
```
message: command_broadcast_intent
title: "com.urbandroid.sleep.alarmclock.ALARM_STATE_CHANGE"
data:
channel: "com.urbandroid.sleep"
group: "alarm_label:work,alarm_enabled:true"
```
There is a potential for users to discover bugs with other applications here as well lol.
Documentation: home-assistant/companion.home-assistant#440
One important thing to note is that all value are sent as a string from firebase so this PR does work around that. …

Allow extras with broadcast intent command

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Performs a sensor update when the webview is paused and resumed.  This will help keep the app importance sensor up to date to properly reflect if the app is in active use or not.  Also kinda nice to update sensors whenever we are back in the app.  Quick way to trigger an update.
https://github.com/home-assistant/android/issues/1288#issuecomment-764627490

Update sensors when the app is resumed or in the background

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
app/src/main/res/values/strings.xml

Fixes: #1326 
A new command `command_activity` is added to handle this specific intent as we need to do several things to properly launch an activity.  The `title` must contain the URI to send to the app.  The `channel` must be used to set the package name of where the intent needs to be sent to. The `group` must be set the intending action string. We handle generating the URI and launching the activity with the intent.
Example:
```
message: command_activity
title: "geo:0,0?q=1600+Amphitheatre+Parkway%2C+CA"
data:
channel: "com.google.android.apps.maps"
group: "android.intent.action.VIEW"
```
```
message: command_activity
title: "google.navigation:q=arbys"
data:
channel: "com.google.android.apps.maps"
group: "android.intent.action.VIEW"
```
Documentation: …

Add a notification command to launch an activity

---

app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
app/src/main/java/io/homeassistant/companion/android/controls/VacuumControl.kt
app/src/main/res/values/strings.xml

Fixes: #1318 
There are 2 state models for vacuums, this PR takes care of both of them.  There are some vacuums that only support on/off and others that support multiple states.  I have chosen to add `start` and `return_to_base`  as those are the closest to `turn_on` and `turn_off`
Documentation: home-assistant/companion.home-assistant#444

Power menu vacuum

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
app/src/main/AndroidManifest.xml

After reviewing more of Googles examples: https://developer.android.com/guide/components/intents-common found a few places to improve.
* `channel` is no longer required.  If we have it we will use it, otherwise we will make a best effort which can allow the user to pick more than 1 app or use the default app.  We will still post the notification if a package is not found.
* `title` is no longer required as not all activities require a URI
* `tag` is used for all the extras, extras now convert to integer as required for setting an alarm/timer.
* `SET_ALARM` permission is added so we can set timers on a device per the examples in the link
* `subject` will be used to specify the MIME type which may be required in some cases like composing a SMS
Documentation: …

Improvements to command activity

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

If `extras` are part of a received intent we will add all the extras as event data, otherwise we will send the intent action like we currently do.
Example of an intent with extra data (tested from: http://www.mibandnotify.com/help/tasker_send_intent.php):
```
{
"event_type": "android.intent_received",
"data": {
"value": 8693,
"intent": "com.mc.miband.stepsGot",
"device_id": "DEVICE_ID"
},
"origin": "REMOTE",
"time_fired": "2021-01-30T07:59:48.081242+00:00",
"context": {
"id": "ID",
"parent_id": null,
"user_id": "USER_ID"
}
}
```
Documentation: home-assistant/companion.home-assistant#447

Add extras to the event data when we receive intents

---

app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationFragment.kt

Probably fixes: #931 
I've been noticing that in our app the login screen was still white while using chrome was dark to match the system theme, even windows had it right.  Discovered that we actually spun up a new webview instance so added the ThemesManager logic here.

Apply system theme during onboarding authentication

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
app/src/main/AndroidManifest.xml

Switch `tag` and `group` parameters to match `command_broadcast_intent`.  This means `tag` is now required instead of `group`.
We had a user point out in discord that activities would not launch in the background.  Turns out we need to grant another permission to do so.  Without proper permission user will see a log like the following:
```
2021-01-31 10:23:57.341 24224-24695/io.homeassistant.companion.android.debug D/MessagingService: Processing device command
2021-01-31 10:23:57.345 1587-2148/? I/ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=google.navigation:q=arbys flg=0x10000000 pkg=com.google.android.apps.maps cmp=com.google.android.apps.maps/com.google.android.maps.MapsActivity} from uid 10419
2021-01-31 10:23:57.345 1587-1638/? D/EventSequenceValidator: inc …
```

Breaking Change: Switch tag and group parameters, also request overlay permission to start activity in background

---

app/src/main/java/io/homeassistant/companion/android/util/NotificationManagerExtensions.kt

Fixes #1346
If a notification is the last one in a group, which is generated by the system and not the user, the notification cannot be canceled.
This is because the group which should be canceled has no groupId.
To fix this issue, we just cancel the last notification in the group. That way, the system removes the group by itself.

Fix cancel notification if last notification in group

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

We noticed in Discord that Sleep as Android was correctly enabling an alarm when we set the extra value to `true` but `false` was misbehaving.  We originally thought it might've been a bug in SAA but they mentioned the values needed to be in boolean.  Yup they do need to be so this PR fixes that.

Convert extras value to boolean when needed

---

app/src/main/java/io/homeassistant/companion/android/bluetooth/BluetoothUtils.kt

Should fix following sentry exception:
```java
java.lang.NullPointerException: btDev.name must not be null
at io.homeassistant.companion.android.bluetooth.BluetoothUtils.getBluetoothDevices(BluetoothUtils.kt:27)
at io.homeassistant.companion.android.sensors.SensorDetailFragment.refreshSensorData(SensorDetailFragment.kt:275)
at io.homeassistant.companion.android.sensors.SensorDetailFragment.updateSensorEntity(SensorDetailFragment.kt:323)
at io.homeassistant.companion.android.sensors.SensorDetailFragment.onCreatePreferences(SensorDetailFragment.kt:71)
at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280) …
```

Fix bluetooth sentry exception

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

Fixes: #1195 by using a special command as we need to launch a new instance of webview.  We also require the same permission from `command_activity` so we will use the same method to grant the permission before processing the command. `title` is optional and without it we just load webview, if provided we add it as the path.
Example:
```
message: command_webview
title: /lovelace/settings
```
Documentation: home-assistant/companion.home-assistant#454
FCM: https://github.com/home-assistant/mobile-apps-fcm-push/pull/37

Add a notification command to open webview to any path

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Fixes: #569 
We now accept `app://` and `intent://` prefix.  When testing in a desktop a blank tab opens so nothing harmful appears to happen elsewhere.
When we detect that a link starts with `app://` we will grab the android package and attempt to launch it, if the package does not exist we take the user to the play store (app or website)
When we detect the link starts with `intent://` we will parse the Uri with the intent scheme and attempt to launch the activity, if the app is not found we will also take the user to the play store (app or website)
Examples using lovelace weblink entity card type:
This example will launch Twitter if it is installed on the device, otherwise it will open the Google Play store app or website.
```yaml
- type: weblink
name: Twitter
url: …
```

Override certain URLs to launch an app or intent scheme

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
app/src/full/java/io/homeassistant/companion/android/notifications/NotificationAction.kt
app/src/full/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt
app/src/main/res/values/strings.xml

When an `action` is set to `REPLY` we will create a reply button in the action.  The user can then enter any text and receive the reply back in the same event that we send for `mobile_app_notification_action`.  It made the most sense to attach this to our actions because android only allows [3 actions](https://developer.android.com/training/notify-user/build-notification#Actions) and reply can be one of them.  Given that a reply is an actionable button and we have to get the data back to HA might as well send it back in the event.
Example service call data:
```
message: reply test
data:
actions:
- action: REPLY
title: reply
```
Example event data:
```
{
"event_type": "mobile_app_notification_action",
"data": {
"message": "reply test",
"action_1_title": "reply",
"action_1_key": "REPLY", …
```

Allow users to add reply button to actionable notification

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Fixes: #1091 by making a best effort to match the existing constants, vibration effects to what it sounds like for iOS.  For a first release these may be ok? We can always adjust as we see fit since we now handle each `hapticType` sent.  It was a bit difficult to map some of these 🙈 lol
https://developer.android.com/reference/android/view/HapticFeedbackConstants#constants_1
https://developer.android.com/reference/android/os/VibrationEffect.html#constants_1
https://developers.home-assistant.io/docs/frontend/external-bus/#trigger-haptic-haptic
Documentation: home-assistant/companion.home-assistant#456
Tested with: https://github.com/custom-cards/button-card
Example lovelace config
```
- type: "custom:button-card"
color_type: card
color: rgb(223, 255, 97)
icon: mdi:volume-minus
tap_action: …
```

Add haptic/vibration support from the external bus in webview

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/res/values/strings.xml
common/src/main/java/io/homeassistant/companion/android/common/data/url/UrlRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/url/UrlRepositoryImpl.kt
common/src/test/java/io/homeassistant/companion/android/common/data/HomeAssistantMockService.kt

Fixes: #678 by switching between internal and external URL when the user clicks on refresh.  If the user does not have an internal connection URL then we will default to the external one always.  Also updated the error message to let users to know that refreshing more than one does something 😄 

Try the other URL when refreshing webview on a connection error

---

app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

The purpose of this change is to map the DPAD_DOWN key which is commonly found on remote controls to the TAB key.  This will allow users to login to the HA app using the remote control.  This is an unsupported experience and therefore we will not be publishing for Android TV.  This is for sideloading only and we will not be doing any support here as we are only sending the TAB key.  Both the android app and HA frontend are not optimized for the TV experience however, there are some users who just want to sideload the app and use it in its current form.  At least with this change a user can do some VERY basic navigation (only one direction forward).  Users should not expect bugs to be fixed until someone comes and adds support for DPAD keys in the front end (if that were to be accepted). …

Map dpad down key to tab key in webviews

---

app/src/full/java/io/homeassistant/companion/android/location/HighAccuracyLocationService.kt

Again i had the high accuracy notification  still visible, even though the high accuracy mode was disabled due to not connected BT devices. This happens not every time and i can't reproduce this.
This PR hopefully fixes the problem.
Some points which may fix this issue
* Make notification objects static
* Use ServiceCompat for stopForeground
* Additionally call cancel to remove notification

Fix left notification when high accuracy mode was disabled

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

Fixes issue reported in the forums where the event was not firing since the data was not as expected:
https://community.home-assistant.io/t/android-intents-sending-receiving-list-starting-activities-too/276192/10?u=dshokouhi

Convert intent extras to a string so they can be sent without error

---

app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
app/src/main/res/values/strings.xml

Fixes: #1383 
Uses the new Sleep API to make 2 new sensors.  1 for sleep confidence and the other for sleep segment. These sensors are for the full version only as it relies on Google services.
https://developers.google.com/location-context/sleep
Documentation: home-assistant/companion.home-assistant#467

Add new sleep sensors for new sleep API

---

app/src/main/java/io/homeassistant/companion/android/authenticator/Authenticator.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Fixes: #1402 by allowing retry attempts until the android system deems it necessary to stop.  We will only close the activity if the user cancels the action by tapping outside of the biometric prompt.  As we are using device credentials we cannot supply a negative button.
User is no longer required to press "Confirm" upon successful authentication
Added some debug logging in case we encounter any issues.
Unable to take screenshots of biometric prompt changes but they can be viewed here: https://developer.android.com/training/sign-in/biometric-auth#no-explicit-user-action

Allow retry attempts for biometric prompt, enable skip confirmation for faster access

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

Fixes the following sentry error that I was able to reproduce:
```
java.lang.IllegalArgumentException: Cannot delete default channel
at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
at android.os.Parcel.createException(Parcel.java:2357)
at android.os.Parcel.readException(Parcel.java:2340)
at android.os.Parcel.readException(Parcel.java:2282)
at android.app.INotificationManager$Stub$Proxy.deleteNotificationChannel(INotificationManager.java:4004)
at android.app.NotificationManager.deleteNotificationChannel(NotificationManager.java:906)
at androidx.core.app.NotificationManagerCompat.deleteNotificationChannel(NotificationManagerCompat.java:341)
at io.homeassistant.companion.android.notifications.MessagingService.removeNotificationChannel(MessagingService.kt:305)
at …
```

Prevent crash when removing default channel

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
app/src/main/java/io/homeassistant/companion/android/database/widget/StaticWidgetDao.kt
app/src/main/java/io/homeassistant/companion/android/database/widget/StaticWidgetEntity.kt
app/src/main/java/io/homeassistant/companion/android/database/widget/TemplateWidgetDao.kt
app/src/main/java/io/homeassistant/companion/android/database/widget/TemplateWidgetEntity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt

Fixes: #1410 by saving the last update text for entity state and template widgets so we can default to retrieving them when things fail.
I have tested this change by first checking out master, setting up one of each widget type that is updated and then upgrading to this branch to ensure no crashes.

Save widget states so we can restore them when calls fail

---

app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryFragment.kt
app/src/main/res/values/strings.xml

Fixes the following sentry crash by catching the error and displaying a toast message to see if the device has a browser.  As I understand it when we use `Intent.ACTION_VIEW` with a properly parsed URI the default browser should load, at least it does on my Pixel.  I thought about trying to resolve the activity but since we require WebView or Chrome you would think the user would have the app? I am open to any other ideas on how to handle this error.  I personally did not expect to see this.
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://www.home-assistant.io flg=0x10000000 }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1776)
at …
```

Catch crash when activity can't start due to missing default browser

---

app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt

Fixes below sentry error since some devices appear to like to send `NaN` instead of just reporting the sensor does not exist.
```
java.lang.NumberFormatException: For input string: "NaN"
at java.lang.Long.parseLong(Long.java:443)
at java.lang.Long.parseLong(Long.java:485)
at java.math.BigDecimal.<init>(BigDecimal.java:344)
at java.math.BigDecimal.<init>(BigDecimal.java:425)
at io.homeassistant.companion.android.sensors.PressureSensorManager.onSensorChanged(PressureSensorManager.kt:82)
at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:701)
at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
at android.os.MessageQueue.next(MessageQueue.java:323)
at android.os.Looper.loop(Looper.java:136)
at …
```

Prevent converting NaN values in pressure sensor

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

Another attempt to fix #1186 
This time we switch from `getDefaultUri()` to `getActualDefaultUri()` as the first option returns a symbolic link where as the latter does not.
https://developer.android.com/reference/android/media/RingtoneManager#getDefaultUri(int)
`Rather than returning the actual ringtone's sound Uri, this will return the symbolic Uri which will resolved to the actual sound when played.`
https://developer.android.com/reference/android/media/RingtoneManager#getActualDefaultRingtoneUri(android.content.Context,%20int)
`This will give the actual sound Uri, instead of using this, most clients can use System#DEFAULT_RINGTONE_URI.`
Then if the alarm ringtone URI comes in as `null` we will then default to the normal ringtone type.  A stackoverflow thread said its possible the …

Switch to a different method to get alarm ringtone, default to normal ringtone if alarm is null

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
app/src/main/java/io/homeassistant/companion/android/database/sensor/SensorDao.kt
app/src/main/java/io/homeassistant/companion/android/database/sensor/Setting.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt

This PR adds the possibility to enable the high accuracy mode, when entering a specific zone (Requires an enabled location zone sensor).
In addition, the user can specify a radius in meters that extends the selected zone by the specified radius. This way the zone is entered X meters before the real zone.
To accomplish that, an internal expanded zone from the original zone is created (ex. `zone.home_expanded`) which adds the defined radius to the original radius. If the radius (Default 0) is 0, then the original zone is used.
If the user decides to use an expanded zone, ONLY the expanded zone, minus the original zone will be used (The blue zone in the image below).
**Example:**
Arriving zone.home
User enters `zone.home_expanded` (1000m radius around `zone.home`) -> High accuracy mode …

Enable high accuracy mode when entering zone

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Fixes: #1433 by ensuring blurView is set to false when unlocked and resumed

Ensure blurView is off when we are unlocked with a timeout

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
app/src/main/java/io/homeassistant/companion/android/util/NotificationManagerExtensions.kt

This PR adds additional logging for MessagingService and NotificationManagerExtensions.
Maybe these logs help to solve the issue https://github.com/home-assistant/android/issues/1435

Add additional logging for MessagingService and NotificationManagerExtensions

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

Fixes #272
Fixes #1365
This PR tries to get the statusbar color from the webview HTML directly. If the color can be parsed, then this color will be used as statusbar color. If not, then the HA backend theme color will be used like before.

Fix statusbar color

---

app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSliderControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LockControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/SceneControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/VacuumControl.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

With the help of @chriss158 for getting the javascript right I was finally able to trigger the more info pop-up when we come from the power menu
https://photos.app.goo.gl/JPUURtcLrpLoSSAZA

Open the more info panel for entity when long pressed in android 11 power menu

---

app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt

This sensor can cause a lot of confusion with users because we have no control over what the next scheduled alarm is. Adding some debug logs so users can follow the update logic to understand when they are skipped due to the allow list.

Add some debug logs for next alarm sensor update logic

---

app/src/main/java/io/homeassistant/companion/android/util/NotificationManagerExtensions.kt

Fixes #1435
This PR fixes a problem that some notifications are not cleared. Reason: Android does group notifications at a certain timeout or at a certain notification count of a app. If the notifications are grouped by this auto group (internal named "ranked_group"), then the last notification of this group cannot be canceled.
Solution: Cancel the notification itself, if the notification is in the auto group. Android should cancel the auto group summary notification by itself.
To reproduce this issue, i needed to create four notifications.
```yaml
service: notify.mobile_app_xxx
data:
title: Wow
message: wowow1
data:
tag: wow1
service: notify.mobile_app_xxx
data:
title: Wow
message: wowow2
data:
tag: wow2
service: notify.mobile_app_xxx
data:
title: Wow
message: wowow3
data:
tag: wow3 …
```

Fix clear_notification if notifications are in the auto group

---

app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt
app/src/main/res/values/strings.xml

Fixes: #1440 
Google provides the battery temperature in tenths of a degree Centigrade so we divide by 10 and send the data, a users HA instance will convert if needed.
https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/BatteryService.java#106
Documentation: home-assistant/companion.home-assistant#481

Add battery temperature sensor

---

common/src/main/java/io/homeassistant/companion/android/common/data/url/UrlRepositoryImpl.kt

Was helping out a user in Discord and it was difficult to tell when and why different URL's were being used.  This adds some debug logs so we can look at the decision being made for what we are sending.
Example logs:
```
2021-03-25 13:39:06.181 13234-13234/io.homeassistant.companion.android.debug D/UrlRepository: Using internal URL
2021-03-25 13:39:06.186 13234-13234/io.homeassistant.companion.android.debug D/UrlRepository: localUrl is: true and usesInternalSsid is: true
2021-03-25 13:39:15.766 13234-13234/io.homeassistant.companion.android.debug D/UrlRepository: localUrl is: false and usesInternalSsid is: false
2021-03-25 13:39:15.766 13234-13234/io.homeassistant.companion.android.debug D/UrlRepository: Using external URL
2021-03-25 13:39:15.767 …
```

Add debug logs to troubleshoot URL switching

---

app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/ServiceFields.kt

We had a user on the forums hit the custom component error message when they did not have any custom components.  It turns out that the user had some `script` setup that did not have `description` under the `fields` and looking at the code we can see its indeed optional.
https://github.com/home-assistant/core/blob/dev/homeassistant/components/script/__init__.py#L70
https://community.home-assistant.io/t/unable-to-configure-a-widget/293451
So now the field is left optional, doesn't seem to cause any issues and I was able to reproduce the issue to confirm the fix. The field still loads and the example is shown.
Reproduced with the following `script`:
```
wakeup:
alias: "Wake Up"
icon: "mdi:party-popper"
description: "Turns on the bedroom lights and then the living room lights after a delay" …
```

Make service field description optional to match core integrations for service call widget

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationException.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt

This PR improves the api call for getZones()
- Implement simple zones cache in the `SensorDetailFragment`, because otherwise the api is called every 5 seconds (Cache will be reset on entering sensor detail screen).
- Fixes double update of data in the `SensorDetailFragment` on entering sensor detail screen
- Fixes following crash by try/catch getZones():
```
io.homeassistant.companion.android.common.data.integration.IntegrationException: null
at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.getZones(IntegrationRepositoryImpl.kt:285)
at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$getZones$1.invokeSuspend
at …
```

Improve getZones api call 

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
app/src/main/AndroidManifest.xml

Fixes: #1272 by introducing a new command to turn on the screen
```
message: command_screen_on
```
Documentation: home-assistant/companion.home-assistant#484
FCM Repo: https://github.com/home-assistant/mobile-apps-fcm-push/pull/42
Also removes a duplicate permission that I noticed during `lint`

Add new notification command to turn on device screen

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsComponent.kt
app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/manage_shortcuts.xml

Hopefully this branch is ok, I see a couple commits from the previous PR but the changes depicted are only from the branch as i have rebased the branch off master.
This now adds a shortcut type list preference so users can pick between Lovelace (default) and an Entity.  For the Entity we grab a list of all entities and let the user select the one they want. We will add in the proper logic to switch between entity and lovelace type along with providing the proper data in shortcut.
This also fixes a bug that I found where the Pin Shortcut is enabled but non-functional as the entire `setOnPreferenceClickListener` was incorrectly wrapped in a condition that would only succeed if the variables were met.  Now we do one check in `onResume` and let the rest of the preference listeners update the …

Shortcuts entity

---

app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt

I noticed that the media player widget image never updated, turns out it never would because the URL we were using was never correct, now we load the actual URL and if on debug build we will print more logging errors to help out.
```
2021-04-05 16:28:49.534 12796-12796/io.homeassistant.companion.android.debug D/Picasso: Main        errored      [R0]+336ms Unrecognized type of request: Request{/api/media_player_proxy/media_player.den_shield_tv?token=TOKEN&cache=CACHE
```
I also had to add a hard resize as my shield is in 4k and the image was too big, so sticking to 1920x1080 as it will load. 
```
2021-04-05 16:16:54.628 7665-7665/io.homeassistant.companion.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
Process: io.homeassistant.companion.android.debug, PID: 7665 …
```

Fix retrieval of media player image in widget

---

app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/util/NotificationActionContentHandler.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/manage_shortcuts.xml

Let users select and use material icons for shortcut icons
Also fixes #1472 

Shortcut icon

---

app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt

Found a bug when attempting to edit a saved shortcut. When switching between a saved lovelace shortcut to entity the shortcut type was not being set properly and the field type is not as expected. Now setting the data to be correct for editing.

Fix shortcut editing when selecting from pinned list

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt

Enable all toggle defaults to false and only got set when a user would toggle it. If the app were updated the variable would reset and never get set again. So once we set the variable, if it evaluates to `true` we will revalidate the menu options.

Set menu options when we evaluate enable all toggle

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt

Fixes the following sentry error by only setting the state if the option exists
```
java.lang.NullPointerException: checkable must not be null
at io.homeassistant.companion.android.sensors.SensorsSettingsFragment.onPrepareOptionsMenu(SensorsSettingsFragment.kt:234)
at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:2821)
at androidx.fragment.app.FragmentManager.dispatchPrepareOptionsMenu(FragmentManager.java:2715)
at androidx.fragment.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:399)
at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:488)
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPrepar …
```

Fix null pointer on checkable menu option

---

app/src/full/java/io/homeassistant/companion/android/location/HighAccuracyLocationService.kt

This PR fixes a crash when the high accuracy service is destroy, but the service is not yet started. Also when the `fusedLocationProviderClient` is null we do not need to remove the location updates anyway.
```
kotlin.UninitializedPropertyAccessException: lateinit property fusedLocationProviderClient has not been initialized
at io.homeassistant.companion.android.location.HighAccuracyLocationService.onDestroy(HighAccuracyLocationService.kt:166)
at android.app.ActivityThread.handleStopService(ActivityThread.java:4449)
at android.app.ActivityThread.access$2100(ActivityThread.java:257)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:233)
at …
```

Fix crash for high accuracy service

---

app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt
app/src/main/res/values/arrays.xml
app/src/main/res/xml/manage_shortcuts.xml

Was looking into the causes of the below sentry error and @chriss158 had pointed out we may be providing a blank list so ensuring the list is always present. As the list is static we will just load it in the XML.  Also cleaning up some old unused arrays.
```
java.lang.IllegalStateException: ListPreference requires an entries array and an entryValues array.
at androidx.preference.ListPreferenceDialogFragmentCompat.onCreate(ListPreferenceDialogFragmentCompat.java:53)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:2685)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
at …
```

Set proper values and defaults for shortcut type list

---

app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt
app/src/main/res/values/strings.xml

When we add a shortcut the UI will update/respond however it does not do this when we update a shortcut. So anytime we update a shortcut we will post a toast message for some visual confirmation.
Thanks for the recommendation @chriss158 :)

Add a toast message for visual feedback when updating a shortcut

---

app/src/main/java/io/homeassistant/companion/android/themes/ThemesManager.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
app/src/main/res/values/strings.xml

Fixes #1496
This PR improves the themes and the coloring of the status bar/navigation bar.
* **Add "Follow Home Assistant" theme setting**
Default theme option is now "Follow Home Assistant". This one will color the status bar/navigation bar like the `app-header-background-color` variable of the set HA Theme. This is exactly the same behavior as we have now, except that the option is now called "Follow Home Assistant" instead of "Follow System-Settings".
I decided to do this, because with the option "Follow system-settings" you can choose if the statusbar ALWAYS colors according to the system, no matter which color the HA theme has (See #1496). Also at the moment it is so, that the theme setting only colors the settings of the app. That is kind of pointless. So, now you can also color the …

Improve Themes

---

app/src/main/java/io/homeassistant/companion/android/settings/log/LogFragment.kt

This PR fixes following crash:
```
java.lang.IllegalStateException: Fragment LogFragment{734e4b0} (9ea226fd-a7ad-4317-9781-eaeb4bf03e50) id=0x7f0a0090} did not return a View from onCreateView() or this was called before onCreateView().
at androidx.fragment.app.Fragment.requireView(Fragment.java:1781)
at io.homeassistant.companion.android.settings.log.LogFragment$refreshLog$1.invokeSuspend(LogFragment.kt:83)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7660)
at …
```

Fix log fragment crash

---

app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt

Found the below sentry error and it seems like the resize attempt is not good enough as per this note from Google
```
The total Bitmap memory used by the RemoteViews object cannot exceed that required to fill the screen 1.5 times, ie. (screen width x screen height x 4 x 1.5) bytes.
```
So a fire tablet that has much smaller screen resolution than a pixel 4 will still have an error like:
```
java.lang.IllegalArgumentException: RemoteViews for widget update exceeds maximum bitmap memory usage (used: 8294400, max: 6912000)
at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
at android.os.Parcel.createException(Parcel.java:2369)
at android.os.Parcel.readException(Parcel.java:2352)
at android.os.Parcel.readException(Parcel.java:2294)
at …
```

Reduce image size to account for varying screen resolutions in media player widget

---

app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt

Noticed the following sentry error and came to realize that the button widget configure activity was crashing on launch in the latest beta, this might have been caused by one of the dependency updates.  The error was pretty specific in this case and since I was able to reproduce the issue I can also confirm the fix.
```
java.lang.IllegalStateException: Method addObserver must be called on the main thread
at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
at androidx.fragment.app.Fragment.initLifecycle(Fragment.java:496)
at androidx.fragment.app.Fragment.<init>(Fragment.java:476)
at androidx.fragment.app.DialogFragment.<init>(DialogFragment.java:138)
at …
```

Fix button widget icon crash

---

app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LockControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/VacuumControl.kt

Adds the `unavailable` state to power menu and changes behavior of tile appearance so this state is not `checked`

Add unavailable state to power menu

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

This PR fixes the the dark statusbar when using HA default light theme.
Looks like calculating the luminance of the color for checking the darkness of a color is better. I tested several theme colors. Looking good.

Fix default theme statusbar color

---

app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
app/src/main/res/values/strings.xml

Fixes: #1475 
So this is an interesting sensor because the media sessions require either a system only permission, which we won't qualify for, or the notification listener (aka notification manager).  This listener is required for getting the data so this sensor is like a notification sensor but only for media sessions.
For the state I had a few considerations. First keeping the state as the total count of sessions won't work because when the user has 1 session (primary) none of the attributes will update.  Keeping the state as just the playback state of the primary controller wont update the attributes often either especially when playing for a long period of time. Things like artist and title won't change so almost whats the point in including them.  We will first attempt to set the …

Add a media session sensor

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt

Fixes: #1515 by clearing out the preference value if we detect a mismatch between the entries and the selected value.
Tested this by creating a zone, adding it to high accuracy, removing the zone and coming back to sensor setting screen.

Clear out preference value if the value does not match the provided entry list

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
buildSrc/src/main/kotlin/Config.kt

Set windowed height using video height
Set resizeMode to match hls.js behavior
Also remove loadControl
Bump ExoPlayer version to 2.13.3 (https://github.com/google/ExoPlayer/compare/r2.13.2...r2.13.3)
The ExoPlayer scaling behavior may have changed with the refactoring in #1448. This PR adjusts the scaling behavior to better match the behavior when using hls.js in the webview.
NB I am also waiting on a PR in the ExoPlayer repo to fix a problem with the starting time. Hopefully it gets merged soon and is available in the next ExoPlayer release due out in early May. We can wait on this PR until then or I can make a separate PR to bump the version once that is ready.

Adjust ExoPlayer scaling to better match hls.js

---

app/build.gradle.kts
app/src/main/java/io/homeassistant/companion/android/nfc/NFCUtil.kt

Signed-off-by: Nagy Tamás (T-bond) <tbondvagyok@gmail.com>
See #1505
No frontend change.
Documentation not changed.
If multiple favor is installed on the user's phone, then the OS will choose which one to open. I could not find documentation about the order they are read. I tested on 3 Samsung phone and on one One Plus, and it worked the order the record were on NFC:
1.  The full favored application
2. The minimal favored application
I don't know if it will work on every phone, as there was not so much documentation about it on the internet. (I also haven't checked the Android source code to see how it works)
The ones I tested it worked correctly, and only one application got triggered.
It should automatically add new favors and follow any application ID changes if they are introduced or …

Write all published application IDs to NFC tags

---

app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

Fixes: #1373 by forcing English as the locale being used to pull the string for sensor registration name.
I was unable to properly test this by changing my language however I did not get any errors nor see any indication that the code failed.  As we do not have our strings locally anymore its a bit difficult to properly test however I would imagine if the code didnt work I would see an error which I did not.

Register sensor names as English only

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
app/src/main/res/values/strings.xml

Fixes #1541 by only showing the toast error message when a user taps to update a widget. Error will not be shown for other updates, only interactions.
Also:
*  Correct camera widget manifest info
*  Use a string for template widget in widget picker

Only show widget errors when selected, other widget fixes

---

app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesFragment.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/quick_setting_tiles.xml

Fixes: #1556 by disabling the entity selection field when the user does not have any `script` or `scene` setup.  We will show a friendly message mentioning whats missing and update when we detect an entity was added.

Prevent selecting an entity for a tile if they are missing

---

app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
app/src/main/res/values/strings.xml

Fixes the below sentry error by preventing rendering and saving blank templates. I don't see a reason to let users save a widget with no data and the failure was due to blank rendering. I assume we may have some blank templates saved out there so we may just avoid rendering blank templates in the widget itself.
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
at java.io.StringReader.<init>(StringReader.java:50)
at android.text.HtmlToSpannedConverter.convert(Html.java:748)
at android.text.Html.fromHtml(Html.java:243)
at android.text.Html.fromHtml(Html.java:186)
at io.homeassistant.companion.android.widgets.template.TemplateWidgetConfigureActivity$renderTemplateText$1$1.run(TemplateWidgetConfigureActivity.kt:121) …
```

Prevent saving and rendering blank template widgets

---

app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt

Fixes: #1546 by checking the supported color modes on a device in addition to supported features. As we do not store the current HA version and users might be on a version earlier than 2021.5 we will account for both methods to make it easier.
For more details on the change: https://github.com/home-assistant/core/issues/50563#issuecomment-847251138
Also dev docs that cover which color modes support dimming/brightness: https://developers.home-assistant.io/docs/core/entity/light/#color-modes
I tested this with both a light that has brightness and one that doesn't.

Account for color mode when determining brightness slider

---

app/src/main/java/io/homeassistant/companion/android/qs/Tile1Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile2Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile3Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile4Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile5Service.kt

This should properly send the expected `null` values (that #1548 expected) to hopefully fix:
```
java.lang.NullPointerException: qsTile must not be null
at io.homeassistant.companion.android.qs.Tile2Service.getTile(Tile2Service.kt:11)
at io.homeassistant.companion.android.qs.TileExtensions.onTileAdded(TileExtensions.kt:46)
at android.service.quicksettings.TileService$H.handleMessage(TileService.java:404)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:241)
at android.app.ActivityThread.main(ActivityThread.java:7582)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```
Documentation: …

Finish null check for tiles

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Fixes #1583 by adding a 2 second delay (thanks to @chriss158 for finding this earlier 😂 albeit for a different issue at the time)
I noticed after 2021.6 core the pop-up was no longer coming up, the JS still worked but according to the logs we were sending the JS before the external bus was connected.  So now we wait for the connection and I added a delay to make sure everything is properly loaded. Might feel a bit odd but it works.

Add a 2s delay to more info pop-up for 2021.6

---

app/build.gradle.kts
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/res/layout/exo_player_control_view.xml
buildSrc/src/main/kotlin/Config.kt

This PR does 3 things related to the ExoPlayer usage:
1) Updates the ExoPlayer version to ~2.14.0~ 2.14.1. In ~2.14.0~ 2.14.1 the VideoListener has been deprecated, so the VideoListener usage has been refactored to use Player.Listener instead.
2) Removes the transparent background from the layout file. This was causing flickering on some devices.
3) Adds http2 support via the Cronet extension.
~v 2.14.0 was released almost a month ago. I'm not sure what the ExoPlayer release schedule is like, but I think it's likely the 2.14.1 patch version will be released soon. There is a useful PR in that patch that I think is worth waiting for. As such, I'll leave this PR in draft mode for the time being.~
v 2.14.1 was released today, and I …

Bump exoplayer version

---

common/src/main/java/io/homeassistant/companion/android/common/data/integration/ZoneAttributes.kt

Fixes: #1596 
Apparently the HA frontend makes this field required however it is not required in YAML configuration so I have opened a bug for the frontend to fix this behavior as it should match the backend docs
https://github.com/home-assistant/frontend/issues/9645
https://www.home-assistant.io/integrations/zone/#icon

Make icon optional for zone attributes

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

Fixes: #1589 
Adds a new key for `alert_once` by default its set to `false` so we will process if set to `true`.
```yaml
- alias: Notify one time
trigger:
...
action:
- service: notify.mobile_app_<your_device_id_here>
data:
title: "One Time"
message: "This will only alert me the first time"
data:
tag: "Alarm"
alert_once: true
```
Documentation: home-assistant/companion.home-assistant#567
FCM PR: https://github.com/home-assistant/mobile-apps-fcm-push/pull/59

Allow notifications to only alert once if set

---

app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterBase.kt

Failing to run the view change on the main thread may cause a
CalledFromWrongThread exception as the view may not have been created
from a thread in the IO pool.
The app was failing to start up for me, I looked into the exception being thrown and it looks like the view is being changed from a different thread than it was created, this change will force the view to be modified by the same context that is used in a successful case.

Invoke error display on main thread to avoid crashing

---

app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/TransmitterManager.kt

As per issue #1715 advertised power setting for Beacon should be set to correspond to the power level we have requested.

Set approximation of correct power beacon transmitter power level in DBs.

---

app/build.gradle.kts
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Bump exoplayer version to 2.15.1 and replace deprecated call to `CronetEngineWrapper` with `CronetEngine.Builder`
For a summary of recent Exoplayer changes (the previous version we used was 2.14.2) see here: https://github.com/google/ExoPlayer/releases

Bump exoplayer version to 2.15.1

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/qs/Tile10Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile11Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile12Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile6Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile7Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile8Service.kt
app/src/main/java/io/homeassistant/companion/android/qs/Tile9Service.kt
app/src/main/res/values/arrays.xml
app/src/main/res/values/strings.xml

Fixes: #1668 by increasing the limit to 12
Documentation: home-assistant/companion.home-assistant#582

Increase the total amount of quick settings tiles to 12

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

This should've been removed with #1329 because we now have the call in `onResume` so no longer necessary in `onCreate`

Remove extra sensor worker call from webview

---

app/src/main/java/io/homeassistant/companion/android/controls/LockControl.kt
app/src/main/res/values/strings.xml

In [June](https://github.com/home-assistant/core/commit/9b705ad6dfddaa97ea135b93ce570a284c5ae731#diff-7505c733e3166b2ffb62662df64a1dc9bbb177af2a0df573676fc4f165a9cd42R18) the LockEntity in core got 3 new states:
- Jammed
- Locking
- Unlocking
This PR adds support in the Android app in the power menu to show these states for locks.
The relevant page in the documentation seems to be [android-power-menu.md](https://github.com/home-assistant/companion.home-assistant/blob/e3dba71b276dc1c7be758c6e2b5d376f54de1588/docs/integrations/android-power-menu.md?plain=1#L18) which currently does not state which states the controls will show. Therefore a change in the documentation have not been requested.

Show lock states jammed, locking and unlocking in the power menu

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
app/src/main/res/values/strings.xml

We are unable to launch the special permission activities from the background so we now need to direct users to opening the app so we can trigger the proper permission screen.
Note: We need to still fix actionable and clickAction notifications, I don't think this approach makes sense there but this is the only approach that will work for these commands as they happen without posting a notification.
Current users will need to grant the Draw over other apps permission as a temporary workaround.

Fix notification command permissions not launching by directing user to open the app

---

app/src/main/AndroidManifest.xml

Fixes #1813
This PR fixes that sensor updates do not work, when the app is in background. Currently all sensor will be only updated if the app was opened. 
Because now exported=false is used in the Receiver SensorReceiver, the intents are only allowed from the own app. If exported=true is set, intents from outside of the app will be allowed.
Before the Android 12 commits, this value was not set. Then the default value of true was used.
> https://developer.android.com/guide/topics/manifest/receiver-element.html#exported
If unspecified, the default value depends on whether the broadcast receiver contains intent filters. If the receiver contains at least one intent filter, then the default value is "true". Otherwise, the default value is "false".
Now that the exported attribute is mandatory …

Fix sensor update for BT and Next alarm sensor not working in background

---

app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconTransmitter.kt
app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/TransmitterManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
app/src/main/res/values/strings.xml

Revert default setting to publish with measured power of -59, in attempt to resolve issues described by #1855.
Setting added to allow override if required.
Documentation: home-assistant/companion.home-assistant#604
As I'm not experiencing issues myself I'm not 100% sure this will solve these problems, but reinstating old behaviour as default seems like a good start.

Add measured power setting to BLE transmitter

---

app/build.gradle.kts
app/src/full/java/io/homeassistant/companion/android/settings/SettingsWearActivity.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt

Small updates.  Also removed a duplicate I added 😬 
https://firebase.google.com/support/release-notes/android#messaging_v23-0-0
https://developer.android.com/jetpack/androidx/releases/lifecycle#2.4.0
https://developer.android.com/jetpack/androidx/releases/activity#1.4.0
I do not see a change log for `firebase-core` but I did test that a new user can login to the app and send themselves a notification so I guess its working? :)
Seems there was a change to the menu's being used and I can confirm they continue to work with the small change

Dependency updates and minor changes to accompany them

---

wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt

Depending on network connection or the device the update may be delayed so we will run another update 5 seconds later to make sure the state is in sync.

Add a short delay and update entities again on wear homescreen

---

app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorWorker.kt
app/src/main/java/io/homeassistant/companion/android/sensors/StepsSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/util/LocationPermissionInfoHandler.kt

fix warnings

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt

Fixes: #1855 by requesting a new permission for users on Android 12 as it is now a requirement.

Request proper android 12 permissions for BLE transmitter

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

In modern material design the system bars should not be darker then the rest of the app.
Fixes #1501 which should not be closed.
Google material design changed over the years and they did not always update all the specifications accordingly.
But gladly with Material 3 / Material You, which's specification just got published, they updated everything.
The status bar color should now always be the same color as the AppBar and the navigation bar color should be the same as either the bottom bar or the background. 
Spec: https://m3.material.io/styles/color/the-color-system/tokens

Remove automatic darkening of system bars

---

wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
wear/src/main/java/io/homeassistant/companion/android/util/RotaryEventDispatcher.kt

Implements the current workaround per recommendation from Google while they work on bringing back `View.RequestFocus()` to compose.
Should make the usability better for users as the list of entities can be quite large :)
https://issuetracker.google.com/issues/204506310

Bring back rotary input support for home screen using workaround

---

common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
wear/build.gradle.kts
wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
wear/src/main/java/io/homeassistant/companion/android/settings/SettingsComposable.kt
wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt
wear/src/main/java/io/homeassistant/companion/android/viewModels/EntityViewModel.kt
wear/src/main/res/values/strings.xml

- Adds a new settings section so users can set and clear favorites (clear is important in case the entity list is old like the user deleted an entity)
- When favorites are set they load as a chip on the home screen, then as soon as entities are loaded they convert to toggles if necessary. This allows them to be executed before we finish loading
Fixes: #1881 
Documentation: home-assistant/companion.home-assistant#610
Theres a lot going on in this PR in a future PR lets do the phone side for grabbing and setting favorites :)

Add settings and favorites for wear so users can quickly execute actions they do regularly faster

---

wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt

Fixes: #1880  For now I opted not to save this to local storage because its probably something that should be in Settings and completed alongside #1885 if a user really wants input booleans collapsed on each time we load its probably better for them to keep it at the bottom or maybe even hidden?
I also switched to a `ListHeader` for the entities as it accounts for proper title spacing and arrangement.

Allow categories in Wear to be collapsed and expanded for easier navigation

---

wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/ListHeader.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/OtherSection.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt

- Switch from the old `SetTitle` function to `ListHeader` as it properly spaces out everything and center aligns etc...
- Show the time at the top in overlays (except settings for now while we wait for the other open PR's that convert it to a Lazy Column) to comply with Material Guidelines: https://developer.android.com/training/wearables/design/overlays#time
- Add a `Scaffold` to favorites to show the scroll indicator and time

Add the time, make better use of list headers on Wear

---

wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt

This restores loading a favorite chip during the loading screen for faster execution, for now we will only show an Entity ID. Once we get Room setup we can go back to loading more details in the chip. This allows for a user to execute a chip as soon as the loading screen is up.

Load a temporary favorite chip for each entity ID until we get entities

---

common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
wear/build.gradle.kts
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/ListHeader.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/OtherSection.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt
wear/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt
wear/src/main/res/values/strings.xml

Fixes: #1878 by providing 2 new settings that default to `false` to preserve existing behavior. Once enabled the user will see a toast message and/or haptic feedback based on their choosing.
Documentation: home-assistant/companion.home-assistant#pending

Add settings for wear haptic feedback and toast on entity selection

---

app/src/main/java/io/homeassistant/companion/android/onboarding/WelcomeFragment.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/views/WelcomeView.kt
app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationDetailFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/notification/views/NotificationDetailView.kt
app/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt

Start to use better compose methods to follow along with #1895 
Also adds preview for notification details
Also adding a vertical scroll modifier to the columns in case the screen is small

Clean up welcome and notification details compose views

---

app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/EventResponse.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/SocketResponse.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/StateChangedEvent.kt

This PR adds support for listening to state changed events.  We setup a flow that can be listened to and when the flow is no longer collection it will automatically unsubscribe from the events in the socket.
N/A

Initial support for websocket state changed events!

---

wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
wear/src/main/res/values/strings.xml

- Add the time and scroll indicator to settings
- Set proper list headers for remaining sections
- Sort entities on home screen

Sort entities, add time and headers in wear settings

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

Fixes the following stack trace provided by a user on Discord which occurs when the high accuracy trigger range is left blank. If the field is left blank we now use the default value.
```
11-12 16:25:01.759  4937 23166 E LocBroadcastReceiver: Issue setting up location tracking
11-12 16:25:01.759  4937 23166 E LocBroadcastReceiver: java.lang.NumberFormatException: For input string: ""
11-12 16:25:01.759  4937 23166 E LocBroadcastReceiver: 	at java.lang.Integer.parseInt(Integer.java:627)
11-12 16:25:01.759  4937 23166 E LocBroadcastReceiver: 	at java.lang.Integer.parseInt(Integer.java:650)
11-12 16:25:01.759  4937 23166 E LocBroadcastReceiver: 	at io.homeassistant.companion.android.sensors.LocationSensorManager.getHighAccuracyModeTriggerRange(LocationSensorManager.kt:714)
11-12 16:25:01.759 …
```

Use default trigger range if field is left blank for high accuracy mode

---

app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt

Fixes: #1911 by including the state of a `open` cover
Tried to apply similar logic for `entityFlow` here but didn't have much luck so wasn't able to add live updates

Check cover state in QS tiles

---

wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetTileShortcutsView.kt
wear/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt

Adds the following UI enhancements for both Favorites and Tiles in settings for easier navigation to select entities.
- Sort by name
- Split by category like home screen
- Collapsing/expandable categories
- Adds preview to set tile shortcut view

Add sorting, split by category, add collapsing categories

---

wear/src/main/AndroidManifest.xml
wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt
wear/src/main/java/io/homeassistant/companion/android/tiles/TileActionReceiver.kt
wear/src/main/java/io/homeassistant/companion/android/tiles/TilesComponent.kt

Fix the default entity icon in the shortcuts tile (#1915).
Also change the TileActionActivity to a TileActionReceiver Broadcast receiver. This makes that clicking an entity in the tile never leads the user to the app.

Wear OS tile: Fix default icon and move to broadcast receiver

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

Currently if we loose our connection with the websocket we also loose our state changed registration.  This should force the websocket to reconnect.
N/A
N/A

Allow the websocket to reconnect

---

app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt

Currently when starting the home assistant app, first the launch screen is shown and then a transition to the webview activity is triggered.
The issue is, that this transition is animated, which should not be the case as a launch screen is supposed to just appear and reveal the app behind itself.
This PR disables the transition animation on startup.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
https://user-images.githubusercontent.com/10547444/142456015-5363b5ba-b37d-4e0a-b346-5634809a07f2.mp4
</td>
<td>
https://user-images.githubusercontent.com/10547444/142456724-4c1c53f2-0736-4fc0-b383-a1a8cb49062c.mp4
</td>
</tr>
</table>

Remove startup activity animation

---

app/src/full/res/values/wear.xml
app/src/main/res/values/wear.xml

After #1796 the onboarding listener was unable to forward an instance to wear as I was overriding `wear.xml` in the full version. So moving the capabilities to the full version so we are no longer overriding them.

Fix forwarding HA instance to wear after phone settings introduction

---

wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt

Was playing around with tiles and noticed that none of the icons were loading because all my selected entities had default icons. Came to find the following error due to a minor issue :)
```
2021-11-21 17:17:08.862 27675-27675/? E/TileService: onResourcesRequest Future failed
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:113)
at kotlinx.coroutines.guava.JobListenableFuture.get(ListenableFuture.kt:427)
at androidx.wear.tiles.TileService$TileProviderWrapper.lambda$onResourcesRequest$2(T …
```

Fix default icon for shortcut tile

---

wear/src/main/AndroidManifest.xml
wear/src/main/java/io/homeassistant/companion/android/tiles/TileActionReceiver.kt

Add haptic feedback to the shortcut tile in Wear OS. This solves #1937 

Add haptic feedback to wear shortcut tile

---

app/build.gradle.kts
app/src/full/java/io/homeassistant/companion/android/settings/SettingsWearViewModel.kt
app/src/full/java/io/homeassistant/companion/android/settings/views/SettingsWearFavoritesView.kt
common/build.gradle.kts
common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
common/src/main/java/io/homeassistant/companion/android/database/wear/Favorites.kt
common/src/main/java/io/homeassistant/companion/android/database/wear/FavoritesDao.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt

Breaking Change: Favorites will need to be setup again as we are migrating to a DB and need to do this one time change
Adds drag and drop for re-ordering the favorites on the Wear OS home screen. Also bumps a few libraries.
Video of drag and drop in action: https://photos.app.goo.gl/iYihc3BGKg7fNbXu5
Fixes #1974
Documentation: home-assistant/companion.home-assistant#621

Allow favorite entities to be dragged and dropped for reordering from phone settings

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

When specifying intent extras for notification command `command_broadcast_intent`, the format used to specify these extras prohibits the use of certain special characters (`,` and `:`). With this PR, we allow extras to be urlencoded to overcome this limitation.
To use this functionality, the extras format is extended by allowing the user to append `:urlencoded` to any extra. The format then becomes a comma-separated list of the following:
`<INTENT_NAME>:<INTENT_VALUE>[:urlencoded]`
If the `:urlencoded` suffix is present, `<INTENT_VALUE>` will be urldecoded before adding it to the intent.
Since the old processing code did not handle `:` in `<INTENT_VALUE>` correctly, existing functionality is not affected.
N/A
Documentation: home-assistant/companion.home-assistant#626
fixes #1949

Add support for urlencoded intent extras

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

When the background of the status bar is bright, the status bar foreground should be dark.
But it is not. It stays light. This is caused, because whenever window.navigationBarColor is set, the foreground colors of the status and navigation bar are reset.
So to fix the bug I just changed the order of when which command is executed.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

Fix foreground color of status bar

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

I just landed the pr /pull/1994, which fixed the issue, that the brightness on the statusbar was not applied at all. But in doing so I introduced a new issue, by accidentally relying on the navigationBarColor when calculating the brightness for the statusbar.
This PR fixes this mistake. Sorry for that 😢

Fix statusbar brightness calculation

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

This fixes #1997. It uses the new theme-update external bus message (introduced in home-assistant/frontend/pull/10819), to detect theme changes within the frontend and update the status and navigation bars accordingly.

Migrate to theme-update event

---

common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/StateChangedEvent.kt

Fixes this:
```
2021-12-09 20:06:16.564 12564-19701/? E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-6
Process: io.homeassistant.companion.android, PID: 12564
java.lang.IllegalArgumentException: Instantiation of [simple type, class io.homeassistant.companion.android.common.data.websocket.impl.entities.StateChangedEvent] value failed for JSON property old_state due to missing (therefore NULL) value for creator parameter oldState which is a non-nullable type
at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.homeassistant.companion.android.common.data.websocket.impl.entities.EventResponse["data"]->io.homeassistant.companion.android.common.data.websocket.impl.entities.StateChangedEvent["old_state"])
at …
```

Fix crash when we don't have new_state or old_state in websocket.

---

app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt
app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearMainView.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingPresenterImpl.kt

Was helping to troubleshoot in #1866 and noticed that one of the data item buffers was not releasing properly so added a `release()` call to sort that out.
```
12-12 22:18:44.119   606   621 E DataBuffer: Internal data leak within a DataBuffer object detected!  Be sure to explicitly call release() on all DataBuffer extending objects when you are done with them. (internal object: com.google.android.gms.common.data.DataHolder@4510387)
```
There was this sentry error where for some reason we did not get a display name?  So now defaulting to "unknown" in those cases although I don't think we should be hitting this on the screen.
```
java.util.NoSuchElementException: Collection is empty.
at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:200)
at …
```

Fix some sentry wear bugs and add some logs with a toast

---

app/src/main/java/io/homeassistant/companion/android/onboarding/WearOnboardingListener.kt

This should fix #2042 
All this fix does is check to make sure the URL is not null in [WearOnboardingListener.kt](https://github.com/home-assistant/android/blob/672e49b6fbd48baff466f0a0ba7dfb3292768602/app/src/main/java/io/homeassistant/companion/android/onboarding/WearOnboardingListener.kt#L37)
N/A
N/A
N/A

Fixes Wear OS onboarding crash

---

wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt

Adds Back button support to the Wear app. Previously when pressing the back button it would exit the app.
https://issuetracker.google.com/issues/210205624
https://user-images.githubusercontent.com/37350695/146850049-a2bc3644-8a47-4f68-94b4-3ada35464b03.mp4

Add Back button support to Wear

---

wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt

After PR #2039 I found that pressing the back button caused the app to crash on the landing page this PR checks if the current page is Screen_Landing thus not running the popBackStack()
One warning is that this does prevent users from exiting the app by pressing the back button
N/A
N/A
N/A

Fix back button crash on Screen_Landing

---

app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt

Fixes following sentry error, same one as we have seen in Wear OS onboarding in #2007 
```
at io.homeassistant.companion.android.launch.LaunchActivity$onOnboardingComplete$1.invokeSuspend(LaunchActivity.kt:95)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:233)
at android.app.ActivityThread.main(ActivityThread.java:8052)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
at …
```

Only complete onboarding if intent data is not null

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

Fixes the following sentry error by only attempting to authenticate when the connection variable is not null
```
at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.authenticate(WebSocketRepositoryImpl.kt:216)
at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.connect(WebSocketRepositoryImpl.kt:185)
at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.sendMessage(WebSocketRepositoryImpl.kt:199)
at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.getStateChanges(WebSocketRepositoryImpl.kt:135)
at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$getStateChanges$1.invokeSusp …
```

Only attempt to authenticate websockets when connection is not null

---

app/src/main/java/io/homeassistant/companion/android/sensors/PowerSensorManager.kt

Corrected the spelling used in the Power Sensor attribute name, changing from 
"ignoring_battery_optizimations" to "ignoring_battery_optimizations"
This is a breaking change, since any template that depends on the name
will need updating to correct to the typo corrected version.
n/a
The existing docs document the correct name of this attribute, so do not need updating.
https://companion.home-assistant.io/docs/core/sensors/#doze-sensor

Breaking change:Typo in power sensor attribute

---

app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt
app/src/main/res/xml/sensors.xml
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorManager.kt

I know some of our advanced users will be disappointed by this change and I'm sorry 🙏 . The issue is that many new users come to the page and blindly enable all sensors which in most cases will result in a high amount of unnecessary updates causing extensive battery drain. A lot of users trust that by default the app will not drain their battery and this toggle gave a false perception of that. The main thing is users were not seeing sensor descriptions which tell them whats recommended like for example creating an allow list for a notification sensor.

Remove enable all sensors toggle to reduce battery complaints

---

app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
common/src/main/res/values/strings.xml

We have noticed a lot of users enabling all sensors and then wondering where the battery drain is coming from. Most of the time its from a notification sensor because given the circumstances they can be extremely chatty. Most users dont need all notification data. So we are introducing a breaking change where the sensor will not report all notification data unless the user explicitly requests it via a sensor setting that is off by default. This should greatly reduce battery complaints and other issues users can see.
Documentation: home-assistant/companion.home-assistant#640

Breaking Change: Enforce an allow list for notification sensors to prevent battery issues

---

app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationFragment.kt

Noticed the following sentry error so decided to catch the error and keep the user on the same screen to prevent a crash:
```
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1260)
at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1633)
at io.homeassistant.companion.android.onboarding.authentication.AuthenticationFragment.buildAuthUrl(AuthenticationFragment.kt:96)
at io.homeassistant.companion.android.onboarding.authentication.AuthenticationFragment.access$buildAuthUrl(AuthenticationFragment.kt:34)
at io.homeassistant.companion.android.onboarding.authentication.AuthenticationFragment$onCreateView$1$1$1$1.invoke(AuthenticationFragment.kt:87)
at …
```

Catch the exception when an invalid URL is used

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

The commit made for [this comment in PR #2066](https://github.com/home-assistant/android/pull/2066#discussion_r774740738) introduced a new bug: a call to `getStateChanges()` now always returns an empty flow, meaning subscribing to the websocket does nothing (and widgets / device controls no longer update until you force a reload).
n/a
Not needed (bugfix)
This code is also in the currently released stable version of the app, 2012.12.2, should I (also) have made an issue?

Fix getStateChanges call always returning empty flow

---

wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt

This PR exits the app on Screen_Landing when the back button is pressed on wear instead of stopping on Screen_Landing
N/A
N/A
N/A

Exit app when back is pressed on Screen_Landing

---

app/src/main/java/io/homeassistant/companion/android/widgets/BaseWidgetProvider.kt

Fixes #2075.
Using the `getAllWidgetIds` function will only check the table for the specific type of widget, so if any new widgets are added in the future this won't need updating.
n/a
n/a
-

Check if there are any widgets before connecting to websocket

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/sensors/LastAppSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorManager.kt
common/src/main/res/values/strings.xml

Adds a new sensor that reports the last used app since the last update. Currently this sensor does not update immediately so will need to look into methods for faster updates. This sensor requires a special permission unlike the others we have so had to add additional checks for it.  We will try to determine the application label and if unable to determine a label we will send the package name.
Documentation: home-assistant/companion.home-assistant#647

Add last used app sensor

---

app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt

While helping out in #2036 I noticed that our debug logs did not include the tile ID used as it would be helpful to know if the user is interacting with the correct tile. Maybe there is a better way to help them by adding a number to the string for "Tile Not Found"? I think we would need separate strings as we need to define them in the manifest. I can do that here too if we feel it will be helpful. 

Add debug logging in quick setting tiles for easier troubleshooting

---

app/src/main/java/io/homeassistant/companion/android/widgets/BaseWidgetProvider.kt
app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt

Currently, any time an entity state change is received (via the websocket) all widgets data is refreshed and views are updated. While it works to keep the widgets 'live', it is very inefficient, especially if there are a lot of state changes and/or you have a lot of widgets.
This PR proposes a way to use the entity state changes the app already receives to update the widgets more efficiently, specifically:
- Only update the widgets that are affected by the state change*
- Re-use the received entity state instead of making a call to the REST API to get the entity state, if possible
\*Right now that is just the entity state and media player widgets. The template widget is rendered on the server which might be affected by state changes in ways we don't know anything about, so just keep …

Widgets: use received entity state changes for updating if possible

---

wear/src/main/java/io/homeassistant/companion/android/util/RotaryEventDispatcher.kt

Fixes: #2090 by catching the exception and passing `0f` to avoid scrolling or a failure. I didn't seem to see a way to detect if a device has rotary input I assume this wont be an issue once google adds rotary input and we avoid our current work around

Catch the failure on devices without rotary input

---

app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSliderControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LockControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/SceneControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/VacuumControl.kt

(Submitted as a result of a discussion in the Discord mobile apps dev channel)
When adding device controls order them by area first, if set, and only then by domain. This matches the autogenerated Lovelace dashboard and probably offers the best user experience.
The UI is provided by the system, this is on a Google Pixel 4a running Android 12. This screenshot is not complete because it is a very long list for me but the result should be obvious: 'Beneden' and 'Boven' are areas I have set and after that it shows devices not in any area by domain (such as Automation and Fan in the screenshot).
Probably not needed?

Group device controls by area first, if set, when adding them

---

app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt

While testing the minimal builds I noticed that the location section was showing during onboarding when it should be hidden, turns out we were always sending `true` so now doing a flavor check

Show the location section during onboarding only if user is on the full flavor

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

Fixes: #2102 by setting the `lastHighAccuracyMode` variable when a notification command updates it. I noticed this because in the logs the service is on but for some reason we are still attempting to stop background updates and start the service which is already running.
```
01-02 10:35:40.941 26154 26154 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = true
01-02 10:35:42.889 26154  3997 D LocBroadcastReceiver: High accuracy mode enabled, because in zone [zone.home_expanded]
01-02 10:35:42.890 26154  3997 D LocBroadcastReceiver: High accuracy mode parameters changed. Enable high accuracy mode.
01-02 10:35:42.890 26154  3997 D LocBroadcastReceiver: Removing background location requests.
01-02 10:35:42.894 26154  3997 D …
```

Set the last high accuracy mode variable when enabled/disabled via notification command

---

app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSliderControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LockControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/SceneControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/VacuumControl.kt

While working on adding area information to the device controls, I noticed a lot of code duplicated across all classes implementing `HaControl` (to which I also added area related code which is exactly the same for each class).
This PR is a small refactor that moves setup and some options that are the same for all/most controls to a default function in the interface. This should make it easier to understand and maintain the control classes.
No visible changes
n/a

Less duplicate code for classes implementing HaControl

---

common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationRepositoryImpl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationService.kt

Was chatting with @jpelgrom in discord and we discovered that logging in on an actual android wear device showed the incorrect URL. In fact it was defaulting to localhost so it was never pulling in the URL. Tested below code by logging into wearable directly and also logging in via phone settings to wear
Should also fix #2114 the user was filtering by `homeassistant` however the error did not print anything to our app so it was easy to miss

Add the actual URL to the authentication calls for wear

---

app/src/main/java/io/homeassistant/companion/android/sensors/LastAppSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
app/src/main/res/xml/preferences.xml
app/src/quest/AndroidManifest.xml

Changes to accommodate being able to upload an app. As some permissions are not allowed this means some sensors will not be available in this version. 
```
ERROR: Validation identified the following errors:
The upload could not be completed because your application contains the following Android permissions that are not supported:
- android.permission.ACCESS_FINE_LOCATION
- android.permission.ACCESS_BACKGROUND_LOCATION
- android.permission.ACCESS_COARSE_LOCATION
- android.permission.CAMERA
- android.permission.READ_PHONE_STATE
- android.permission.ACTIVITY_RECOGNITION
- android.permission.ACCESS_NOTIFICATION_POLICY
- android.permission.QUERY_ALL_PACKAGES
- android.permission.SYSTEM_ALERT_WINDOW
- android.permission.PACKAGE_USAGE_STATS
Please remove the following permissions and upload …
```

Quest changes round 1

---

app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/AreaRegistryResponse.kt
common/src/main/java/io/homeassistant/companion/android/util/RegistriesDataHandler.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/EntityListView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/ListHeader.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt

Based on the work in #1970, this PR uses area information for entities to improve the main list shown on Wear OS. Should fix #1795.
I haven't worked on Wear OS or with Compose before, so happy to get any feedback from more frequent Wear OS contributors 🙂
Still to do:
Further possible improvements: 
Favorites is still at the top, directly below that the user will see their areas with entities:
Tapping on an area shows a list of all entities in the area:
(the first item is an input boolean, the second a light, ...)
Back on the main screen, below the areas the app shows chips for domains with entities not in any area (so 'More entities' refers to more than in the areas):
And finally at the bottom of the list is the chip for 'All entities', which shows all entities regardless of area status, …

Add areas to entity list on Wear

---

common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetTileShortcutsView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt

Adds the option to show names on shortcuts tile. Fixes #1976
Not needed

Show names on shortcuts tile

---

app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt

When sending a message to an Iphone and an Android phone, it is currently necessary to distinguish between a newline control character. 
The Iphone uses `\n` and Android uses the html code `<br>`.
This is a problem when a message is sent via a Notify group consisting of an Iphone and Android. 
```
notify:
- name: all_devices
platform: group
services:
- service: mobile_app_android
- service: mobile_app_iphone
```
```
service: notify.all_devices
data:
message: test1\n\ntest2\n\ntest3
```
As a simple solution we just replace all `\n` with `<br>`. Then we can also use the control character `\n` for Android phones.

Fix handling of line feed control char

---

wear/src/main/java/io/homeassistant/companion/android/tiles/TemplateTile.kt

Fixes #2145 by removing `* 60` as the saved value is already in seconds, so there is no need to multiply (see [my comment on the issue](https://github.com/home-assistant/android/issues/2145#issuecomment-1013717094) for slightly more details). Tested and refreshing is working as intended on the emulator.
n/a
n/a

Fix template tile refresh interval

---

app/src/main/java/io/homeassistant/companion/android/widgets/BaseWidgetProvider.kt

Fixes the following sentry error by only applying the flow if we have it. Seems to impact a good chunk of users according to Sentry.
```
at io.homeassistant.companion.android.widgets.BaseWidgetProvider$onScreenOn$1.invokeSuspend(BaseWidgetProvider.kt:79)
at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at …
```

Only collect the entity flow if we are not null

---

app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt

Fixes the following sentry error by defaulting to the correct value instead of crashing. I also noticed if a user clears out the field they can no longer add back a negative number so changed the field only for this setting as its the only one that expects a default value.
```
java.lang.NumberFormatException: For input string: ""
at java.lang.Integer.parseInt(Integer.java:627)
at java.lang.Integer.parseInt(Integer.java:650)
at io.homeassistant.companion.android.sensors.BluetoothSensorManager.updateBLEDevice(BluetoothSensorManager.kt:169)
at io.homeassistant.companion.android.sensors.BluetoothSensorManager.updateBLESensor(BluetoothSensorManager.kt:195)
at io.homeassistant.companion.android.sensors.BluetoothSensorManager.requestSensorUpdate(BluetoothSensorManager.kt:109)
at …
```

Prevent null values for BLE measured power, also allow negative values in case entire field is cleared out

---

app/src/main/java/io/homeassistant/companion/android/settings/websocket/WebsocketSettingFragment.kt

Adds a title and help icon to the toolbar in the websocket settings. The documentation link should be helpful in the future once the feature is pushed to more users.
|Light|Dark|
|----|----|
|![settings-light](https://user-images.githubusercontent.com/8148535/150214336-3969dc4a-6620-4521-aaa4-543a45bc99e9.png)|![settings-dark](https://user-images.githubusercontent.com/8148535/150214342-a3e69a54-9005-4992-83f7-ba614eebf988.png)|
n/a

Add title, help to websocket settings

---

app/build.gradle.kts

Yet another attempt to fix #2153.
According to Gradle, two dependencies were still adding Google libraries to the app (see [this comment](https://github.com/home-assistant/android/issues/2153#issuecomment-1016813714)). This PR addresses that by:
- embedding ExoPlayer Cronet for minimal builds + excluding the Play Services dependency from the default (see [this comment](https://github.com/home-assistant/android/issues/2153#issuecomment-1016933008) for details)*
- moving the Wear OS remote interactions to full, already only used in the full app
Checked the merged manifest and classes in the generated APK and no `com.google.android.gms` to be found!
\* Note that this will increase the app download size for minimal and quest by ~8MB. Because this doesn't require code changes and should ensure …

Fix minimal including Play Services dependencies

---

app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt
common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

This should fix issue with random interruptions in work manager.  If we just use KEEP instead of REPLACE then we could end up waiting 15 minutes for the work to requeue.  This should work around that and requeue the next time your screen comes on.

This should fix issue with random interruptions in work manager.

---

app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt

Since this notification is meant to be persistent I figured it makes more sense to open the app from it. All my other apps that use a persistent notification have their pending intents set to open their app.

Open the app from the persistent websocket notification

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

When long pressing on a device control to view the entity details, the more info panel sometimes didn't show up in the frontend or only flashed on screen for <1 second. I'd say it works 5/6 times, but it still fails frequently enough that it annoys me so I decided to investigate. 
I only noticed this for device controls but it should also apply to linking to an entity from a notification and quick settings tiles.
<details>
<summary>Details</summary>
Being able to reproduce this probably depends on your the speed of the network, device and HA instance. I just long pressed on a device control and waited to see if it would open the more info panel, on average it failed 1/6 times.
I started by adding a callback to the `webView.evaluateJavascript` call to see if there was a significant delay. …

Improve reliability of opening entity 'more info' panel via intent

---

app/build.gradle.kts
app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaFailedControl.kt
app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt

Fixes #2169
Did a quick check to see where else the app loads the entity and added a try/catch to the quick settings tiles state and camera widget as well.
All of these failure states are generated by the system, this is on a Google Pixel 4a running Android 12.
Device controls will now show 'Not Found' if the exception is a HTTP 404 response, tapping on it shows more details, and it will show a simple tile in case of any other exception (tapping does nothing). Other controls can still be loaded and used:
|HttpException: 404|Tap on 'Not Found' tile|Other exceptions|
|-------|-------|-------|
|![404-notfound](https://user-images.githubusercontent.com/8148535/150613024-b81c0912-c16f-439f-926e-5f1871e02f14.png)|![404-notfound-tap](https://user-images.githubusercontent.com/8148535/150613039-ab1 …

Don't crash app on tiles/widgets/device controls if entity doesn't load

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt

The notification rate limit reset time is [in UTC](https://companion.home-assistant.io/docs/notifications/notification-details#:~:text=The%20rate%20limit%20resets%20at%20midnight%20UTC%20daily.), but using `LocalDateTime.parse` will ignore timezone information and make the app think it is midnight local time. This PR fixes that so it displays the right time for everyone not living in UTC time.
(Also removes unnecessary safe calls in the function.)
This device is set to Central European Time, so UTC+1.
|Light|Dark|
|-----|-----|
|![image](https://user-images.githubusercontent.com/8148535/150814739-a9114e1b-fac6-4932-8475-420914c38737.png)|![image](https://user-images.githubusercontent.com/8148535/150814798-c6654aa7-3a97-4f23-a10a-c075b87d2c87.png)|
n/a

Fix notification rate limit reset time

---

app/src/main/java/io/homeassistant/companion/android/settings/widgets/ManageWidgetsViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/widgets/views/ManageWidgetsView.kt
app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
app/src/main/res/xml/changelog_master.xml
common/src/main/res/values/strings.xml

With the new Compose-based UI for managing widgets, the empty state arguably became worse, showing only the text "No Widgets Found" with almost no formatting and no information on how you can solve it.
This PR updates the empty state for the widget settings to restore the summary text (edited to reflect that camera widgets won't show up) and make the layout look nicer (following Material guidelines).
For devices running Android 8+ with a compatible launcher, this PR will also add a button to the widget settings screen to add a new widget to the home screen, to make it easier to 'solve the problem' of no added widgets or for when users simply decide to add a widget while browsing the list of existing widgets.
As a reminder, the current empty state of the "Manage Widgets" screen on the …

Update widget settings empty state, add "Add widget" button

---

app/build.gradle.kts
build.gradle.kts
common/build.gradle.kts
wear/build.gradle.kts

AGP 7.1.0's Lint DSL has renamed `isAbortOnError` to `abortOnError` (although according to the [documentation](https://developer.android.com/reference/tools/gradle-api/7.0/com/android/build/api/dsl/Lint) this was already in 7.0?) and has removed the functions to edit the `disable` set. This PR updates the lint configuration to fix the build.
Closes #2202 
n/a
n/a

Bump and fix Android Gradle Plugin from 7.0.4 to 7.1.0

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
common/src/main/res/values/strings.xml

Fixes the below sentry error by checking for permissions and if the user has not granted them we notify the user and explain how to grant them. As this command needs a different permission not linked to a particular activity and the commands are sent in the background we take the user to app details and have them grant the permission. String was also updated to reflect this. Only impacts users on Android 12 who attempt to use `command_bluetooth` without proper permissions, usualy a user will have already granted this permission assuming they had the sensor enabled.
```
java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10309, packageName = io.homeassistant.companion.android, attributionTag = null, token = …
```

Check for permissions and notify if they are missing when command_bluetooth is used

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Fixes the below sentry error by preventing the case when `group` is blank. We just use the same condition as when we set the values so we know they are not null or blank.
https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt#L665
```
java.lang.StringIndexOutOfBoundsException: length=0; index=6
at java.lang.String.substring(String.java:2027)
at io.homeassistant.companion.android.notifications.MessagingManager.getGroupNotificationBuilder(MessagingManager.kt:827)
at io.homeassistant.companion.android.notifications.MessagingManager.sendNotification(MessagingManager.kt:721)
at io.homeassistant.companion.android.notifications.MessagingManager.access$sendNotification(MessagingManager.kt:72)
at …
```

Use same group check as before when a group is used to avoid null error

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

This is a PR to fix my reported issue at #2198. It adds a few more types to the `MessagingManager` to enable users to send more complex types as intent extras. The current behaviour has not been changed. More types can also be added as needed.
n.a.
Documentation: home-assistant/companion.home-assistant#670

Added more types to MessagingManager intent extras

---

app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt
app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearFavoritesView.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt
wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt
wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt

This PR adds support to the Wear OS app to toggle other entities I could easily test: entities in the `cover` and `fan` domain. It also fixes the chip for locks being highlighted as on or off, but the toggle itself always being off.
Fixes #2211
**Wear OS**
Something changed in Android Studio 2021.1 and now my emulator screenshots are all fuzzy, sorry about that.
Open/closed for covers is 'converted' to on/off, matching device controls on phones.
**Phone settings**
|Light|Dark|
|----|----|
|![Companion app on phone showing the Wear OS favorite settings, with new entities cover/fan at the top of the list, light mode](https://user-images.githubusercontent.com/8148535/151711022-93b9dced-9eef-4db4-9d16-b77f7fde9e52.png)|![Companion app on phone showing the Wear OS favorite settings, with new …

Allow toggling covers and fans on Wear OS

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt

Was helping a user in the forums and for some reason their network state intent is not picking up and I came to find this intent which is related to the wifi state itself. Linking it to wifi state sensor as that is all this intent looks at. On my Pixel I dont see this intent but its possible other devices will pick it up, my pixel does pick up the network state change intent as expected when wifi is turned on/off.
https://developer.android.com/reference/android/net/wifi/WifiManager#WIFI_STATE_CHANGED_ACTION
https://community.home-assistant.io/t/force-updates-for-app-sensors/383846/23?u=dshokouhi

Add an intent for the wifi state sensor

---

app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidgetConfigureActivity.kt

Found a small bug in the new option to add widgets to your home screen via the app: invalid configuration only causes an exception when trying to save the data. However, when adding them via the app, the app will try saving the data _after_ asking the launcher to add a widget, resulting in an error after adding a widget to the home screen and the widget on the home screen will never be updated.
This PR adjusts that process to check the variable/input that would typically cause the exception before asking the launcher to add a widget. Validation in general could be better, but at least now adding widgets from the app will match the behavior of adding widgets from the home screen.
(To test: add the updated widget without setting any values.)
n/a
n/a

Fix adding widgets with invalid config via app to home screen

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/EntityRegistryResponse.kt
common/src/main/java/io/homeassistant/companion/android/util/RegistriesDataHandler.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt

Right now the Wear OS app is usable, but the current approach can still create long lists on a small screen if you have a lot of entities and/or when we start supporting more domains in the future. Thinking about what you'd use the app for and how we matched the autogenerated Lovelace dashboard in showing areas first and then domains for usability, I believe we should hide configuration and diagnostic (non-primary) entities on the home screen from the main areas and domains lists, which [the autogenerated dashboard also started doing in 2021.11](https://www.home-assistant.io/blog/2021/11/03/release-202111/#entity-categorization).
This PR filters the entities shown in 'Areas' and 'More entities' on the home screen to only show primary entities. All types of entities, primary and …

Breaking change: hide non-primary entities on Wear home screen

---

app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt

We noticed in discord when the setting was set to Screen On the connection was lingering longer than we expected. So changing the call to use `isInteractive` from PowerManager as we know the screen on/off intents are linked to it.
https://developer.android.com/reference/android/os/PowerManager#isInteractive()
Now when I test with default settings the notification goes away after 30 seconds of the screen being off

Check the interactive state instead of display state for websocket connection

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

This PR adds support for clicking on links which trigger a download of a file from the `WebViewActivity` to the Downloads folder. These links can be created both by the frontend (for example, downloading device diagnostics or supervisor back-ups) and third-party integrations or add-ons, the app will use the default callback from the webview for this.
Downloads are passed to the system's `DownloadManager`, so there is basically no logic for downloading/service in the app itself.
Fixes #2212, will probably fix #1341 but I'm unable to test with the community add-on that is mentioned in the issue.
After tapping on a download, the system will display a download notification:
When it is finished, another notification is shown (alerting by default) which can be tapped to open the file:
On …

Support downloading files from WebViewActivity

---

app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
common/src/main/res/values/strings.xml

Changes the firebase error message to mention the loss of cloud notifications since we have local WebSocket notifications now as well also changes the skip button to continue as skip sounded like it should've had another option with it
Don't know why the error page glitches the logo out like that

Change Firebase Error

---

app/src/main/java/io/homeassistant/companion/android/sensors/DNDSensorManager.kt

This PR is a breaking change as we are going to switch from the undocumented variable and use the actual android API so we can use the standard practice. This android API is only available on Android 6+ devices.
Documentation: home-assistant/companion.home-assistant#678

Breaking change: Switch to android API to determine state of DND

---

app/src/main/java/io/homeassistant/companion/android/sensors/LastAppSensorManager.kt

Breaking change because the state will no longer reflect the app name but will instead be the package name so it is always guaranteed to be unique.
Fixes: #2126 
Documentation: home-assistant/companion.home-assistant#679

Breaking change: Always use package name for state of last used app

---

app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesFragment.kt
app/src/main/res/xml/changelog_master.xml

There's still more places where `button` and `input_button` entities can be supported! This PR adds support for them in the quick settings tiles, and will resolve #2244.
Documentation: home-assistant/companion.home-assistant#680

Support (input_)button entities in quick settings tiles

---

app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
app/src/main/res/xml/changelog_master.xml

Suggesting a few tweaks to improve the device control used for `climate` entities:
1. Use temperature unit related attributes, and use this to better match the controls offered by the frontend (number formatting / step size). This also fixes the situation where the current control always sets temperature values in multiples of 0.5 degrees even though the resulting value might not be supported, and always rounds what is displayed to a full number. If the unit isn't known, don't show anything* and use the settings with the least precision.
2. If the entity supports setting temperature and the [`hvac_modes`](https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes) only include values that match what is [available in the …

Tweak device control for climate entities

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

If the authentication that is provided to the websocket is invalid, Home Assistant will immediately close the websocket after sending the `auth_invalid` message. Because the `onClosing` function will reset the Job used for monitoring the authentication result, this can result in a race condition where the job is changed before the result is processed. As a result, the job won't complete and checking authentication will have to wait for the timeout to complete. Example log:
```
2022-02-10 21:55:44.561 10649-10682/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onOpen
2022-02-10 21:55:44.564 10649-10682/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-02-10 21:55:44.870 …
```

Fix websocket invalid auth race condition

---

app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidgetConfigureActivity.kt
app/src/main/res/drawable/ic_volume_down.xml
app/src/main/res/drawable/ic_volume_up.xml
app/src/main/res/layout/widget_media_controls.xml
app/src/main/res/layout/widget_media_controls_configure.xml
common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
common/src/main/java/io/homeassistant/companion/android/database/widget/MediaPlayerControlsWidgetEntity.kt
common/src/main/res/values/strings.xml

I added 2 optional volume buttons to the media player widget.
https://github.com/home-assistant/companion.home-assistant/pull/682
If there is any feedback, let me know. This is my first time in a kotlin/android project.
I am also wondering if I should add a mute/unmute button for completeness.

Add volume up/down buttons on media player widget

---

app/src/main/java/io/homeassistant/companion/android/settings/widgets/ManageWidgetsViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/widgets/views/ManageWidgetsView.kt
app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt
app/src/main/res/layout/widget_camera_configure.xml
app/src/main/res/xml/camera_widget_info.xml
common/src/main/java/io/homeassistant/companion/android/database/widget/CameraWidgetDao.kt
common/src/main/res/values/strings.xml

Currently, you can reconfigure all of the widgets except for the camera widget. This PR changes that and will allow users to also edit the camera widget. 
While it is a very simple widget, having just one widget not configurable is inconsistent, Android 12 will show options to edit the widget in the launcher which will make it faster to change the camera (edit instead of delete + scroll widgets list + add again), and this will 'fix' the widgets settings in the app being empty when only camera widgets have been added (which could be confusing).
Code based on editing an entity/state widget.
|-----|-----|------|
|Settings|![Widget settings in the app showing two camera widgets, light mode](https://user-images.githubusercontent.com/8148535/153267913-bb93fb18-a99e-4f78-bfdf-a …

Allow reconfiguring camera widgets

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt

Fixes the following sentry errors by performing a null check before attempting to send the message:
```
at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$sendMessage$2.invokeSuspend(WebSocketRepositoryImpl.kt:313)
at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$sendMessage$2.invoke
at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$sendMessage$2.invoke
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:146)
at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:103)
at …
```

Check that connection is not null before attempting to send a message

---

wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt
wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt

This PR improves the icons that are displayed in the Wear OS app by using information about the state and device class, if available, to better match the icons in frontend when no specific icon has been set by the user. When no state is available (= shortcuts tile) the icons mostly match what was already used.
A few examples, I'm not going to show every possible combination.
|     |Before|After|
|Covers: blind class closed + garage class open|![image](https://user-images.githubusercontent.com/8148535/154135256-f2c4757f-a2cf-4565-8f8f-dc55235f5aff.png)|![image](https://user-images.githubusercontent.com/8148535/154135225-efd17e83-242e-4647-8043-28b1294abc47.png)|
|Covers: blind class open + garage class open|![image](https://user-images.githubusercontent.com/8148535/15413 …

Wear use state and device class for entity icons

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt

Fixes: #2303 
```
service: notify.mobile_app_pixel_6_pro
data:
message: test action
data:
actions:
- action: URI
title: history
uri: settings://notification_history
```
or
```
service: notify.mobile_app_pixel_6_pro
data:
message: test
data:
clickAction: settings://notification_history
```
Documentation: home-assistant/companion.home-assistant#693

Allow opening notification history from URI action

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
app/src/main/res/xml/preferences.xml
common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/res/values/strings.xml

Fixes #2162 by adding a remote debugging switch (default off) to settings. On a debug build we will still have debugging enabled no matter what but on other builds we will let the user decide. This will allow users to troubleshoot issues without needing to install a debug build.
Documentation: home-assistant/companion.home-assistant#692

Allow enabling chrome remote debugging in settings

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
app/src/main/java/io/homeassistant/companion/android/settings/websocket/views/WebsocketSettingView.kt
app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt
common/src/main/java/io/homeassistant/companion/android/database/settings/WebsocketSetting.kt
common/src/main/res/values/strings.xml

Fixes: #2279 by adding a new option that only maintains the connection when on the defined home wifi
Not needed as we do not describe any setting on this page.

Add new option for persistent connection to only connect when on home wifi

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

This fixes the condition when a user is trying to just enable/disable the transmitter.  Reported via: https://community.home-assistant.io/t/enable-ble-transmitter-via-notification-command-dont-work-anymore/396224

Fix BLE command when enabling or disabling the transmitter

---

app/src/main/java/io/homeassistant/companion/android/settings/widgets/views/ManageWidgetsView.kt

Fixes showing null when no attributeIds is present when a label isn't provided
Before:
After:

Fix showing null when no attributeIds is present

---

app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearFavoritesView.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultButtonControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaFailedControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesViewModel.kt
app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidgetConfigureActivity.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/DetailsPanelView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt

The Wear OS details panel introduced a new location in the code base where entity properties are used to determine feature support, in addition to phone/'full Android' device controls. To prevent duplicate code or code getting out of sync, especially when more features are supported on Wear OS in the future, and perhaps in more places (widgets?), I propose using extensions to keep the code in one place and make code elsewhere easier to read.
I've added the code to the existing file used for the `Entity` data class, but maybe another location is better (in the `util` package, or a new `common.data.util` package)?
n/a
Not needed

Add extensions to Entity for domain, lights features

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt

The intent to request that battery optimizations are ignored for the app returns an activity result, not a permissions result. Changed to the correct callback to fix refreshing the setting after accepting/denying.
n/a
Not needed, bug fix.

Fix refreshing settings after requesting background access

---

app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/DetailsPanelView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt

Now that there is a details screen for Wear OS, this PR adds support for controlling a `fan` entity's speed.
On the `InlineSlider`, `steps` has been set to 9 to allow controlling in steps of 10%, I think that is a good balance between quickly changing the value and specific control for fans.
(Also updates the label for the light brightness slider because that is also in %.)
Documentation: home-assistant/companion.home-assistant#702

Add fan speed to Wear OS detail panel

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
common/src/main/res/values/strings.xml

Fixes: #2343 by adding the proper permission to the manifest and then directing users who have not granted the permission to the app info screen to grant the permission, just like we do for bluetooth permissions.
Documentation: home-assistant/companion.home-assistant#707

Check for phone permissions when using call intent

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/main/res/layout/view_image_flipper.xml
app/src/main/res/layout/view_single_frame.xml

I have added the ability for a user to define `video` as part of an Android notification. This video will be downloaded and home assistant will attempt to parse frames from this video to show in a notification. The goal is to find 5 frames but it will work for any number of frames < 5 as well. 
https://user-images.githubusercontent.com/14866235/156859680-5c76f67d-4e27-4ec5-a6ee-c6c96937ce91.mp4
Documentation: home-assistant/companion.home-assistant#705

FEAT: Ability to show video in notification as a gif

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

Fixes: #2336 by only skipping some of the reports when high accuracy mode is off. When high accuracy mode is on we can assume the app will not get a report in the future nor do we need to worry about the 5 second delay as the `time` could be off slightly per the logs above.
I thought it might be better to check for high accuracy mode being on instead of simply increasing the time check which is set to 5 seconds.

Only skip some reports when high accuracy mode is off

---

app/src/full/java/io/homeassistant/companion/android/location/HighAccuracyLocationService.kt
app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/main/java/io/homeassistant/companion/android/settings/notification/views/NotificationChannelView.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorUpdateFrequencyView.kt
app/src/main/java/io/homeassistant/companion/android/settings/websocket/views/WebsocketSettingView.kt
app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorWorkerBase.kt
common/src/main/java/io/homeassistant/companion/android/common/util/AppNotifChannels.kt
common/src/main/java/io/homeassistant/companion/android/common/util/DisabledLocationHandler.kt
common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt

I realized that we didn't hide all app created channels, we only hid the ones most users will see. So I opted to move all app created channels to its own file so we can maintain them in a single location. I also opted to add the `General` channel to the exclusion list because that is the default channel if not specified so it should be treated like an app created channel.

Hide delete icon on more app created channels

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Unfortunately, I tried on my personal device and was still seeing this fail. Turns out that compressing wasn't enough and I need to manually scale down the bitmap to get it to work. This is a small addendum to #2353 
Sorry for the extra PR 😦

Force resize of video frames instead of compressing

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/minimal/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

Fixes: #2328 by introducing a new command for high accuracy mode commands to set the update interval. Once set the service will restart with the new interval. I also noticed failed commands for high accuracy mode was not posting the notification as it should so added that as well.
example:
```
service: notify.mobile_app_pixel_6_pro
data:
message: command_high_accuracy_mode
title: high_accuracy_set_update_interval
data:
high_accuracy_update_interval: 60
```
Documentation: home-assistant/companion.home-assistant#709
FCM: https://github.com/home-assistant/mobile-apps-fcm-push/pull/68

Allow changing high accuracy update interval via command

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt
common/src/main/res/values/strings.xml

Adds a new sensor for the "Network Type" to show the transport type being used.  Possible states can be `bluetooth`, `cellular`, `ethernet`, `lowpan`, `vpn`, `wifi` or `wifi_aware`
Documentation: home-assistant/companion.home-assistant#710
Adding this as a sensor because it reports potentially good data if a user wants to know if they are on vpn or something, also because I had already done the work mistakenly so why throw it out 😛 https://github.com/home-assistant/android/issues/2350#issuecomment-1061272547

Add a transport sensor

---

app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt

Fix #2273 by replacing the `NetworkType.CONNECTED` constraint on the job for `WebsocketManager` with a check that does not take the validation status (= internet access) of the network into account. This change shouldn't have any negative consequences because validation will change network state for which the app is registered to receive broadcasts (in order to start websocket again).
Related: [WorkManager 2.7.1 code for constraint](https://android.googlesource.com/platform/frameworks/support.git/+/886e6487b3b009732a88af4bd242d4ae30f801ab/work/work-runtime/src/main/java/androidx/work/impl/constraints/controllers/NetworkConnectedController.java), [Google issue tracker request](https://issuetracker.google.com/issues/140056060)
n/a
I don't think this is necessary

Remove internet connectivity requirement for WebsocketManager

---

app/src/main/AndroidManifest.xml
app/src/main/res/layout/widget_button_configure.xml
app/src/main/res/layout/widget_button_configure_dynamic_field.xml
app/src/main/res/layout/widget_camera_configure.xml
app/src/main/res/layout/widget_media_controls_configure.xml
app/src/main/res/layout/widget_static_configure.xml

Had a user report in discord that the app was crashing when the autocomplete text field was expanded and the device orientation changed.  
https://discord.com/channels/330944238910963714/562408603345092636/954056480284373063
This causes the following crash:
```
2022-03-17 09:58:00.274 17976-17976/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: io.homeassistant.companion.android, PID: 17976
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
at android.view.ViewRootImpl.setView(ViewRootImpl.java:1153)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:399)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
at android.widget.PopupWindow.invokePopup(PopupWindow.java:1576)
at …
```

Fix widget crash on orientation change and landscape layout fixes

---

app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt

Fixes #2387
This probably worked fine with headsets, as those also provide audio input.
Fix headphone sensor: #2387

fix headphone sensor: check audio OUTPUT devices, not INPUT

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

I have been noticing in discord and the forums that some users are struggling to perform a simple operation of opening an app via a notification command. Command activity and broadcast intent are really more designed for specific use cases of triggering certain parts of an app.
This PR introduces a new command to make opening an app much easier. The user is required to enter a value for `package_name` parameter. If we are able to resolve the launch intent we will launch the app, otherwise we will take the user to the play store to install the app.
Documentation: home-assistant/companion.home-assistant#718
FCM: https://github.com/home-assistant/mobile-apps-fcm-push/pull/69

Add a command to easily launch an application, or take user to install page

---

app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt

This PR includes a more generic fix for #2386 to make sure that the UI _never_ crashes on a sensor update initiated by toggling a sensor on/off or changing a sensor setting, the app should instead fail silently because it might not be related to the user's action.
n/a
n/a

Don't crash on sensor update on on/off/setting change

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt
common/src/main/res/values/strings.xml

Noticed that we were missing some of the volume streams, not all devices show to the user all the streams so better to cover all our bases. Samsung devices for example show System volume while others do not. All are still controllable and report data.
Documentation: home-assistant/companion.home-assistant#720

Add missing volume streams to sensor and command

---

app/src/main/java/io/homeassistant/companion/android/util/OnSwipeListener.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

Fixes #2392 
Unfortunately the default `GestureDetector.OnGestureListener` doesn't provide information about the number of pointers and the direction of a swipe, so a custom class has been created based on the default to fix these issues. At least adding more swipe gestures will be easier in the future :)
I've also checked the frontend for an event to fire to open the quick bar and this still doesn't appear to exist.
Swiping while opened doesn't switch between quick bar modes as mentioned in the documentation and there doesn't seem to be a reliable way to make this work, so I've also opened a PR to update the documentation to reflect what the gesture actually does.
https://user-images.githubusercontent.com/8148535/159681345-0efb95d7-de16-4477-820d-1d14eb3723ce.mp4
Documentation: …

Fix gesture detection on WebViewActivity

---

common/src/main/java/io/homeassistant/companion/android/database/wear/Favorites.kt
common/src/main/java/io/homeassistant/companion/android/database/wear/FavoritesDao.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt

Updating the Favorites Dao to remove blocking operations, and instead use coroutines. Also tried to make updates so the code is easier to follow.
- Flow and List aren't nullable, so I removed the `?` annotations.
- Tried to change `position` to be an implementation detail. `position` is updated so resembles an auto-incrementing value, and there can be "gaps" in the rows. i.e., position 0 may be followed by position 2 if position 1 was deleted.
- Grouped multiple operations into Transactions
- https://developer.android.com/reference/androidx/room/Query
- https://developer.android.com/reference/androidx/room/Transaction

Use suspend and transactions for Favorites dao

---

common/build.gradle.kts
common/schemas/io.homeassistant.companion.android.database.AppDatabase/24.json
common/schemas/io.homeassistant.companion.android.database.AppDatabase/25.json
common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt

Fixes data in the database being lost on updating due to the version being increased from 24 to 25 without a migration and `fallbackToDestructiveMigration()` on the builder, by exporting the database schema + adding a migration:
- Room creates a new schema file when there is a change, so it'll be easier to spot when there's a change and the version has to be increased
- using these export files we can generate automatic migrations instead of having to write SQL for migrations
To replicate the issue, start on commit 81831a978e89f24e90d44b1a748378087df63f55 / beta-2210 or earlier and update to ff0fb0da89a05aabc659e9b48bdb85c2d4bf268e / beta-2214. To test the fix, start on the same commit but instead update to the latest commit in this PR.
n/a
n/a
This change will require that we have schema …

Add AppDatabase v24 -> v25 auto migration

---

app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultButtonControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSliderControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaFailedControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LockControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/VacuumControl.kt

Updates HaControls and ControlsProviderService to use coroutines, avoiding `runBlocking` calls. Every call to `performAction` used `runBlocking` to call a coroutine, and it would be more efficient to launch so the main thread doesn't block.
Additionally replaces companion objects with plain objects, since the classes didn't do anything.

Remove blocking calls from HaControls

---

app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt

- Request an update for the detected activity sensor every minute if the app is currently doing faster sensor updates, instead of every 2 minutes, to try to have an up-to-date recognition value every time the data is sent.
- Fix inconsistent update behaviour after changing the setting but before restarting when registered for the `ACTION_TIME_TICK` intent by always checking the setting, and not only when set to 'fast while charging'.
n/a
No update required because when no update interval is mentioned, it should default to the sensor update frequency setting which this PR will accomplish.

Faster 'Detected Activity' sensor while updating fast

---

app/src/main/res/values/arrays.xml
common/src/main/res/values/strings.xml

- Renames Lovelace to Dashboard to follow core 2022.4
- Remove unused string array that also included Lovelace
|Light|Dark|
|-----|-----|
|![Snippet of the shortcut settings page showing 'Select shortcut type' with two options: 'Dashboard' or 'Entity ID', and a text input field with the hint 'Dashboard View or Dashboard', light mode](https://user-images.githubusercontent.com/8148535/162074647-3737cedf-1825-4c5f-b4af-0760604e55e1.png)|![Snippet of the shortcut settings page showing 'Select shortcut type' with two options: 'Dashboard' or 'Entity ID', and a text input field with the hint 'Dashboard View or Dashboard', dark mode](https://user-images.githubusercontent.com/8148535/162074798-057bca25-6483-4811-ac32-4b8fe8472ab4.png)|
Documentation: home-assistant/companion.home-assistant#730

Rename Lovelace to Dashboard

---

app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
common/src/main/java/io/homeassistant/companion/android/database/qs/TileDao.kt

Updates the TileDao to remove unused functions and make some operations non-blocking.
- Deleted getAll functions that build an unused variable
- Updated `TileDao.add` to use suspend and not block

Streamline TileDao

---

app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorSettingsViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorManager.kt
common/src/main/java/io/homeassistant/companion/android/database/sensor/SensorDao.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt

Cleans up some Flow interactions with SensorDao by using a helper to automatically convert it into a state. Also updates a few functions to be non-blocking

Use collectAsState for SensorDao.getAllFlow

---

common/src/main/res/values/strings.xml

Renames Lovelace to Dashboard to follow core 2022.4. Missed these strings the last time.
|Light|Dark|
|-----|-----|
|![A setting titled 'Keep screen on' with the description 'Do not lock screen when dashboard is active', light mode](https://user-images.githubusercontent.com/8148535/162610716-514bfff8-ce50-4df0-b0ec-5a61eebe2750.png)|![A setting titled 'Keep screen on' with the description 'Do not lock screen when dashboard is active', dark mode](https://user-images.githubusercontent.com/8148535/162610711-6260fa7f-5e31-4020-99cb-b7e1597e0313.png)|
|![A setting titled 'Autoplay Videos' with the description 'Autoplay Videos when dashboard is active. Enabling this setting may increase data usage unexpectedly, proceed with caution.', light …

Rename more Lovelace to Dashboard

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

Ability to toggle persistent connection mode using notification commands
Fix for #2323 
Documentation: home-assistant/companion.home-assistant#732

Add persistent websocket connection notification command

---

app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingViewModel.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryFragment.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/HomeAssistantSearcher.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupView.kt

Small cleanup in OnboardingViewModel. Most notably HomeAssistantSearcher is now a lifecycle observer.

Convert HomeAssistantSearcher to LifecycleObserver

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragmentFactory.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsViewModel.kt

Did you ever notice that opening the tile and shortcuts settings takes a little longer than other settings fragments? Turns out it is because the app was loading all the icons for the icon picker on the main thread, every time the fragment resumed. This PR fixes that by moving it to a background thread and only doing it once.
(also cleaning up some annotations for the shortcuts fragment)
n/a
n/a

Don't block UI thread when opening tile + shortcuts settings

---

app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidDialogFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidRecyclerViewAdapter.kt
app/src/main/res/layout/dialog_ssid.xml
app/src/main/res/layout/item_ssid.xml
common/src/main/res/values/strings.xml

Implements/fixes #2417 by:
- showing a chip suggesting to add the SSID of the currently connected network, if not already added to the list of home SSIDs
- tinting the icon color for listed SSIDs to blue for the currently connected network, grey for other networks
I've also added content descriptions to the `ImageButton`s and fixed some small lint warnings for the dialog.
|Chip suggestion|![image](https://user-images.githubusercontent.com/8148535/163247717-d58df6b6-2c7a-4760-acac-e7775991844a.png)|![image](https://user-images.githubusercontent.com/8148535/163247742-17691a38-c2ad-4791-9d07-1c5072ade922.png)|
|Highlight current connection|![image](https://user-images.githubusercontent.com/8148535/163247935-17c28501-b6f0-4b81-836c-bb39f510cd00.png)|![ima …

Suggest or highlight current SSID in home SSID dialog

---

common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/home/views/DetailsPanelView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt

Resolves #2449
\+ (emulator buzzes)
Not needed

Add haptic + toast feedback to Wear OS details screen

---

app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/LastRebootSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/StepsSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/LastUpdateManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorManager.kt
common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
common/src/main/java/io/homeassistant/companion/android/database/sensor/SensorSetting.kt

Moving off a string type to a strict enum, since there are only certain valid values. Added a type converter to Room so this should be backwards compatible.

Use enum for sensor setting type

---

app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearActivity.kt
common/src/main/res/values/strings.xml

If the Wear OS app is installed but there are no connected devices, the Wear OS Settings section of the app seemingly endlessly loads, while in fact it simply didn't show a proper error message for the situation. This PR fixes that.
|Light|Dark|
|-----|-----|
|![A screenshot of a screen with the title 'Wear OS Settings', showing a message that reads 'No connected Wear devices, please make sure Bluetooth is on and your watch is paired.', light mode](https://user-images.githubusercontent.com/8148535/165370280-a2c1b762-f5db-458c-9a30-30dc5f7a9b5f.png)|![A screenshot of a screen with the title 'Wear OS Settings', showing a message that reads 'No connected Wear devices, please make sure Bluetooth is on and your watch is paired.', dark …

Fix Wear OS Settings endlessly loading with no connected devices

---

app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt

Fixes #2481, [confirmed by user](https://github.com/home-assistant/android/issues/2481#issuecomment-1111157550).
Specifically for this issue: make sure that the current mode of a climate entity (= HA state) is in the list of supported modes before attempting to use the template that includes state. The entity that caused problems in the issue will now use the more generic / simple range template for the control.
In general for future bugs that haven't been found yet: handle errors when creating individual controls. When trying to add a new control, the app will skip a control for a specific entity if it throws an exception instead of skipping all controls, and for existing controls it will show a control with an error state similar to network errors instead of crashing.
Example of a …

Handle individual exceptions while creating device controls better

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
common/src/main/res/values/strings.xml

Fixes: #2485 the state will update as soon as the value changes which takes place when the service is started or restarted
Documentation: home-assistant/companion.home-assistant#737

Add a sensor for high accuracy update interval

---

app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt

I recently noticed that the media widget didn't show any details for me when playing a podcast. Turns out that the app I used doesn't set the _media_artist_, but it does set the _media_album_artist_. This PR adjusts the media widget to show media labels more often:
- if _media_artist_ isn't set, use _media_album_artist_ if present for the artist
- if no artist is set but _media_album_name_ is set, show only the album name for the 'artist' slot
Example media_player entity state while `playing` (only relevant attributes shown):
```
media_title: 453- The Book of Tasty and Healthy Food
media_album_name: 99% Invisible
media_album_artist: Roman Mars
entity_picture: [url]
```
Will result in the following widgets, top version 2022.3.0-full, bottom with PR:
|Light|Dark|
|-----|-----|
|![Two media …

Show media player artist/album more often

---

app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorManager.kt
common/src/main/java/io/homeassistant/companion/android/database/sensor/SensorWithAttributes.kt

When the app collects sensor attributes, it is stored in the app's database as a string and converted back to it's original type when sent to the server, if possible. This PR updates the "if possible" part to also include lists. This will allow users to use array features in HA templating for these values.
Because this changes the format for attribute values, this is a **breaking change**. Based on a quick search, this will have changes for the following sensors:
- Bluetooth Connection
- Last Notification
- Last Removed Notification
- Active Notification Count
I've tested this with core 2022.4.7. Fixes #2474.
n/a
n/a

Breaking change: send sensor list attributes as list to server

---

common/src/main/java/io/homeassistant/companion/android/database/sensor/SensorSetting.kt

#2469 introduced a bug which resulted in sensor settings always being considered of the type `STRING` when read from the database because [`===`](https://kotlinlang.org/docs/equality.html#referential-equality) was used in the type converter. It looks like there is some magic in the database that breaks this comparison for strings, so only compare the contents instead.
n/a
n/a

Fix sensor setting type converter

---

app/build.gradle.kts
common/build.gradle.kts
wear/build.gradle.kts

Fixes #2465, fixes #2477
https://github.com/FasterXML/jackson-databind/issues/3412 results in a crash when the app tries to use the Jackson databind library on devices with API level < 26 (= basically any API call, so from the moment the app starts and tries to contact the server). Manually specify the `jackson-databind` dependency with the latest version that includes a fix for now, Gradle will choose the highest version which solves the problem.
n/a
n/a

Fix crash on app start/API use on SDK <26

---

app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
common/src/main/java/io/homeassistant/companion/android/common/bluetooth/BluetoothUtils.kt

Fixes: #2499 by sending the last state if the string is blank, the default will be `unknown` unless there is a better default to use? Either way we shouldn't send a blank string :)
Noticed one of my devices failed to start the transmitter and this is caused by the BT on the device not supporting advertising so adding a check for that.  Here is the failure I noticed:
```
[05-01 12:15:00.337 27750:28542 E/BeaconTransmitter]
Cannot start advertising due to exception
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.le.BluetoothLeAdvertiser.startAdvertising(android.bluetooth.le.AdvertiseSettings, android.bluetooth.le.AdvertiseData, android.bluetooth.le.AdvertiseCallback)' on a null object reference
at …
```

BLE Transmit fix blank state and check device supports advertising

---

app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt

This PR ~+ home-assistant/mobile-apps-fcm-push#73~ adds support for setting the visibility* of push notifications, which allows you to control what notification content is visible on the lock screen when the device is locked.
Example use cases:
- setting visibility to `secret` to completely hide a notification from the lock screen
- setting visibility to `public` to make a notification visible on the lock screen, when in the system settings you've set it to hide sensitive content from the lock screen
Users on Android 5-7 will benefit most from this change because the system setting only allows controlling the visibility of all notifications. On Android 8+ notification channels allow limiting visibility beyond the general system setting (first use case), but they don't allow users to make …

Allow setting push notification visibility/sensitivity

---

wear/src/main/java/io/homeassistant/companion/android/tiles/TemplateTile.kt

Fixes #2492
I opted to keep the refresh icon on the tile because it still is a good reminder that this functionality exists
Template used: `It is currently {{ now() }}`
https://user-images.githubusercontent.com/8148535/167253933-55145f91-a42a-4b78-b827-186a88c0be33.mp4
n/a

Allow refreshing Wear template tile by tapping anywhere

---

common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/EntityRegistryResponse.kt
common/src/main/java/io/homeassistant/companion/android/util/RegistriesDataHandler.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt

This PR will hide any entities marked as 'hidden' using [2022.4's option for this](https://www.home-assistant.io/blog/2022/04/06/release-20224/#hide-entities) from the Wear OS home screen (Areas / More entities lists).
These entities are still available when using the 'All entities' button and in other places in the app. This behavior is consistent with how the Wear OS app treats non-primary entities (#2216), and also mostly with frontend (not visible on autogenerated dashboards, but still available in the full list/search/automations UI/device page/...).
Because this might hide entities users are currently seeing on the app's home screen, this is a **breaking change**.
Resolves #2507
As an example, I've hidden a light named "Balk ✨", which you can see in HA's frontend: "(Hidden)" is …

Breaking change: hide hidden entities on Wear home screen

---

app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt

Fixes #2251 (the functionality, not the System UI crash)
I've commented on the reason for these changes on the [Google issue tracker](https://issuetracker.google.com/issues/218542096#comment9), but the short version is: due to a security-related change the app needs to provide unique, mutable `PendingIntent`s to the system for the device control app intents.
Tested on a device with Android 11 + an emulator with Android 12 on the November 2021 security patch (to make sure controls still work as they did before on those versions), as well as a device with Android 12 on the May 2022 security patch (to see if the changes 'fix' the issue).
n/a
n/a

Fix device controls crashing System UI on long press

---

app/src/full/java/io/homeassistant/companion/android/CrashHandling.kt
app/src/main/java/io/homeassistant/companion/android/settings/log/LogFragment.kt
app/src/main/res/layout/fragment_log.xml
app/src/minimal/java/io/homeassistant/companion/android/CrashHandling.kt
common/src/main/res/values/strings.xml

To make fixing app crashes easier, let's save the stacktrace for a crash and show it in the app settings' log viewer. This should allow most users to provide a crash log that can be used to fix issues without having to reproduce it, install another app and/or use a computer. Sentry already records these errors, this PR simply adds a hook to also store it somewhere the app can use.
If crash reporting is enabled and there was a crash in the last 12 hours (if it is older, it's probably not relevant), a tab row will be added to the top of the screen to allow the user to view the crash stacktrace.
|Light|Dark|
|-----|-----|
|![image](https://user-images.githubusercontent.com/8148535/168430849-55d7f1b2-e737-4573-891e-4371cc197557.png)|![image](https://user-images.githubusercontent.com/8148535/16 …

Save + show crash stacktrace in app settings logs

---

app/src/main/java/io/homeassistant/companion/android/settings/widgets/views/ManageWidgetsView.kt

This PR sets the width of the `LazyColumn` in the widget settings screen to the full width of the screen to also allow scrolling the screen when touching in the empty space next to the buttons. Before this PR, the scrollable area is only as wide as the widest composable in the column, while most users expect to be able to scroll anywhere.
(To reproduce: create a lot of widgets with short names, for example 1/2/3/4/5/etc, and try dragging to scroll to the right of the buttons in the empty space.)
n/a
n/a

Fix widget settings scrolling with narrow buttons

---

app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
app/src/main/res/values-v31/styles.xml
app/src/main/res/values/styles.xml

This PR handles any exceptions thrown after logging in to Home Assistant while doing initial registration of the app (issue #2519), by asking the user to check their configuration.
I've also updated the launch screen theme's AlertDialog theme to remove the Home Assistant logo as the dialog's background on API < 31.
|Light|Dark|
|-----|-----|
|![A dialog with the text 'Unable to connect to Home Assistant. Failed to perform SSL handshake, please ensure your certificate is valid.', light theme](https://user-images.githubusercontent.com/8148535/168920141-a61ed4bd-2b3b-407c-b63b-ed59a1d57666.png)|![A dialog with the text 'Unable to connect to Home Assistant. Failed to perform SSL handshake, please ensure your certificate is valid.', dark …

Catch exceptions during app registration

---

app/src/main/java/io/homeassistant/companion/android/sensors/TimeZoneManager.kt

This PR changes the time zone sensor's state to the 'current' name that reflects whether the time zone is in summer/daylight savings time or not (bonus: it 'fixes' 50% of #2530).
The sensor previously had 'Central European Standard Time' as the state.
|Light|Dark|
|-----|-----|
|![Time zone sensor showing 'Central European Summer Time' as the state, light mode](https://user-images.githubusercontent.com/8148535/169397594-807cb533-4854-4b12-bd9d-47116050084e.png)|![Time zone sensor showing 'Central European Summer Time' as the state, dark mode](https://user-images.githubusercontent.com/8148535/169397568-767df4d1-1ddf-49d9-8dfa-fc36d1289806.png)|
n/a

Improve time zone sensor state

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt

This PR improves error handling for SSL-related errors in the WebViewActivity to match the error handling during onboarding, by showing the correct error message more often;
- Actually use the `onReceivedSslError` callback error (the code for error messages was already there, but it simply wasn't being used?)
- Also show SSL errors in the external auth callback
- If the user has to check the logs, use the correct function name to allow identifying which function receives an error
n/a
n/a

Better SSL error handling in WebViewActivity

---

app/src/main/java/io/homeassistant/companion/android/widgets/BaseWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
common/src/main/java/io/homeassistant/companion/android/database/widget/ButtonWidgetDao.kt
common/src/main/java/io/homeassistant/companion/android/database/widget/CameraWidgetDao.kt
common/src/main/java/io/homeassistant/companion/android/database/widget/MediaPlayerControlsWidgetDao.kt
common/src/main/java/io/homeassistant/companion/android/database/widget/StaticWidgetDao.kt
common/src/main/java/io/homeassistant/companion/android/database/widget/TemplateWidgetDao.kt
common/src/main/java/io/homeassistant/companion/android/database/widget/WidgetDao.kt

Adds a base class for the widget configure activities. As a result some logic can be shared - initially just the delete dialog.
Also updated the delete widget operation to use coroutines.

Create a WidgetConfigureActivity base class

---

app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
app/src/main/java/io/homeassistant/companion/android/settings/widgets/ManageWidgetsViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/widgets/views/ManageWidgetsView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/EntityListView.kt
wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt

Small change to use the `key` property in `items` loops in LazyColumns. This helps reduce re-renders and improve performance, by telling Compose which rendered item corresponds with which data item.

Update compose items loops to use keys

---

app/src/main/java/io/homeassistant/companion/android/util/ChangeLog.kt

Currently, the changelog is shown every time a new version is detected, which includes a new app install. However, when the app has just been installed _everything_ is new, and this dialog is shown immediately after logging in which can be confusing ('do I need to do something with this information?'). I suggest adjusting it to only show up if the app has been used before to improve the first run experience.
n/a, no dialog means you get to the frontend after logging in instead of being interrupted by the changelog
n/a

Don't show changelog immediately on new app installs

---

app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt

#2540 introduced two potential crashes when opening the 'Manage Tiles' screen if there are any tiles stored in the database and a bug for updating existing tiles. I guess everyone tested a fresh install and didn't press back?
1: A crash because we're trying to update [state used by Compose while it is a snapshot](https://stackoverflow.com/q/66891349/4214819) on the IO thread. Fixed by switching to the main thread when updating these variables.
<details>
<summary>java.lang.IllegalStateException: Reading a state that was created after the snapshot was taken or in a snapshot that has not yet been applied</summary>
```
2022-05-31 19:20:29.420 11315-11371/io.homeassistant.companion.android.debug E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: …
```

Fix manage tiles screen crash if there are tiles, updating tiles

---

common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt

If the app is unable to read the Home Assistant config (for example, if the server is temporarily down, the device has no internet connection, ...), this should return the stored HA version + still retry the next time instead of overwriting it with null/empty string as successful. This was probably the intended behavior, but changed when switching to the websocket which returns `null` on problems instead of throwing an exception.
This will prevent version 'downgrades' which resulted in less functionality for sensor updates and/or the app showing a security warning.
n/a
n/a

Improve HA version check when unable to read config

---

app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt

Fixes: #2545 the state of the last update sensor will reflect this intent
This intent will not be guaranteed however it does show up in testing
https://developer.android.com/reference/android/content/Intent#ACTION_SHUTDOWN

Register for the shutdown intent to send 1 final sensor update before device restarts or powers down

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailViewModel.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
common/src/main/java/io/homeassistant/companion/android/common/bluetooth/BluetoothUtils.kt

Fix #2579 by changing the location high accuracy mode Bluetooth device constraint to use Bluetooth device addresses instead of device names, to ensure values are unique. Device names that are currently stored in the database will be converted to a device address when possible, making the change invisible to most users.
This PR also includes changes to be able to display a friendly name instead of the stored value (like the Bluetooth device name instead of the device address) for all list types in the sensor settings details screen.
The Bluetooth device list setting now looks like this:
|Light|Dark|
|-----|-----|
|![Sensor settings for the background location sensor, showing a value of 'Steel HR FD, OnePlus Bullets Wireless' for the 'High accuracy mode only when connected to BT devices' …

Use Bluetooth device address for high accuracy mode BT constraint, fixes settings crash

---

app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationDetailFragment.kt
app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationHistoryFragment.kt
app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt
common/src/main/java/io/homeassistant/companion/android/common/sensors/LastUpdateManager.kt
common/src/main/java/io/homeassistant/companion/android/database/authentication/AuthenticationDao.kt
common/src/main/java/io/homeassistant/companion/android/database/notification/NotificationDao.kt
common/src/main/java/io/homeassistant/companion/android/database/qs/TileDao.kt
common/src/main/java/io/homeassistant/companion/android/database/sensor/SensorDao.kt
common/src/main/java/io/homeassistant/companion/android/database/widget/ButtonWidgetDao.kt
common/src/main/java/io/homeassistant/companion/android/database/widget/CameraWidgetDao.kt

Some additional work to make Dao methods run non-blocking using coroutines. Converted some methods to use coroutines and removed some unused methods.

Update delete methods in daos

---

app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt

This is basically part 2 of #2597, as I realised earlier today that the app doesn't need to load everything and do a full update for the service button widget to show the feedback state. The ✅ (or ❌) will now show up a lot faster than before.
n/a
n/a

Improve service button widget feedback state speed

---

app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragmentFactory.kt
app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailFragment.kt

The problem described in #2592 also applies to the settings screen; after recreation you always end up in the main settings screen but when you press back things get interesting with an unexpected backstack and multiple fragments/layers of text. This PR fixes it by only replacing `R.id.content` with a fragment if there were none.
I've also updated the `SettingsFragmentFactory` used during recreation to remove all classes without constructor arguments, for these fragments the `else` branch can be used.
n/a
n/a

Fix settings fragment backstack on recreation

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt

Fixes: #2586 by providing a `metered` attribute for the network type sensor.
Documentation: home-assistant/companion.home-assistant#763

Add attribute to network type sensor if network is metered

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/LastUpdateManager.kt

Fixes #2550 _Cannot add new Intent to Last Update Trigger sensor_
Now the `Last Update Trigger` sensor's settings screen handles removing non-last list items correctly.
The fix is intended to be backwards compatible, so existing installations with incorrect state will be fixed automatically upon the first call of the `sendLastUpdate()` method (= by an update in the background, or when the user edits the list).
[video before the fix: reproduction of the bug](https://user-images.githubusercontent.com/1349654/171994081-0fede94b-c223-46db-93b6-f2c23244b48a.mp4)
[video after the fix: the bug cannot be reproduced anymore](https://user-images.githubusercontent.com/1349654/171994305-86835a33-8b1d-4f8f-a1ff-ada6da129341.mp4)
I did some refactoring in the `sendLastUpdate()` method to clarify and …

Fix removing non-last list items from Last Update Trigger sensor's settings

---

app/src/main/java/io/homeassistant/companion/android/settings/widgets/views/ManageWidgetsView.kt

This PR fixes a potential crash found while discussing issue #2421 ([comment](https://github.com/home-assistant/android/issues/2421#issuecomment-1159768481)), where the app crashed because of a duplicate widget ID in the list (Compose uses widget IDs as stable keys).
Presumably this can be achieved when doing a partial restore, where the database will contain a widget with ID `x` which is not added to the launcher. When the launcher then creates a new widget for ID `x` that is of another type, the previous data is not replaced by the app because the ID is in another table. This change will make sure the app doesn't crash in that case and the user can still clear out the previously deleted widget(s).
n/a
n/a

Don't crash manage widgets screen on duplicate id

---

app/src/main/AndroidManifest.xml

* The webview activity now handles keyboard|keyboardHidden|navigation
configuration changes by keyboard connection changes, to avoid the
activity restart which leads to frontend reload.
It fixes https://github.com/home-assistant/android/issues/2622
N/A
N/A

Fix webview restart on keyboard changes (#2622)

---

app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt

When using the device controls or Wear OS app, multiple messages have to be sent and received on the websocket connection in order to show the entity information. Right now the app waits on a response before sending the next message, which is inefficient because some requests take longer than others (depending on device/server/network/data/...). This PR changes these initial requests to be called `async` - the app doesn't care in which order the responses arrive, as long as they all arrive before continuing.
I've also included another small change in the device controls where it will now load the initial data first, and only start listening for updates after controls have been provided to the system.
n/a
n/a

Speed up device controls/Wear OS loading by doing network async

---

app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt

Fixes #2637 
The state of the Internal Storage sensor was stored in the `companion object` of `StorageSensorManager`. It was calculated once when the `companion object` was initialized. I fixed it and also did some refactoring.
Based on the code, the Free and the Total attributes' unit was supposed to be dynamic (KB / MB / GB), but it always displayed GB because the logic was flawed. Now it can not only output 0GB for smaller values (<1GB) but also 345MB or 640KB for example.
This app may come in handy for testing this:
[Fill Storage – Google Play](https://play.google.com/store/apps/details?id=com.arumcomm.fillstorage)

Fix Storage sensors to update continuously and display correct size unit

---

app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt

Fixes #2217 - the app will no longer suppress/continue on failed registration during onboarding, and if it failed because the `mobile_app` integration is missing it will show a specific error message to indicate this
|Light|Dark|
|-----|-----|
|![A dialog with the text 'Unable to connect to Home Assistant. The 'Mobile App' integration is required to use the app, but it is not available on your Home Assistant server. Please check your server configuration and try again. ', light mode](https://user-images.githubusercontent.com/8148535/176257550-61438868-3b5e-4c88-a53e-29d5ab895d92.png)|![A dialog with the text 'Unable to connect to Home Assistant. The 'Mobile App' integration is required to use the app, but it is not available on your Home Assistant server. Please check your server …

Don't complete onboarding on registration error

---

app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt

Fix #2647 by improving the null check + ensuring that the button's icon has a minimum size, to prevent crashes due to a size of `0`
n/a
n/a

Fix background crash due to button widgets without size

---

app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetDynamicFieldAdapter.kt

Fixes #2604 and visual issues for the service fields
These fixes don't really relate to the changes included in the version I mentioned in the issue, but were mainly caused by race conditions/re-use of resources so I'm going to blame it on the app got faster 🙂
n/a
n/a

Fix editing service button widget shows/creates incorrect field values

---

app/src/main/java/io/homeassistant/companion/android/controls/CameraControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultButtonControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSliderControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
app/src/main/java/io/homeassistant/companion/android/controls/HaFailedControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/LockControl.kt
app/src/main/java/io/homeassistant/companion/android/controls/VacuumControl.kt
app/src/main/res/drawable/control_camera_placeholder.xml
app/src/main/res/layout/widget_camera.xml
common/src/main/res/values/strings.xml

Add support for `camera` entities to device controls. The control is only supported on Android 12+.
As usual with device controls, the appearance depends on the manufacturer. These screenshots are for Google's implementation, note that if the camera isn't active they decided to not show the snapshot:
|State: `idle`|State: `recording` or `streaming`|
|-----|-----|
|![A device control tile with a camera icon, the state 'Idle', the title 'RTSP camera' and a gray background](https://user-images.githubusercontent.com/8148535/178028050-29ae1196-f549-437b-8868-f8e894bdaec1.png)|![A device control tile with a camera icon and the state 'Streaming', no title is shown and the background of the tile is a still image of the stream](https://user-images.githubusercontent.com/8148535/178028126-dd36b7c9-f4 …

Add camera device control

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/LastUpdateManager.kt

Fixes: #2673 
Need to make sure on a new install the setting toggle shows up as well.

Fix last update add new intent toggle not showing up on new installs

---

app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt

A three finger swipe gesture was added as a workaround to open the quick bar while it was only possible with a physical keyboard; Home Assistant 2022.5 added a button for it to the toolbar and a later update broke support for the app's workaround (see [this comment](https://github.com/home-assistant/android/issues/2686#issuecomment-1186577056)). Because it is no longer functional on recent versions and an alternative is available, add a comment in the code to mark it for removal.
Closes #2686
n/a
The documentation is related but doesn't depend on this PR being merged to be true
Documentation: home-assistant/companion.home-assistant#777

Deprecate Android WebView quick bar gesture support

---

app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt

Fixes: #2696 
This is a breaking change because the friendly name will now be added to the Mac address if we have it, otherwise it will print the address again.
New format will be: `MAC (Name)`
Also cleaned up some warnings and removed a commented line

Breaking Change: Add friendly BT name next to the mac address if we have it

---

app/src/full/java/io/homeassistant/companion/android/location/HighAccuracyLocationService.kt
app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

- Stops using deprecated priority constants introduced in latest [location dependency update](https://developers.google.com/android/guides/releases#june_07_2022)
- Stops using deprecated constructor usage, not sure when this was deprecated
- Adds a short delay when high accuracy mode is disabling so we can ensure the request to remove location updates has completed before we register for normal background updates. During testing I found that when I was manually enabling and disabling high accuracy mode from settings the updates were not coming in consistently (if at all) anymore and it turns out we were requesting updates before the service was successfully destroyed. After adding this delay the frequency in updates returned.

Minor location update fixes

---

app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt

Fixes: #2675 
Adds Channel ID, Category and also Group ID from notifications.
Documentation: home-assistant/companion.home-assistant#774

Add channel, category and group to notification sensor attributes

---

app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt
app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearTemplateTile.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
common/src/main/res/values/strings.xml
wear/src/main/java/io/homeassistant/companion/android/tiles/TemplateTile.kt

Parse HTML for the template tile, similar to the template widget. Supports the following styling:
- bold/italic/underline
- color
- size (with \<big> and \<small> tags)
- headers (\<h1>, \<h2>, etc.)
The following snippet will result in the screenshot:
```html
This <b>is <i>an</i> example</b><br><big>Of HTML</big><br>Of HTML<br><span style='color:#03a9f4'><small>And markups</small></span>
```
**Breaking change: new lines in the form of `\n` are no longer supported. Need to use `<br>` for a new line**
Documentation: home-assistant/companion.home-assistant#767

Implement html styling on the template tile

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/homeassistant/companion/android/settings/log/LogFragment.kt
common/src/main/res/values/strings.xml

When targeting Android 13, [the `WRITE_EXTERNAL_STORAGE` permission will stop working](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions) (requesting it simply does nothing), which is currently used for saving the logs. Turns out it actually isn't required at all since Android 4.4 for the directory we're using according to the documentation! The permission request has been removed on Android 6 and above, still requesting it on Android 5 due to [a possible bug](https://issuetracker.google.com/issues/37013142) for some devices (the permission will automatically be granted on that version and it is still used for downloads in that case).
As a result, the `WRITE_EXTERNAL_STORAGE` permission is only required for devices on Android <10 to handle …

Remove external storage permission for logs, completely on Android 10+

---

app/src/main/java/io/homeassistant/companion/android/widgets/BaseWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/BaseWidgetProvider.kt
app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidgetConfigureActivity.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
app/src/main/res/layout/widget_button_configure.xml
app/src/main/res/layout/widget_camera_configure.xml
app/src/main/res/layout/widget_media_controls_configure.xml
app/src/main/res/layout/widget_static_configure.xml
app/src/main/res/layout/widget_template_configure.xml
common/src/main/res/values/strings.xml

Automatically deletes widgets from the database that are no longer bound to the widget provider but that are still in the database when asked to update all widgets. This will remove unnecessary updates (and websocket connections!) due to 'stale'/old widgets that aren't exposed to the user. The PR also removes the "Delete widget" button on the widget configuration screen as it is no longer required.
No issue to link here, but "remove unused widgets from Settings > Companion app > Manage Widgets" has been a 'solution' for multiple issues in the past.
The "Delete widget" button has been removed when updating a widget:
|Light|Dark|
|-----|-----|
|![Settings for a template widget, with the only button being 'Update Widget' and no longer also including 'Delete Widget', light …

Automatically delete 'stale'/old widgets from database

---

common/src/main/java/io/homeassistant/companion/android/common/sensors/LastUpdateManager.kt

Fixes #2703
The Last Update Sensor's list of Intents was reordered on every update when there were 10+ entries. It was caused by the lexicographic ordering of numbers (contained in the `name` DB field). It was caused by the sequence continuity detection I added recently because I haven't tested it with more than 10 entries. 
I fixed it by sorting it ~~like it is displayed on the UI~~ numerically.

Fix unwanted reordering of Last Update Sensor's Intent list when there are 10+ entries

---

app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt

I noticed on a cold start that we did some weird double registration of location updates.
```
2022-07-25 08:53:47.589 32009-32109/? D/LocBroadcastReceiver: Registering for zone based location updates
2022-07-25 08:53:47.604 32009-32107/? D/LocBroadcastReceiver: Registering for location updates.
2022-07-25 08:53:47.616 32009-32108/? D/LocBroadcastReceiver: High accuracy mode parameters changed. Disable high accuracy mode.
2022-07-25 08:53:47.623 32009-32108/? D/LocBroadcastReceiver: Registering for location updates.
2022-07-25 08:53:47.624 32009-32108/? D/LocBroadcastReceiver: High accuracy mode geo parameters changed. Reconfigure zones.
2022-07-25 08:53:47.624 32009-32108/? D/LocBroadcastReceiver: Removing geofence location requests.
2022-07-25 08:53:47.624 32009-32108/? …
```

Use correct default value for update interval to avoid double registrations on cold start
